module

public import GibbsMeasure.Specification
public import Mathlib.Analysis.SpecialFunctions.Exp
public import Mathlib.Algebra.BigOperators.Ring.Finset
public import Mathlib.Data.Set.Finite.Lattice

/-!
# Interaction Potentials

This file introduces **interaction potentials** for lattice systems.

## Main definitions

- `Potential S E`: a family `Φ Δ : (S → E) → ℝ` indexed by finite interaction supports
  `Δ : Finset S`.
- `Potential.IsPotential`: locality/measurability of each `Φ Δ` w.r.t. `cylinderEvents Δ`.
- `Potential.IsFinitary`: only finitely many interaction terms are non-zero.
- `Potential.IsLocallyFinitary`: for every finite volume `Λ`, only finitely many interaction
  terms with nonzero strength have support intersecting `Λ`.

## Main results

- `IsPotential.eq_of_eqOn`: if a potential is admissible, then each interaction term depends only
  on the coordinates in its support.
- Every `IsFinitary` potential is automatically `IsLocallyFinitary`.
-/

@[expose] public section

open scoped BigOperators

open ProbabilityTheory Set Finset MeasureTheory ENNReal

variable {S E : Type*} [MeasurableSpace E]

/-- A (multi-body) interaction potential: a family of real-valued functions indexed by finite
subsets of `S`. -/
def Potential (S E : Type*) [MeasurableSpace E] : Type _ :=
  (Δ : Finset S) → (S → E) → ℝ

namespace Potential

variable (Φ : Potential S E)

/-- A potential is *admissible* if each interaction term `Φ Δ` is measurable with respect to the
σ-algebra generated by the coordinates in `Δ`. -/
class IsPotential (Φ : Potential S E) : Prop where
  measurable (Δ : Finset S) :
    Measurable[cylinderEvents (X := fun _ : S ↦ E) (Δ : Set S)] (Φ Δ)

/-- A potential is *finitary* if only finitely many interaction terms are non-zero. This avoids any
analytic summability issues: all Hamiltonians we define are finite sums. -/
class IsFinitary (Φ : Potential S E) : Prop where
  finite_support : ( {Δ : Finset S | Φ Δ ≠ 0} ).Finite

/-- A potential is *locally finitary* if, for every finite volume `Λ`, only finitely many
interaction terms with nonzero strength have support intersecting `Λ`.

This is the natural weakening of `IsFinitary`: infinitely many interaction terms are allowed
globally, but any fixed finite volume sees only finitely many of them. -/
class IsLocallyFinitary (Φ : Potential S E) : Prop where
  finite_support (Λ : Finset S) :
    ({Δ : Finset S | ((Δ : Set S) ∩ (Λ : Set S)).Nonempty ∧ Φ Δ ≠ 0} : Set (Finset S)).Finite

instance (Φ : Potential S E) [IsFinitary Φ] : IsLocallyFinitary Φ where
  finite_support Λ :=
    (IsFinitary.finite_support (Φ := Φ)).subset <| by
      intro Δ hΔ
      exact hΔ.2

section Locality

variable {Φ}

/-- If a real-valued function is measurable w.r.t. `cylinderEvents Δ`, then it depends only on the
coordinates in `Δ`. -/
lemma IsPotential.eq_of_eqOn [IsPotential Φ] {Δ : Finset S} {η ζ : S → E}
    (h : ∀ x ∈ Δ, η x = ζ x) :
    Φ Δ η = Φ Δ ζ := by
  have hf :
      Measurable[cylinderEvents (X := fun _ : S ↦ E) (Δ : Set S)] (Φ Δ) :=
    IsPotential.measurable (Φ := Φ) Δ
  have hA :
      MeasurableSet[cylinderEvents (X := fun _ : S ↦ E) (Δ : Set S)]
        ((Φ Δ) ⁻¹' {Φ Δ η}) := by
    exact hf (measurableSet_singleton _)
  have hA' :
      MeasurableSet[
          MeasurableSpace.comap (Set.restrict (π := fun _ : S ↦ E) (Δ : Set S))
            (inferInstance : MeasurableSpace (Δ → E))]
        ((Φ Δ) ⁻¹' {Φ Δ η}) := by
    rw [← MeasureTheory.cylinderEvents_eq_comap_restrict (S := S) (E := E) (Δ := (Δ : Set S))]
    exact hA
  rcases hA' with ⟨B, hB, hpreim⟩
  have hη_mem : η ∈ (Set.restrict (π := fun _ : S ↦ E) (Δ : Set S)) ⁻¹' B := by
    have : η ∈ ((Φ Δ) ⁻¹' {Φ Δ η}) := by simp
    simp [hpreim]
  have hre : Set.restrict (π := fun _ : S ↦ E) (Δ : Set S) η =
      Set.restrict (π := fun _ : S ↦ E) (Δ : Set S) ζ := by
    funext x
    exact h x x.2
  have hζ_mem : ζ ∈ (Set.restrict (π := fun _ : S ↦ E) (Δ : Set S)) ⁻¹' B := by
    simpa [Set.mem_preimage, hre] using (show Set.restrict (π := fun _ : S ↦ E) (Δ : Set S) η ∈ B by
      simpa [Set.mem_preimage] using hη_mem)
  have : ζ ∈ ((Φ Δ) ⁻¹' {Φ Δ η}) := by
    simpa [hpreim] using hζ_mem
  exact (by
    simpa [Set.mem_preimage] using this : Φ Δ ζ = Φ Δ η).symm

end Locality

section InteractingHamiltonian

variable [DecidableEq S]
variable {Φ}

/-- The finite set of interaction supports that meet `Λ` and carry a nonzero interaction term. -/
noncomputable def interactingSupport [IsLocallyFinitary Φ] (Λ : Finset S) : Finset (Finset S) :=
  (IsLocallyFinitary.finite_support (Φ := Φ) Λ).toFinset

omit [DecidableEq S] in
lemma mem_interactingSupport [IsLocallyFinitary Φ] {Λ Δ : Finset S} :
    Δ ∈ interactingSupport (Φ := Φ) Λ ↔
      ((Δ : Set S) ∩ (Λ : Set S)).Nonempty ∧ Φ Δ ≠ 0 := by
  simp [interactingSupport]

omit [DecidableEq S] in
lemma interactingSupport_subset_of_subset [IsLocallyFinitary Φ] {Λ₁ Λ₂ : Finset S}
    (hΛ : Λ₁ ⊆ Λ₂) :
    interactingSupport (Φ := Φ) Λ₁ ⊆ interactingSupport (Φ := Φ) Λ₂ := by
  intro Δ hΔ
  rcases (mem_interactingSupport (Φ := Φ)).1 hΔ with ⟨⟨x, hxΔ, hxΛ₁⟩, hΦΔ⟩
  have hxΛ₂ : x ∈ (Λ₂ : Set S) := by
    have : x ∈ Λ₂ := hΛ (by simpa using hxΛ₁)
    simpa using this
  exact (mem_interactingSupport (Φ := Φ)).2 ⟨⟨x, hxΔ, hxΛ₂⟩, hΦΔ⟩

/-- The interacting Hamiltonian in a volume `Λ`: sum of all interaction terms whose support meets
`Λ`.

This is the standard finite-volume Hamiltonian \(H^{int}_Λ(η) = \sum_{Δ : Δ ∩ Λ ≠ ∅} Φ_Δ(η)\).
The local finiteness assumption ensures this is a finite sum. -/
noncomputable def interactingHamiltonian [IsLocallyFinitary Φ] (Λ : Finset S) (η : S → E) : ℝ :=
  Finset.sum (interactingSupport (Φ := Φ) Λ) (fun Δ => Φ Δ η)

omit [DecidableEq S] in
lemma measurable_interactingHamiltonian [IsLocallyFinitary Φ] [IsPotential Φ] (Λ : Finset S) :
    Measurable (interactingHamiltonian (Φ := Φ) Λ) := by
  classical
  set t : Finset (Finset S) := interactingSupport (Φ := Φ) Λ with ht
  change Measurable (fun η : S → E => Finset.sum t (fun Δ => Φ Δ η))
  refine Finset.induction_on t ?_ ?_
  · simp
  · intro a s ha hs_meas
    have ha_meas : Measurable (fun η : S → E => Φ a η) :=
      (IsPotential.measurable (Φ := Φ) a).mono
        (cylinderEvents_le_pi (X := fun _ : S ↦ E) (Δ := (a : Set S))) le_rfl
    simpa [Finset.sum_insert ha] using ha_meas.add hs_meas

/-! ### Boltzmann weights and the cocycle identity -/

/-- Unnormalized Boltzmann weight `ρ_Λ(η) = exp (-β H^{int}_Λ(η))`, valued in `ℝ≥0∞`. -/
noncomputable def boltzmannWeight [IsLocallyFinitary Φ] (β : ℝ) (Λ : Finset S) (η : S → E) : ℝ≥0∞ :=
  ENNReal.ofReal (Real.exp (-β * interactingHamiltonian (Φ := Φ) Λ η))

omit [DecidableEq S] in
lemma measurable_boltzmannWeight [IsLocallyFinitary Φ] [IsPotential Φ] (β : ℝ) (Λ : Finset S) :
    Measurable (boltzmannWeight (Φ := Φ) β Λ) := by
  have hH : Measurable fun η : S → E => interactingHamiltonian (Φ := Φ) Λ η :=
    measurable_interactingHamiltonian (Φ := Φ) Λ
  simpa [boltzmannWeight] using
    (((measurable_const.mul hH).exp).ennreal_ofReal)

omit [DecidableEq S] in
lemma interactingHamiltonian_sub_eq_sum_sub [IsLocallyFinitary Φ]
    (Λ : Finset S) (η ζ : S → E) :
    interactingHamiltonian (Φ := Φ) Λ η - interactingHamiltonian (Φ := Φ) Λ ζ =
      Finset.sum (interactingSupport (Φ := Φ) Λ) (fun Δ => Φ Δ η - Φ Δ ζ) := by
  simp [interactingHamiltonian, Finset.sum_sub_distrib]

omit [DecidableEq S] in
lemma interactingHamiltonian_sub_eq_of_subset_eqOn_compl
    [IsLocallyFinitary Φ] [IsPotential Φ] {Λ₁ Λ₂ : Finset S}
    (hΛ : Λ₁ ⊆ Λ₂) {η ζ : S → E} (hrestrict : ∀ s ∉ Λ₁, ζ s = η s) :
    interactingHamiltonian (Φ := Φ) Λ₁ η - interactingHamiltonian (Φ := Φ) Λ₁ ζ =
      interactingHamiltonian (Φ := Φ) Λ₂ η - interactingHamiltonian (Φ := Φ) Λ₂ ζ := by
  have hsubset := interactingSupport_subset_of_subset (Φ := Φ) hΛ
  rw [interactingHamiltonian_sub_eq_sum_sub, interactingHamiltonian_sub_eq_sum_sub]
  refine Finset.sum_subset hsubset ?_
  intro Δ hΔ₂ hΔ₁
  have hΔ₂' := (mem_interactingSupport (Φ := Φ)).1 hΔ₂
  have hΔ₁' :
      ¬ (((Δ : Set S) ∩ (Λ₁ : Set S)).Nonempty ∧ Φ Δ ≠ 0) := by
    intro h
    exact hΔ₁ ((mem_interactingSupport (Φ := Φ)).2 h)
  have hΔ_out : ∀ x ∈ Δ, x ∉ Λ₁ := by
    intro x hxΔ hxΛ₁
    exact hΔ₁' ⟨⟨x, by simpa using hxΔ, by simpa using hxΛ₁⟩, hΔ₂'.2⟩
  have hΦΔ : Φ Δ η = Φ Δ ζ := by
    apply IsPotential.eq_of_eqOn (Φ := Φ) (Δ := Δ) (η := η) (ζ := ζ)
    intro x hxΔ
    exact (hrestrict x (hΔ_out x hxΔ)).symm
  simp [hΦΔ]

omit [DecidableEq S] in
lemma boltzmannWeight_mul_comm_of_hamiltonian_sum_eq [IsLocallyFinitary Φ]
    (β : ℝ) {Λ₁ Λ₂ : Finset S} {η ζ : S → E}
    (hsum :
      interactingHamiltonian (Φ := Φ) Λ₂ ζ + interactingHamiltonian (Φ := Φ) Λ₁ η =
        interactingHamiltonian (Φ := Φ) Λ₁ ζ + interactingHamiltonian (Φ := Φ) Λ₂ η) :
    boltzmannWeight (Φ := Φ) β Λ₂ ζ * boltzmannWeight (Φ := Φ) β Λ₁ η =
      boltzmannWeight (Φ := Φ) β Λ₁ ζ * boltzmannWeight (Φ := Φ) β Λ₂ η := by
  let H (Λ : Finset S) (σ : S → E) : ℝ := interactingHamiltonian (Φ := Φ) Λ σ
  have hargs :
      (-β * H Λ₂ ζ) + (-β * H Λ₁ η) = (-β * H Λ₁ ζ) + (-β * H Λ₂ η) := by
    simpa [H, mul_add, add_comm, add_left_comm, add_assoc, mul_assoc] using
      congrArg (fun x => (-β) * x) hsum
  have h_exp :
      Real.exp (-β * H Λ₂ ζ) * Real.exp (-β * H Λ₁ η) =
        Real.exp (-β * H Λ₁ ζ) * Real.exp (-β * H Λ₂ η) := by
    calc
      Real.exp (-β * H Λ₂ ζ) * Real.exp (-β * H Λ₁ η)
          = Real.exp ((-β * H Λ₂ ζ) + (-β * H Λ₁ η)) := by
              simpa using (Real.exp_add (-β * H Λ₂ ζ) (-β * H Λ₁ η)).symm
      _ = Real.exp ((-β * H Λ₁ ζ) + (-β * H Λ₂ η)) := congrArg Real.exp hargs
      _ = Real.exp (-β * H Λ₁ ζ) * Real.exp (-β * H Λ₂ η) := by
            simpa using (Real.exp_add (-β * H Λ₁ ζ) (-β * H Λ₂ η))
  dsimp [boltzmannWeight, H]
  calc
    ENNReal.ofReal (Real.exp (-β * interactingHamiltonian Λ₂ ζ)) *
        ENNReal.ofReal (Real.exp (-β * interactingHamiltonian Λ₁ η))
        = ENNReal.ofReal
            (Real.exp (-β * interactingHamiltonian Λ₂ ζ) *
              Real.exp (-β * interactingHamiltonian Λ₁ η)) := by
            exact (ENNReal.ofReal_mul (Real.exp_pos _).le).symm
    _ = ENNReal.ofReal
          (Real.exp (-β * interactingHamiltonian Λ₁ ζ) *
            Real.exp (-β * interactingHamiltonian Λ₂ η)) := by
          simpa [H] using congrArg ENNReal.ofReal h_exp
    _ = ENNReal.ofReal (Real.exp (-β * interactingHamiltonian Λ₁ ζ)) *
        ENNReal.ofReal (Real.exp (-β * interactingHamiltonian Λ₂ η)) := by
          exact ENNReal.ofReal_mul (Real.exp_pos _).le

omit [DecidableEq S] in
lemma boltzmannWeight_mul_comm_of_hamiltonian_sub_eq [IsLocallyFinitary Φ]
    (β : ℝ) {Λ₁ Λ₂ : Finset S} {η ζ : S → E}
    (hH :
      interactingHamiltonian (Φ := Φ) Λ₁ η - interactingHamiltonian (Φ := Φ) Λ₁ ζ =
        interactingHamiltonian (Φ := Φ) Λ₂ η - interactingHamiltonian (Φ := Φ) Λ₂ ζ) :
    boltzmannWeight (Φ := Φ) β Λ₂ ζ * boltzmannWeight (Φ := Φ) β Λ₁ η =
      boltzmannWeight (Φ := Φ) β Λ₁ ζ * boltzmannWeight (Φ := Φ) β Λ₂ η := by
  let H (Λ : Finset S) (σ : S → E) : ℝ := interactingHamiltonian (Φ := Φ) Λ σ
  have hsum : H Λ₂ ζ + H Λ₁ η = H Λ₁ ζ + H Λ₂ η := by
    have : H Λ₁ η + H Λ₂ ζ = H Λ₂ η + H Λ₁ ζ :=
      (sub_eq_sub_iff_add_eq_add).1 hH
    calc
      H Λ₂ ζ + H Λ₁ η = H Λ₁ η + H Λ₂ ζ := by simp [add_comm]
      _ = H Λ₂ η + H Λ₁ ζ := this
      _ = H Λ₁ ζ + H Λ₂ η := by simp [add_comm]
  exact boltzmannWeight_mul_comm_of_hamiltonian_sum_eq (Φ := Φ) β hsum

omit [DecidableEq S] in
/-- The cocycle identity for interacting Boltzmann weights (Georgii identity 4.6), expressed as
`Specification.IsPremodifier`. -/
lemma isPremodifier_boltzmannWeight (β : ℝ) [IsLocallyFinitary Φ] [IsPotential Φ] :
    Specification.IsPremodifier (S := S) (E := E) (boltzmannWeight (Φ := Φ) β) := by
  refine ⟨?_, ?_⟩
  · intro Λ
    exact measurable_boltzmannWeight (Φ := Φ) β Λ
  · intro Λ₁ Λ₂ ζ η hΛ hrestrict
    exact boltzmannWeight_mul_comm_of_hamiltonian_sub_eq (Φ := Φ) β
      (interactingHamiltonian_sub_eq_of_subset_eqOn_compl (Φ := Φ) hΛ hrestrict)

/-! ### Normalization (definition only) -/

section Normalization

/-- The **partition function** (normalizing factor) for the Boltzmann weights in volume `Λ` with
boundary condition `η`. This is just `Specification.premodifierZ` specialized to the Boltzmann
premodifier. -/
noncomputable def partitionFunction (Φ : Potential S E) [IsLocallyFinitary Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν] (Λ : Finset S) (η : S → E) : ℝ≥0∞ :=
  Specification.premodifierZ (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β) Λ η

omit [DecidableEq S] in
/-- The σ-finite-reference partition function for Boltzmann weights.

This is the λ-partition function appearing in Georgii's admissibility condition for σ-finite
reference measures. -/
noncomputable def sigmaFinitePartitionFunction (Φ : Potential S E) [IsLocallyFinitary Φ]
    (β : ℝ) (ν : Measure E) [SigmaFinite ν] (Λ : Finset S) (η : S → E) : ℝ≥0∞ :=
  Specification.sigmaFiniteLambdaZ (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β) Λ η

/-- Admissibility of the Boltzmann premodifier for the reference measure `ν`: every finite-volume
partition function is nonzero and finite. The nonzero part follows automatically for the finite
Hamiltonians in this file; the predicate matches the normalized premodifier API. -/
abbrev IsBoltzmannAdmissible (Φ : Potential S E) [IsLocallyFinitary Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν] : Prop :=
  Specification.IsPremodifierAdmissible (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β)

omit [DecidableEq S] in
/-- σ-finite-reference admissibility of the Boltzmann premodifier. -/
abbrev IsSigmaFiniteBoltzmannAdmissible (Φ : Potential S E) [IsLocallyFinitary Φ]
    (β : ℝ) (ν : Measure E) [SigmaFinite ν] : Prop :=
  Specification.IsSigmaFiniteLambdaAdmissible
    (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β)

omit [DecidableEq S] in
/-- For probability reference measures, the σ-finite-reference and probability partition functions
agree. -/
lemma partitionFunction_eq_sigmaFinitePartitionFunction
    (Φ : Potential S E) [IsLocallyFinitary Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν] (Λ : Finset S) (η : S → E) :
    partitionFunction (S := S) (E := E) Φ β ν Λ η =
      sigmaFinitePartitionFunction (S := S) (E := E) Φ β ν Λ η := by
  exact Specification.premodifierZ_eq_sigmaFiniteLambdaZ
    (S := S) (E := E) (ν := ν) (ρ := boltzmannWeight (Φ := Φ) β) Λ η

omit [DecidableEq S] in
/-- For probability reference measures, the probability and σ-finite Boltzmann admissibility
predicates agree. -/
lemma isBoltzmannAdmissible_iff_isSigmaFiniteBoltzmannAdmissible
    (Φ : Potential S E) [IsLocallyFinitary Φ] (β : ℝ) (ν : Measure E)
    [IsProbabilityMeasure ν] :
    IsBoltzmannAdmissible (S := S) (E := E) Φ β ν ↔
      IsSigmaFiniteBoltzmannAdmissible (S := S) (E := E) Φ β ν := by
  exact Specification.isPremodifierAdmissible_iff_isSigmaFiniteLambdaAdmissible
    (S := S) (E := E) (ν := ν) (ρ := boltzmannWeight (Φ := Φ) β)

omit [DecidableEq S] in
lemma measurable_partitionFunction (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν] (Λ : Finset S) :
    Measurable[cylinderEvents (X := fun _ : S ↦ E) (Λ : Set S)ᶜ]
      (partitionFunction (S := S) (E := E) Φ β ν Λ) := by
  simpa [partitionFunction, Specification.premodifierZ] using
    (Measurable.lintegral_kernel
      (κ := (Specification.isssd (S := S) (E := E) ν Λ))
      (f := boltzmannWeight (Φ := Φ) β Λ)
      (measurable_boltzmannWeight (S := S) (E := E) (Φ := Φ) β Λ))

/-- The (normalized) Gibbs modifier associated to the Boltzmann weights, i.e.
\(\rho'_Λ(η) = \rho_Λ(η) / \int \rho_Λ \, d(\text{isssd}_Λ(η))\). -/
noncomputable def gibbsModifier (Φ : Potential S E) [IsLocallyFinitary Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν] (Λ : Finset S) (η : S → E) : ℝ≥0∞ :=
  boltzmannWeight (Φ := Φ) β Λ η /
    partitionFunction (S := S) (E := E) Φ β ν Λ η

omit [DecidableEq S] in
/-- The normalized Boltzmann density relative to a σ-finite reference measure. -/
noncomputable def sigmaFiniteGibbsModifier (Φ : Potential S E) [IsLocallyFinitary Φ]
    (β : ℝ) (ν : Measure E) [SigmaFinite ν] (Λ : Finset S) (η : S → E) : ℝ≥0∞ :=
  boltzmannWeight (Φ := Φ) β Λ η /
    sigmaFinitePartitionFunction (S := S) (E := E) Φ β ν Λ η

omit [DecidableEq S] in
lemma measurable_gibbsModifier (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν] (Λ : Finset S) :
    Measurable (gibbsModifier (S := S) (E := E) Φ β ν Λ) := by
  have hpre : Specification.IsPremodifier (S := S) (E := E) (boltzmannWeight (Φ := Φ) β) :=
    isPremodifier_boltzmannWeight (Φ := Φ) β
  simpa [gibbsModifier, partitionFunction, Specification.premodifierZ, div_eq_mul_inv] using
    (hpre.measurable_div_isssd (ρ := boltzmannWeight (Φ := Φ) β) ν Λ)

omit [DecidableEq S] in
/-- Measurability of the σ-finite normalized Boltzmann density. -/
lemma measurable_sigmaFiniteGibbsModifier
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [SigmaFinite ν] (Λ : Finset S) :
    Measurable (sigmaFiniteGibbsModifier (S := S) (E := E) Φ β ν Λ) := by
  have hpre : Specification.IsPremodifier (S := S) (E := E) (boltzmannWeight (Φ := Φ) β) :=
    isPremodifier_boltzmannWeight (Φ := Φ) β
  simpa [sigmaFiniteGibbsModifier, sigmaFinitePartitionFunction,
    Specification.sigmaFiniteLambdaZ, div_eq_mul_inv] using
    (Specification.sigmaFinitePremodifierNorm_measurable
      (S := S) (E := E) (ρ := boltzmannWeight (Φ := Φ) β) ν hpre Λ)

omit [DecidableEq S] in
/-- `gibbsModifier` is definitionally the normalized premodifier `premodifierNorm` applied to the
Boltzmann weights. -/
lemma gibbsModifier_eq_premodifierNorm (Φ : Potential S E) [IsLocallyFinitary Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν] :
    gibbsModifier (S := S) (E := E) Φ β ν
      = Specification.premodifierNorm (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β) := by
  funext Λ η
  simp [gibbsModifier, partitionFunction, Specification.premodifierNorm, Specification.premodifierZ]

omit [DecidableEq S] in
/-- `sigmaFiniteGibbsModifier` is definitionally the σ-finite normalized premodifier applied to the
Boltzmann weights. -/
lemma sigmaFiniteGibbsModifier_eq_sigmaFinitePremodifierNorm
    (Φ : Potential S E) [IsLocallyFinitary Φ] (β : ℝ) (ν : Measure E) [SigmaFinite ν] :
    sigmaFiniteGibbsModifier (S := S) (E := E) Φ β ν =
      Specification.sigmaFinitePremodifierNorm
        (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β) := by
  funext Λ η
  simp [sigmaFiniteGibbsModifier, sigmaFinitePartitionFunction,
    Specification.sigmaFinitePremodifierNorm, Specification.sigmaFiniteLambdaZ]

omit [DecidableEq S] in
/-- For probability reference measures, the probability and σ-finite normalized Boltzmann densities
agree. -/
lemma gibbsModifier_eq_sigmaFiniteGibbsModifier
    (Φ : Potential S E) [IsLocallyFinitary Φ] (β : ℝ) (ν : Measure E)
    [IsProbabilityMeasure ν] :
    gibbsModifier (S := S) (E := E) Φ β ν =
      sigmaFiniteGibbsModifier (S := S) (E := E) Φ β ν := by
  rw [gibbsModifier_eq_premodifierNorm,
    sigmaFiniteGibbsModifier_eq_sigmaFinitePremodifierNorm,
    Specification.premodifierNorm_eq_sigmaFinitePremodifierNorm]

omit [DecidableEq S] in
/-- The σ-finite normalized Gibbs modifier has partition function `1` in every finite volume. -/
lemma lintegral_sigmaFiniteGibbsModifier_eq_one
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [SigmaFinite ν]
    (hZ : IsSigmaFiniteBoltzmannAdmissible (S := S) (E := E) Φ β ν)
    (Λ : Finset S) (ξ : S → E) :
    ∫⁻ x, sigmaFiniteGibbsModifier (S := S) (E := E) Φ β ν Λ x
      ∂(Specification.sigmaFiniteLambdaFun (S := S) (E := E) ν Λ ξ) = 1 := by
  let ρ : Finset S → (S → E) → ℝ≥0∞ := boltzmannWeight (Φ := Φ) β
  have hpre : Specification.IsPremodifier (S := S) (E := E) ρ :=
    isPremodifier_boltzmannWeight (Φ := Φ) β
  have hnorm :
      sigmaFiniteGibbsModifier (S := S) (E := E) Φ β ν =
        Specification.sigmaFinitePremodifierNorm (S := S) (E := E) ν ρ := by
    simpa [ρ] using
      sigmaFiniteGibbsModifier_eq_sigmaFinitePremodifierNorm
        (S := S) (E := E) (Φ := Φ) β ν
  rw [hnorm]
  exact Specification.lintegral_sigmaFinitePremodifierNorm_eq_one
    (S := S) (E := E) (ρ := ρ) ν hpre hZ Λ ξ

omit [DecidableEq S] in
/-- The normalized finite-volume Gibbs kernel associated to a σ-finite reference measure.

Its value at a boundary condition `η` is the σ-finite λ-kernel with density
`sigmaFiniteGibbsModifier`. These kernels are proper, and under
`IsSigmaFiniteBoltzmannAdmissible` each finite-volume kernel is Markov. -/
noncomputable def sigmaFiniteGibbsKernel
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [SigmaFinite ν] (Λ : Finset S) :
    Kernel[cylinderEvents Λᶜ] (S → E) (S → E) :=
  Specification.sigmaFinitePremodifierKernel
    (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β)
    (isPremodifier_boltzmannWeight (Φ := Φ) β) Λ

omit [DecidableEq S] in
/-- Evaluation of `sigmaFiniteGibbsKernel`. -/
lemma sigmaFiniteGibbsKernel_apply
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [SigmaFinite ν] (Λ : Finset S) (η : S → E) :
    sigmaFiniteGibbsKernel (S := S) (E := E) Φ β ν Λ η =
      (Specification.sigmaFiniteLambdaFun (S := S) (E := E) ν Λ η).withDensity
        (sigmaFiniteGibbsModifier (S := S) (E := E) Φ β ν Λ) := by
  rw [sigmaFiniteGibbsKernel, Specification.sigmaFinitePremodifierKernel_apply]
  rw [sigmaFiniteGibbsModifier_eq_sigmaFinitePremodifierNorm]

omit [DecidableEq S] in
/-- Under admissibility, each σ-finite Gibbs finite-volume kernel is a probability kernel. -/
lemma isMarkovKernel_sigmaFiniteGibbsKernel
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [SigmaFinite ν]
    (hZ : IsSigmaFiniteBoltzmannAdmissible (S := S) (E := E) Φ β ν)
    (Λ : Finset S) :
    IsMarkovKernel (sigmaFiniteGibbsKernel (S := S) (E := E) Φ β ν Λ) := by
  exact Specification.isMarkovKernel_sigmaFinitePremodifierKernel
    (S := S) (E := E) (ρ := boltzmannWeight (Φ := Φ) β) ν
    (isPremodifier_boltzmannWeight (Φ := Φ) β) hZ Λ

omit [DecidableEq S] in
/-- Each σ-finite Gibbs finite-volume kernel is proper with respect to the outside-volume
σ-algebra. -/
lemma isProper_sigmaFiniteGibbsKernel
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [SigmaFinite ν] (Λ : Finset S) :
    (sigmaFiniteGibbsKernel (S := S) (E := E) Φ β ν Λ).IsProper := by
  exact Specification.isProper_sigmaFinitePremodifierKernel
    (S := S) (E := E) (ρ := boltzmannWeight (Φ := Φ) β) ν
    (isPremodifier_boltzmannWeight (Φ := Φ) β) Λ

omit [DecidableEq S] in
/-- For a probability spin law, admissible Boltzmann premodifiers yield Georgii-consistent
normalized σ-finite Gibbs kernels (DLR projective family). -/
lemma isConsistent_sigmaFiniteGibbsKernel
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : IsSigmaFiniteBoltzmannAdmissible (S := S) (E := E) Φ β ν) :
    IsConsistent (sigmaFiniteGibbsKernel (S := S) (E := E) Φ β ν) := by
  classical
  simpa [sigmaFiniteGibbsKernel] using
    Specification.IsPremodifier.isConsistent_modificationKer_sigmaFinitePremodifierNorm
      (S := S) (E := E)
      (ρ := boltzmannWeight (Φ := Φ) β)
      (isPremodifier_boltzmannWeight (Φ := Φ) β) hZ

omit [DecidableEq S] in
/-- The Σ-finite–reference Gibbs kernels form a Georgii specification once σ-finite Boltzmann
admissibility holds. With a probability spin law this matches **`gibbsSpecificationOfAdmissible`**
kernels
(`sigmaFiniteGibbsSpecificationOfAdmissible_eq_gibbsSpecificationOfAdmissible`). -/
@[simps! -fullyApplied]
noncomputable def sigmaFiniteGibbsSpecificationOfAdmissible
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : IsSigmaFiniteBoltzmannAdmissible (S := S) (E := E) Φ β ν) :
    Specification S E :=
  { toPreSpecification := {
      toFun := sigmaFiniteGibbsKernel (S := S) (E := E) Φ β ν
      isConsistent' := isConsistent_sigmaFiniteGibbsKernel (S := S) (E := E) Φ β ν hZ }
    isMarkovKernel' := fun Λ =>
      isMarkovKernel_sigmaFiniteGibbsKernel (S := S) (E := E) Φ β ν hZ Λ
    isProper' := fun Λ =>
      isProper_sigmaFiniteGibbsKernel (S := S) (E := E) Φ β ν Λ }

omit [DecidableEq S] in
/-- The partition function for Boltzmann weights is never `0` (since the weight is strictly
positive everywhere and `isssd` is a probability measure). -/
lemma premodifierZ_boltzmannWeight_ne_zero (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν] (Λ : Finset S) (η : S → E) :
    Specification.premodifierZ (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β) Λ η ≠ 0 := by
  let μ : Measure (S → E) := Specification.isssd (S := S) (E := E) ν Λ η
  have hμ_univ : μ Set.univ = 1 := by
    simpa [μ] using
      (IsProbabilityMeasure.measure_univ
        (μ := Specification.isssd (S := S) (E := E) ν Λ η))
  have hf_meas : Measurable (boltzmannWeight (Φ := Φ) β Λ) :=
    measurable_boltzmannWeight (Φ := Φ) β Λ
  have hsupport : Function.support (boltzmannWeight (Φ := Φ) β Λ) = Set.univ := by
    ext x
    simp [boltzmannWeight, Real.exp_pos]
  have hpos :
      (0 : ℝ≥0∞) < ∫⁻ x, boltzmannWeight (Φ := Φ) β Λ x ∂μ := by
    have : (0 : ℝ≥0∞) < μ (Function.support (boltzmannWeight (Φ := Φ) β Λ)) := by
      simp [hsupport, hμ_univ]
    exact (MeasureTheory.lintegral_pos_iff_support hf_meas).2 this
  simpa [Specification.premodifierZ, μ] using (ne_of_gt hpos)

omit [DecidableEq S] in
/-- The partition function for Boltzmann weights is never `0`. -/
lemma partitionFunction_ne_zero (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν] (Λ : Finset S) (η : S → E) :
    partitionFunction (S := S) (E := E) Φ β ν Λ η ≠ 0 := by
  simpa [partitionFunction] using
    (premodifierZ_boltzmannWeight_ne_zero (S := S) (E := E) (Φ := Φ) β ν Λ η)

omit [DecidableEq S] in
/-- A uniform finite upper bound on the Boltzmann weight in volume `Λ` makes the partition
function finite. This is a basic reusable criterion for concrete finite-volume models to discharge
the `Z ≠ ⊤` hypothesis in `gibbsSpecification`. -/
lemma partitionFunction_ne_top_of_boltzmannWeight_le
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν] (Λ : Finset S) (η : S → E)
    {C : ℝ≥0∞} (hC : C ≠ ⊤)
    (hbound : ∀ σ : S → E, boltzmannWeight (Φ := Φ) β Λ σ ≤ C) :
    partitionFunction (S := S) (E := E) Φ β ν Λ η ≠ ⊤ := by
  let μ : Measure (S → E) := Specification.isssd (S := S) (E := E) ν Λ η
  haveI : IsProbabilityMeasure μ := by
    dsimp [μ]
    exact ProbabilityTheory.IsMarkovKernel.isProbabilityMeasure
      (κ := Specification.isssd (S := S) (E := E) ν Λ) η
  have hle :
      ∫⁻ σ, boltzmannWeight (Φ := Φ) β Λ σ ∂μ ≤ C :=
    lintegral_le_const (μ := μ) (Filter.Eventually.of_forall hbound)
  exact ne_top_of_le_ne_top hC
    (by simpa [partitionFunction, Specification.premodifierZ, μ] using hle)

omit [DecidableEq S] in
/-- Boltzmann admissibility follows from finiteness of the partition functions; strict positivity of
the Boltzmann weights supplies the `Z ≠ 0` half. -/
lemma isBoltzmannAdmissible_of_premodifierZ_ne_top
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : ∀ (Λ : Finset S) (η : S → E),
      Specification.premodifierZ (S := S) (E := E) ν
        (boltzmannWeight (Φ := Φ) β) Λ η ≠ ⊤) :
    IsBoltzmannAdmissible (S := S) (E := E) Φ β ν := by
  intro Λ η
  refine ⟨?_, ?_⟩
  · simpa using premodifierZ_boltzmannWeight_ne_zero
      (S := S) (E := E) (Φ := Φ) β ν Λ η
  · exact hZ Λ η

omit [DecidableEq S] in
/-- σ-finite Boltzmann admissibility follows from finiteness of the direct λ-partition functions;
for probability reference measures, strict positivity is inherited from the corresponding
`isssd` partition function. -/
lemma isSigmaFiniteBoltzmannAdmissible_of_sigmaFinitePartitionFunction_ne_top
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : ∀ (Λ : Finset S) (η : S → E),
      sigmaFinitePartitionFunction (S := S) (E := E) Φ β ν Λ η ≠ ⊤) :
    IsSigmaFiniteBoltzmannAdmissible (S := S) (E := E) Φ β ν := by
  intro Λ η
  refine ⟨?_, hZ Λ η⟩
  have hEq := partitionFunction_eq_sigmaFinitePartitionFunction
    (S := S) (E := E) (Φ := Φ) β ν Λ η
  exact fun hzero =>
    partitionFunction_ne_zero (S := S) (E := E) (Φ := Φ) β ν Λ η (by
      rw [hEq]
      simpa [sigmaFinitePartitionFunction] using hzero)

omit [DecidableEq S] in
/-- Pointwise **`Z ≠ ⊤`** for the σ-finite λ-partition function yields the normalized
σ-finite-reference Gibbs specification. This constructor uses the λ-partition function directly. -/
noncomputable def sigmaFiniteGibbsSpecificationOfSigmaFinitePartitionFunctionFinite
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : ∀ (Λ : Finset S) (η : S → E),
      sigmaFinitePartitionFunction (S := S) (E := E) Φ β ν Λ η ≠ ⊤) :
    Specification S E :=
  sigmaFiniteGibbsSpecificationOfAdmissible (S := S) (E := E) Φ β ν
    (isSigmaFiniteBoltzmannAdmissible_of_sigmaFinitePartitionFunction_ne_top
      (S := S) (E := E) (Φ := Φ) β ν hZ)

omit [DecidableEq S] in
/-- Pointwise **`Z ≠ ⊤`** for **`premodifierZ`** implies σ-finite Boltzmann admissibility and hence
the normalized σ-finite-reference Gibbs specification.

This is a compatibility constructor for probability-reference APIs stated with `premodifierZ`.
For a hypothesis stated in terms of the λ-partition function, use
`sigmaFiniteGibbsSpecificationOfSigmaFinitePartitionFunctionFinite`. -/
noncomputable def sigmaFiniteGibbsSpecification
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : ∀ (Λ : Finset S) (η : S → E),
      Specification.premodifierZ (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β) Λ η ≠ ⊤) :
    Specification S E :=
  sigmaFiniteGibbsSpecificationOfAdmissible (S := S) (E := E) Φ β ν
    ((isBoltzmannAdmissible_iff_isSigmaFiniteBoltzmannAdmissible (S := S) (E := E) (Φ := Φ) β ν).1
      (isBoltzmannAdmissible_of_premodifierZ_ne_top (S := S) (E := E) (Φ := Φ) β ν hZ))

omit [DecidableEq S] in
/-- Under Boltzmann admissibility, the normalized Gibbs density is an actual modifier for `isssd`
(consistency holds). -/
lemma isModifier_gibbsModifier_of_admissible
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : IsBoltzmannAdmissible (S := S) (E := E) Φ β ν) :
    (Specification.isssd (S := S) (E := E) ν).IsModifier
      (gibbsModifier (S := S) (E := E) Φ β ν) := by
  let ρ : Finset S → (S → E) → ℝ≥0∞ := boltzmannWeight (Φ := Φ) β
  have hpre : Specification.IsPremodifier (S := S) (E := E) ρ :=
    isPremodifier_boltzmannWeight (Φ := Φ) β
  have hmod' :
      (Specification.isssd (S := S) (E := E) ν).IsModifier
        (Specification.premodifierNorm (S := S) (E := E) ν ρ) :=
    Specification.IsPremodifier.isModifier_premodifierNorm
      (S := S) (E := E) (ν := ν) (ρ := ρ) hpre hZ
  simpa [gibbsModifier_eq_premodifierNorm (S := S) (E := E) (Φ := Φ) β ν, ρ] using hmod'

omit [DecidableEq S] in
/-- Under the finiteness assumption `Z ≠ ⊤`, the Gibbs modifier is an actual modifier for `isssd`
(consistency holds). The missing `Z ≠ 0` half is automatic for Boltzmann weights. -/
lemma isModifier_gibbsModifier (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : ∀ (Λ : Finset S) (η : S → E),
      Specification.premodifierZ (S := S) (E := E) ν
        (boltzmannWeight (Φ := Φ) β) Λ η ≠ ⊤) :
    (Specification.isssd (S := S) (E := E) ν).IsModifier
      (gibbsModifier (S := S) (E := E) Φ β ν) :=
  isModifier_gibbsModifier_of_admissible (S := S) (E := E) (Φ := Φ) β ν
    (isBoltzmannAdmissible_of_premodifierZ_ne_top
      (S := S) (E := E) (Φ := Φ) β ν hZ)

/-- The Gibbs specification associated to an admissible Boltzmann premodifier: the modification of
the independent specification by the *normalized* Boltzmann weights. -/
noncomputable def gibbsSpecificationOfAdmissible
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : IsBoltzmannAdmissible (S := S) (E := E) Φ β ν) :
    Specification S E :=
  (Specification.isssd (S := S) (E := E) ν).modification
    (gibbsModifier (S := S) (E := E) Φ β ν)
    (isModifier_gibbsModifier_of_admissible (S := S) (E := E) (Φ := Φ) β ν hZ)

omit [DecidableEq S] in
/-- For probability `ν`, σ-finite normalized Gibbs kernels coincide with kernels of the
`isssd` modification **`gibbsSpecificationOfAdmissible`**. -/
lemma sigmaFiniteGibbsKernel_eq_gibbsSpecificationOfAdmissible_apply
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : IsBoltzmannAdmissible (S := S) (E := E) Φ β ν)
    (Λ : Finset S) (η : S → E) :
    sigmaFiniteGibbsKernel (S := S) (E := E) Φ β ν Λ η =
      gibbsSpecificationOfAdmissible Φ β ν hZ Λ η := by
  simp only [sigmaFiniteGibbsKernel_apply, gibbsSpecificationOfAdmissible,
    Specification.modification_apply]
  have hμ :
      Specification.sigmaFiniteLambdaFun (S := S) (E := E) ν Λ η =
        Specification.isssd (S := S) (E := E) ν Λ η :=
    congr_arg (fun κ : Kernel[cylinderEvents Λᶜ] (S → E) (S → E) => κ η)
      (Specification.sigmaFiniteLambdaFun_eq_isssdFun (S := S) (E := E) (ν := ν) Λ)
  have hρ :
      sigmaFiniteGibbsModifier (S := S) (E := E) Φ β ν Λ =
        gibbsModifier (S := S) (E := E) Φ β ν Λ :=
    funext fun σ =>
      (congr_fun (congr_fun (gibbsModifier_eq_sigmaFiniteGibbsModifier (Φ := Φ) β ν) Λ) σ).symm
  rw [hμ, hρ]

omit [DecidableEq S] in
/-- For probability `ν`, the σ-finite Gibbs specification is equal to the `isssd` modification by
normalized Boltzmann weights. -/
lemma sigmaFiniteGibbsSpecificationOfAdmissible_eq_gibbsSpecificationOfAdmissible
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : IsBoltzmannAdmissible (S := S) (E := E) Φ β ν) :
    sigmaFiniteGibbsSpecificationOfAdmissible (S := S) (E := E) Φ β ν
        ((isBoltzmannAdmissible_iff_isSigmaFiniteBoltzmannAdmissible
          (S := S) (E := E) (Φ := Φ) β ν).1 hZ) =
      gibbsSpecificationOfAdmissible Φ β ν hZ := by
  ext Λ η A hA
  exact congrArg (fun μ : Measure (S → E) => μ A)
    (sigmaFiniteGibbsKernel_eq_gibbsSpecificationOfAdmissible_apply
      (S := S) (E := E) (Φ := Φ) β ν hZ Λ η)

/-- The Gibbs specification associated to a potential: the modification of the independent
specification by the *normalized* Boltzmann weights.

We must assume the partition functions are finite (`Z ≠ ⊤`) to normalize in `ℝ≥0∞`. -/
noncomputable def gibbsSpecification (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : ∀ (Λ : Finset S) (η : S → E),
      Specification.premodifierZ (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β) Λ η ≠ ⊤) :
    Specification S E :=
  gibbsSpecificationOfAdmissible Φ β ν
    (isBoltzmannAdmissible_of_premodifierZ_ne_top
      (S := S) (E := E) (Φ := Φ) β ν hZ)

omit [DecidableEq S] in
/-- For probability `ν`, the σ-finite specification built from `premodifierZ` finiteness agrees
with `gibbsSpecification`. -/
lemma sigmaFiniteGibbsSpecification_eq_gibbsSpecification
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hZ : ∀ (Λ : Finset S) (η : S → E),
      Specification.premodifierZ (S := S) (E := E) ν (boltzmannWeight (Φ := Φ) β) Λ η ≠ ⊤) :
    sigmaFiniteGibbsSpecification (S := S) (E := E) Φ β ν hZ =
      gibbsSpecification Φ β ν hZ := by
  exact sigmaFiniteGibbsSpecificationOfAdmissible_eq_gibbsSpecificationOfAdmissible
    (S := S) (E := E) (Φ := Φ) β ν
    (isBoltzmannAdmissible_of_premodifierZ_ne_top
      (S := S) (E := E) (Φ := Φ) β ν hZ)

/-- Gibbs specification constructed from pointwise finite upper bounds on the Boltzmann weights.

This constructor reduces the finiteness hypothesis for concrete models to a finite upper bound on
the Boltzmann weight in each volume. -/
noncomputable def gibbsSpecificationOfBoltzmannWeightBounded
    (Φ : Potential S E) [IsLocallyFinitary Φ] [IsPotential Φ]
    (β : ℝ) (ν : Measure E) [IsProbabilityMeasure ν]
    (hbound : ∀ (Λ : Finset S), ∃ C : ℝ≥0∞,
      C ≠ ⊤ ∧ ∀ σ : S → E, boltzmannWeight (Φ := Φ) β Λ σ ≤ C) :
    Specification S E :=
  gibbsSpecification Φ β ν fun Λ η => by
    rcases hbound Λ with ⟨C, hC, hle⟩
    simpa [partitionFunction] using
      partitionFunction_ne_top_of_boltzmannWeight_le
        (S := S) (E := E) (Φ := Φ) β ν Λ η hC hle

end Normalization
end InteractingHamiltonian

end Potential
