/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/
module

public import GibbsMeasure.Model.BoundaryLawPhaseTransition
public import GibbsMeasure.Mathlib.MeasureTheory.Function.ConditionalExpectation.Countable

/-!
# Georgii Theorem (11.9)(c): the limit formulas for the boundary law of an extreme point

Sites `ℤ`, a countable state space `E`, counting measure, a positive matrix `Q` with finite
powers (Georgii (11.1)), and its specification `γ^Q`. Theorem (11.9)(c) has two clauses. The
*representation* clause — every `μ ∈ ex 𝒢(Q)` is the measure (11.10) of a boundary law — is
`exists_isBoundaryLaw_boundaryLawMeasure_eq_of_mem_extremePoints`
(`GibbsMeasure/Model/BoundaryLawUniqueness.lean`). This file proves the *quantitative* clause:
for any fixed `a ∈ E` there are sequences `(x_n)`, `(y_n)` in `E` with

`ℓ_i(x)/ℓ_0(a) = lim_n Q^{n+i}(x_n, x)/Q^n(x_n, a)`   `(i < 0)`,
`r_i(y)/r_0(a) = lim_n Q^{n-i}(y, y_n)/Q^n(a, y_n)`   `(i > 0)`.

## Georgii's argument, and where each step lives

For `i < 0`, `μ`-almost every `ω` in `{σ_0 = a}` satisfies

`ℓ_i(x) Q^{-i}(x, a)/ℓ_0(a) = μ(σ_i = x | σ_0 = a) = μ(σ_i = x | 𝓕_{{0}})(ω)`
` = lim_n μ(σ_i = x | 𝓕_{]-∞,-n] ∪ {0}})(ω) = lim_n γ^Q_{]-n,0[}(σ_i = x | ω)`
` = lim_n Q^{n+i}(ω_{-n}, x) Q^{-i}(x, a)/Q^n(ω_{-n}, a)`,

and `μ(σ_0 = a) = ℓ_0(a) r_0(a) > 0` supplies such an `ω`; then `x_n = ω_{-n}`.

* the first equality is the two-site marginal of (11.10),
  `IsBoundaryLaw.boundaryLawMeasure_preimage_inter_preimage`
  (`GibbsMeasure/Model/BoundaryLaw.lean`);
* the second is `MeasureTheory.toReal_measure_inter_fibre_div_ae_eq_condExp_indicator`
  (`GibbsMeasure/Mathlib/MeasureTheory/Function/ConditionalExpectation/Countable.lean`):
  conditioning on a countable-valued coordinate is elementary;
* the third is `tendsto_condExp_indicator_cylinderEvents_union` below — Lévy's downward theorem
  (`MeasureTheory.tendsto_ae_condExp_of_antitone`) together with the triviality of the *left*
  tail of an extreme Gibbs measure (`iInf_cylinderEvents_Iic_le_tailSigmaAlgebra`,
  `GibbsMeasure/Specification/MarkovIntChains.lean`, and Georgii Theorem (7.7)) and the freezing
  lemma `MeasureTheory.exists_ae_eq_single_of_forall_measure_eq_zero_or_one`, which turn the
  limit `μ(· | ⋂_n 𝓕_{]-∞,-n] ∪ {0}})` into a function of `σ_0`, i.e. into `μ(· | 𝓕_{{0}})`;
* the fourth is the DLR equation conditioned down from `𝓕_{]-n,0[ᶜ}` to `𝓕_{]-∞,-n] ∪ {0}}`,
  `Specification.IsGibbsMeasure.condExp_cylinderEvents_ae_eq_toReal_of_dependsOn`
  (`GibbsMeasure/Specification/MarkovIntChains.lean`), legitimate because the kernel value
  depends only on the two boundary spins `ω_{-n}`, `ω_0`;
* the fifth is `transferSpecification_Ioo_apply_preimage_singleton`
  (`GibbsMeasure/Model/BoundaryLawUniqueness.lean`), Georgii (11.2) for a one-site event.

The right-hand statement is the mirror image, with the *right* tail
(`iInf_cylinderEvents_Ici_le_tailSigmaAlgebra`) and the volumes `]0, n[`.

## Main declarations

* `MeasureTheory.GibbsMeasure.Markov.tendsto_condExp_indicator_cylinderEvents_union`: the
  backward-martingale step, for an arbitrary antitone family of coordinate sets avoiding one
  site.
* `MeasureTheory.GibbsMeasure.Markov.IsBoundaryLaw.exists_tendsto_left`,
  `MeasureTheory.GibbsMeasure.Markov.IsBoundaryLaw.exists_tendsto_right`: the two limit formulas
  of Theorem (11.9)(c) for the boundary law of an extreme point.
* `MeasureTheory.GibbsMeasure.Markov.exists_isBoundaryLaw_and_tendsto_of_mem_extremePoints`:
  **Georgii Theorem (11.9)(c) in full** — representation plus both limit formulas.
-/

@[expose] public section

open MeasureTheory ProbabilityTheory Set Filter
open scoped ENNReal Topology

noncomputable section

namespace MeasureTheory.GibbsMeasure.Markov

variable {E : Type*} [MeasurableSpace E] [Countable E] [MeasurableSingletonClass E]

/-! ## The backward-martingale step -/

section CondExpLimit

variable {μ : Measure (ℤ → E)} [IsProbabilityMeasure μ]

/-- **The backward-martingale step of Georgii's proof of Theorem (11.9)(c).** Let `T n` be an
antitone family of coordinate sets avoiding a site `j`, and let `μ` be trivial on `⋂_n 𝓕_{T n}`.
Then for every measurable `A` the conditional expectations `μ(A | 𝓕_{{j} ∪ T n})` converge
`μ`-almost surely to the elementary conditional probability `μ(A | σ_j = ω_j)`.

Lévy's downward theorem gives convergence to `μ(A | ⋂_n 𝓕_{{j} ∪ T n})`; the triviality of
`⋂_n 𝓕_{T n}` makes that limit a function of the single coordinate `σ_j`, hence equal to
`μ(A | 𝓕_{{j}})`; and `𝓕_{{j}}` is generated by a countable-valued random variable, so
conditioning on it is elementary. -/
theorem tendsto_condExp_indicator_cylinderEvents_union (j : ℤ) {T : ℕ → Set ℤ} (hT : Antitone T)
    (hj : ∀ n, j ∉ T n)
    (htriv : ∀ B, MeasurableSet[⨅ n, cylinderEvents (X := fun _ : ℤ ↦ E) (T n)] B →
      μ B = 0 ∨ μ B = 1)
    {A : Set (ℤ → E)} (hA : MeasurableSet A) :
    ∀ᵐ ω ∂μ, Tendsto
      (fun n : ℕ ↦ (μ[A.indicator (1 : (ℤ → E) → ℝ) | cylinderEvents ({j} ∪ T n)]) ω) atTop
      (𝓝 ((μ (A ∩ (fun σ : ℤ → E ↦ σ j) ⁻¹' {ω j})
          / μ ((fun σ : ℤ → E ↦ σ j) ⁻¹' {ω j})).toReal)) := by
  classical
  have hanti : Antitone fun n : ℕ ↦ cylinderEvents (X := fun _ : ℤ ↦ E) ({j} ∪ T n) :=
    fun m n hmn ↦ cylinderEvents_mono (Set.union_subset_union_right _ (hT hmn))
  have hle : ∀ n : ℕ, cylinderEvents (X := fun _ : ℤ ↦ E) ({j} ∪ T n)
      ≤ (MeasurableSpace.pi : MeasurableSpace (ℤ → E)) := fun _ ↦ cylinderEvents_le_pi
  have hiInfle : (⨅ n : ℕ, cylinderEvents (X := fun _ : ℤ ↦ E) ({j} ∪ T n))
      ≤ (MeasurableSpace.pi : MeasurableSpace (ℤ → E)) := (iInf_le _ 0).trans cylinderEvents_le_pi
  obtain ⟨q, hqm, hq⟩ := exists_ae_eq_single_of_forall_measure_eq_zero_or_one (μ := μ) hj htriv
    (f := μ[A.indicator (1 : (ℤ → E) → ℝ) | ⨅ n : ℕ, cylinderEvents ({j} ∪ T n)])
    stronglyMeasurable_condExp.measurable
  have hle0 : cylinderEvents (X := fun _ : ℤ ↦ E) ({j} : Set ℤ)
      ≤ ⨅ n : ℕ, cylinderEvents ({j} ∪ T n) :=
    le_iInf fun _ ↦ cylinderEvents_mono Set.subset_union_left
  have hqmeas : Measurable[cylinderEvents (X := fun _ : ℤ ↦ E) ({j} : Set ℤ)]
      fun σ : ℤ → E ↦ q (σ j) :=
    hqm.comp (measurable_cylinderEvent_apply (X := fun _ : ℤ ↦ E) (by simp))
  have hqint : Integrable (fun σ : ℤ → E ↦ q (σ j)) μ := integrable_condExp.congr hq
  have hstep : μ[A.indicator (1 : (ℤ → E) → ℝ) | cylinderEvents ({j} : Set ℤ)]
      =ᵐ[μ] μ[A.indicator (1 : (ℤ → E) → ℝ) | ⨅ n : ℕ, cylinderEvents ({j} ∪ T n)] := by
    refine ((condExp_condExp_of_le hle0 hiInfle).symm.trans (condExp_congr_ae hq)).trans ?_
    rw [condExp_of_stronglyMeasurable cylinderEvents_le_pi hqmeas.stronglyMeasurable hqint]
    exact hq.symm
  have hcond := toReal_measure_inter_fibre_div_ae_eq_condExp_indicator (μ := μ)
    (Y := fun σ : ℤ → E ↦ σ j) (measurable_pi_apply j) hA
  rw [← cylinderEvents_singleton_int (E := E) j] at hcond
  filter_upwards [tendsto_ae_condExp_of_antitone (μ := μ) (A.indicator (1 : (ℤ → E) → ℝ)) hanti
    hle, hstep, hcond] with ω h1 h2 h3
  rw [h3.trans h2]
  exact h1

end CondExpLimit

/-! ## The kernel values of `γ^Q` on a one-site event depend only on the two boundary spins -/

section DependsOn

variable {Q : E → E → ℝ≥0∞} [Nonempty E]

/-- Georgii (11.2) for the event `{σ_j = x}`: the kernel value depends only on the two boundary
spins `ω_i`, `ω_k`, so it is `𝓕_Δ`-measurable for any `Δ` containing them both. -/
theorem dependsOn_transferSpecification_Ioo_preimage_singleton (hQ : IsTransferMatrix Q)
    {i j k : ℤ} (hij : i < j) (hjk : j < k) (x : E) {Δ : Set ℤ} (hi : i ∈ Δ) (hk : k ∈ Δ) :
    DependsOn (fun ω : ℤ → E ↦ transferSpecification Q hQ (Finset.Ioo i k) ω
      ((fun σ : ℤ → E ↦ σ j) ⁻¹' {x})) Δ := by
  intro ω ω' h
  dsimp only
  rw [transferSpecification_Ioo_apply_preimage_singleton hQ hij hjk ω x,
    transferSpecification_Ioo_apply_preimage_singleton hQ hij hjk ω' x, h _ hi, h _ hk]

/-- **Georgii's `μ(σ_j = x | 𝓕_Δ) = γ^Q_{]i,k[}(σ_j = x | ·)`**, the ℤ-analogue of
`IsGibbsMeasure.condExp_indicator_ae_eq_toReal_of_isMarkovSpecification`
(`GibbsMeasure/Model/TreeBoundaryLawChains.lean`): for a Gibbs measure of `γ^Q`, a volume
`]i, k[` and any set of coordinates `Δ ⊆ ]i, k[ᶜ` containing the two boundary sites `i`, `k`,
the conditional probability of a one-site event inside `]i, k[` is the explicit ratio of powers
of `Q`. -/
theorem condExp_indicator_ae_eq_transferSpecification_Ioo (hQ : IsTransferMatrix Q)
    {μ : Measure (ℤ → E)} [IsProbabilityMeasure μ]
    (hμ : (transferSpecification Q hQ).IsGibbsMeasure μ) {i j k : ℤ} (hij : i < j) (hjk : j < k)
    {Δ : Set ℤ} (hi : i ∈ Δ) (hk : k ∈ Δ) (hΔ : Δ ⊆ ((Finset.Ioo i k : Finset ℤ) : Set ℤ)ᶜ)
    (x : E) :
    μ[((fun σ : ℤ → E ↦ σ j) ⁻¹' {x}).indicator (1 : (ℤ → E) → ℝ) | cylinderEvents Δ]
      =ᵐ[μ] fun ω ↦ ((Kernel.ofMatrix Q ^ (j - i).toNat) (ω i) {x}
          * (Kernel.ofMatrix Q ^ (k - j).toNat) x {ω k}
          / (Kernel.ofMatrix Q ^ (k - i).toNat) (ω i) {ω k}).toReal := by
  refine (hμ.condExp_cylinderEvents_ae_eq_toReal_of_dependsOn hΔ
    ((measurable_pi_apply j) (measurableSet_singleton x))
    (dependsOn_transferSpecification_Ioo_preimage_singleton hQ hij hjk x hi hk)).trans
    (Eventually.of_forall fun ω ↦ ?_)
  dsimp only
  rw [transferSpecification_Ioo_apply_preimage_singleton hQ hij hjk ω x]

end DependsOn

/-! ## Georgii Theorem (11.9)(c): the limit formulas -/

section LimitFormulas

variable {Q : E → E → ℝ≥0∞} [Nonempty E] {ℓ r : ℤ → E → ℝ≥0∞}

/-- **Georgii Theorem (11.9)(c), the left vectors.** If the measure (11.10) of a boundary law
`{ℓ_i, r_i}` is extreme in `𝒢(γ^Q)` then, for every reference state `a`, there is a sequence
`(x_n)` in `E` with `ℓ_i(y)/ℓ_0(a) = lim_n Q^{n+i}(x_n, y)/Q^n(x_n, a)` for all `i < 0` and
`y ∈ E`. Georgii's `x_n` is `ω_{-n}` for a single configuration `ω` with `ω_0 = a` at which the
countably many almost-sure statements all hold; such an `ω` exists because
`μ(σ_0 = a) = ℓ_0(a) r_0(a) > 0`. -/
theorem IsBoundaryLaw.exists_tendsto_left (hQ : IsTransferMatrix Q) (hbl : IsBoundaryLaw Q ℓ r)
    (hμ : boundaryLawMeasure hbl ∈ (G (transferSpecification Q hQ)).extremePoints ℝ≥0∞)
    (a : E) :
    ∃ x : ℕ → E, ∀ i : ℤ, i < 0 → ∀ y : E, Tendsto
      (fun n : ℕ ↦ ((Kernel.ofMatrix Q ^ ((n : ℤ) + i).toNat) (x n) {y}).toReal
        / ((Kernel.ofMatrix Q ^ n) (x n) {a}).toReal) atTop
      (𝓝 ((ℓ i y).toReal / (ℓ 0 a).toReal)) := by
  classical
  set μ := boundaryLawMeasure hbl with hμ_def
  have hgibbs : (transferSpecification Q hQ).IsGibbsMeasure μ :=
    isGibbsMeasure_transferSpecification_boundaryLawMeasure hQ hbl
  set T : ℕ → Set ℤ := fun n ↦ Set.Iic ((-1 : ℤ) - n) with hT_def
  have hTanti : Antitone T := fun m n hmn ↦ Set.Iic_subset_Iic.2 (by
    have : (m : ℤ) ≤ (n : ℤ) := by exact_mod_cast hmn
    omega)
  have hT0 : ∀ n : ℕ, (0 : ℤ) ∉ T n := fun n ↦ by
    have : (0 : ℤ) ≤ (n : ℤ) := Int.natCast_nonneg n
    simp only [hT_def, Set.mem_Iic, not_le]
    omega
  have htriv : ∀ B, MeasurableSet[⨅ n, cylinderEvents (X := fun _ : ℤ ↦ E) (T n)] B →
      μ B = 0 ∨ μ B = 1 := fun B hB ↦
    tailTrivial_of_mem_extremePoints_G hμ B
      (iInf_cylinderEvents_Iic_le_tailSigmaAlgebra (E := E) (-1) B hB)
  -- the explicit finite-volume kernel values, as a function of `n` and `ω`
  set Expl : ℤ → E → ℕ → (ℤ → E) → ℝ≥0∞ := fun i y n ω ↦
    (Kernel.ofMatrix Q ^ (i - ((-1 : ℤ) - n)).toNat) (ω ((-1 : ℤ) - n)) {y}
      * (Kernel.ofMatrix Q ^ ((0 : ℤ) - i).toNat) y {ω 0}
      / (Kernel.ofMatrix Q ^ ((0 : ℤ) - ((-1 : ℤ) - n)).toNat) (ω ((-1 : ℤ) - n)) {ω 0}
    with hExpl_def
  have main : ∀ (i : ℤ) (y : E), i < 0 → ∀ᵐ ω ∂μ, Tendsto
      (fun n : ℕ ↦ (Expl i y n ω).toReal) atTop
      (𝓝 ((μ ((fun σ : ℤ → E ↦ σ i) ⁻¹' {y} ∩ (fun σ : ℤ → E ↦ σ 0) ⁻¹' {ω 0})
          / μ ((fun σ : ℤ → E ↦ σ 0) ⁻¹' {ω 0})).toReal)) := by
    intro i y hi
    have hAmeas : MeasurableSet ((fun σ : ℤ → E ↦ σ i) ⁻¹' {y}) :=
      (measurable_pi_apply i) (measurableSet_singleton y)
    have h1 := tendsto_condExp_indicator_cylinderEvents_union (μ := μ) 0 hTanti hT0 htriv hAmeas
    have h2 : ∀ᵐ ω ∂μ, ∀ n : ℕ, ((-1 : ℤ) - n < i) →
        (μ[((fun σ : ℤ → E ↦ σ i) ⁻¹' {y}).indicator (1 : (ℤ → E) → ℝ)
          | cylinderEvents ({0} ∪ T n)]) ω = (Expl i y n ω).toReal := by
      rw [ae_all_iff]
      intro n
      by_cases hn : (-1 : ℤ) - n < i
      · have hsub : ({0} ∪ T n : Set ℤ)
            ⊆ ((Finset.Ioo ((-1 : ℤ) - n) 0 : Finset ℤ) : Set ℤ)ᶜ := by
          rintro m (hm | hm)
          · rw [Set.mem_singleton_iff] at hm
            simp only [Set.mem_compl_iff, Finset.coe_Ioo, Set.mem_Ioo, not_and, not_lt]
            omega
          · simp only [hT_def, Set.mem_Iic] at hm
            simp only [Set.mem_compl_iff, Finset.coe_Ioo, Set.mem_Ioo, not_and, not_lt]
            omega
        filter_upwards [condExp_indicator_ae_eq_transferSpecification_Ioo hQ hgibbs hn hi
          (Δ := ({0} ∪ T n : Set ℤ)) (Set.mem_union_right _ (by simp [hT_def]))
          (Set.mem_union_left _ rfl) hsub y] with ω hω
        exact fun _ ↦ hω
      · exact Eventually.of_forall fun _ hcon ↦ absurd hcon hn
    filter_upwards [h1, h2] with ω hω1 hω2
    refine hω1.congr' ?_
    filter_upwards [eventually_ge_atTop (-i).toNat] with n hn
    have hn' : ((-i).toNat : ℤ) ≤ (n : ℤ) := by exact_mod_cast hn
    have hni : (-i) ≤ ((-i).toNat : ℤ) := Int.self_le_toNat _
    exact hω2 n (by omega)
  -- combine over the countably many pairs `(i, y)` and pick a configuration with `ω_0 = a`
  have main' : ∀ᵐ ω ∂μ, ∀ (i : ℤ) (y : E), i < 0 → Tendsto
      (fun n : ℕ ↦ (Expl i y n ω).toReal) atTop
      (𝓝 ((μ ((fun σ : ℤ → E ↦ σ i) ⁻¹' {y} ∩ (fun σ : ℤ → E ↦ σ 0) ⁻¹' {ω 0})
          / μ ((fun σ : ℤ → E ↦ σ 0) ⁻¹' {ω 0})).toReal)) := by
    rw [ae_all_iff]
    intro i
    rw [ae_all_iff]
    intro y
    by_cases hi : i < 0
    · filter_upwards [main i y hi] with ω hω using fun _ ↦ hω
    · exact Eventually.of_forall fun _ hcon ↦ absurd hcon hi
  have hfibre : MeasurableSet ((fun σ : ℤ → E ↦ σ (0 : ℤ)) ⁻¹' {a}) :=
    (measurable_pi_apply 0) (measurableSet_singleton a)
  have hmass : μ ((fun σ : ℤ → E ↦ σ (0 : ℤ)) ⁻¹' {a}) = ℓ 0 a * r 0 a := by
    have := hbl.boundaryLawMeasure_preimage_inter_preimage (i := (0 : ℤ)) (j := (0 : ℤ))
      le_rfl a a
    rw [Set.inter_self] at this
    rw [← hμ_def] at this
    rw [this, show ((0 : ℤ) - 0).toNat = 0 by omega, Kernel.pow_zero_apply_singleton]
    simp
  have hposmass : μ ((fun σ : ℤ → E ↦ σ (0 : ℤ)) ⁻¹' {a}) ≠ 0 := by
    rw [hmass]
    exact (ENNReal.mul_pos (hbl.left_pos 0 a).ne' (hbl.right_pos 0 a).ne').ne'
  have hrestne : μ.restrict ((fun σ : ℤ → E ↦ σ (0 : ℤ)) ⁻¹' {a}) ≠ 0 := by
    intro h
    apply hposmass
    have := congrArg (fun ν : Measure (ℤ → E) ↦ ν Set.univ) h
    simpa [Measure.restrict_apply_univ] using this
  have : (ae (μ.restrict ((fun σ : ℤ → E ↦ σ (0 : ℤ)) ⁻¹' {a}))).NeBot :=
    MeasureTheory.ae_neBot.2 hrestne
  obtain ⟨ω, hω0, hωlim⟩ :=
    ((ae_restrict_mem hfibre).and (ae_restrict_of_ae main')).exists
  rw [Set.mem_preimage, Set.mem_singleton_iff] at hω0
  -- the limit, with the explicit constants
  refine ⟨fun n ↦ ω (-(n : ℤ)), fun i hi y ↦ ?_⟩
  set C : ℝ≥0∞ := (Kernel.ofMatrix Q ^ ((0 : ℤ) - i).toNat) y {a} with hC_def
  obtain ⟨m, hm⟩ : ∃ m : ℕ, ((0 : ℤ) - i).toNat = m + 1 := ⟨((0 : ℤ) - i).toNat - 1, by omega⟩
  have hCpos : C ≠ 0 := by rw [hC_def, hm]; exact (hQ.pow_pos m y a).ne'
  have hCtop : C ≠ ⊤ := by rw [hC_def, hm]; exact hQ.pow_ne_top m y a
  have hCreal : (0 : ℝ) < C.toReal := ENNReal.toReal_pos hCpos hCtop
  -- evaluate the limit of the almost-sure statement at this `ω`
  have hnum : μ ((fun σ : ℤ → E ↦ σ i) ⁻¹' {y} ∩ (fun σ : ℤ → E ↦ σ 0) ⁻¹' {ω 0})
      = ℓ i y * C * r 0 a := by
    rw [hω0]
    have := hbl.boundaryLawMeasure_preimage_inter_preimage (i := i) (j := (0 : ℤ)) hi.le y a
    rw [← hμ_def] at this
    rw [this, hC_def]
  have hlim := hωlim i y hi
  rw [hnum, hω0, hmass] at hlim
  -- rewrite the `ℝ≥0∞` limit as a limit of real ratios
  have hL : ((ℓ i y * C * r 0 a) / (ℓ 0 a * r 0 a)).toReal
      = ((ℓ i y).toReal / (ℓ 0 a).toReal) * C.toReal := by
    rw [ENNReal.toReal_div, ENNReal.toReal_mul, ENNReal.toReal_mul, ENNReal.toReal_mul]
    have h1 : (0 : ℝ) < (ℓ 0 a).toReal :=
      ENNReal.toReal_pos (hbl.left_pos 0 a).ne' (hbl.left_ne_top 0 a)
    have h2 : (0 : ℝ) < (r 0 a).toReal :=
      ENNReal.toReal_pos (hbl.right_pos 0 a).ne' (hbl.right_ne_top 0 a)
    field_simp
  have hExplReal : ∀ n : ℕ, (Expl i y n ω).toReal
      = (((Kernel.ofMatrix Q ^ (i - ((-1 : ℤ) - n)).toNat) (ω ((-1 : ℤ) - n)) {y}).toReal
          / ((Kernel.ofMatrix Q ^ ((0 : ℤ) - ((-1 : ℤ) - n)).toNat)
              (ω ((-1 : ℤ) - n)) {a}).toReal) * C.toReal := by
    intro n
    simp only [hExpl_def]
    rw [hω0, ENNReal.toReal_div, ENNReal.toReal_mul, ← hC_def]
    ring
  rw [hL] at hlim
  simp_rw [hExplReal] at hlim
  have hlim' := hlim.div_const C.toReal
  simp_rw [mul_div_cancel_right₀ _ hCreal.ne'] at hlim'
  -- shift the index by one and rewrite the exponents
  rw [← Filter.tendsto_add_atTop_iff_nat 1]
  refine hlim'.congr fun n ↦ ?_
  have he1 : (i - ((-1 : ℤ) - n)).toNat = (((n + 1 : ℕ) : ℤ) + i).toNat := by
    have : (0 : ℤ) ≤ (n : ℤ) := Int.natCast_nonneg n
    push_cast
    omega
  have he2 : ((0 : ℤ) - ((-1 : ℤ) - n)).toNat = n + 1 := by
    have : (0 : ℤ) ≤ (n : ℤ) := Int.natCast_nonneg n
    omega
  have he3 : ((-1 : ℤ) - n) = -((n + 1 : ℕ) : ℤ) := by push_cast; ring
  rw [he1, he2, he3]

/-- **Georgii Theorem (11.9)(c), the right vectors.** The mirror image of
`IsBoundaryLaw.exists_tendsto_left`: for every reference state `a` there is a sequence `(y_n)`
in `E` with `r_i(y)/r_0(a) = lim_n Q^{n-i}(y, y_n)/Q^n(a, y_n)` for all `i > 0` and `y ∈ E`.
The proof is the same, with the *right* tail `⋂_n 𝓕_{[n,∞[}` and the volumes `]0, n[`. -/
theorem IsBoundaryLaw.exists_tendsto_right (hQ : IsTransferMatrix Q) (hbl : IsBoundaryLaw Q ℓ r)
    (hμ : boundaryLawMeasure hbl ∈ (G (transferSpecification Q hQ)).extremePoints ℝ≥0∞)
    (a : E) :
    ∃ z : ℕ → E, ∀ i : ℤ, 0 < i → ∀ y : E, Tendsto
      (fun n : ℕ ↦ ((Kernel.ofMatrix Q ^ ((n : ℤ) - i).toNat) y {z n}).toReal
        / ((Kernel.ofMatrix Q ^ n) a {z n}).toReal) atTop
      (𝓝 ((r i y).toReal / (r 0 a).toReal)) := by
  classical
  set μ := boundaryLawMeasure hbl with hμ_def
  have hgibbs : (transferSpecification Q hQ).IsGibbsMeasure μ :=
    isGibbsMeasure_transferSpecification_boundaryLawMeasure hQ hbl
  set T : ℕ → Set ℤ := fun n ↦ Set.Ici (1 + (n : ℤ)) with hT_def
  have hTanti : Antitone T := fun m n hmn ↦ Set.Ici_subset_Ici.2 (by
    have : (m : ℤ) ≤ (n : ℤ) := by exact_mod_cast hmn
    omega)
  have hT0 : ∀ n : ℕ, (0 : ℤ) ∉ T n := fun n ↦ by
    have : (0 : ℤ) ≤ (n : ℤ) := Int.natCast_nonneg n
    simp only [hT_def, Set.mem_Ici, not_le]
    omega
  have htriv : ∀ B, MeasurableSet[⨅ n, cylinderEvents (X := fun _ : ℤ ↦ E) (T n)] B →
      μ B = 0 ∨ μ B = 1 := fun B hB ↦
    tailTrivial_of_mem_extremePoints_G hμ B
      (iInf_cylinderEvents_Ici_le_tailSigmaAlgebra (E := E) 0 B (by simpa [hT_def] using hB))
  set Expl : ℤ → E → ℕ → (ℤ → E) → ℝ≥0∞ := fun i y n ω ↦
    (Kernel.ofMatrix Q ^ (i - (0 : ℤ)).toNat) (ω 0) {y}
      * (Kernel.ofMatrix Q ^ ((1 + (n : ℤ)) - i).toNat) y {ω (1 + (n : ℤ))}
      / (Kernel.ofMatrix Q ^ ((1 + (n : ℤ)) - (0 : ℤ)).toNat) (ω 0) {ω (1 + (n : ℤ))}
    with hExpl_def
  have main : ∀ (i : ℤ) (y : E), 0 < i → ∀ᵐ ω ∂μ, Tendsto
      (fun n : ℕ ↦ (Expl i y n ω).toReal) atTop
      (𝓝 ((μ ((fun σ : ℤ → E ↦ σ i) ⁻¹' {y} ∩ (fun σ : ℤ → E ↦ σ 0) ⁻¹' {ω 0})
          / μ ((fun σ : ℤ → E ↦ σ 0) ⁻¹' {ω 0})).toReal)) := by
    intro i y hi
    have hAmeas : MeasurableSet ((fun σ : ℤ → E ↦ σ i) ⁻¹' {y}) :=
      (measurable_pi_apply i) (measurableSet_singleton y)
    have h1 := tendsto_condExp_indicator_cylinderEvents_union (μ := μ) 0 hTanti hT0 htriv hAmeas
    have h2 : ∀ᵐ ω ∂μ, ∀ n : ℕ, (i < 1 + (n : ℤ)) →
        (μ[((fun σ : ℤ → E ↦ σ i) ⁻¹' {y}).indicator (1 : (ℤ → E) → ℝ)
          | cylinderEvents ({0} ∪ T n)]) ω = (Expl i y n ω).toReal := by
      rw [ae_all_iff]
      intro n
      by_cases hn : i < 1 + (n : ℤ)
      · have hsub : ({0} ∪ T n : Set ℤ)
            ⊆ ((Finset.Ioo (0 : ℤ) (1 + (n : ℤ)) : Finset ℤ) : Set ℤ)ᶜ := by
          rintro m (hm | hm)
          · rw [Set.mem_singleton_iff] at hm
            simp only [Set.mem_compl_iff, Finset.coe_Ioo, Set.mem_Ioo, not_and, not_lt]
            omega
          · simp only [hT_def, Set.mem_Ici] at hm
            simp only [Set.mem_compl_iff, Finset.coe_Ioo, Set.mem_Ioo, not_and, not_lt]
            omega
        filter_upwards [condExp_indicator_ae_eq_transferSpecification_Ioo hQ hgibbs hi hn
          (Δ := ({0} ∪ T n : Set ℤ)) (Set.mem_union_left _ rfl)
          (Set.mem_union_right _ (by simp [hT_def])) hsub y] with ω hω
        exact fun _ ↦ hω
      · exact Eventually.of_forall fun _ hcon ↦ absurd hcon hn
    filter_upwards [h1, h2] with ω hω1 hω2
    refine hω1.congr' ?_
    filter_upwards [eventually_ge_atTop i.toNat] with n hn
    have hn' : (i.toNat : ℤ) ≤ (n : ℤ) := by exact_mod_cast hn
    have hni : i ≤ (i.toNat : ℤ) := Int.self_le_toNat _
    exact hω2 n (by omega)
  have main' : ∀ᵐ ω ∂μ, ∀ (i : ℤ) (y : E), 0 < i → Tendsto
      (fun n : ℕ ↦ (Expl i y n ω).toReal) atTop
      (𝓝 ((μ ((fun σ : ℤ → E ↦ σ i) ⁻¹' {y} ∩ (fun σ : ℤ → E ↦ σ 0) ⁻¹' {ω 0})
          / μ ((fun σ : ℤ → E ↦ σ 0) ⁻¹' {ω 0})).toReal)) := by
    rw [ae_all_iff]
    intro i
    rw [ae_all_iff]
    intro y
    by_cases hi : 0 < i
    · filter_upwards [main i y hi] with ω hω using fun _ ↦ hω
    · exact Eventually.of_forall fun _ hcon ↦ absurd hcon hi
  have hfibre : MeasurableSet ((fun σ : ℤ → E ↦ σ (0 : ℤ)) ⁻¹' {a}) :=
    (measurable_pi_apply 0) (measurableSet_singleton a)
  have hmass : μ ((fun σ : ℤ → E ↦ σ (0 : ℤ)) ⁻¹' {a}) = ℓ 0 a * r 0 a := by
    have := hbl.boundaryLawMeasure_preimage_inter_preimage (i := (0 : ℤ)) (j := (0 : ℤ))
      le_rfl a a
    rw [Set.inter_self] at this
    rw [← hμ_def] at this
    rw [this, show ((0 : ℤ) - 0).toNat = 0 by omega, Kernel.pow_zero_apply_singleton]
    simp
  have hposmass : μ ((fun σ : ℤ → E ↦ σ (0 : ℤ)) ⁻¹' {a}) ≠ 0 := by
    rw [hmass]
    exact (ENNReal.mul_pos (hbl.left_pos 0 a).ne' (hbl.right_pos 0 a).ne').ne'
  have hrestne : μ.restrict ((fun σ : ℤ → E ↦ σ (0 : ℤ)) ⁻¹' {a}) ≠ 0 := by
    intro h
    apply hposmass
    have := congrArg (fun ν : Measure (ℤ → E) ↦ ν Set.univ) h
    simpa [Measure.restrict_apply_univ] using this
  have : (ae (μ.restrict ((fun σ : ℤ → E ↦ σ (0 : ℤ)) ⁻¹' {a}))).NeBot :=
    MeasureTheory.ae_neBot.2 hrestne
  obtain ⟨ω, hω0, hωlim⟩ :=
    ((ae_restrict_mem hfibre).and (ae_restrict_of_ae main')).exists
  rw [Set.mem_preimage, Set.mem_singleton_iff] at hω0
  refine ⟨fun n ↦ ω (n : ℤ), fun i hi y ↦ ?_⟩
  set C : ℝ≥0∞ := (Kernel.ofMatrix Q ^ (i - (0 : ℤ)).toNat) a {y} with hC_def
  obtain ⟨m, hm⟩ : ∃ m : ℕ, (i - (0 : ℤ)).toNat = m + 1 := ⟨(i - (0 : ℤ)).toNat - 1, by omega⟩
  have hCpos : C ≠ 0 := by rw [hC_def, hm]; exact (hQ.pow_pos m a y).ne'
  have hCtop : C ≠ ⊤ := by rw [hC_def, hm]; exact hQ.pow_ne_top m a y
  have hCreal : (0 : ℝ) < C.toReal := ENNReal.toReal_pos hCpos hCtop
  have hnum : μ ((fun σ : ℤ → E ↦ σ i) ⁻¹' {y} ∩ (fun σ : ℤ → E ↦ σ 0) ⁻¹' {ω 0})
      = ℓ 0 a * C * r i y := by
    rw [hω0, Set.inter_comm]
    have := hbl.boundaryLawMeasure_preimage_inter_preimage (i := (0 : ℤ)) (j := i) hi.le a y
    rw [← hμ_def] at this
    rw [this, hC_def]
  have hlim := hωlim i y hi
  rw [hnum, hω0, hmass] at hlim
  have hL : ((ℓ 0 a * C * r i y) / (ℓ 0 a * r 0 a)).toReal
      = ((r i y).toReal / (r 0 a).toReal) * C.toReal := by
    rw [ENNReal.toReal_div, ENNReal.toReal_mul, ENNReal.toReal_mul, ENNReal.toReal_mul]
    have h1 : (0 : ℝ) < (ℓ 0 a).toReal :=
      ENNReal.toReal_pos (hbl.left_pos 0 a).ne' (hbl.left_ne_top 0 a)
    have h2 : (0 : ℝ) < (r 0 a).toReal :=
      ENNReal.toReal_pos (hbl.right_pos 0 a).ne' (hbl.right_ne_top 0 a)
    field_simp
  have hExplReal : ∀ n : ℕ, (Expl i y n ω).toReal
      = (((Kernel.ofMatrix Q ^ ((1 + (n : ℤ)) - i).toNat) y {ω (1 + (n : ℤ))}).toReal
          / ((Kernel.ofMatrix Q ^ ((1 + (n : ℤ)) - (0 : ℤ)).toNat)
              a {ω (1 + (n : ℤ))}).toReal) * C.toReal := by
    intro n
    simp only [hExpl_def]
    rw [hω0, ENNReal.toReal_div, ENNReal.toReal_mul, ← hC_def]
    ring
  rw [hL] at hlim
  simp_rw [hExplReal] at hlim
  have hlim' := hlim.div_const C.toReal
  simp_rw [mul_div_cancel_right₀ _ hCreal.ne'] at hlim'
  rw [← Filter.tendsto_add_atTop_iff_nat 1]
  refine hlim'.congr fun n ↦ ?_
  have he1 : ((1 + (n : ℤ)) - i).toNat = (((n + 1 : ℕ) : ℤ) - i).toNat := by
    push_cast
    omega
  have he2 : ((1 + (n : ℤ)) - (0 : ℤ)).toNat = n + 1 := by
    have : (0 : ℤ) ≤ (n : ℤ) := Int.natCast_nonneg n
    omega
  have he3 : (1 + (n : ℤ)) = ((n + 1 : ℕ) : ℤ) := by push_cast; ring
  rw [he1, he2, he3]

/-- **Georgii Theorem (11.9)(c), in full.** Every `μ ∈ ex 𝒢(Q)` has a representing boundary law
`{ℓ_i, r_i}`, and for every reference state `a ∈ E` there are sequences `(x_n)`, `(y_n)` in `E`
with

`ℓ_i(x)/ℓ_0(a) = lim_n Q^{n+i}(x_n, x)/Q^n(x_n, a)`   `(i < 0)`,
`r_i(y)/r_0(a) = lim_n Q^{n-i}(y, y_n)/Q^n(a, y_n)`   `(i > 0)`. -/
theorem exists_isBoundaryLaw_and_tendsto_of_mem_extremePoints (hQ : IsTransferMatrix Q)
    {μ : Measure (ℤ → E)} [IsProbabilityMeasure μ]
    (hμ : μ ∈ (G (transferSpecification Q hQ)).extremePoints ℝ≥0∞) (a : E) :
    ∃ (ℓ r : ℤ → E → ℝ≥0∞) (hbl : IsBoundaryLaw Q ℓ r), μ = boundaryLawMeasure hbl ∧
      (∃ x : ℕ → E, ∀ i : ℤ, i < 0 → ∀ y : E, Tendsto
        (fun n : ℕ ↦ ((Kernel.ofMatrix Q ^ ((n : ℤ) + i).toNat) (x n) {y}).toReal
          / ((Kernel.ofMatrix Q ^ n) (x n) {a}).toReal) atTop
        (𝓝 ((ℓ i y).toReal / (ℓ 0 a).toReal))) ∧
      (∃ z : ℕ → E, ∀ i : ℤ, 0 < i → ∀ y : E, Tendsto
        (fun n : ℕ ↦ ((Kernel.ofMatrix Q ^ ((n : ℤ) - i).toNat) y {z n}).toReal
          / ((Kernel.ofMatrix Q ^ n) a {z n}).toReal) atTop
        (𝓝 ((r i y).toReal / (r 0 a).toReal))) := by
  obtain ⟨ℓ, r, hbl, rfl⟩ :=
    exists_isBoundaryLaw_boundaryLawMeasure_eq_of_mem_extremePoints Q hQ hμ
  exact ⟨ℓ, r, hbl, rfl, hbl.exists_tendsto_left hQ hμ a, hbl.exists_tendsto_right hQ hμ a⟩

end LimitFormulas

end MeasureTheory.GibbsMeasure.Markov

end
