/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/
module

public import GibbsMeasure.Mathlib.LinearAlgebra.Matrix.SymmetricRange
public import GibbsMeasure.Mathlib.Probability.Moments.Covariance
public import GibbsMeasure.Mathlib.Probability.Distributions.Gaussian.Limit
public import Mathlib.Probability.Distributions.Gaussian.IsGaussianProcess.Independence
public import Mathlib.Probability.ConditionalExpectation
public import Mathlib.Probability.Martingale.Convergence

/-!
# Conditional expectations of Gaussian processes

* **Gaussian regression** (`ProbabilityTheory.IsGaussianProcess.exists_condExp_eq_affine`): if
  `X : Ω → ℝ` and `Y : ι → Ω → ℝ` (`ι` finite) are jointly Gaussian, then the conditional
  expectation of `X` given the σ-algebra generated by `Y` is an affine function of `Y`:
  `P[X | σ(Y)] = u + ∑ i, v i * Y i` a.e. The coefficients `v` solve `Cov(Y) v = Cov(X, Y)`;
  no invertibility of `Cov(Y)` is assumed
  (`Matrix.IsHermitian.exists_mulVec_eq_of_forall_dotProduct_eq_zero`).
  The residual `X - ∑ v i • Y i` is uncorrelated with, hence (Gaussian) independent of, `Y`, so
  its conditional expectation is its mean.
* **Closure under conditioning** (`ProbabilityTheory.IsGaussianProcess.sum_elim_condExp`): for a
  Gaussian process `X : T → Ω → ℝ` and a countable `s : Set T`, the process obtained by adjoining
  the conditional expectations `P[X t | ⨆ u ∈ s, σ(X u)]` to `X` is again Gaussian. Each such
  conditional expectation is the `L¹`-limit (Lévy's upward theorem,
  `MeasureTheory.tendsto_eLpNorm_condExp`) of conditional expectations given finitely many
  coordinates, which are affine by Gaussian regression, and `L¹`-limits of Gaussian processes are
  Gaussian (`ProbabilityTheory.IsGaussianProcess.of_tendsto_eLpNorm_one`).
-/

@[expose] public section

open MeasureTheory Filter Topology Matrix
open scoped ENNReal NNReal

namespace MeasureTheory

variable {Ω : Type*} {m m0 : MeasurableSpace Ω} {μ : Measure Ω}

/-- **Orthogonality of the conditional-expectation residual.** If `f` is `m`-measurable then
`f` is orthogonal to `g - μ[g | m]`, i.e. `∫ f * (g - μ[g | m]) = 0`. Intended home:
`Mathlib/MeasureTheory/Function/ConditionalExpectation/PullOut.lean`. -/
theorem integral_mul_sub_condExp_eq_zero (hm : m ≤ m0) [SigmaFinite (μ.trim hm)] {f g : Ω → ℝ}
    (hf : AEStronglyMeasurable[m] f μ) (hg : Integrable g μ) (hfg : Integrable (f * g) μ)
    (hfc : Integrable (f * μ[g | m]) μ) :
    ∫ ω, f ω * (g ω - μ[g | m] ω) ∂μ = 0 := by
  have h1 : ∫ ω, (f * g) ω ∂μ = ∫ ω, (f * μ[g | m]) ω ∂μ := by
    rw [← integral_condExp hm (f := f * g)]
    exact integral_congr_ae (condExp_mul_of_aestronglyMeasurable_left hf hfg hg)
  have h2 : (fun ω ↦ f ω * (g ω - μ[g | m] ω)) = fun ω ↦ (f * g) ω - (f * μ[g | m]) ω := by
    funext ω; simp only [Pi.mul_apply]; ring
  rw [h2, integral_sub hfg hfc, h1, sub_self]

end MeasureTheory

namespace ProbabilityTheory

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P : Measure Ω}

/-- Adding a constant to a Gaussian random vector yields a Gaussian random vector. -/
theorem HasGaussianLaw.add_const {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [MeasurableSpace E] [BorelSpace E] {X : Ω → E} (hX : HasGaussianLaw X P) (c : E) :
    HasGaussianLaw (fun ω ↦ X ω + c) P := by
  have hmap : P.map (fun ω ↦ X ω + c) = (P.map X).map (fun x ↦ x + c) := by
    rw [AEMeasurable.map_map_of_aemeasurable (by fun_prop) hX.aemeasurable]
    rfl
  refine ⟨?_⟩
  rw [hmap]
  have := hX.isGaussian_map
  infer_instance

/-- Adding a deterministic function to a Gaussian process yields a Gaussian process. -/
theorem IsGaussianProcess.add_const {T : Type*} {X : T → Ω → ℝ} (hX : IsGaussianProcess X P)
    (c : T → ℝ) : IsGaussianProcess (fun t ω ↦ X t ω + c t) P where
  hasGaussianLaw I := by
    have := (hX.hasGaussianLaw I).add_const (I.restrict c)
    exact this.congr (Filter.Eventually.of_forall fun ω ↦ rfl)

/-- If every coordinate of `Y` is an affine function of finitely many coordinates of the
Gaussian process `X`, then `Y` is a Gaussian process. The affine version of
`ProbabilityTheory.IsGaussianProcess.of_isGaussianProcess`. -/
theorem IsGaussianProcess.of_isGaussianProcess_affine {T S : Type*} {X : T → Ω → ℝ}
    {Y : S → Ω → ℝ} (hX : IsGaussianProcess X P)
    (h : ∀ s, ∃ I : Finset T, ∃ L : (I → ℝ) →L[ℝ] ℝ, ∃ c : ℝ,
      ∀ ω, Y s ω = L (I.restrict (X · ω)) + c) :
    IsGaussianProcess Y P := by
  choose I L c hL using h
  have hY' : IsGaussianProcess (fun s ω ↦ Y s ω - c s) P :=
    hX.of_isGaussianProcess fun s ↦ ⟨I s, L s, fun ω ↦ by rw [hL s ω, add_sub_cancel_right]⟩
  have := hY'.add_const c
  simpa using this

section Regression

variable {ι : Type*} [Fintype ι] {X : Ω → ℝ} {Y : ι → Ω → ℝ}

/-- **Gaussian regression.** If `X` and the finite family `Y` are jointly Gaussian, the
conditional expectation of `X` given the σ-algebra generated by `Y` is an affine function
`u + ∑ i, v i * Y i` of `Y`. -/
theorem IsGaussianProcess.exists_condExp_eq_affine
    (hXY : IsGaussianProcess (fun o : Option ι ↦ o.elim X Y) P) (hX : Measurable X)
    (hY : ∀ i, Measurable (Y i)) :
    ∃ (u : ℝ) (v : ι → ℝ),
      P[X | MeasurableSpace.comap (fun ω i ↦ Y i ω) MeasurableSpace.pi] =ᵐ[P]
        fun ω ↦ u + ∑ i, v i * Y i ω := by
  classical
  have hP : IsProbabilityMeasure P := hXY.isProbabilityMeasure
  have hm : MeasurableSpace.comap (fun ω i ↦ Y i ω) MeasurableSpace.pi ≤ mΩ :=
    (measurable_pi_lambda _ hY).comap_le
  have hYm : ∀ i, Measurable[MeasurableSpace.comap (fun ω i ↦ Y i ω) MeasurableSpace.pi] (Y i) :=
    fun i ↦ (measurable_pi_apply (a := i)).comp
      (comap_measurable (m := MeasurableSpace.pi) (fun ω i ↦ Y i ω))
  generalize hm_def : MeasurableSpace.comap (fun ω i ↦ Y i ω) MeasurableSpace.pi = m at hm hYm ⊢
  have hX2 : MemLp X 2 P := (hXY.hasGaussianLaw_eval none).memLp_two
  have hY2 : ∀ i, MemLp (Y i) 2 P := fun i ↦ (hXY.hasGaussianLaw_eval (some i)).memLp_two
  set C : Matrix ι ι ℝ := fun i j ↦ cov[Y i, Y j; P] with hC_def
  have hC : C.PosSemidef := Matrix.posSemidef_covariance hY2
  set c : ι → ℝ := fun j ↦ cov[X, Y j; P] with hc_def
  -- Solve `C v = c`.
  obtain ⟨v, hv⟩ : ∃ v, C *ᵥ v = c := by
    refine hC.1.exists_mulVec_eq_of_forall_dotProduct_eq_zero fun a ha ↦ ?_
    have hmem : MemLp (∑ j, a j • Y j) 2 P := memLp_finsetSum' _ fun j _ ↦ (hY2 j).const_smul _
    have hvar : Var[∑ j, a j • Y j; P] = 0 := by
      rw [← covariance_self hmem.aestronglyMeasurable.aemeasurable,
        covariance_sum_smul_sum_smul (fun j _ ↦ hY2 j) a a]
      have : a ⬝ᵥ (C *ᵥ a) = ∑ i, ∑ j, a i * a j * C i j := by
        simp only [dotProduct, Matrix.mulVec, Finset.mul_sum]
        exact Finset.sum_congr rfl fun i _ ↦ Finset.sum_congr rfl fun j _ ↦ by ring
      rw [ha, dotProduct_zero] at this
      exact this.symm
    have hconst := ae_eq_integral_of_variance_eq_zero hmem hvar
    calc a ⬝ᵥ c = cov[X, ∑ j, a j • Y j; P] := by
          rw [covariance_sum_right (fun j ↦ (hY2 j).const_smul _) hX2]
          simp only [dotProduct, covariance_smul_right, hc_def]
      _ = cov[X, fun _ ↦ P[∑ j, a j • Y j]; P] := covariance_congr_ae (by rfl) hconst
      _ = 0 := covariance_const_right _
  -- The residual `W` is uncorrelated with, hence independent of, `Y`.
  set W : Ω → ℝ := X - ∑ j, v j • Y j with hW_def
  have hW2 : MemLp W 2 P := hX2.sub (memLp_finsetSum' _ fun j _ ↦ (hY2 j).const_smul _)
  have hcov : ∀ k, cov[W, Y k; P] = 0 := by
    intro k
    rw [hW_def, covariance_sub_left hX2 (memLp_finsetSum' _ fun j _ ↦ (hY2 j).const_smul _) (hY2 k),
      covariance_sum_left (fun j ↦ (hY2 j).const_smul _) (hY2 k)]
    simp only [covariance_smul_left]
    have hk := congrFun hv k
    simp only [Matrix.mulVec, dotProduct, hC_def, hc_def] at hk
    rw [sub_eq_zero, ← hk]
    exact Finset.sum_congr rfl fun j _ ↦ by rw [covariance_comm (Y k), mul_comm]
  have hSum : (∑ j, v j • Y j) = fun a ↦ ∑ j, (v j • Y j) a := funext fun a ↦ Finset.sum_apply _ _ _
  have hWmeas : Measurable[mΩ] W := by
    refine hX.sub ?_
    rw [hSum]
    exact Finset.measurable_sum (m := mΩ) _ fun j _ ↦ (hY j).const_smul _
  have hWY : IsGaussianProcess (Sum.elim (fun _ : Unit ↦ W) Y) P := by
    refine hXY.of_isGaussianProcess fun s ↦ ?_
    cases s with
    | inl _ =>
      refine ⟨Finset.univ, ContinuousLinearMap.proj (R := ℝ) (⟨none, Finset.mem_univ _⟩ :
        (Finset.univ : Finset (Option ι))) - ∑ j, v j • ContinuousLinearMap.proj (R := ℝ)
          (⟨some j, Finset.mem_univ _⟩ : (Finset.univ : Finset (Option ι))), fun ω ↦ ?_⟩
      simp [hW_def, Finset.restrict_def]
    | inr j =>
      refine ⟨{some j}, ContinuousLinearMap.proj (R := ℝ) (⟨some j, Finset.mem_singleton_self _⟩ :
        ({some j} : Finset (Option ι))), fun ω ↦ ?_⟩
      simp [Finset.restrict_def]
  have hindep : IndepFun W (fun ω k ↦ Y k ω) P := by
    have := hWY.indepFun_of_covariance_eq_zero (X := fun _ : Unit ↦ W) (Y := Y)
      (fun _ ↦ hWmeas.aemeasurable (μ := P)) (fun k ↦ (hY k).aemeasurable) (fun _ k ↦ hcov k)
    exact this.comp (measurable_pi_apply ()) measurable_id
  rw [IndepFun_iff_Indep, hm_def] at hindep
  have hcondW : P[W | m] =ᵐ[P] fun _ ↦ P[W] :=
    condExp_indep_eq hWmeas.comap_le hm (comap_measurable W).stronglyMeasurable hindep
  set S : Ω → ℝ := ∑ j, v j • Y j with hS_def
  have hSm : StronglyMeasurable[m] S := by
    refine Measurable.stronglyMeasurable ?_
    rw [hSum]
    exact Finset.measurable_sum (m := m) _ fun j _ ↦ (hYm j).const_smul _
  have hSint : Integrable S P :=
    (memLp_finsetSum' _ fun j _ ↦ (hY2 j).const_smul _).integrable one_le_two
  have hcondS : P[S | m] = S := condExp_of_stronglyMeasurable hm hSm hSint
  have hXeq : X = W + S := by rw [hW_def, hS_def, sub_add_cancel]
  refine ⟨P[W], v, ?_⟩
  rw [hXeq]
  filter_upwards [condExp_add (hW2.integrable one_le_two) hSint m, hcondW] with ω h1 h2
  rw [h1, Pi.add_apply, h2, hcondS, hS_def, Finset.sum_apply]
  simp [smul_eq_mul]

end Regression

/-- The σ-algebra generated by a family of real random variables, seen as one vector-valued
random variable, is the supremum of the σ-algebras generated by its members. -/
theorem _root_.MeasurableSpace.comap_pi_eq_iSup_comap {ι : Type*} (Y : ι → Ω → ℝ) :
    MeasurableSpace.comap (fun ω i ↦ Y i ω) MeasurableSpace.pi =
      ⨆ i, MeasurableSpace.comap (Y i) inferInstance := by
  rw [MeasurableSpace.pi, MeasurableSpace.comap_iSup]
  simp_rw [MeasurableSpace.comap_comp]
  rfl

section Closure

variable {T : Type*} {X : T → Ω → ℝ}

/-- **A Gaussian process is closed under conditioning on countably many of its coordinates.**
For a Gaussian process `X` with measurable coordinates and a countable `s : Set T`, adjoining the
conditional expectations `P[X t | ⨆ u ∈ s, σ(X u)]` to `X` gives a Gaussian process. -/
theorem IsGaussianProcess.sum_elim_condExp (hX : IsGaussianProcess X P)
    (hXm : ∀ t, Measurable (X t)) {s : Set T} (hs : s.Countable) :
    IsGaussianProcess
      (Sum.elim X fun t ↦ P[X t | ⨆ u ∈ s, MeasurableSpace.comap (X u) inferInstance]) P := by
  classical
  have hP : IsProbabilityMeasure P := hX.isProbabilityMeasure
  rcases s.eq_empty_or_nonempty with rfl | hne
  · simp only [Set.mem_empty_iff_false, iSup_false, iSup_bot, condExp_bot]
    refine hX.of_isGaussianProcess_affine fun r ↦ ?_
    cases r with
    | inl u =>
      exact ⟨{u}, ContinuousLinearMap.proj (R := ℝ) (⟨u, Finset.mem_singleton_self _⟩ :
        ({u} : Finset T)), 0, fun ω ↦ by simp [Finset.restrict_def]⟩
    | inr t => exact ⟨∅, 0, P[X t], fun ω ↦ by simp⟩
  obtain ⟨f, rfl⟩ := hs.exists_eq_range hne
  set Δ : ℕ → Finset T := fun n ↦ (Finset.range (n + 1)).image f with hΔ_def
  have hΔmono : Monotone Δ := fun a b hab ↦
    Finset.image_subset_image (Finset.range_subset_range.2 (by omega))
  have hle : ∀ Λ : Finset T, (⨆ u ∈ (Λ : Set T), MeasurableSpace.comap (X u) inferInstance) ≤ mΩ :=
    fun Λ ↦ iSup₂_le fun u _ ↦ (hXm u).comap_le
  set ℱ : Filtration ℕ mΩ :=
    { seq := fun n ↦ ⨆ u ∈ (Δ n : Set T), MeasurableSpace.comap (X u) inferInstance
      mono' := fun a b hab ↦ biSup_mono (Finset.coe_subset.2 (hΔmono hab))
      le' := fun n ↦ hle (Δ n) } with hℱ_def
  have hsup : (⨆ n, ℱ n) = ⨆ u ∈ Set.range f, MeasurableSpace.comap (X u) inferInstance := by
    refine le_antisymm (iSup_le fun n ↦ biSup_mono fun u hu ↦ ?_) (iSup₂_le fun u hu ↦ ?_)
    · obtain ⟨k, _, rfl⟩ := Finset.mem_image.1 hu
      exact ⟨k, rfl⟩
    · obtain ⟨k, rfl⟩ := hu
      exact le_iSup_of_le k (le_iSup₂_of_le (f k) (by simp [hΔ_def]; exact ⟨k, le_rfl, rfl⟩) le_rfl)
  -- Each finite-stage conditional expectation is affine in finitely many coordinates.
  have hreg : ∀ n t, ∃ (u : ℝ) (v : Δ n → ℝ),
      P[X t | ℱ n] =ᵐ[P] fun ω ↦ u + ∑ j, v j * X j ω := by
    intro n t
    have hjoint : IsGaussianProcess (fun o : Option (Δ n) ↦ o.elim (X t) fun j ↦ X j) P := by
      have := hX.comp_right fun o : Option (Δ n) ↦ o.elim t Subtype.val
      refine this.congr fun o ↦ ?_
      cases o <;> rfl
    have hσ : MeasurableSpace.comap (fun ω (j : Δ n) ↦ X j ω) MeasurableSpace.pi = ℱ n := by
      rw [MeasurableSpace.comap_pi_eq_iSup_comap]
      change _ = ⨆ u ∈ (Δ n : Set T), MeasurableSpace.comap (X u) inferInstance
      rw [iSup_subtype']
      rfl
    obtain ⟨u, v, huv⟩ := hjoint.exists_condExp_eq_affine (hXm t) fun j ↦ hXm j
    exact ⟨u, v, hσ ▸ huv⟩
  choose u v huv using hreg
  have hZ : ∀ n, IsGaussianProcess (Sum.elim X fun t ↦ P[X t | ℱ n]) P := by
    intro n
    refine (hX.of_isGaussianProcess_affine (Y := Sum.elim X fun t ω ↦ u n t + ∑ j, v n t j * X j ω)
      fun r ↦ ?_).congr fun r ↦ ?_
    · cases r with
      | inl w =>
        exact ⟨{w}, ContinuousLinearMap.proj (R := ℝ) (⟨w, Finset.mem_singleton_self _⟩ :
          ({w} : Finset T)), 0, fun ω ↦ by simp [Finset.restrict_def]⟩
      | inr t =>
        exact ⟨Δ n, ∑ j, v n t j • ContinuousLinearMap.proj (R := ℝ) j, u n t, fun ω ↦ by
          simp [Finset.restrict_def, add_comm]⟩
    · cases r with
      | inl w => exact Filter.EventuallyEq.rfl
      | inr t => exact (huv n t).symm
  refine IsGaussianProcess.of_tendsto_eLpNorm_one hZ (fun r ↦ ?_) fun r ↦ ?_
  · cases r with
    | inl w => exact (hXm w).aemeasurable
    | inr t =>
      exact (stronglyMeasurable_condExp.mono
        (hsup ▸ iSup_le fun n ↦ ℱ.le n)).measurable.aemeasurable
  · cases r with
    | inl w => simp
    | inr t =>
      have := tendsto_eLpNorm_condExp (μ := P) (ℱ := ℱ) (X t)
      rwa [hsup] at this

end Closure

section Reconstruction

/-- **Conditional law of a function of an independent input.** Let `m ≤ m0`, let `W : Ω → ℝ` be
measurable and independent of `m`, and let `G : Ω × ℝ → Ω` be measurable for `m ⊗ Borel` with
`G (ω, W ω) = ω`. Then the conditional probability of `A` given `m` is
`ω ↦ (μ.map W) {w | G (ω, w) ∈ A}`: conditionally on `m`, the configuration is obtained by feeding
an independent copy of `W` into `G`. -/
theorem condExp_indicator_ae_eq_map_of_indep {m m0 : MeasurableSpace Ω} {μ : Measure Ω}
    [IsProbabilityMeasure μ] (hm : m ≤ m0) {W : Ω → ℝ} (hW : Measurable[m0] W)
    (hindep : Indep m (MeasurableSpace.comap W inferInstance) μ) {G : Ω × ℝ → Ω}
    (hG : Measurable[m.prod inferInstance, m0] G) (hGW : ∀ ω, G (ω, W ω) = ω)
    {A : Set Ω} (hA : MeasurableSet[m0] A) :
    μ[A.indicator 1 | m] =ᵐ[μ] fun ω ↦ ((μ.map W) {w | G (ω, w) ∈ A}).toReal := by
  classical
  set ν : Measure ℝ := μ.map W with hν_def
  have hν : IsProbabilityMeasure ν := Measure.isProbabilityMeasure_map hW.aemeasurable
  have hGA : MeasurableSet[m.prod inferInstance] (G ⁻¹' A) := hG hA
  have hsec : Measurable[m] fun ω ↦ ν {w | G (ω, w) ∈ A} :=
    @measurable_measure_prodMk_left Ω ℝ m _ ν _ _ hGA
  have hid : @Measurable Ω Ω m0 m id := measurable_id.mono hm le_rfl
  have hpair : @Measurable Ω (Ω × ℝ) m0 (m.prod inferInstance) fun ω ↦ (ω, W ω) :=
    @Measurable.prodMk Ω m0 Ω ℝ m _ _ _ hid hW
  have hprod : @Measure.map Ω (Ω × ℝ) m0 (m.prod inferInstance) (fun ω ↦ (ω, W ω)) μ =
      @Measure.prod Ω ℝ m _ (μ.trim hm) ν := by
    have hind : @IndepFun Ω Ω ℝ m0 m _ id W μ := by
      rw [IndepFun_iff_Indep (mβ := m) id W μ, MeasurableSpace.comap_id]
      exact hindep
    have hidae : @AEMeasurable Ω Ω m m0 id μ := @Measurable.aemeasurable Ω Ω m0 m id μ hid
    have := (indepFun_iff_map_prod_eq_prod_map_map (mβ := m) (f := id) (g := W)
      hidae hW.aemeasurable).1 hind
    have h2 : μ.trim hm = @Measure.map Ω Ω m0 m id μ := trim_eq_map hm
    rw [h2]
    exact this
  refine (ae_eq_condExp_of_forall_setIntegral_eq hm
    ((integrable_const (1 : ℝ)).indicator hA) (fun B _ _ ↦ ?_) (fun B hB _ ↦ ?_)
    hsec.ennreal_toReal.stronglyMeasurable.aestronglyMeasurable).symm
  · exact (Integrable.of_bound (C := 1) ((hsec.ennreal_toReal.mono hm le_rfl).aestronglyMeasurable)
      (Filter.Eventually.of_forall fun ω ↦ by
        rw [Real.norm_eq_abs, abs_of_nonneg ENNReal.toReal_nonneg]
        exact ENNReal.toReal_le_of_le_ofReal zero_le_one (by simpa using prob_le_one))).integrableOn
  · -- Both sides equal `μ (A ∩ B)`.
    set C : Set (Ω × ℝ) := {p | p.1 ∈ B} ∩ G ⁻¹' A with hC_def
    have hC : MeasurableSet[m.prod inferInstance] C :=
      (@measurable_fst Ω ℝ m _ _ hB).inter hGA
    have hCsec : ∀ ω, Prod.mk ω ⁻¹' C = if ω ∈ B then {w | G (ω, w) ∈ A} else ∅ := by
      intro ω
      ext w
      by_cases hω : ω ∈ B <;> simp [hC_def, hω]
    have hlhs : ∫ ω in B, ((ν {w | G (ω, w) ∈ A}).toReal) ∂μ = (μ (A ∩ B)).toReal := by
      rw [integral_toReal ((hsec.mono hm le_rfl).aemeasurable.restrict)
        (Filter.Eventually.of_forall fun ω ↦ measure_lt_top _ _)]
      congr 1
      calc ∫⁻ ω in B, ν {w | G (ω, w) ∈ A} ∂μ
          = ∫⁻ ω, ν (Prod.mk ω ⁻¹' C) ∂μ := by
            rw [← lintegral_indicator (hm B hB)]
            refine lintegral_congr fun ω ↦ ?_
            rw [hCsec]
            by_cases hω : ω ∈ B <;> simp [hω]
        _ = ∫⁻ ω, ν (Prod.mk ω ⁻¹' C) ∂(μ.trim hm) :=
            (lintegral_trim hm (@measurable_measure_prodMk_left Ω ℝ m _ ν _ _ hC)).symm
        _ = (@Measure.prod Ω ℝ m _ (μ.trim hm) ν) C :=
            (@Measure.prod_apply Ω ℝ m _ (μ.trim hm) ν _ C hC).symm
        _ = μ ((fun ω ↦ (ω, W ω)) ⁻¹' C) := by
            rw [← hprod, Measure.map_apply hpair hC]
        _ = μ (A ∩ B) := by
            congr 1
            ext ω
            simp [hC_def, hGW, and_comm]
    rw [hlhs, setIntegral_indicator hA, integral_const, smul_eq_mul, mul_one, measureReal_def,
      Measure.restrict_apply_univ, Set.inter_comm]

end Reconstruction

end ProbabilityTheory
