/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/
module

public import Mathlib.Analysis.SpecialFunctions.Exponential
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import GibbsMeasure.Mathlib.Analysis.Calculus.IteratedDeriv.Lemmas

/-!
# One-parameter groups of rotations `t ↦ exp (t A)` of a skew-adjoint operator

For a skew-adjoint operator `A` on a real Hilbert space `V`, `t ↦ exp (t • A)` is a one-parameter
group of unitaries, i.e. of linear isometric equivalences of `V` (`skewAdjoint.expRotation`).
The orbit `t ↦ exp (t • A) y` of a vector is smooth, with second derivative
`exp (t • A) (A (A y))` (`skewAdjoint.iteratedDeriv_two_expRotation_apply`), of norm at most
`‖A‖² ‖y‖`.
-/

@[expose] public section

open NormedSpace

namespace skewAdjoint

variable {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℝ V] [CompleteSpace V]

/-- `t • A` is skew-adjoint when `A` is. -/
lemma smul_mem_skewAdjoint {A : V →L[ℝ] V} (hA : A ∈ skewAdjoint (V →L[ℝ] V)) (t : ℝ) :
    t • A ∈ skewAdjoint (V →L[ℝ] V) :=
  skewAdjoint.smul_mem t hA

/-- `exp (t • A)` is unitary when `A` is skew-adjoint. -/
lemma exp_smul_mem_unitary {A : V →L[ℝ] V} (hA : A ∈ skewAdjoint (V →L[ℝ] V)) (t : ℝ) :
    exp (t • A) ∈ unitary (V →L[ℝ] V) :=
  let +nondep : NormedAlgebra ℚ (V →L[ℝ] V) := .restrictScalars ℚ ℝ _
  exp_mem_unitary_of_mem_skewAdjoint (smul_mem_skewAdjoint hA t)

/-- The one-parameter group of rotations `t ↦ exp (t • A)` generated by a skew-adjoint operator
`A`, as linear isometric equivalences. -/
noncomputable def expRotation {A : V →L[ℝ] V} (hA : A ∈ skewAdjoint (V →L[ℝ] V)) (t : ℝ) :
    V ≃ₗᵢ[ℝ] V :=
  Unitary.linearIsometryEquiv ⟨exp (t • A), exp_smul_mem_unitary hA t⟩

/-- `t ↦ exp (t • A)` is smooth. -/
lemma contDiff_exp_smul (A : V →L[ℝ] V) (n : WithTop ℕ∞) :
    ContDiff ℝ n fun t : ℝ ↦ exp (t • A) := by
  refine contDiff_iff_contDiffAt.2 fun t ↦ ?_
  exact (exp_analytic (𝕂 := ℝ) (t • A)).contDiffAt.comp t
    (contDiff_id.smul contDiff_const).contDiffAt

/-- `d/dt exp (t • A) = exp (t • A) * A`. -/
lemma deriv_exp_smul (A : V →L[ℝ] V) : deriv (fun t : ℝ ↦ exp (t • A)) = fun t ↦ exp (t • A) * A :=
  funext fun t ↦ (hasDerivAt_exp_smul_const A t).deriv

/-- The second derivative of `t ↦ exp (t • A)` is `exp (t • A) * A * A`. -/
lemma iteratedDeriv_two_exp_smul (A : V →L[ℝ] V) (t : ℝ) :
    iteratedDeriv 2 (fun t : ℝ ↦ exp (t • A)) t = exp (t • A) * A * A := by
  rw [iteratedDeriv_succ, iteratedDeriv_one, deriv_exp_smul A]
  exact ((hasDerivAt_exp_smul_const A t).mul_const A).deriv

variable {A : V →L[ℝ] V} (hA : A ∈ skewAdjoint (V →L[ℝ] V))
include hA

@[simp] lemma expRotation_apply (t : ℝ) (y : V) : expRotation hA t y = exp (t • A) y := rfl

/-- The group law `exp (s • A) ∘ exp (t • A) = exp ((s + t) • A)`. -/
lemma expRotation_add (s t : ℝ) (y : V) :
    expRotation hA s (expRotation hA t y) = expRotation hA (s + t) y := by
  let +nondep : NormedAlgebra ℚ (V →L[ℝ] V) := .restrictScalars ℚ ℝ _
  simp only [expRotation_apply]
  rw [add_smul, exp_add_of_commute ((Commute.refl A).smul_left s |>.smul_right t)]
  rfl

lemma expRotation_zero (y : V) : expRotation hA 0 y = y := by
  simp [expRotation_apply]

/-- The orbit `t ↦ exp (t • A) y` is smooth. -/
lemma contDiff_expRotation_apply (n : WithTop ℕ∞) (y : V) :
    ContDiff ℝ n fun t : ℝ ↦ expRotation hA t y :=
  (ContinuousLinearMap.apply ℝ V y).contDiff.comp (contDiff_exp_smul A n)

/-- The second derivative of the orbit `t ↦ exp (t • A) y` is `exp (t • A) (A (A y))`. -/
lemma iteratedDeriv_two_expRotation_apply (t : ℝ) (y : V) :
    iteratedDeriv 2 (fun t : ℝ ↦ expRotation hA t y) t = expRotation hA t (A (A y)) := by
  have := (ContinuousLinearMap.apply ℝ V y).iteratedDeriv_comp_left (n := 2) (x := t)
    (contDiff_exp_smul A 2).contDiffAt
  simp only [Function.comp_def, ContinuousLinearMap.apply_apply] at this
  rw [expRotation_apply]
  change iteratedDeriv 2 (fun t : ℝ ↦ exp (t • A) y) t = _
  rw [this, iteratedDeriv_two_exp_smul A]
  rfl

/-- `‖d²/dt² exp (t • A) y‖ ≤ ‖A‖² ‖y‖`. -/
lemma norm_iteratedDeriv_two_expRotation_apply_le (t : ℝ) (y : V) :
    ‖iteratedDeriv 2 (fun t : ℝ ↦ expRotation hA t y) t‖ ≤ ‖A‖ ^ 2 * ‖y‖ := by
  rw [iteratedDeriv_two_expRotation_apply hA, LinearIsometryEquiv.norm_map, pow_two, mul_assoc]
  exact (A.le_opNorm _).trans (mul_le_mul_of_nonneg_left (A.le_opNorm y) (norm_nonneg A))

end skewAdjoint
