/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/
module

public import GibbsMeasure.Mathlib.Analysis.InnerProductSpace.OrthogonalExtend
public import Mathlib.Geometry.Euclidean.Angle.Oriented.Rotation

/-!
# The special orthogonal group is generated by rotations in planes

Every linear isometric equivalence of positive determinant of a finite-dimensional real inner
product space `F` is a product of *plane rotations*: rotations `o.rotation θ` of a
two-dimensional subspace `K` extended by the identity on `Kᗮ` (`Submodule.orthogonalExtend`).
This is the Cartan–Dieudonné theorem (`LinearIsometryEquiv.reflections_generate_dim`) together
with the fact that a product of two reflections in hyperplanes is a rotation in the plane spanned
by their normal vectors (`Submodule.reflection_mul_reflection_eq_one_or_exists_orthogonalExtend`).

* `LinearIsometryEquiv.det_toLinearEquiv_list_prod`: the determinant of a product of isometries.
* `LinearIsometryEquiv.exists_list_ne_zero_even_length_reflections_prod_of_det_pos`: an isometry
  of positive determinant is a product of an even number of reflections in hyperplanes.
* `LinearIsometryEquiv.exists_list_orthogonalExtend_rotation_prod_of_det_pos`: an isometry of
  positive determinant is a product of plane rotations.

Intended home: `Mathlib/Geometry/Euclidean/Angle/Oriented/Rotation.lean`.
-/

@[expose] public section

open Module Submodule

noncomputable section

namespace LinearIsometryEquiv

section Det

variable {R M : Type*} [CommRing R] [SeminormedAddCommGroup M] [Module R M]

theorem det_toLinearEquiv_mul (e e' : M ≃ₗᵢ[R] M) :
    LinearMap.det ((e * e').toLinearEquiv : M →ₗ[R] M) =
      LinearMap.det (e.toLinearEquiv : M →ₗ[R] M) * LinearMap.det (e'.toLinearEquiv : M →ₗ[R] M) :=
  by rw [← LinearMap.det_comp]; rfl

theorem det_toLinearEquiv_one : LinearMap.det ((1 : M ≃ₗᵢ[R] M).toLinearEquiv : M →ₗ[R] M) = 1 :=
  LinearMap.det_id

theorem det_toLinearEquiv_list_prod (l : List (M ≃ₗᵢ[R] M)) :
    LinearMap.det (l.prod.toLinearEquiv : M →ₗ[R] M) =
      (l.map fun e ↦ LinearMap.det (e.toLinearEquiv : M →ₗ[R] M)).prod := by
  induction l with
  | nil => rw [List.prod_nil, det_toLinearEquiv_one, List.map_nil, List.prod_nil]
  | cons e l ih => rw [List.prod_cons, det_toLinearEquiv_mul, ih, List.map_cons, List.prod_cons]

end Det

end LinearIsometryEquiv

namespace Submodule

variable {F : Type*} [NormedAddCommGroup F] [InnerProductSpace ℝ F]

/-- Reflections in equal subspaces agree. -/
theorem reflection_congr {K L : Submodule ℝ F} [K.HasOrthogonalProjection]
    [L.HasOrthogonalProjection] (h : K = L) : K.reflection = L.reflection := by
  subst h
  rfl

/-- The reflection in the hyperplane orthogonal to `0` is the identity. -/
theorem reflection_orthogonal_span_singleton_zero : (ℝ ∙ (0 : F))ᗮ.reflection = 1 := by
  ext x
  rw [LinearIsometryEquiv.coe_one, id]
  exact reflection_mem_subspace_eq_self
    (mem_orthogonal_singleton_iff_inner_right.2 (inner_zero_left x))

/-- The determinant of the reflection in the hyperplane orthogonal to a non-zero vector is `-1`.
-/
theorem det_reflection_orthogonal_span_singleton [FiniteDimensional ℝ F] {v : F} (hv : v ≠ 0) :
    LinearMap.det ((ℝ ∙ v)ᗮ.reflection.toLinearEquiv : F →ₗ[ℝ] F) = -1 := by
  rw [det_reflection, orthogonal_orthogonal, finrank_span_singleton hv, pow_one]

/-- The product of the reflections in the hyperplanes orthogonal to two non-zero vectors `v`, `w`
is the identity (if `v` and `w` are parallel) or a rotation in the plane `K = span {v, w}`,
extended by the identity on `Kᗮ`. -/
theorem reflection_mul_reflection_eq_one_or_exists_orthogonalExtend [FiniteDimensional ℝ F]
    {v w : F} (hv : v ≠ 0) (hw : w ≠ 0) :
    (ℝ ∙ v)ᗮ.reflection * (ℝ ∙ w)ᗮ.reflection = 1 ∨
      ∃ (K : Submodule ℝ F) (_ : Fact (finrank ℝ K = 2)) (o : Orientation ℝ K (Fin 2))
        (θ : Real.Angle),
        (ℝ ∙ v)ᗮ.reflection * (ℝ ∙ w)ᗮ.reflection = K.orthogonalExtend (o.rotation θ) := by
  set K : Submodule ℝ F := (ℝ ∙ v) ⊔ (ℝ ∙ w) with hKdef
  have hvK : v ∈ K := mem_sup_left (mem_span_singleton_self v)
  have hwK : w ∈ K := mem_sup_right (mem_span_singleton_self w)
  have hK1 : 1 ≤ finrank ℝ K := by
    rw [← finrank_span_singleton (K := ℝ) hv]
    exact finrank_mono le_sup_left
  have hK2 : finrank ℝ K ≤ 2 := by
    have h := finrank_sup_add_finrank_inf_eq (ℝ ∙ v) (ℝ ∙ w)
    rw [finrank_span_singleton hv, finrank_span_singleton hw, ← hKdef] at h
    omega
  rcases (show finrank ℝ K = 1 ∨ finrank ℝ K = 2 by omega) with h1 | h2
  · left
    have hvK' : ℝ ∙ v = K :=
      eq_of_le_of_finrank_eq le_sup_left (by rw [finrank_span_singleton hv, h1])
    obtain ⟨c, rfl⟩ := mem_span_singleton.1 (hvK' ▸ hwK)
    have hc : IsUnit c := isUnit_iff_ne_zero.2 fun h ↦ hw (by rw [h, zero_smul])
    have hspan : (ℝ ∙ c • v)ᗮ = (ℝ ∙ v)ᗮ := by rw [span_singleton_smul_eq hc]
    rw [reflection_congr hspan, reflection_mul_reflection]
  · right
    have hK : Fact (finrank ℝ K = 2) := ⟨h2⟩
    let o : Orientation ℝ K (Fin 2) := (finBasisOfFinrankEq ℝ K h2).orientation
    have hv' : (⟨v, hvK⟩ : K) ≠ 0 := fun h ↦ hv (congrArg Subtype.val h)
    have hw' : (⟨w, hwK⟩ : K) ≠ 0 := fun h ↦ hw (congrArg Subtype.val h)
    have hprod : (ℝ ∙ v)ᗮ.reflection * (ℝ ∙ w)ᗮ.reflection =
        K.orthogonalExtend
          ((ℝ ∙ (⟨v, hvK⟩ : K))ᗮ.reflection * (ℝ ∙ (⟨w, hwK⟩ : K))ᗮ.reflection) := by
      rw [← orthogonalExtend_mul, orthogonalExtend_reflection_orthogonal_span_singleton,
        orthogonalExtend_reflection_orthogonal_span_singleton]
    have hdet : 0 < LinearMap.det
        ((((ℝ ∙ (⟨v, hvK⟩ : K))ᗮ.reflection * (ℝ ∙ (⟨w, hwK⟩ : K))ᗮ.reflection).toLinearEquiv :
          K →ₗ[ℝ] K)) := by
      rw [LinearIsometryEquiv.det_toLinearEquiv_mul, det_reflection_orthogonal_span_singleton hv',
        det_reflection_orthogonal_span_singleton hw']
      norm_num
    obtain ⟨θ, hθ⟩ := o.exists_linearIsometryEquiv_eq_of_det_pos hdet
    exact ⟨K, hK, o, θ, by rw [hprod, hθ]⟩

end Submodule

namespace LinearIsometryEquiv

variable {F : Type*} [NormedAddCommGroup F] [InnerProductSpace ℝ F] [FiniteDimensional ℝ F]

omit [FiniteDimensional ℝ F] in
open Classical in
/-- Reflections in the hyperplanes orthogonal to the zero vectors of a list may be dropped from
the product. -/
theorem prod_map_reflection_filter_ne_zero (l : List F) :
    ((l.filter fun v ↦ decide (v ≠ 0)).map fun v ↦ (ℝ ∙ v)ᗮ.reflection).prod =
      (l.map fun v ↦ (ℝ ∙ v)ᗮ.reflection).prod := by
  induction l with
  | nil => rfl
  | cons v l ih =>
    by_cases hv : v = 0
    · rw [List.filter_cons_of_neg (by simpa using hv), ih, List.map_cons, List.prod_cons, hv,
        reflection_orthogonal_span_singleton_zero, one_mul]
    · rw [List.filter_cons_of_pos (by simpa using hv), List.map_cons, List.map_cons,
        List.prod_cons, List.prod_cons, ih]

/-- An isometry of positive determinant is a product of an even number of reflections in
hyperplanes orthogonal to non-zero vectors. -/
theorem exists_list_ne_zero_even_length_reflections_prod_of_det_pos {φ : F ≃ₗᵢ[ℝ] F}
    (hφ : 0 < LinearMap.det (φ.toLinearEquiv : F →ₗ[ℝ] F)) :
    ∃ l : List F, (∀ v ∈ l, v ≠ 0) ∧ Even l.length ∧
      φ = (l.map fun v ↦ (ℝ ∙ v)ᗮ.reflection).prod := by
  classical
  obtain ⟨l, -, hl⟩ := φ.reflections_generate_dim
  refine ⟨l.filter fun v ↦ decide (v ≠ 0), fun v hv ↦ by simpa using (List.mem_filter.1 hv).2, ?_,
    by rw [prod_map_reflection_filter_ne_zero, hl]⟩
  have hdet : LinearMap.det (φ.toLinearEquiv : F →ₗ[ℝ] F) =
      (-1) ^ (l.filter fun v ↦ decide (v ≠ 0)).length := by
    rw [hl, ← prod_map_reflection_filter_ne_zero, det_toLinearEquiv_list_prod, List.map_map,
      List.map_congr_left (g := fun _ ↦ (-1 : ℝ)) fun v hv ↦ ?_, List.map_const',
      List.prod_replicate]
    exact det_reflection_orthogonal_span_singleton (by simpa using (List.mem_filter.1 hv).2)
  rw [hdet] at hφ
  rcases Nat.even_or_odd (l.filter fun v ↦ decide (v ≠ 0)).length with h | h
  · exact h
  · rw [h.neg_one_pow] at hφ
    norm_num at hφ

/-- A product of an even number of reflections in hyperplanes orthogonal to non-zero vectors is a
product of plane rotations. -/
theorem exists_list_orthogonalExtend_rotation_prod_map_reflection :
    ∀ l : List F, (∀ v ∈ l, v ≠ 0) → Even l.length →
      ∃ L : List (F ≃ₗᵢ[ℝ] F),
        (∀ g ∈ L, ∃ (K : Submodule ℝ F) (_ : Fact (finrank ℝ K = 2))
          (o : Orientation ℝ K (Fin 2)) (θ : Real.Angle), g = K.orthogonalExtend (o.rotation θ)) ∧
        (l.map fun v ↦ (ℝ ∙ v)ᗮ.reflection).prod = L.prod
  | [], _, _ => ⟨[], by simp, by simp⟩
  | [v], _, h => absurd h (by simp)
  | v :: w :: l, hne, hev => by
    obtain ⟨L, hL, hprod⟩ := exists_list_orthogonalExtend_rotation_prod_map_reflection l
      (fun x hx ↦ hne x (by simp [hx])) (by simpa [Nat.even_add_one] using hev)
    have hv : v ≠ 0 := hne v (by simp)
    have hw : w ≠ 0 := hne w (by simp)
    rw [List.map_cons, List.map_cons, List.prod_cons, List.prod_cons, ← mul_assoc, hprod]
    rcases reflection_mul_reflection_eq_one_or_exists_orthogonalExtend hv hw with
      h1 | ⟨K, hK, o, θ, h⟩
    · exact ⟨L, hL, by rw [h1, one_mul]⟩
    · refine ⟨K.orthogonalExtend (o.rotation θ) :: L, ?_, by rw [h, List.prod_cons]⟩
      intro g hg
      rcases List.mem_cons.1 hg with rfl | hg
      · exact ⟨K, hK, o, θ, rfl⟩
      · exact hL g hg

/-- **The special orthogonal group is generated by plane rotations.** Every linear isometric
equivalence of positive determinant of a finite-dimensional real inner product space is a product
of rotations `o.rotation θ` of two-dimensional subspaces `K`, extended by the identity on `Kᗮ`. -/
theorem exists_list_orthogonalExtend_rotation_prod_of_det_pos {φ : F ≃ₗᵢ[ℝ] F}
    (hφ : 0 < LinearMap.det (φ.toLinearEquiv : F →ₗ[ℝ] F)) :
    ∃ L : List (F ≃ₗᵢ[ℝ] F),
      (∀ g ∈ L, ∃ (K : Submodule ℝ F) (_ : Fact (finrank ℝ K = 2))
        (o : Orientation ℝ K (Fin 2)) (θ : Real.Angle), g = K.orthogonalExtend (o.rotation θ)) ∧
      φ = L.prod := by
  obtain ⟨l, hne, hev, rfl⟩ := exists_list_ne_zero_even_length_reflections_prod_of_det_pos hφ
  obtain ⟨L, hL, hprod⟩ := exists_list_orthogonalExtend_rotation_prod_map_reflection l hne hev
  exact ⟨L, hL, hprod⟩

end LinearIsometryEquiv

end
