/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/
module

public import GibbsMeasure.Topology.ClusterPoints
public import GibbsMeasure.Topology.LocalConvergence
public import Mathlib.Analysis.SpecificLimits.Basic
public import Mathlib.MeasureTheory.Integral.Lebesgue.Add
public import Mathlib.MeasureTheory.MeasurableSpace.CountablyGenerated
public import Mathlib.MeasureTheory.Measure.Decomposition.RadonNikodym
public import Mathlib.MeasureTheory.Measure.Sum
public import Mathlib.MeasureTheory.Measure.Trim
public import Mathlib.MeasureTheory.Measure.WithDensity

/-!
# Georgii Proposition (4.15)

A cluster point of a locally equicontinuous sequence of random fields is the limit of a
subsequence.

Georgii's proof, which is the one formalised here, makes **no assumption on the state space**
`(E, ℰ)`. Its point is that, although `𝓕_Λ` need not be countably generated, it always contains
a countably generated sub-σ-algebra `𝒜_Λ` carrying the restrictions `μ_n|𝓕_Λ`: with
`ν = ∑_{n} 2⁻ⁿ μ_n` and `h_{n,Λ}` a Radon–Nikodym density of `μ_n|𝓕_Λ` with respect to `ν|𝓕_Λ`,
one takes for `𝒜_Λ` the σ-algebra generated by the countably many functions `h_{n,Λ}`, and for
`𝒜⁰_Λ` the countable π-system of finite intersections of their sublevel sets. A diagonal
subsequence converges on the countable family `𝒜⁰ = ⋃_Λ 𝒜⁰_Λ`, a Dynkin-system argument (using
the equicontinuity tail estimate `B \ C_m ↓ ∅`) upgrades this to all of `𝒜_Λ`, and finally
`μ_n(A) = ν(h_{n,Λ} 1_A) = ν(h_{n,Λ} f_A) = μ_n(f_A)` for `f_A = ν(1_A | 𝒜_Λ)` transfers the
convergence from `𝒜_Λ` back to `𝓕_Λ`.

## Main statements

* `MeasureTheory.GibbsMeasure.exists_subseq_tendsto_of_mapClusterPt`: Georgii (4.15).
* `MeasureTheory.GibbsMeasure.exists_subseq_tendsto_of_locallyEquicontinuous`: Georgii (4.9)
  and (4.15) combined.
-/

@[expose] public section

open Filter Function MeasurableSpace MeasureTheory MeasureTheory.GibbsMeasure Set Topology
open scoped ENNReal Topology

noncomputable section

namespace MeasureTheory.GibbsMeasure

/-! ### A countable generating π-system for a finite-volume cylinder σ-algebra -/

section PiSystem

variable {α : Type*}

/-- The family of finite intersections of a family of sets: the π-system it generates. -/
def finiteInters (b : Set (Set α)) : Set (Set α) :=
  Set.range fun F : Finset b ↦ ⋂ x ∈ F, (x : Set α)

lemma subset_finiteInters (b : Set (Set α)) : b ⊆ finiteInters b := by
  classical
  intro s hs
  exact ⟨{⟨s, hs⟩}, by simp⟩

lemma countable_finiteInters {b : Set (Set α)} (hb : b.Countable) :
    (finiteInters b).Countable := by
  have := hb.to_subtype
  exact Set.countable_range _

lemma isPiSystem_finiteInters (b : Set (Set α)) : IsPiSystem (finiteInters b) := by
  classical
  rintro _ ⟨F₁, rfl⟩ _ ⟨F₂, rfl⟩ -
  refine ⟨F₁ ∪ F₂, ?_⟩
  ext y
  simp only [Set.mem_iInter, Finset.mem_union, Set.mem_inter_iff]
  constructor
  · intro h
    exact ⟨fun i hi ↦ h i (Or.inl hi), fun i hi ↦ h i (Or.inr hi)⟩
  · rintro ⟨h₁, h₂⟩ i (hi | hi)
    · exact h₁ i hi
    · exact h₂ i hi

lemma generateFrom_finiteInters (b : Set (Set α)) :
    MeasurableSpace.generateFrom (finiteInters b) = MeasurableSpace.generateFrom b := by
  refine le_antisymm (MeasurableSpace.generateFrom_le ?_)
    (MeasurableSpace.generateFrom_mono (subset_finiteInters b))
  rintro _ ⟨F, rfl⟩
  exact F.measurableSet_biInter fun x _ ↦ MeasurableSpace.measurableSet_generateFrom x.2

lemma generateFrom_iUnion' {ι : Sort*} (s : ι → Set (Set α)) :
    MeasurableSpace.generateFrom (⋃ i, s i) = ⨆ i, MeasurableSpace.generateFrom (s i) := by
  refine le_antisymm (MeasurableSpace.generateFrom_le ?_)
    (iSup_le fun i ↦ MeasurableSpace.generateFrom_mono (Set.subset_iUnion s i))
  intro t ht
  obtain ⟨i, hi⟩ := Set.mem_iUnion.1 ht
  exact (le_iSup (fun i ↦ MeasurableSpace.generateFrom (s i)) i) _
    (MeasurableSpace.measurableSet_generateFrom hi)

end PiSystem



/-! ### A countable generating π-system for a σ-algebra generated by countably many functions -/

section FunGen

variable {α : Type*}

/-- The countable family of generators of the σ-algebra generated by a sequence of
`ℝ≥0∞`-valued functions: preimages of a countable generating set of `ℝ≥0∞`. -/
def funGen (h : ℕ → α → ℝ≥0∞) : Set (Set α) :=
  ⋃ n, (fun G ↦ h n ⁻¹' G) '' countableGeneratingSet ℝ≥0∞

lemma countable_funGen (h : ℕ → α → ℝ≥0∞) : (funGen h).Countable :=
  Set.countable_iUnion fun _ ↦ countable_countableGeneratingSet.image _

lemma generateFrom_funGen (h : ℕ → α → ℝ≥0∞) :
    generateFrom (funGen h) = ⨆ n, MeasurableSpace.comap (h n) inferInstance := by
  rw [funGen, generateFrom_iUnion']
  refine iSup_congr fun n ↦ ?_
  rw [← comap_generateFrom, generateFrom_countableGeneratingSet]

lemma measurable_funGen (h : ℕ → α → ℝ≥0∞) (n : ℕ) :
    Measurable[generateFrom (funGen h)] (h n) := by
  rw [generateFrom_funGen]
  intro s hs
  exact le_iSup (fun n ↦ MeasurableSpace.comap (h n) inferInstance) n _ ⟨s, hs, rfl⟩

lemma generateFrom_funGen_le {m : MeasurableSpace α} {h : ℕ → α → ℝ≥0∞}
    (hh : ∀ n, Measurable[m] (h n)) : generateFrom (funGen h) ≤ m := by
  rw [generateFrom_funGen]
  exact iSup_le fun n ↦ measurable_iff_comap_le.1 (hh n)

end FunGen


/-! ### Bounded convergence under setwise convergence on a sub-σ-algebra -/

section BoundedConvergence

variable {α : Type*}

lemma natCast_le_iff_le_floor {r : ℝ≥0∞} (hr : r ≠ ∞) (j : ℕ) :
    ((j : ℕ) : ℝ≥0∞) ≤ r ↔ j ≤ ⌊r.toReal⌋₊ := by
  rw [← ENNReal.toReal_le_toReal (ENNReal.natCast_ne_top j) hr, ENNReal.toReal_natCast]
  exact (Nat.le_floor_iff ENNReal.toReal_nonneg).symm

lemma floor_natCast_le {r : ℝ≥0∞} (hr : r ≠ ∞) : ((⌊r.toReal⌋₊ : ℕ) : ℝ≥0∞) ≤ r :=
  (natCast_le_iff_le_floor hr _).2 le_rfl

lemma le_floor_natCast_add_one {r : ℝ≥0∞} (hr : r ≠ ∞) :
    r ≤ ((⌊r.toReal⌋₊ : ℕ) : ℝ≥0∞) + 1 := by
  have h1 : r.toReal < (⌊r.toReal⌋₊ : ℝ) + 1 := Nat.lt_floor_add_one _
  have h2 : ((⌊r.toReal⌋₊ : ℕ) : ℝ≥0∞) + 1 ≠ ∞ :=
    ENNReal.add_ne_top.2 ⟨ENNReal.natCast_ne_top _, ENNReal.one_ne_top⟩
  rw [← ENNReal.toReal_le_toReal hr h2, ENNReal.toReal_add (ENNReal.natCast_ne_top _)
    ENNReal.one_ne_top, ENNReal.toReal_natCast, ENNReal.toReal_one]
  linarith

/-- The discrete layer-cake approximation `⌊N f⌋ / N` of a `[0,1]`-valued function `f`,
written as a finite sum of indicators of sublevel sets of `f`. -/
def layerApprox (f : α → ℝ≥0∞) (N : ℕ) (x : α) : ℝ≥0∞ :=
  ∑ j ∈ Finset.range N,
    Set.indicator {y | ((j + 1 : ℕ) : ℝ≥0∞) ≤ (N : ℝ≥0∞) * f y} (fun _ ↦ (N : ℝ≥0∞)⁻¹) x

lemma layerApprox_eq {f : α → ℝ≥0∞} {N : ℕ} {x : α}
    (hx : (N : ℝ≥0∞) * f x ≤ (N : ℝ≥0∞)) :
    layerApprox f N x = ((⌊((N : ℝ≥0∞) * f x).toReal⌋₊ : ℕ) : ℝ≥0∞) * (N : ℝ≥0∞)⁻¹ := by
  classical
  have hNt : (N : ℝ≥0∞) ≠ ∞ := ENNReal.natCast_ne_top N
  have hrtop : (N : ℝ≥0∞) * f x ≠ ∞ := ne_top_of_le_ne_top hNt hx
  have hMN : ⌊((N : ℝ≥0∞) * f x).toReal⌋₊ ≤ N := by
    have h1 : ((N : ℝ≥0∞) * f x).toReal ≤ (N : ℝ) := by
      have := ENNReal.toReal_mono hNt hx
      simpa using this
    calc ⌊((N : ℝ≥0∞) * f x).toReal⌋₊ ≤ ⌊(N : ℝ)⌋₊ := Nat.floor_mono h1
      _ = N := Nat.floor_natCast N
  have hfilter : Finset.filter (fun j : ℕ ↦ ((j + 1 : ℕ) : ℝ≥0∞) ≤ (N : ℝ≥0∞) * f x)
      (Finset.range N) = Finset.range ⌊((N : ℝ≥0∞) * f x).toReal⌋₊ := by
    ext j
    simp only [Finset.mem_filter, Finset.mem_range, natCast_le_iff_le_floor hrtop]
    exact ⟨fun h ↦ h.2, fun h ↦ ⟨lt_of_lt_of_le h hMN, h⟩⟩
  rw [layerApprox]
  simp only [Set.indicator_apply, Set.mem_ofPred_eq]
  rw [← Finset.sum_filter, hfilter, Finset.sum_const, Finset.card_range, nsmul_eq_mul]

lemma layerApprox_le_self {f : α → ℝ≥0∞} (hf1 : ∀ x, f x ≤ 1) {N : ℕ} (hN : N ≠ 0) (x : α) :
    layerApprox f N x ≤ f x := by
  have hN0 : (N : ℝ≥0∞) ≠ 0 := by exact_mod_cast hN
  have hNt : (N : ℝ≥0∞) ≠ ∞ := ENNReal.natCast_ne_top N
  have hx : (N : ℝ≥0∞) * f x ≤ (N : ℝ≥0∞) := by
    calc (N : ℝ≥0∞) * f x ≤ (N : ℝ≥0∞) * 1 := by gcongr; exact hf1 x
      _ = (N : ℝ≥0∞) := mul_one _
  have hrtop : (N : ℝ≥0∞) * f x ≠ ∞ := ne_top_of_le_ne_top hNt hx
  rw [layerApprox_eq hx]
  calc ((⌊((N : ℝ≥0∞) * f x).toReal⌋₊ : ℕ) : ℝ≥0∞) * (N : ℝ≥0∞)⁻¹
      ≤ ((N : ℝ≥0∞) * f x) * (N : ℝ≥0∞)⁻¹ := by gcongr; exact floor_natCast_le hrtop
    _ = f x := by
        rw [mul_comm ((N : ℝ≥0∞)) (f x), mul_assoc, ENNReal.mul_inv_cancel hN0 hNt, mul_one]

lemma le_layerApprox_add {f : α → ℝ≥0∞} (hf1 : ∀ x, f x ≤ 1) {N : ℕ} (hN : N ≠ 0) (x : α) :
    f x ≤ layerApprox f N x + (N : ℝ≥0∞)⁻¹ := by
  have hN0 : (N : ℝ≥0∞) ≠ 0 := by exact_mod_cast hN
  have hNt : (N : ℝ≥0∞) ≠ ∞ := ENNReal.natCast_ne_top N
  have hx : (N : ℝ≥0∞) * f x ≤ (N : ℝ≥0∞) := by
    calc (N : ℝ≥0∞) * f x ≤ (N : ℝ≥0∞) * 1 := by gcongr; exact hf1 x
      _ = (N : ℝ≥0∞) := mul_one _
  have hrtop : (N : ℝ≥0∞) * f x ≠ ∞ := ne_top_of_le_ne_top hNt hx
  have hfx : f x = ((N : ℝ≥0∞) * f x) * (N : ℝ≥0∞)⁻¹ := by
    rw [mul_comm ((N : ℝ≥0∞)) (f x), mul_assoc, ENNReal.mul_inv_cancel hN0 hNt, mul_one]
  rw [layerApprox_eq hx]
  calc f x = ((N : ℝ≥0∞) * f x) * (N : ℝ≥0∞)⁻¹ := hfx
    _ ≤ (((⌊((N : ℝ≥0∞) * f x).toReal⌋₊ : ℕ) : ℝ≥0∞) + 1) * (N : ℝ≥0∞)⁻¹ := by
        gcongr; exact le_floor_natCast_add_one hrtop
    _ = ((⌊((N : ℝ≥0∞) * f x).toReal⌋₊ : ℕ) : ℝ≥0∞) * (N : ℝ≥0∞)⁻¹ + (N : ℝ≥0∞)⁻¹ := by
        rw [add_mul, one_mul]

lemma measurableSet_layerSet {a : MeasurableSpace α} {f : α → ℝ≥0∞} (hf : Measurable[a] f)
    (j N : ℕ) : MeasurableSet[a] {y | ((j + 1 : ℕ) : ℝ≥0∞) ≤ (N : ℝ≥0∞) * f y} :=
  measurableSet_le measurable_const (measurable_const.mul hf)

lemma measurable_layerApprox {a : MeasurableSpace α} {f : α → ℝ≥0∞} (hf : Measurable[a] f)
    (N : ℕ) : Measurable[a] (layerApprox f N) := by
  have h : layerApprox f N = fun x ↦ ∑ j ∈ Finset.range N,
      Set.indicator {y | ((j + 1 : ℕ) : ℝ≥0∞) ≤ (N : ℝ≥0∞) * f y} (fun _ ↦ (N : ℝ≥0∞)⁻¹) x := rfl
  rw [h]
  exact Finset.measurable_sum _ fun j _ ↦ measurable_const.indicator (measurableSet_layerSet hf j N)

lemma lintegral_layerApprox {a m0 : MeasurableSpace α} (ha : a ≤ m0)
    {f : α → ℝ≥0∞} (hf : Measurable[a] f) (N : ℕ) (ρ : Measure α) :
    ∫⁻ x, layerApprox f N x ∂ρ
      = ∑ j ∈ Finset.range N,
          (N : ℝ≥0∞)⁻¹ * ρ {y | ((j + 1 : ℕ) : ℝ≥0∞) ≤ (N : ℝ≥0∞) * f y} := by
  have h : ∀ x, layerApprox f N x = ∑ j ∈ Finset.range N,
      Set.indicator {y | ((j + 1 : ℕ) : ℝ≥0∞) ≤ (N : ℝ≥0∞) * f y} (fun _ ↦ (N : ℝ≥0∞)⁻¹) x :=
    fun _ ↦ rfl
  simp only [h]
  rw [lintegral_finsetSum]
  · refine Finset.sum_congr rfl fun j _ ↦ ?_
    exact lintegral_indicator_const (ha _ (measurableSet_layerSet hf j N)) _
  · exact fun j _ ↦ measurable_const.indicator (ha _ (measurableSet_layerSet hf j N))

/-- **Bounded convergence for setwise convergence on a sub-σ-algebra.** If a sequence of
probability measures converges setwise on a sub-σ-algebra `a`, then the integrals of every
`a`-measurable function bounded by `1` converge. -/
lemma tendsto_lintegral_of_tendsto_setwise {a m0 : MeasurableSpace α}
    (ha : a ≤ m0) {ρs : ℕ → Measure α} {ρ : Measure α}
    (hρs : ∀ k, IsProbabilityMeasure (ρs k)) (hρ : IsProbabilityMeasure ρ)
    {f : α → ℝ≥0∞} (hfm : Measurable[a] f) (hf1 : ∀ x, f x ≤ 1)
    (hconv : ∀ B, MeasurableSet[a] B → Tendsto (fun k ↦ ρs k B) atTop (𝓝 (ρ B))) :
    Tendsto (fun k ↦ ∫⁻ x, f x ∂(ρs k)) atTop (𝓝 (∫⁻ x, f x ∂ρ)) := by
  have hlow : ∀ (N : ℕ), N ≠ 0 → ∀ σ : Measure α,
      ∫⁻ x, layerApprox f N x ∂σ ≤ ∫⁻ x, f x ∂σ := fun N hN σ ↦
    lintegral_mono fun x ↦ layerApprox_le_self hf1 hN x
  have hup : ∀ (N : ℕ), N ≠ 0 → ∀ σ : Measure α, IsProbabilityMeasure σ →
      ∫⁻ x, f x ∂σ ≤ ∫⁻ x, layerApprox f N x ∂σ + (N : ℝ≥0∞)⁻¹ := by
    intro N hN σ hσ
    have := hσ
    calc ∫⁻ x, f x ∂σ ≤ ∫⁻ x, (layerApprox f N x + (N : ℝ≥0∞)⁻¹) ∂σ :=
          lintegral_mono fun x ↦ le_layerApprox_add hf1 hN x
      _ = ∫⁻ x, layerApprox f N x ∂σ + (N : ℝ≥0∞)⁻¹ := by
          rw [lintegral_add_right _ measurable_const, lintegral_const, measure_univ, mul_one]
  have hlay : ∀ N : ℕ, N ≠ 0 → Tendsto (fun k ↦ ∫⁻ x, layerApprox f N x ∂(ρs k)) atTop
      (𝓝 (∫⁻ x, layerApprox f N x ∂ρ)) := by
    intro N hN
    simp only [lintegral_layerApprox ha hfm]
    refine tendsto_finsetSum _ fun j _ ↦ ?_
    exact ENNReal.Tendsto.const_mul (hconv _ (measurableSet_layerSet hfm j N))
      (Or.inr (ENNReal.inv_ne_top.2 (Nat.cast_ne_zero.2 hN)))
  refine tendsto_of_le_liminf_of_limsup_le ?_ ?_
  · have haux : Tendsto
        (fun N : ℕ ↦ liminf (fun k ↦ ∫⁻ x, f x ∂(ρs k)) atTop + (N : ℝ≥0∞)⁻¹) atTop
        (𝓝 (liminf (fun k ↦ ∫⁻ x, f x ∂(ρs k)) atTop)) := by
      simpa using (tendsto_const_nhds (x := liminf (fun k ↦ ∫⁻ x, f x ∂(ρs k)) atTop)
        (f := (atTop : Filter ℕ))).add ENNReal.tendsto_inv_nat_nhds_zero
    refine ge_of_tendsto haux ?_
    filter_upwards [eventually_gt_atTop 0] with N hN
    calc ∫⁻ x, f x ∂ρ ≤ ∫⁻ x, layerApprox f N x ∂ρ + (N : ℝ≥0∞)⁻¹ := hup N hN.ne' ρ hρ
      _ ≤ liminf (fun k ↦ ∫⁻ x, f x ∂(ρs k)) atTop + (N : ℝ≥0∞)⁻¹ := by
          gcongr
          rw [← (hlay N hN.ne').liminf_eq]
          exact liminf_le_liminf (Eventually.of_forall fun k ↦ hlow N hN.ne' (ρs k))
  · have haux : Tendsto (fun N : ℕ ↦ ∫⁻ x, f x ∂ρ + (N : ℝ≥0∞)⁻¹) atTop
        (𝓝 (∫⁻ x, f x ∂ρ)) := by
      simpa using (tendsto_const_nhds (x := ∫⁻ x, f x ∂ρ) (f := (atTop : Filter ℕ))).add
        ENNReal.tendsto_inv_nat_nhds_zero
    refine ge_of_tendsto haux ?_
    filter_upwards [eventually_gt_atTop 0] with N hN
    calc limsup (fun k ↦ ∫⁻ x, f x ∂(ρs k)) atTop
        ≤ limsup (fun k ↦ ∫⁻ x, layerApprox f N x ∂(ρs k) + (N : ℝ≥0∞)⁻¹) atTop :=
          limsup_le_limsup (Eventually.of_forall fun k ↦ hup N hN.ne' (ρs k) (hρs k))
      _ = ∫⁻ x, layerApprox f N x ∂ρ + (N : ℝ≥0∞)⁻¹ :=
          ((hlay N hN.ne').add tendsto_const_nhds).limsup_eq
      _ ≤ ∫⁻ x, f x ∂ρ + (N : ℝ≥0∞)⁻¹ := add_le_add (hlow N hN.ne' ρ) le_rfl

end BoundedConvergence

/-! ### Radon–Nikodym densities on a sub-σ-algebra -/

section LocalDensity

variable {α : Type*}

/-- **Georgii's `h_{n,Λ}`.** A Radon–Nikodym density of `ρ` restricted to the sub-σ-algebra `m`
with respect to `ν` restricted to `m`. -/
def localDensity {m m0 : MeasurableSpace α} (hm : m ≤ m0) (ρ ν : Measure α) : α → ℝ≥0∞ :=
  (ρ.trim hm).rnDeriv (ν.trim hm)

lemma measurable_localDensity {m m0 : MeasurableSpace α} (hm : m ≤ m0) (ρ ν : Measure α) :
    Measurable[m] (localDensity hm ρ ν) :=
  Measure.measurable_rnDeriv _ _

lemma absolutelyContinuous_trim {m m0 : MeasurableSpace α} (hm : m ≤ m0) {ρ ν : Measure α}
    (hρν : ρ ≪ ν) : (ρ.trim hm) ≪ (ν.trim hm) := by
  intro s hs
  obtain ⟨t, hst, htm, ht0⟩ := @exists_measurable_superset_of_null α m (ν.trim hm) s hs
  refine measure_mono_null hst ?_
  rw [trim_measurableSet_eq hm htm] at ht0 ⊢
  exact hρν ht0

/-- **Georgii (4.15).** If `h` is a density of `ρ|_m` with respect to `ν|_m`, then
`ρ(g) = ν(h g)` for every `m`-measurable `g ≥ 0`. -/
lemma lintegral_localDensity_mul {m m0 : MeasurableSpace α} (hm : m ≤ m0) {ρ ν : Measure α}
    [IsFiniteMeasure ρ] [IsFiniteMeasure ν] (hρν : ρ ≪ ν) {g : α → ℝ≥0∞} (hg : Measurable[m] g) :
    ∫⁻ x, g x ∂ρ = ∫⁻ x, localDensity hm ρ ν x * g x ∂ν := by
  have hwd : (ν.trim hm).withDensity (localDensity hm ρ ν) = ρ.trim hm :=
    Measure.withDensity_rnDeriv_eq _ _ (absolutelyContinuous_trim hm hρν)
  calc ∫⁻ x, g x ∂ρ = ∫⁻ x, g x ∂(ρ.trim hm) := (lintegral_trim hm hg).symm
    _ = ∫⁻ x, g x ∂((ν.trim hm).withDensity (localDensity hm ρ ν)) := by rw [hwd]
    _ = ∫⁻ x, (localDensity hm ρ ν * g) x ∂(ν.trim hm) :=
        lintegral_withDensity_eq_lintegral_mul _ (measurable_localDensity hm ρ ν) hg
    _ = ∫⁻ x, localDensity hm ρ ν x * g x ∂ν :=
        lintegral_trim hm ((measurable_localDensity hm ρ ν).mul hg)

/-- **Georgii's `f_A = ν(1_A | 𝒜_Λ)`**, realized as a Radon–Nikodym density of `ν(A ∩ ·)|_a`
with respect to `ν|_a`, truncated at `1`. -/
def condDensity {a m0 : MeasurableSpace α} (ha : a ≤ m0) (ν : Measure α) (A : Set α) :
    α → ℝ≥0∞ :=
  fun x ↦ min (localDensity ha (ν.restrict A) ν x) 1

lemma measurable_condDensity {a m0 : MeasurableSpace α} (ha : a ≤ m0) (ν : Measure α)
    (A : Set α) : Measurable[a] (condDensity ha ν A) :=
  (measurable_localDensity ha _ _).min measurable_const

lemma condDensity_le_one {a m0 : MeasurableSpace α} (ha : a ≤ m0) (ν : Measure α)
    (A : Set α) (x : α) : condDensity ha ν A x ≤ 1 := min_le_right _ _

lemma condDensity_ae_eq {a m0 : MeasurableSpace α} (ha : a ≤ m0) (ν : Measure α)
    [IsFiniteMeasure ν] (A : Set α) :
    condDensity ha ν A =ᵐ[ν] localDensity ha (ν.restrict A) ν := by
  have hle : (ν.restrict A).trim ha ≤ ν.trim ha :=
    Measure.le_iff.2 fun s hs ↦ by
      rw [trim_measurableSet_eq ha hs, trim_measurableSet_eq ha hs]
      exact Measure.le_iff'.1 Measure.restrict_le_self s
  have h1 : localDensity ha (ν.restrict A) ν ≤ᵐ[ν] 1 :=
    ae_of_ae_trim ha (Measure.rnDeriv_le_one_of_le hle)
  filter_upwards [h1] with x hx
  simpa [condDensity] using min_eq_left hx

/-- **Georgii (4.15), the transfer step.** For an `a`-measurable `g ≥ 0` the integral of `g` over
`A` equals the integral of `g` against the conditional density `f_A`; this is what makes the
`σ`-algebra `a` generated by the densities carry the restrictions of the measures. -/
lemma setLIntegral_eq_lintegral_mul_condDensity {a m0 : MeasurableSpace α} (ha : a ≤ m0)
    (ν : Measure α) [IsFiniteMeasure ν] (A : Set α) {g : α → ℝ≥0∞} (hg : Measurable[a] g) :
    ∫⁻ x in A, g x ∂ν = ∫⁻ x, g x * condDensity ha ν A x ∂ν := by
  have habs : ν.restrict A ≪ ν := Measure.absolutelyContinuous_of_le Measure.restrict_le_self
  have h1 : ∫⁻ x in A, g x ∂ν = ∫⁻ x, localDensity ha (ν.restrict A) ν x * g x ∂ν :=
    lintegral_localDensity_mul ha habs hg
  rw [h1]
  refine lintegral_congr_ae ?_
  filter_upwards [condDensity_ae_eq ha ν A] with x hx
  rw [hx, mul_comm]

end LocalDensity

/-! ### Georgii's countable algebra `𝒜⁰` of (4.15) -/

section Seeds

open MeasurableSpace

variable {S E : Type*} [MeasurableSpace E]

/-- The sequence `μ₀ = μ, μ₁ = μs 0, μ₂ = μs 1, …`: the cluster point followed by the sequence. -/
def clusterSeq (μs : ℕ → Measure (S → E)) (μ : Measure (S → E)) : ℕ → Measure (S → E)
  | 0 => μ
  | (n + 1) => μs n

lemma isProbabilityMeasure_clusterSeq {μs : ℕ → Measure (S → E)} {μ : Measure (S → E)}
    (hμs : ∀ n, IsProbabilityMeasure (μs n)) (hμ : IsProbabilityMeasure μ) (n : ℕ) :
    IsProbabilityMeasure (clusterSeq μs μ n) := by
  cases n with
  | zero => exact hμ
  | succ n => exact hμs n

/-- **Georgii's `ν = ∑_{n ≥ 1} 2⁻ⁿ μₙ`** (here also charging the cluster point `μ`, which makes
the densities of `μ` available as well). -/
def domMeasure (μs : ℕ → Measure (S → E)) (μ : Measure (S → E)) : Measure (S → E) :=
  Measure.sum fun n ↦ ((2 : ℝ≥0∞)⁻¹ ^ n) • clusterSeq μs μ n

lemma clusterSeq_absolutelyContinuous_domMeasure {μs : ℕ → Measure (S → E)}
    {μ : Measure (S → E)} (n : ℕ) : clusterSeq μs μ n ≪ domMeasure μs μ := by
  intro s hs
  have h1 : ((2 : ℝ≥0∞)⁻¹ ^ n) • clusterSeq μs μ n ≤ domMeasure μs μ :=
    Measure.le_sum _ n
  have h2 : ((2 : ℝ≥0∞)⁻¹ ^ n) * (clusterSeq μs μ n) s = 0 := by
    have h := Measure.le_iff'.1 h1 s
    rw [hs, nonpos_iff_eq_zero] at h
    simpa using h
  have h3 : ((2 : ℝ≥0∞)⁻¹ ^ n) ≠ 0 := by simp
  rcases mul_eq_zero.1 h2 with h | h
  · exact absurd h h3
  · exact h

lemma isFiniteMeasure_domMeasure {μs : ℕ → Measure (S → E)} {μ : Measure (S → E)}
    (hμs : ∀ n, IsProbabilityMeasure (μs n)) (hμ : IsProbabilityMeasure μ) :
    IsFiniteMeasure (domMeasure μs μ) := by
  constructor
  have h1 : domMeasure μs μ Set.univ
      = ∑' n, ((2 : ℝ≥0∞)⁻¹ ^ n) * (clusterSeq μs μ n) Set.univ := by
    rw [domMeasure, Measure.sum_apply _ MeasurableSet.univ]
    simp
  have h2 : ∀ n, (clusterSeq μs μ n) Set.univ = 1 := fun n ↦ by
    have := isProbabilityMeasure_clusterSeq hμs hμ n
    exact measure_univ
  rw [h1]
  simp only [h2, mul_one, ENNReal.tsum_geometric_two]
  exact ENNReal.ofNat_lt_top

/-- **Georgii's densities `h_{n,Λ}`**: a density of `μₙ|𝓕_Λ` with respect to `ν|𝓕_Λ`. -/
def localDens (μs : ℕ → Measure (S → E)) (μ : Measure (S → E)) (Λ : Finset S) (n : ℕ) :
    (S → E) → ℝ≥0∞ :=
  localDensity (m := cylinderEvents (X := fun _ : S ↦ E) (Λ : Set S)) cylinderEvents_le_pi
    (clusterSeq μs μ n) (domMeasure μs μ)

/-- **Georgii's `𝒜_Λ`**: the σ-algebra generated by the densities `h_{n,Λ}`, `n ≥ 1`. -/
@[instance_reducible]
def densAlgebra (μs : ℕ → Measure (S → E)) (μ : Measure (S → E)) (Λ : Finset S) :
    MeasurableSpace (S → E) :=
  generateFrom (funGen (localDens μs μ Λ))

/-- **Georgii's `𝒜⁰_Λ`**: a *countable* π-system generating `𝒜_Λ`, whatever the state space. -/
def densSeedsLocal (μs : ℕ → Measure (S → E)) (μ : Measure (S → E)) (Λ : Finset S) :
    Set (Set (S → E)) :=
  finiteInters (funGen (localDens μs μ Λ))

variable (μs : ℕ → Measure (S → E)) (μ : Measure (S → E))

lemma countable_densSeedsLocal (Λ : Finset S) : (densSeedsLocal μs μ Λ).Countable :=
  countable_finiteInters (countable_funGen _)

lemma isPiSystem_densSeedsLocal (Λ : Finset S) : IsPiSystem (densSeedsLocal μs μ Λ) :=
  isPiSystem_finiteInters _

lemma generateFrom_densSeedsLocal (Λ : Finset S) :
    generateFrom (densSeedsLocal μs μ Λ) = densAlgebra μs μ Λ :=
  generateFrom_finiteInters _

lemma measurable_localDens (Λ : Finset S) (n : ℕ) :
    Measurable[densAlgebra μs μ Λ] (localDens μs μ Λ n) :=
  measurable_funGen _ n

lemma densAlgebra_le (Λ : Finset S) :
    densAlgebra μs μ Λ ≤ cylinderEvents (X := fun _ : S ↦ E) (Λ : Set S) :=
  generateFrom_funGen_le fun _ ↦ measurable_localDensity _ _ _

lemma densSeedsLocal_subset_localEvents (Λ : Finset S) :
    densSeedsLocal μs μ Λ ⊆ localEvents S E := by
  intro A hA
  refine mem_localEvents_of_cylinderEvents Λ (densAlgebra_le μs μ Λ _ ?_)
  rw [← generateFrom_densSeedsLocal μs μ Λ]
  exact measurableSet_generateFrom hA

lemma univ_mem_densSeedsLocal (Λ : Finset S) : Set.univ ∈ densSeedsLocal μs μ Λ :=
  ⟨∅, by simp⟩

/-- **Georgii's `𝒜⁰ = ⋃_Λ 𝒜⁰_Λ`**: a countable family of local events. -/
def densSeeds [Countable S] : Set (Set (S → E)) := ⋃ Λ : Finset S, densSeedsLocal μs μ Λ

lemma countable_densSeeds [Countable S] : (densSeeds μs μ).Countable :=
  Set.countable_iUnion fun Λ ↦ countable_densSeedsLocal μs μ Λ

lemma densSeedsLocal_subset_densSeeds [Countable S] (Λ : Finset S) :
    densSeedsLocal μs μ Λ ⊆ densSeeds μs μ :=
  Set.subset_iUnion (fun Λ : Finset S ↦ densSeedsLocal μs μ Λ) Λ

lemma nonempty_densSeeds [Countable S] : (densSeeds μs μ).Nonempty :=
  ⟨Set.univ, densSeedsLocal_subset_densSeeds μs μ ∅ (univ_mem_densSeedsLocal μs μ ∅)⟩

lemma densSeeds_subset_localEvents [Countable S] : densSeeds μs μ ⊆ localEvents S E := by
  rintro A hA
  obtain ⟨Λ, hΛ⟩ := Set.mem_iUnion.1 hA
  exact densSeedsLocal_subset_localEvents μs μ Λ hΛ

end Seeds

/-! ### From `𝒜_Λ` back to `𝓕_Λ` -/

section Transfer

variable {α : Type*}

/-- **Georgii (4.15), transfer from `𝒜_Λ` to `𝓕_Λ`.** If the density of `ρ|_m` with respect to
`ν|_m` is measurable for the sub-σ-algebra `a ⊆ m`, then `ρ(A) = ρ(f_A)` for every `A ∈ m`,
where `f_A` is `a`-measurable and bounded by `1`. -/
lemma measure_eq_lintegral_condDensity {a m m0 : MeasurableSpace α} (ham : a ≤ m) (hm : m ≤ m0)
    {ρ ν : Measure α} [IsFiniteMeasure ρ] [IsFiniteMeasure ν] (hρν : ρ ≪ ν)
    (hdens : Measurable[a] (localDensity hm ρ ν)) {A : Set α} (hA : MeasurableSet[m] A) :
    ρ A = ∫⁻ x, condDensity (ham.trans hm) ν A x ∂ρ := by
  have hfmeas : Measurable[m] (condDensity (ham.trans hm) ν A) :=
    (measurable_condDensity (ham.trans hm) ν A).mono ham le_rfl
  calc ρ A = ∫⁻ x, A.indicator 1 x ∂ρ := (lintegral_indicator_one (hm _ hA)).symm
    _ = ∫⁻ x, localDensity hm ρ ν x * A.indicator 1 x ∂ν :=
        lintegral_localDensity_mul hm hρν (measurable_const.indicator hA)
    _ = ∫⁻ x in A, localDensity hm ρ ν x ∂ν := by
        rw [← lintegral_indicator (hm _ hA)]
        refine lintegral_congr fun x ↦ ?_
        by_cases hx : x ∈ A <;> simp [hx]
    _ = ∫⁻ x, localDensity hm ρ ν x * condDensity (ham.trans hm) ν A x ∂ν :=
        setLIntegral_eq_lintegral_mul_condDensity (ham.trans hm) ν A hdens
    _ = ∫⁻ x, condDensity (ham.trans hm) ν A x ∂ρ :=
        (lintegral_localDensity_mul hm hρν hfmeas).symm

end Transfer

/-! ### Georgii Proposition (4.15) -/

section Georgii415

open MeasurableSpace

variable {S E : Type*} [MeasurableSpace E]

/-- **Georgii (4.15), the Dynkin-system step and the transfer from `𝒜_Λ` to `𝓕_Λ`.**
If a subsequence of a locally equicontinuous sequence converges on the countable algebra
`𝒜⁰`, then it converges on every local event. -/
theorem tendsto_of_tendsto_densSeeds [Countable S] {P : ℕ → Measure (S → E)}
    {Q : Measure (S → E)} (hPprob : ∀ n, IsProbabilityMeasure (P n))
    (hQprob : IsProbabilityMeasure Q)
    (hle : ∀ (Λ : Finset S) (A : ℕ → Set (S → E)),
      (∀ m, MeasurableSet[cylinderEvents (X := fun _ : S ↦ E) (Λ : Set S)] (A m)) →
      Antitone A → (⋂ m, A m) = ∅ →
      Tendsto (fun m ↦ limsup (fun i ↦ P i (A m)) atTop) atTop (𝓝 0))
    {φ : ℕ → ℕ} (hφ : StrictMono φ)
    (hconv : ∀ t ∈ densSeeds P Q, Tendsto (fun k ↦ P (φ k) t) atTop (𝓝 (Q t)))
    {B : Set (S → E)} (hB : B ∈ localEvents S E) :
    Tendsto (fun k ↦ P (φ k) B) atTop (𝓝 (Q B)) := by
  classical
  have hQ' := hQprob
  have hφtop : Tendsto φ atTop atTop := hφ.tendsto_atTop
  -- Georgii's Dynkin-system argument on `𝒜_Λ`, volume by volume
  have key : ∀ (Λ : Finset S) (t : Set (S → E)), MeasurableSet[densAlgebra P Q Λ] t →
      Tendsto (fun k ↦ P (φ k) t) atTop (𝓝 (Q t)) := by
    intro Λ
    have hAle : densAlgebra P Q Λ ≤ cylinderEvents (X := fun _ : S ↦ E) (Λ : Set S) :=
      densAlgebra_le P Q Λ
    refine @MeasurableSpace.induction_on_inter (S → E) (densAlgebra P Q Λ)
      (fun t _ ↦ Tendsto (fun k ↦ P (φ k) t) atTop (𝓝 (Q t)))
      (densSeedsLocal P Q Λ) (generateFrom_densSeedsLocal P Q Λ).symm
      (isPiSystem_densSeedsLocal P Q Λ) ?_ ?_ ?_ ?_
    · simp
    · intro t ht
      exact hconv t (densSeedsLocal_subset_densSeeds P Q Λ ht)
    · intro t htm h
      have htm' : MeasurableSet t := cylinderEvents_le_pi _ (hAle _ htm)
      have h1 : ∀ k, P (φ k) tᶜ = 1 - P (φ k) t := fun k ↦ by
        have := hPprob (φ k)
        exact prob_compl_eq_one_sub htm'
      have h2 : Q tᶜ = 1 - Q t := prob_compl_eq_one_sub htm'
      simp only [h1, h2]
      exact ENNReal.Tendsto.sub tendsto_const_nhds h (Or.inl (by simp))
    · intro f hdisj hfm hf
      have hfmc : ∀ i, MeasurableSet[cylinderEvents (X := fun _ : S ↦ E) (Λ : Set S)] (f i) :=
        fun i ↦ hAle _ (hfm i)
      have hfm' : ∀ i, MeasurableSet (f i) := fun i ↦ cylinderEvents_le_pi _ (hfmc i)
      set C : ℕ → Set (S → E) := fun m ↦ ⋃ i ∈ Finset.range m, f i with hC
      have hCmono : Monotone C := fun m₁ m₂ hm ↦
        Set.iUnion₂_subset fun i hi ↦
          Set.subset_iUnion₂ (s := fun i (_ : i ∈ Finset.range m₂) ↦ f i) i
            (Finset.mem_range.2 (lt_of_lt_of_le (Finset.mem_range.1 hi) hm))
      have hCsub : ∀ m, C m ⊆ ⋃ i, f i := fun m ↦
        Set.iUnion₂_subset fun i _ ↦ Set.subset_iUnion f i
      have hCmeas : ∀ m, MeasurableSet[cylinderEvents (X := fun _ : S ↦ E) (Λ : Set S)] (C m) :=
        fun m ↦ Finset.measurableSet_biUnion _ fun i _ ↦ hfmc i
      have hCmeas' : ∀ m, MeasurableSet (C m) := fun m ↦ cylinderEvents_le_pi _ (hCmeas m)
      have hCsum : ∀ (ρ : Measure (S → E)) (m : ℕ), ρ (C m) = ∑ i ∈ Finset.range m, ρ (f i) :=
        fun ρ m ↦ measure_biUnion_finset (hdisj.set_pairwise _) fun i _ ↦ hfm' i
      have hCconv : ∀ m, Tendsto (fun k ↦ P (φ k) (C m)) atTop (𝓝 (Q (C m))) := by
        intro m
        simp only [hCsum]
        exact tendsto_finsetSum _ fun i _ ↦ hf i
      -- the tail `B \ C m ↓ ∅`
      have hdiffmeas : ∀ m, MeasurableSet[cylinderEvents (X := fun _ : S ↦ E) (Λ : Set S)]
          ((⋃ i, f i) \ C m) := fun m ↦ (MeasurableSet.iUnion hfmc).diff (hCmeas m)
      have hanti : Antitone fun m ↦ (⋃ i, f i) \ C m := fun m₁ m₂ hm ↦
        Set.sdiff_subset_sdiff_right (hCmono hm)
      have hempty : (⋂ m, (⋃ i, f i) \ C m) = ∅ := by
        refine Set.eq_empty_iff_forall_notMem.2 fun x hx ↦ ?_
        obtain ⟨i, hi⟩ := Set.mem_iUnion.1 (Set.mem_iInter.1 hx 0).1
        exact (Set.mem_iInter.1 hx (i + 1)).2
          (Set.mem_iUnion₂.2 ⟨i, Finset.self_mem_range_succ i, hi⟩)
      have hM := hle Λ (fun m ↦ (⋃ i, f i) \ C m) hdiffmeas hanti hempty
      have hup : limsup (fun k ↦ P (φ k) (⋃ i, f i)) atTop ≤ Q (⋃ i, f i) := by
        refine ENNReal.le_of_forall_pos_le_add fun ε hε _ ↦ ?_
        have hhalf : (0 : ℝ≥0∞) < (ε : ℝ≥0∞) / 2 := ENNReal.half_pos (by simpa using hε.ne')
        obtain ⟨m, hm⟩ := (hM.eventually_lt_const hhalf).exists
        have hev1 : ∀ᶠ k in atTop, P (φ k) ((⋃ i, f i) \ C m) < (ε : ℝ≥0∞) / 2 :=
          hφtop.eventually (eventually_lt_of_limsup_lt hm)
        have hev2 : ∀ᶠ k in atTop, P (φ k) (C m) < Q (C m) + (ε : ℝ≥0∞) / 2 :=
          (hCconv m).eventually_lt_const (ENNReal.lt_add_right (measure_ne_top _ _) hhalf.ne')
        refine Filter.limsup_le_of_le (h := ?_)
        filter_upwards [hev1, hev2] with k h1 h2
        have hsplit : P (φ k) ((⋃ i, f i) \ C m) + P (φ k) (C m) = P (φ k) (⋃ i, f i) := by
          have := measure_sdiff_add_inter (μ := P (φ k)) (⋃ i, f i) (hCmeas' m)
          rwa [Set.inter_eq_self_of_subset_right (hCsub m)] at this
        calc P (φ k) (⋃ i, f i)
            = P (φ k) ((⋃ i, f i) \ C m) + P (φ k) (C m) := hsplit.symm
          _ ≤ (ε : ℝ≥0∞) / 2 + (Q (C m) + (ε : ℝ≥0∞) / 2) := add_le_add h1.le h2.le
          _ = Q (C m) + ε := by
              rw [add_comm ((ε : ℝ≥0∞) / 2), add_assoc, ENNReal.add_halves]
          _ ≤ Q (⋃ i, f i) + ε := by gcongr; exact hCsub m
      have hlow : Q (⋃ i, f i) ≤ liminf (fun k ↦ P (φ k) (⋃ i, f i)) atTop := by
        have hμC : Tendsto (fun m ↦ Q (C m)) atTop (𝓝 (Q (⋃ m, C m))) :=
          tendsto_measure_iUnion_atTop hCmono
        have hunion : (⋃ m, C m) = ⋃ i, f i := by
          refine Set.Subset.antisymm (Set.iUnion_subset hCsub) (Set.iUnion_subset fun i ↦ ?_)
          exact fun x hx ↦ Set.mem_iUnion.2
            ⟨i + 1, Set.mem_iUnion₂.2 ⟨i, Finset.self_mem_range_succ i, hx⟩⟩
        rw [hunion] at hμC
        refine le_of_tendsto hμC (Eventually.of_forall fun m ↦ ?_)
        rw [← (hCconv m).liminf_eq]
        exact liminf_le_liminf (Eventually.of_forall fun k ↦ measure_mono (hCsub m))
      exact tendsto_of_le_liminf_of_limsup_le hlow hup
  -- Georgii's transfer from `𝒜_Λ` to `𝓕_Λ`
  obtain ⟨Λ, hΛ⟩ := mem_localEvents_iff_cylinderEvents.1 hB
  have hν : IsFiniteMeasure (domMeasure P Q) := isFiniteMeasure_domMeasure hPprob hQprob
  have ham : densAlgebra P Q Λ ≤ cylinderEvents (X := fun _ : S ↦ E) (Λ : Set S) :=
    densAlgebra_le P Q Λ
  have hm : cylinderEvents (X := fun _ : S ↦ E) (Λ : Set S) ≤
      (inferInstance : MeasurableSpace (S → E)) := cylinderEvents_le_pi
  have hrep : ∀ n, clusterSeq P Q n B
      = ∫⁻ x, condDensity (ham.trans hm) (domMeasure P Q) B x ∂(clusterSeq P Q n) := by
    intro n
    have := isProbabilityMeasure_clusterSeq hPprob hQprob n
    exact measure_eq_lintegral_condDensity ham hm
      (clusterSeq_absolutelyContinuous_domMeasure n) (measurable_localDens P Q Λ n) hΛ
  have hfinal := tendsto_lintegral_of_tendsto_setwise (ham.trans hm)
    (ρs := fun k ↦ P (φ k)) (ρ := Q) (fun k ↦ hPprob (φ k)) hQprob
    (measurable_condDensity (ham.trans hm) (domMeasure P Q) B)
    (condDensity_le_one (ham.trans hm) (domMeasure P Q) B)
    (fun B' hB' ↦ key Λ B' hB')
  have e1 : ∀ k, ∫⁻ x, condDensity (ham.trans hm) (domMeasure P Q) B x ∂(P (φ k))
      = P (φ k) B := fun k ↦ (hrep (φ k + 1)).symm
  have e2 : ∫⁻ x, condDensity (ham.trans hm) (domMeasure P Q) B x ∂Q = Q B := (hrep 0).symm
  simpa only [e1, e2] using hfinal

/-- **Georgii Proposition (4.15).** A cluster point of a locally equicontinuous *sequence* of
random fields is the limit of a subsequence. No assumption whatsoever is made on the state
space `(E, ℰ)`. -/
theorem exists_subseq_tendsto_of_mapClusterPt [Countable S]
    {μs : ℕ → WithLocalConvergence S E} {μ : WithLocalConvergence S E}
    (hle : LocallyEquicontinuous atTop fun n ↦ (μs n).toMeasure)
    (hcp : MapClusterPt μ atTop μs) :
    ∃ φ : ℕ → ℕ, StrictMono φ ∧ Tendsto (μs ∘ φ) atTop (𝓝 μ) := by
  classical
  have hPprob : ∀ n, IsProbabilityMeasure ((μs n).toMeasure : Measure (S → E)) :=
    fun n ↦ (μs n).toMeasure.2
  have hQprob : IsProbabilityMeasure (μ.toMeasure : Measure (S → E)) := μ.toMeasure.2
  -- Georgii's countable algebra `𝒜⁰ = {A₁, A₂, …}`
  obtain ⟨A, hA⟩ := (countable_densSeeds (μs := fun n ↦ ((μs n).toMeasure : Measure (S → E)))
      (μ := (μ.toMeasure : Measure (S → E)))).exists_eq_range (nonempty_densSeeds _ _)
  have hAmem : ∀ ℓ, A ℓ ∈ densSeeds (fun n ↦ ((μs n).toMeasure : Measure (S → E)))
      (μ.toMeasure : Measure (S → E)) := fun ℓ ↦ hA ▸ Set.mem_range_self ℓ
  have hAloc : ∀ ℓ, A ℓ ∈ localEvents S E :=
    fun ℓ ↦ densSeeds_subset_localEvents _ _ (hAmem ℓ)
  -- the diagonal subsequence: a cluster point in the metrizable space `ℕ → ℝ≥0∞`
  set T : WithLocalConvergence S E → (ℕ → ℝ≥0∞) :=
    fun ν ℓ ↦ ((ν.toMeasure : Measure (S → E)) (A ℓ)) with hT
  have hTcont : Continuous T :=
    continuous_pi fun ℓ ↦ WithSetwiseTopology.continuous_apply_enn (hAloc ℓ)
  have hcp' : MapClusterPt (T μ) atTop (T ∘ μs) :=
    hcp.map hTcont.continuousAt (le_of_eq Filter.map_map)
  obtain ⟨φ, hφ, hφlim⟩ := hcp'.tendsto_subseq
  have hcoord : ∀ ℓ, Tendsto (fun k ↦ ((μs (φ k)).toMeasure : Measure (S → E)) (A ℓ)) atTop
      (𝓝 ((μ.toMeasure : Measure (S → E)) (A ℓ))) := fun ℓ ↦ tendsto_pi_nhds.1 hφlim ℓ
  refine ⟨φ, hφ, ?_⟩
  rw [tendsto_withLocalConvergence_iff]
  intro B hB
  refine tendsto_of_tendsto_densSeeds hPprob hQprob (fun Λ As h1 h2 h3 ↦ hle Λ As h1 h2 h3)
    hφ ?_ hB
  intro t ht
  obtain ⟨ℓ, hℓ⟩ : ∃ ℓ, A ℓ = t := by rw [hA] at ht; exact ht
  exact hℓ ▸ hcoord ℓ


/-- **Georgii (4.15)** for a sequence of probability measures. -/
theorem exists_strictMono_tendsto_of_mapClusterPt [Countable S]
    {μs : ℕ → ProbabilityMeasure (S → E)} {μ : ProbabilityMeasure (S → E)}
    (hle : LocallyEquicontinuous atTop μs)
    (hcp : MapClusterPt (WithSetwiseTopology.ofMeasure μ : WithLocalConvergence S E) atTop
      fun n ↦ (WithSetwiseTopology.ofMeasure (μs n) : WithLocalConvergence S E)) :
    ∃ φ : ℕ → ℕ, StrictMono φ ∧
      Tendsto (fun k ↦ (WithSetwiseTopology.ofMeasure (μs (φ k)) : WithLocalConvergence S E))
        atTop (𝓝 (WithSetwiseTopology.ofMeasure μ)) :=
  exists_subseq_tendsto_of_mapClusterPt
    (μs := fun n ↦ (WithSetwiseTopology.ofMeasure (μs n) : WithLocalConvergence S E)) hle hcp

/-- **Georgii (4.9) + (4.15).** Over a standard Borel state space, every locally equicontinuous
sequence of random fields has a subsequence converging in the topology of local convergence. -/
theorem exists_subseq_tendsto_of_locallyEquicontinuous [Countable S] [StandardBorelSpace E]
    {μs : ℕ → WithLocalConvergence S E}
    (hle : LocallyEquicontinuous atTop fun n ↦ (μs n).toMeasure) :
    ∃ (μ : WithLocalConvergence S E) (φ : ℕ → ℕ),
      StrictMono φ ∧ Tendsto (μs ∘ φ) atTop (𝓝 μ) := by
  obtain ⟨μ, hμ⟩ := exists_mapClusterPt_of_locallyEquicontinuous hle
  obtain ⟨φ, hφ, h⟩ := exists_subseq_tendsto_of_mapClusterPt hle hμ
  exact ⟨μ, φ, hφ, h⟩

end Georgii415

end MeasureTheory.GibbsMeasure

end
