/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/
module

public import Mathlib.InformationTheory.KullbackLeibler.DataProcessing
public import Mathlib.MeasureTheory.Function.ConditionalExpectation.RadonNikodym
public import Mathlib.MeasureTheory.Measure.MeasuredSets
public import Mathlib.Probability.Martingale.Convergence
public import Mathlib.Probability.Process.PartitionFiltration

/-!
# Relative entropy on a sub-sigma-algebra

Georgii, *Gibbs Measures and Phase Transitions*, §15.1, defines the *relative entropy* of `μ`
with respect to `ν` on a sub-sigma-algebra `𝒜` of `𝓕` as
`𝓗_𝒜(μ | ν) = ν(f_𝒜 log f_𝒜)` if `μ ≪ ν` on `𝒜` (with `f_𝒜` the density of `μ|𝒜` with respect
to `ν|𝒜`), and `∞` otherwise (Definition (15.1)).

For probability measures this is exactly Mathlib's Kullback–Leibler divergence of the trimmed
measures, `InformationTheory.klDiv (μ.trim hm) (ν.trim hm)` (with `hm : m ≤ m𝓧`). For finite
measures Mathlib's `klDiv` differs from Georgii's `ν(f log f)` by the additive correction
`ν univ - μ univ`, which makes it nonnegative; Georgii disposes of the normalisation with the
scaling identity (15.2) and then assumes probability measures. We therefore do **not** introduce a
new definition: everything is stated for `klDiv` of trimmed measures.

## Main statements

* `toReal_klDiv_smul_smul`: scaling, Georgii (15.2), in Mathlib's normalisation.
* `klDiv_trim_eq_lintegral_klFun_condExp`, `klDiv_trim_eq_lintegral_klFun_of_trim_eq_withDensity`:
  Georgii (15.3), `𝓗_𝒜(μ | ν) = ν(ψ ∘ f_𝒜)` with `ψ = klFun` (Georgii's (15.4)) and `f_𝒜` the
  conditional expectation of the density, resp. any `𝒜`-measurable density.
* Georgii (15.5): (a) is `zero_le`; (b) is `klDiv_trim_eq_zero_iff`; (c) is `klDiv_trim_mono`
  (Mathlib's `klDiv_trim_le`); (d) is `klDiv_add_add_le` / `klDiv_smul_add_smul_le`
  (joint subadditivity and convexity of `klDiv` in the pair of measures).
* `iSup_klDiv_trim`, `tendsto_klDiv_trim`: Georgii (15.6) for an increasing sequence of
  sigma-algebras (a `Filtration ℕ m𝓧`): the relative entropies increase to the relative entropy on
  `⨆ n, ℱ n`.
* `klDiv_trim_generateFrom_eq_sum`: the relative entropy on the sigma-algebra generated by a finite
  measurable partition `P` is `∑ A ∈ P, μ A * log (μ A / ν A)` (up to the finite-measure
  correction).
* `klDiv_trim_eq_iSup_finset_partition`, `klDiv_trim_eq_iSup_sum`: Georgii (15.7),
  `𝓗_𝒜(μ | ν) = ⨆ P, ∑ A ∈ P, μ A * log (μ A / ν A)` over finite `𝒜`-measurable partitions `P`.

Along the way: `klDiv_restrict_le`, `mul_log_le_klDiv_of_measurableSet` (the two-set lower bound),
`klDiv_trim_eq_of_measurable_rnDeriv` (a sufficient sub-sigma-algebra loses no information).
-/

@[expose] public section

open Real MeasureTheory MeasurableSpace ProbabilityTheory Set Filter
open scoped ENNReal NNReal Topology symmDiff

namespace InformationTheory

variable {𝓧 : Type*} {m m𝓧 : MeasurableSpace 𝓧} {μ ν : Measure 𝓧}

section Scaling

variable [IsFiniteMeasure μ] [IsFiniteMeasure ν]

/-- Georgii (15.2) in Mathlib's normalisation: `klDiv (a • μ) (b • ν)` in terms of `klDiv μ ν`.
Georgii's `𝓗(aμ | bν) = a 𝓗(μ | ν) + a μ(Ω) log (a / b)` is this identity minus the correction
term `(b • ν) univ - (a • μ) univ`. -/
lemma toReal_klDiv_smul_smul (hμν : μ ≪ ν) (h_int : Integrable (llr μ ν) μ) (a : ℝ≥0) {b : ℝ≥0}
    (hb : b ≠ 0) :
    (klDiv (a • μ) (b • ν)).toReal =
      a * (klDiv μ ν).toReal + a * μ.real univ * log (a / b) + (b - a) * ν.real univ := by
  by_cases ha : a = 0
  · simp [ha, measureReal_def]
  have h_int' : Integrable (llr (a • μ) ν) (a • μ) := by
    refine Integrable.smul_measure_nnreal ?_
    rw [integrable_congr (llr_smul_nnreal_left hμν a ha)]
    fun_prop
  rw [toReal_klDiv_smul_right (hμν.smul_left a) h_int' hb, toReal_klDiv_smul_left hμν h_int a,
    log_div (by exact_mod_cast ha) (by exact_mod_cast hb)]
  simp only [measureReal_nnreal_smul_apply]
  ring

end Scaling

section SubSigmaAlgebra

variable [IsFiniteMeasure μ] [IsFiniteMeasure ν]

/-- Georgii (15.3) with `f_𝒜 = ν[∂μ/∂ν | m]`: the relative entropy on `m` is the `ν`-integral of
`klFun` (Georgii's `ψ`) of the conditional expectation of the density, as a Lebesgue integral. -/
lemma klDiv_trim_eq_lintegral_klFun_condExp (hm : m ≤ m𝓧) (hμν : μ ≪ ν) :
    klDiv (μ.trim hm) (ν.trim hm)
      = ∫⁻ x, ENNReal.ofReal (klFun ((ν[fun x ↦ (μ.rnDeriv ν x).toReal | m]) x)) ∂ν := by
  rw [klDiv_eq_lintegral_klFun_of_ac (hμν.trim hm)]
  have hmeas : Measurable[m]
      fun x ↦ ENNReal.ofReal (klFun ((ν[fun x ↦ (μ.rnDeriv ν x).toReal | m]) x)) :=
    ENNReal.measurable_ofReal.comp (measurable_klFun.comp stronglyMeasurable_condExp.measurable)
  rw [← lintegral_trim hm hmeas]
  refine lintegral_congr_ae ?_
  filter_upwards [toReal_rnDeriv_trim hm hμν] with x hx
  rw [hx]

/-- Georgii (15.3): if `μ = f • ν` on `m` for an `m`-measurable `f ≥ 0`, then
`𝓗_m(μ | ν) = ν(klFun ∘ f)`. -/
lemma klDiv_trim_eq_lintegral_klFun_of_trim_eq_withDensity (hm : m ≤ m𝓧) {f : 𝓧 → ℝ≥0∞}
    (hf : Measurable[m] f) (h : μ.trim hm = (ν.trim hm).withDensity f) :
    klDiv (μ.trim hm) (ν.trim hm) = ∫⁻ x, ENNReal.ofReal (klFun (f x).toReal) ∂ν := by
  have hac : μ.trim hm ≪ ν.trim hm := h ▸ withDensity_absolutelyContinuous _ _
  have hmeas : Measurable[m] fun x ↦ ENNReal.ofReal (klFun (f x).toReal) :=
    ENNReal.measurable_ofReal.comp (measurable_klFun.comp (ENNReal.measurable_toReal.comp hf))
  rw [klDiv_eq_lintegral_klFun_of_ac hac, ← lintegral_trim hm hmeas]
  refine lintegral_congr_ae ?_
  have h' := @Measure.rnDeriv_withDensity _ m (ν.trim hm) _ f hf
  rw [← h] at h'
  filter_upwards [h'] with x hx
  rw [hx]

/-- Georgii (15.5)(b): the relative entropy on `m` vanishes iff `μ = ν` on `m`. -/
lemma klDiv_trim_eq_zero_iff (hm : m ≤ m𝓧) :
    klDiv (μ.trim hm) (ν.trim hm) = 0 ↔ ∀ s, MeasurableSet[m] s → μ s = ν s := by
  rw [klDiv_eq_zero_iff]
  constructor
  · intro h s hs
    rw [← trim_measurableSet_eq hm hs, ← trim_measurableSet_eq hm hs, h]
  · intro h
    exact @Measure.ext _ m _ _ fun s hs ↦ by
      rw [trim_measurableSet_eq hm hs, trim_measurableSet_eq hm hs, h s hs]

/-- Georgii (15.5)(c): the relative entropy is monotone in the sigma-algebra. This is Mathlib's
data processing inequality `klDiv_trim_le`, restated for two nested sub-sigma-algebras. -/
lemma klDiv_trim_mono {m₁ m₂ : MeasurableSpace 𝓧} (h₁₂ : m₁ ≤ m₂) (h₂ : m₂ ≤ m𝓧) :
    klDiv (μ.trim (h₁₂.trans h₂)) (ν.trim (h₁₂.trans h₂)) ≤ klDiv (μ.trim h₂) (ν.trim h₂) := by
  rw [← trim_trim (hm₁₂ := h₁₂) (hm₂ := h₂), ← trim_trim (hm₁₂ := h₁₂) (hm₂ := h₂)]
  exact klDiv_trim_le _ _ h₁₂

end SubSigmaAlgebra

section Convexity

variable {μ₁ μ₂ ν₁ ν₂ : Measure 𝓧} [IsFiniteMeasure μ₁] [IsFiniteMeasure μ₂]
  [IsFiniteMeasure ν₁] [IsFiniteMeasure ν₂]

/-- The Kullback–Leibler divergence is jointly subadditive in the pair of measures. Together with
the homogeneity `klDiv_smul_same` this is the joint convexity, Georgii (15.5)(d). -/
lemma klDiv_add_add_le : klDiv (μ₁ + μ₂) (ν₁ + ν₂) ≤ klDiv μ₁ ν₁ + klDiv μ₂ ν₂ := by
  by_cases h₁ : μ₁ ≪ ν₁
  swap; · simp [h₁]
  by_cases h₂ : μ₂ ≪ ν₂
  swap; · simp [h₂]
  set ξ := ν₁ + ν₂ with hξ
  have hν₁ : ν₁ ≪ ξ := Measure.AbsolutelyContinuous.rfl.add_right ν₂
  have hν₂ : ν₂ ≪ ξ := Measure.AbsolutelyContinuous.rfl.add_right' ν₁
  rw [klDiv_eq_lintegral_klFun_of_ac (h₁.add h₂), klDiv_eq_lintegral_klFun_of_ac h₁,
    klDiv_eq_lintegral_klFun_of_ac h₂,
    ← lintegral_rnDeriv_mul hν₁ (by fun_prop), ← lintegral_rnDeriv_mul hν₂ (by fun_prop),
    ← lintegral_add_left (by fun_prop)]
  refine lintegral_mono_ae ?_
  have h_one : ν₁.rnDeriv ξ + ν₂.rnDeriv ξ =ᵐ[ξ] 1 :=
    (Measure.rnDeriv_add' ν₁ ν₂ ξ).symm.trans (Measure.rnDeriv_self ξ)
  filter_upwards [h_one, Measure.rnDeriv_add' μ₁ μ₂ ξ, Measure.rnDeriv_mul_rnDeriv (κ := ξ) h₁,
    Measure.rnDeriv_mul_rnDeriv (κ := ξ) h₂, Measure.rnDeriv_ne_top ν₁ ξ,
    Measure.rnDeriv_ne_top ν₂ ξ,
    Measure.rnDeriv_ne_top μ₁ ξ, Measure.rnDeriv_ne_top μ₂ ξ]
    with x h1 hadd hm1 hm2 hg1 hg2 hf1 hf2
  simp only [Pi.add_apply, Pi.one_apply, Pi.mul_apply] at h1 hadd hm1 hm2
  rw [hadd, ← hm1, ← hm2]
  rw [← hm1] at hf1
  rw [← hm2] at hf2
  set f₁ := μ₁.rnDeriv ν₁ x
  set f₂ := μ₂.rnDeriv ν₂ x
  set g₁ := ν₁.rnDeriv ξ x
  set g₂ := ν₂.rnDeriv ξ x
  have hg1' : g₁.toReal + g₂.toReal = 1 := by
    rw [← ENNReal.toReal_add hg1 hg2, h1, ENNReal.toReal_one]
  have key := convexOn_klFun.2 (show f₁.toReal ∈ Ici 0 from ENNReal.toReal_nonneg)
    (show f₂.toReal ∈ Ici 0 from ENNReal.toReal_nonneg)
    (show 0 ≤ g₁.toReal from ENNReal.toReal_nonneg) (show 0 ≤ g₂.toReal from ENNReal.toReal_nonneg)
    hg1'
  simp only [smul_eq_mul] at key
  calc ENNReal.ofReal (klFun (f₁ * g₁ + f₂ * g₂).toReal)
      = ENNReal.ofReal (klFun (g₁.toReal * f₁.toReal + g₂.toReal * f₂.toReal)) := by
        rw [ENNReal.toReal_add hf1 hf2,
          ENNReal.toReal_mul, ENNReal.toReal_mul, mul_comm f₁.toReal, mul_comm f₂.toReal]
    _ ≤ ENNReal.ofReal (g₁.toReal * klFun f₁.toReal + g₂.toReal * klFun f₂.toReal) :=
        ENNReal.ofReal_le_ofReal key
    _ = g₁ * ENNReal.ofReal (klFun f₁.toReal) + g₂ * ENNReal.ofReal (klFun f₂.toReal) := by
        rw [ENNReal.ofReal_add
          (mul_nonneg ENNReal.toReal_nonneg (klFun_nonneg ENNReal.toReal_nonneg))
          (mul_nonneg ENNReal.toReal_nonneg (klFun_nonneg ENNReal.toReal_nonneg)),
          ENNReal.ofReal_mul ENNReal.toReal_nonneg, ENNReal.ofReal_mul ENNReal.toReal_nonneg,
          ENNReal.ofReal_toReal hg1, ENNReal.ofReal_toReal hg2]

/-- Georgii (15.5)(d): the Kullback–Leibler divergence is jointly convex in the pair of measures
(no normalisation `a + b = 1` is needed, by homogeneity). -/
lemma klDiv_smul_add_smul_le (a b : ℝ≥0) :
    klDiv (a • μ₁ + b • μ₂) (a • ν₁ + b • ν₂) ≤ a * klDiv μ₁ ν₁ + b * klDiv μ₂ ν₂ :=
  klDiv_add_add_le.trans (by rw [klDiv_smul_same, klDiv_smul_same])

end Convexity


section Restrict

variable [IsFiniteMeasure μ] [IsFiniteMeasure ν]

/-- Restricting both measures to a measurable set does not increase the Kullback–Leibler
divergence. -/
lemma klDiv_restrict_le {s : Set 𝓧} (hs : MeasurableSet s) :
    klDiv (μ.restrict s) (ν.restrict s) ≤ klDiv μ ν := by
  by_cases hμν : μ ≪ ν
  swap; · simp [hμν]
  rw [klDiv_eq_lintegral_klFun_of_ac hμν, klDiv_eq_lintegral_klFun_of_ac (hμν.restrict s)]
  have h_rn : (μ.restrict s).rnDeriv (ν.restrict s) =ᵐ[ν.restrict s] μ.rnDeriv ν := by
    have := Measure.rnDeriv_withDensity (ν.restrict s) (Measure.measurable_rnDeriv μ ν)
    rwa [← restrict_withDensity hs, Measure.withDensity_rnDeriv_eq μ ν hμν] at this
  calc ∫⁻ x, ENNReal.ofReal (klFun ((μ.restrict s).rnDeriv (ν.restrict s) x).toReal) ∂(ν.restrict s)
      = ∫⁻ x, ENNReal.ofReal (klFun (μ.rnDeriv ν x).toReal) ∂(ν.restrict s) := by
        refine lintegral_congr_ae ?_
        filter_upwards [h_rn] with x hx using by rw [hx]
    _ ≤ ∫⁻ x, ENNReal.ofReal (klFun (μ.rnDeriv ν x).toReal) ∂ν :=
        lintegral_mono' Measure.restrict_le_self le_rfl

/-- The two-set lower bound: `μ s * log (μ s / ν s) + ν s - μ s ≤ klDiv μ ν` for every measurable
`s`. -/
lemma mul_log_le_klDiv_of_measurableSet {s : Set 𝓧} (hs : MeasurableSet s) :
    ENNReal.ofReal (μ.real s * log (μ.real s / ν.real s) + ν.real s - μ.real s) ≤ klDiv μ ν := by
  have h := mul_log_le_klDiv (μ.restrict s) (ν.restrict s)
  simp only [measureReal_restrict_apply_univ] at h
  exact h.trans (klDiv_restrict_le hs)

omit [IsFiniteMeasure μ] [IsFiniteMeasure ν] in
/-- If `ν` vanishes on a set charged by `μ`, the Kullback–Leibler divergence is infinite. -/
lemma klDiv_eq_top_of_measure_eq_zero {s : Set 𝓧} (hν : ν s = 0) (hμ : μ s ≠ 0) :
    klDiv μ ν = ∞ :=
  klDiv_of_not_ac fun h ↦ hμ (h hν)

end Restrict


section Filtration

variable [IsFiniteMeasure μ] [IsFiniteMeasure ν] (ℱ : Filtration ℕ m𝓧)

/-- The union of the sigma-algebras of a filtration is a ring of sets. -/
lemma _root_.MeasureTheory.Filtration.isSetRing_iUnion_measurableSet :
    IsSetRing {s | ∃ n, MeasurableSet[ℱ n] s} where
  empty_mem := ⟨0, @MeasurableSet.empty _ (ℱ 0)⟩
  union_mem := by
    rintro s t ⟨n, hs⟩ ⟨k, ht⟩
    exact ⟨max n k, (ℱ.mono (le_max_left n k) _ hs).union (ℱ.mono (le_max_right n k) _ ht)⟩
  sdiff_mem := by
    rintro s t ⟨n, hs⟩ ⟨k, ht⟩
    exact ⟨max n k, (ℱ.mono (le_max_left n k) _ hs).diff (ℱ.mono (le_max_right n k) _ ht)⟩

/-- Along a filtration, the relative entropies are nondecreasing (Georgii (15.5)(c)). -/
lemma monotone_klDiv_trim :
    Monotone fun n ↦ klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n)) :=
  fun _ k hnk ↦ klDiv_trim_mono (μ := μ) (ν := ν) (ℱ.mono hnk) (ℱ.le k)

/-- Each relative entropy along a filtration is bounded by the one on `⨆ n, ℱ n`. -/
lemma klDiv_trim_le_klDiv_trim_iSup (n : ℕ) :
    klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n))
      ≤ klDiv (μ.trim (iSup_le ℱ.le)) (ν.trim (iSup_le ℱ.le)) :=
  klDiv_trim_mono (le_iSup ℱ n) (iSup_le ℱ.le)

/-- The absolutely continuous half of Georgii (15.6): if `μ ≪ ν` on `⨆ n, ℱ n`, the relative
entropy there is at most the supremum along the filtration. The proof is Lévy's upward theorem for
the densities (`Integrable.tendsto_ae_condExp`) and Fatou's lemma for `klFun ≥ 0`. -/
lemma klDiv_trim_iSup_le_iSup_klDiv_trim_of_ac
    (h : μ.trim (iSup_le ℱ.le) ≪ ν.trim (iSup_le ℱ.le)) :
    klDiv (μ.trim (iSup_le ℱ.le)) (ν.trim (iSup_le ℱ.le))
      ≤ ⨆ n, klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n)) := by
  set hsup : (⨆ n, ℱ n) ≤ m𝓧 := iSup_le ℱ.le
  set μ' := μ.trim hsup with hμ'
  set ν' := ν.trim hsup with hν'
  -- the same filtration, seen inside the limit sigma-algebra `⨆ n, ℱ n`
  let ℱ' : @Filtration 𝓧 ℕ _ (⨆ n, ℱ n) := ⟨fun n ↦ ℱ n, fun _ _ h ↦ ℱ.mono h, fun n ↦ le_iSup ℱ n⟩
  have h_trim : ∀ n, μ.trim (ℱ.le n) = μ'.trim (ℱ'.le n) := fun n ↦ trim_trim.symm
  have h_trim' : ∀ n, ν.trim (ℱ.le n) = ν'.trim (ℱ'.le n) := fun n ↦ trim_trim.symm
  set f : 𝓧 → ℝ := fun x ↦ (μ'.rnDeriv ν' x).toReal with hf
  have hf_meas : Measurable[⨆ n, ℱ n] f := (Measure.measurable_rnDeriv μ' ν').ennreal_toReal
  have hf_int : Integrable f ν' := Measure.integrable_toReal_rnDeriv
  have h_levy : ∀ᵐ x ∂ν', Tendsto (fun n ↦ (ν'[f | ℱ' n]) x) atTop (𝓝 (f x)) :=
    hf_int.tendsto_ae_condExp hf_meas.stronglyMeasurable
  calc klDiv μ' ν'
      = ∫⁻ x, ENNReal.ofReal (klFun (f x)) ∂ν' := klDiv_eq_lintegral_klFun_of_ac h
    _ = ∫⁻ x, liminf (fun n ↦ ENNReal.ofReal (klFun ((ν'[f | ℱ' n]) x))) atTop ∂ν' := by
        refine lintegral_congr_ae ?_
        filter_upwards [h_levy] with x hx
        exact (((ENNReal.continuous_ofReal.tendsto _).comp
          ((continuous_klFun.tendsto _).comp hx)).liminf_eq).symm
    _ ≤ liminf (fun n ↦ ∫⁻ x, ENNReal.ofReal (klFun ((ν'[f | ℱ' n]) x)) ∂ν') atTop :=
        lintegral_liminf_le fun n ↦ ENNReal.measurable_ofReal.comp
          (measurable_klFun.comp (stronglyMeasurable_condExp.mono (ℱ'.le n)).measurable)
    _ = liminf (fun n ↦ klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n))) atTop := by
        congr 1
        ext n
        rw [h_trim n, h_trim' n, klDiv_trim_eq_lintegral_klFun_condExp (ℱ'.le n) h]
    _ = ⨆ n, klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n)) :=
        (tendsto_atTop_iSup (monotone_klDiv_trim ℱ)).liminf_eq

private lemma mul_log_div_le_mul_log_div {c x y ε : ℝ} (hc : 0 < c) (hcx : c ≤ x) (hy : 0 < y)
    (hyε : y ≤ ε) (hεc : ε ≤ c) :
    c * log (c / ε) ≤ x * log (x / y) := by
  have hε : 0 < ε := hy.trans_le hyε
  have h1 : c / ε ≤ x / y := div_le_div₀ (hc.le.trans hcx) hcx hy hyε
  have h2 : 0 ≤ log (c / ε) := log_nonneg ((one_le_div hε).mpr hεc)
  exact mul_le_mul hcx (log_le_log (div_pos hc hε) h1) h2 (hc.le.trans hcx)

/-- The singular half of Georgii (15.6): if `μ` is not absolutely continuous with respect to `ν` on
`⨆ n, ℱ n`, the relative entropies along the filtration are unbounded. A set of the limit
sigma-algebra charged by `μ` but null for `ν` is approximated by sets of the filtration
(`exists_measure_symmDiff_lt_of_generateFrom_isSetRing`), on which the two-set lower bound
`mul_log_le_klDiv_of_measurableSet` blows up. -/
lemma iSup_klDiv_trim_eq_top_of_not_ac
    (h : ¬ μ.trim (iSup_le ℱ.le) ≪ ν.trim (iSup_le ℱ.le)) :
    ⨆ n, klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n)) = ∞ := by
  set hsup : (⨆ n, ℱ n) ≤ m𝓧 := iSup_le ℱ.le
  -- a set of the limit sigma-algebra on which `ν` vanishes but `μ` does not
  obtain ⟨s, hs, hνs, hμs⟩ : ∃ s, MeasurableSet[⨆ n, ℱ n] s ∧ ν s = 0 ∧ μ s ≠ 0 := by
    by_contra! hcon
    refine h (Measure.AbsolutelyContinuous.mk fun s hs hνs ↦ ?_)
    rw [trim_measurableSet_eq hsup hs] at hνs ⊢
    exact hcon s hs hνs
  -- approximate it by sets of the filtration
  have happrox : ∀ ε : ℝ≥0∞, 0 < ε →
      ∃ n, ∃ t, MeasurableSet[ℱ n] t ∧ μ (t ∆ s) < ε ∧ ν (t ∆ s) < ε := by
    intro ε hε
    have hC := ℱ.isSetRing_iUnion_measurableSet
    obtain ⟨t, ⟨n, ht⟩, htε⟩ := @exists_measure_symmDiff_lt_of_generateFrom_isSetRing 𝓧 (⨆ n, ℱ n)
      ((μ + ν).trim hsup) _ _ hC ⟨{univ}, countable_singleton _, by
        simp only [singleton_subset_iff]; exact ⟨0, @MeasurableSet.univ _ (ℱ 0)⟩, by simp⟩
      (MeasurableSpace.measurableSpace_iSup_eq ℱ) s hs ε hε
    refine ⟨n, t, ht, ?_⟩
    rw [trim_measurableSet_eq hsup (((le_iSup ℱ n) _ ht).symmDiff hs), Measure.add_apply] at htε
    exact ⟨(le_self_add).trans_lt htε, (le_add_self).trans_lt htε⟩
  refine iSup_eq_top.mpr fun b hb ↦ ?_
  have hM : 0 ≤ μ.real univ := measureReal_nonneg
  have hb0 : 0 ≤ b.toReal := ENNReal.toReal_nonneg
  have ha : 0 < μ.real s := ENNReal.toReal_pos hμs (measure_ne_top _ _)
  set c := μ.real s / 2 with hc
  have hc0 : 0 < c := by positivity
  set ε₀ := c * exp (-(b.toReal + μ.real univ + 1) / c) with hε₀
  have hε₀0 : 0 < ε₀ := by positivity
  have hε₀c : ε₀ ≤ c := by
    rw [hε₀, mul_le_iff_le_one_right hc0, exp_le_one_iff]
    exact div_nonpos_of_nonpos_of_nonneg (by linarith) hc0.le
  have hclog : c * log (c / ε₀) = b.toReal + μ.real univ + 1 := by
    have : c / ε₀ = exp ((b.toReal + μ.real univ + 1) / c) := by
      rw [hε₀, ← div_div, div_self hc0.ne', one_div, ← exp_neg, neg_div, neg_neg]
    rw [this, log_exp]
    field_simp
  obtain ⟨n, t, ht, hμt, hνt⟩ := happrox (ENNReal.ofReal ε₀) (ENNReal.ofReal_pos.mpr hε₀0)
  rw [ENNReal.lt_ofReal_iff_toReal_lt (measure_ne_top _ _), ← measureReal_def] at hμt hνt
  refine ⟨n, ?_⟩
  have hx : c ≤ μ.real t := by
    have : μ.real s ≤ μ.real t + μ.real (t ∆ s) :=
      (measureReal_mono (μ := μ) (fun x hx ↦ by
        by_cases hxt : x ∈ t
        · exact Or.inl hxt
        · exact Or.inr (Or.inr ⟨hx, hxt⟩))).trans (measureReal_union_le _ _)
    linarith
  have hy : ν.real t ≤ ε₀ := by
    have : ν.real t ≤ ν.real (t ∆ s) + ν.real s :=
      (measureReal_mono (μ := ν) (fun x hx ↦ by
        by_cases hxs : x ∈ s
        · exact Or.inr hxs
        · exact Or.inl (Or.inl ⟨hx, hxs⟩))).trans (measureReal_union_le _ _)
    have h0 : ν.real s = 0 := by simp [measureReal_def, hνs]
    linarith
  have hμt0 : μ t ≠ 0 := by
    intro h0
    have : μ.real t = 0 := by simp [measureReal_def, h0]
    linarith
  by_cases hνt0 : ν t = 0
  · rw [klDiv_eq_top_of_measure_eq_zero (s := t) (by rwa [trim_measurableSet_eq _ ht])
      (by rwa [trim_measurableSet_eq _ ht])]
    exact hb
  have hy0 : 0 < ν.real t := ENNReal.toReal_pos hνt0 (measure_ne_top _ _)
  have hxM : μ.real t ≤ μ.real univ := measureReal_mono (subset_univ t)
  calc b = ENNReal.ofReal b.toReal := (ENNReal.ofReal_toReal hb.ne).symm
    _ < ENNReal.ofReal (b.toReal + 1) := by
        rw [ENNReal.ofReal_lt_ofReal_iff (by linarith [ENNReal.toReal_nonneg (a := b)])]
        linarith
    _ ≤ ENNReal.ofReal (μ.real t * log (μ.real t / ν.real t) + ν.real t - μ.real t) := by
        refine ENNReal.ofReal_le_ofReal ?_
        have := mul_log_div_le_mul_log_div hc0 hx hy0 hy hε₀c
        linarith
    _ = ENNReal.ofReal ((μ.trim (ℱ.le n)).real t * log ((μ.trim (ℱ.le n)).real t
          / (ν.trim (ℱ.le n)).real t) + (ν.trim (ℱ.le n)).real t - (μ.trim (ℱ.le n)).real t) := by
        simp only [measureReal_def, trim_measurableSet_eq _ ht]
    _ ≤ klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n)) := mul_log_le_klDiv_of_measurableSet ht

/-- Georgii (15.6), for a sequence of sigma-algebras: the supremum of the relative entropies on
the sigma-algebras of a filtration `ℱ` is the relative entropy on `⨆ n, ℱ n`. -/
theorem iSup_klDiv_trim :
    ⨆ n, klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n))
      = klDiv (μ.trim (iSup_le ℱ.le)) (ν.trim (iSup_le ℱ.le)) := by
  refine le_antisymm (iSup_le fun n ↦ klDiv_trim_le_klDiv_trim_iSup ℱ n) ?_
  by_cases h : μ.trim (iSup_le ℱ.le) ≪ ν.trim (iSup_le ℱ.le)
  · exact klDiv_trim_iSup_le_iSup_klDiv_trim_of_ac ℱ h
  · rw [iSup_klDiv_trim_eq_top_of_not_ac ℱ h]
    exact le_top

/-- Georgii (15.6) with the limit sigma-algebra given as `m = ⨆ n, ℱ n`. -/
theorem iSup_klDiv_trim_of_iSup_eq (hm : m ≤ m𝓧) (h : ⨆ n, ℱ n = m) :
    ⨆ n, klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n)) = klDiv (μ.trim hm) (ν.trim hm) := by
  subst h
  exact iSup_klDiv_trim ℱ

/-- Georgii (15.6), limit form: the relative entropies along a filtration converge (monotonically)
to the relative entropy on `⨆ n, ℱ n`. -/
theorem tendsto_klDiv_trim :
    Tendsto (fun n ↦ klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n))) atTop
      (𝓝 (klDiv (μ.trim (iSup_le ℱ.le)) (ν.trim (iSup_le ℱ.le)))) := by
  rw [← iSup_klDiv_trim ℱ]
  exact tendsto_atTop_iSup (monotone_klDiv_trim ℱ)

end Filtration

section FinitePartition

variable [IsFiniteMeasure μ] [IsFiniteMeasure ν]

omit [IsFiniteMeasure μ] [IsFiniteMeasure ν] in
/-- A family of pairwise disjoint sets is a π-system. -/
lemma _root_.Set.PairwiseDisjoint.isPiSystem {S : Set (Set 𝓧)} (h : S.PairwiseDisjoint id) :
    IsPiSystem S := by
  intro s hs t ht hst
  obtain rfl : s = t := by
    by_contra hne
    exact hst.ne_empty (Set.disjoint_iff_inter_eq_empty.mp (h hs ht hne))
  simpa using hs

private lemma klFun_div_mul {x y : ℝ} (hy : y ≠ 0) :
    klFun (x / y) * y = x * log (x / y) + y - x := by
  rw [klFun_apply]
  field_simp

omit [IsFiniteMeasure μ] [IsFiniteMeasure ν] in
private lemma sum_measure_of_partition {m' : MeasurableSpace 𝓧} (ρ : @Measure 𝓧 m')
    {P : Finset (Set 𝓧)} (hP_disj : (P : Set (Set 𝓧)).PairwiseDisjoint id)
    (hP_cover : ⋃₀ (P : Set (Set 𝓧)) = univ) (hP_meas : ∀ A ∈ P, MeasurableSet[m'] A) :
    ρ univ = ∑ A ∈ P, ρ A := by
  rw [← hP_cover, sUnion_eq_biUnion]
  exact measure_biUnion_finset hP_disj hP_meas

/-- Georgii's formula for the relative entropy on the sigma-algebra generated by a finite
measurable partition `P` (the summands of (15.7)), in Mathlib's normalisation and assuming
`μ ≪ ν` on `P`; without that assumption the left-hand side is `∞`
(`klDiv_eq_top_of_measure_eq_zero`). -/
theorem klDiv_trim_generateFrom_eq_sum {P : Finset (Set 𝓧)}
    (hP_disj : (P : Set (Set 𝓧)).PairwiseDisjoint id) (hP_cover : ⋃₀ (P : Set (Set 𝓧)) = univ)
    (hP_meas : ∀ A ∈ P, MeasurableSet A) (hac : ∀ A ∈ P, ν A = 0 → μ A = 0) :
    klDiv (μ.trim (generateFrom_le hP_meas)) (ν.trim (generateFrom_le hP_meas))
      = ∑ A ∈ P, ENNReal.ofReal (μ.real A * log (μ.real A / ν.real A) + ν.real A - μ.real A) := by
  have hP : generateFrom (P : Set (Set 𝓧)) ≤ m𝓧 := generateFrom_le hP_meas
  have hmeasP : ∀ A ∈ P, MeasurableSet[generateFrom (P : Set (Set 𝓧))] A :=
    fun A hA ↦ measurableSet_generateFrom (Finset.mem_coe.mpr hA)
  set f : 𝓧 → ℝ≥0∞ := fun x ↦ ∑ A ∈ P, A.indicator (fun _ ↦ μ A / ν A) x with hf
  have hf_meas : Measurable[generateFrom (P : Set (Set 𝓧))] f :=
    Finset.measurable_sum _ fun A hA ↦ measurable_const.indicator (hmeasP A hA)
  have hf_eq : ∀ A ∈ P, EqOn f (fun _ ↦ μ A / ν A) A := by
    intro A hA x hx
    simp only [hf]
    rw [Finset.sum_eq_single A]
    · exact indicator_of_mem hx _
    · intro B hB hBA
      exact indicator_of_notMem (Set.disjoint_right.mp (hP_disj hB hA hBA) hx) _
    · intro h
      exact absurd hA h
  have hμA : ∀ A ∈ P, μ A / ν A * ν A = μ A := by
    intro A hA
    by_cases hν : ν A = 0
    · simp [hν, hac A hA hν]
    · rw [div_eq_mul_inv, mul_assoc, ENNReal.inv_mul_cancel hν (measure_ne_top _ _), mul_one]
  have h_apply : ∀ A ∈ P, ((ν.trim hP).withDensity f) A = μ A := by
    intro A hA
    rw [withDensity_apply _ (hmeasP A hA), setLIntegral_congr_fun (hmeasP A hA) (hf_eq A hA),
      setLIntegral_const, trim_measurableSet_eq hP (hmeasP A hA), hμA A hA]
  have h_dens : μ.trim hP = (ν.trim hP).withDensity f := by
    refine ext_of_generate_finite (P : Set (Set 𝓧)) rfl hP_disj.isPiSystem ?_ ?_
    · intro A hA
      rw [Finset.mem_coe] at hA
      rw [trim_measurableSet_eq hP (hmeasP A hA), h_apply A hA]
    · rw [sum_measure_of_partition _ hP_disj hP_cover hmeasP,
        sum_measure_of_partition _ hP_disj hP_cover hmeasP]
      exact Finset.sum_congr rfl fun A hA ↦ by
        rw [trim_measurableSet_eq hP (hmeasP A hA), h_apply A hA]
  have hU : (⋃ A ∈ P, id A) = univ := by
    rw [eq_univ_iff_forall]
    intro x
    have hx : x ∈ ⋃₀ (P : Set (Set 𝓧)) := hP_cover ▸ mem_univ x
    obtain ⟨A, hA, hxA⟩ := mem_sUnion.mp hx
    exact mem_iUnion₂.mpr ⟨A, Finset.mem_coe.mp hA, hxA⟩
  have hsplit : ∫⁻ x, ENNReal.ofReal (klFun (f x).toReal) ∂ν
      = ∑ A ∈ P, ∫⁻ x in A, ENNReal.ofReal (klFun (f x).toReal) ∂ν :=
    calc ∫⁻ x, ENNReal.ofReal (klFun (f x).toReal) ∂ν
        = ∫⁻ x in ⋃ A ∈ P, id A, ENNReal.ofReal (klFun (f x).toReal) ∂ν := by
          rw [hU, Measure.restrict_univ]
      _ = ∑ A ∈ P, ∫⁻ x in id A, ENNReal.ofReal (klFun (f x).toReal) ∂ν :=
          lintegral_biUnion_finset hP_disj hP_meas _
      _ = ∑ A ∈ P, ∫⁻ x in A, ENNReal.ofReal (klFun (f x).toReal) ∂ν := rfl
  rw [klDiv_trim_eq_lintegral_klFun_of_trim_eq_withDensity hP hf_meas h_dens, hsplit]
  refine Finset.sum_congr rfl fun A hA ↦ ?_
  rw [setLIntegral_congr_fun (hP_meas A hA) (fun x hx ↦ by rw [hf_eq A hA hx]), setLIntegral_const,
    ENNReal.toReal_div]
  by_cases hν : ν A = 0
  · simp [measureReal_def, hν, hac A hA hν]
  · have hν' : ν.real A ≠ 0 := (measureReal_ne_zero_iff (measure_ne_top _ _)).mpr hν
    rw [← measureReal_def, ← measureReal_def, ← ENNReal.ofReal_toReal (measure_ne_top ν A),
      ← measureReal_def,
      ← ENNReal.ofReal_mul (klFun_nonneg (div_nonneg measureReal_nonneg measureReal_nonneg)),
      klFun_div_mul hν']

/-- Georgii's formula for the relative entropy on the sigma-algebra generated by a finite
measurable partition `P`: `∑ A ∈ P, μ A * log (μ A / ν A)`, up to the finite-measure correction
`ν univ - μ univ` (which vanishes for probability measures). -/
theorem toReal_klDiv_trim_generateFrom_eq_sum {P : Finset (Set 𝓧)}
    (hP_disj : (P : Set (Set 𝓧)).PairwiseDisjoint id) (hP_cover : ⋃₀ (P : Set (Set 𝓧)) = univ)
    (hP_meas : ∀ A ∈ P, MeasurableSet A) (hac : ∀ A ∈ P, ν A = 0 → μ A = 0) :
    (klDiv (μ.trim (generateFrom_le hP_meas)) (ν.trim (generateFrom_le hP_meas))).toReal
      = ∑ A ∈ P, μ.real A * log (μ.real A / ν.real A) + ν.real univ - μ.real univ := by
  have h_nonneg : ∀ A ∈ P, 0 ≤ μ.real A * log (μ.real A / ν.real A) + ν.real A - μ.real A := by
    intro A hA
    by_cases hν : ν A = 0
    · simp [measureReal_def, hν, hac A hA hν]
    · rw [← klFun_div_mul ((measureReal_ne_zero_iff (measure_ne_top _ _)).mpr hν)]
      exact mul_nonneg (klFun_nonneg (div_nonneg measureReal_nonneg measureReal_nonneg))
        measureReal_nonneg
  have hμ : μ.real univ = ∑ A ∈ P, μ.real A := by
    rw [measureReal_def, sum_measure_of_partition μ hP_disj hP_cover hP_meas,
      ENNReal.toReal_sum fun _ _ ↦ measure_ne_top _ _]
    rfl
  have hν : ν.real univ = ∑ A ∈ P, ν.real A := by
    rw [measureReal_def, sum_measure_of_partition ν hP_disj hP_cover hP_meas,
      ENNReal.toReal_sum fun _ _ ↦ measure_ne_top _ _]
    rfl
  rw [klDiv_trim_generateFrom_eq_sum hP_disj hP_cover hP_meas hac,
    ENNReal.toReal_sum fun A _ ↦ ENNReal.ofReal_ne_top,
    Finset.sum_congr rfl fun A hA ↦ ENNReal.toReal_ofReal (h_nonneg A hA),
    Finset.sum_sub_distrib, Finset.sum_add_distrib, hμ, hν]

/-- If the density of `μ` with respect to `ν` on `m₂` is measurable with respect to a smaller
sigma-algebra `m₁ ≤ m₂` (`m₁` is *sufficient*), the relative entropies on `m₁` and `m₂` agree. -/
lemma klDiv_trim_eq_of_measurable_rnDeriv {m₁ m₂ : MeasurableSpace 𝓧} (h₁₂ : m₁ ≤ m₂)
    (h₂ : m₂ ≤ m𝓧) (hac : μ.trim h₂ ≪ ν.trim h₂)
    (hf : Measurable[m₁] ((μ.trim h₂).rnDeriv (ν.trim h₂))) :
    klDiv (μ.trim (h₁₂.trans h₂)) (ν.trim (h₁₂.trans h₂)) = klDiv (μ.trim h₂) (ν.trim h₂) := by
  set f := (μ.trim h₂).rnDeriv (ν.trim h₂) with hf_def
  have h₂' : μ.trim h₂ = (ν.trim h₂).withDensity f := (Measure.withDensity_rnDeriv_eq _ _ hac).symm
  have h₁' : μ.trim (h₁₂.trans h₂) = (ν.trim (h₁₂.trans h₂)).withDensity f := by
    rw [← trim_trim (hm₁₂ := h₁₂) (hm₂ := h₂), ← trim_trim (hm₁₂ := h₁₂) (hm₂ := h₂), h₂',
      trim_withDensity h₁₂ hf]
  rw [klDiv_trim_eq_lintegral_klFun_of_trim_eq_withDensity _ hf h₁',
    klDiv_trim_eq_lintegral_klFun_of_trim_eq_withDensity _ (hf.mono h₁₂ le_rfl) h₂']

omit [IsFiniteMeasure μ] [IsFiniteMeasure ν] in
/-- Rewriting the sub-sigma-algebra in a relative entropy. -/
lemma klDiv_trim_congr {m₁ m₂ : MeasurableSpace 𝓧} (h : m₁ = m₂) (h₁ : m₁ ≤ m𝓧) (h₂ : m₂ ≤ m𝓧) :
    klDiv (μ.trim h₁) (ν.trim h₁) = klDiv (μ.trim h₂) (ν.trim h₂) := by
  subst h
  rfl

/-- Georgii (15.7): the relative entropy on a sigma-algebra `m` is the supremum, over all finite
`m`-measurable partitions `P`, of the relative entropy on the finite sigma-algebra generated by
`P` (computed in `klDiv_trim_generateFrom_eq_sum`). -/
theorem klDiv_trim_eq_iSup_finset_partition (hm : m ≤ m𝓧) :
    klDiv (μ.trim hm) (ν.trim hm)
      = ⨆ (P : Finset (Set 𝓧)) (hP : (P : Set (Set 𝓧)).PairwiseDisjoint id ∧
          ⋃₀ (P : Set (Set 𝓧)) = univ ∧ ∀ A ∈ P, MeasurableSet[m] A),
          klDiv (μ.trim ((generateFrom_le hP.2.2).trans hm))
            (ν.trim ((generateFrom_le hP.2.2).trans hm)) := by
  refine le_antisymm ?_ (iSup₂_le fun P hP ↦ klDiv_trim_mono (generateFrom_le hP.2.2) hm)
  by_cases hac : μ.trim hm ≪ ν.trim hm
  swap
  · -- without absolute continuity, a two-set partition already has infinite relative entropy
    obtain ⟨s, hs, hνs, hμs⟩ : ∃ s, MeasurableSet[m] s ∧ ν s = 0 ∧ μ s ≠ 0 := by
      by_contra! hcon
      refine hac (Measure.AbsolutelyContinuous.mk fun s hs hνs ↦ ?_)
      rw [trim_measurableSet_eq hm hs] at hνs ⊢
      exact hcon s hs hνs
    classical
    have hP : ((({s, sᶜ} : Finset (Set 𝓧)) : Set (Set 𝓧)).PairwiseDisjoint id ∧
        ⋃₀ (({s, sᶜ} : Finset (Set 𝓧)) : Set (Set 𝓧)) = univ ∧
        ∀ A ∈ ({s, sᶜ} : Finset (Set 𝓧)), MeasurableSet[m] A) := by
      refine ⟨?_, ?_, ?_⟩
      · simp only [Finset.coe_insert, Finset.coe_singleton]
        rw [Set.pairwiseDisjoint_insert]
        refine ⟨Set.pairwiseDisjoint_singleton _ _, ?_⟩
        simp only [mem_singleton_iff, forall_eq, id]
        exact fun _ ↦ disjoint_compl_right
      · simp
      · simp [hs, hs.compl]
    refine le_iSup₂_of_le {s, sᶜ} hP ?_
    have hs' : MeasurableSet[generateFrom (({s, sᶜ} : Finset (Set 𝓧)) : Set (Set 𝓧))] s :=
      measurableSet_generateFrom (by simp)
    refine le_of_le_of_eq le_top (klDiv_eq_top_of_measure_eq_zero (s := s) ?_ ?_).symm
    · rwa [trim_measurableSet_eq _ hs']
    · rwa [trim_measurableSet_eq _ hs']
  · -- with absolute continuity: the density is measurable for a countably generated
    -- sub-sigma-algebra, which is the limit of the finite sigma-algebras of `countableFiltration`
    set f := (μ.trim hm).rnDeriv (ν.trim hm) with hf
    have hf_meas : Measurable[m] f := Measure.measurable_rnDeriv _ _
    let m' : MeasurableSpace 𝓧 := MeasurableSpace.comap f inferInstance
    have hm'm : m' ≤ m := hf_meas.comap_le
    have hm' : m' ≤ m𝓧 := hm'm.trans hm
    have : @CountablyGenerated 𝓧 m' := CountablyGenerated.comap f
    let ℱ₀ : @Filtration 𝓧 ℕ _ m' := @countableFiltration 𝓧 m' _
    let ℱ : Filtration ℕ m𝓧 := ⟨fun n ↦ ℱ₀ n, fun _ _ h ↦ ℱ₀.mono h, fun n ↦ (ℱ₀.le n).trans hm'⟩
    have hsup : ⨆ n, ℱ n = m' := @iSup_countableFiltration 𝓧 m' _
    have hf' : Measurable[m'] f := comap_measurable f
    calc klDiv (μ.trim hm) (ν.trim hm)
        = klDiv (μ.trim hm') (ν.trim hm') :=
          (klDiv_trim_eq_of_measurable_rnDeriv hm'm hm hac hf').symm
      _ = ⨆ n, klDiv (μ.trim (ℱ.le n)) (ν.trim (ℱ.le n)) :=
          (iSup_klDiv_trim_of_iSup_eq ℱ hm' hsup).symm
      _ ≤ _ := by
          refine iSup_le fun n ↦ ?_
          have hfin := @finite_countablePartition 𝓧 m' _ n
          set P : Finset (Set 𝓧) := hfin.toFinset with hP_def
          have hP : (P : Set (Set 𝓧)).PairwiseDisjoint id ∧ ⋃₀ (P : Set (Set 𝓧)) = univ ∧
              ∀ A ∈ P, MeasurableSet[m] A := by
            refine ⟨?_, ?_, ?_⟩
            · rw [hfin.coe_toFinset]
              intro s hs t ht hst
              exact @disjoint_countablePartition 𝓧 m' _ n s t hs ht hst
            · rw [hfin.coe_toFinset]
              exact @sUnion_countablePartition 𝓧 m' _ n
            · intro A hA
              rw [hfin.mem_toFinset] at hA
              exact hm'm _ (@measurableSet_countablePartition 𝓧 m' _ n A hA)
          refine le_iSup₂_of_le P hP (le_of_eq ?_)
          refine klDiv_trim_congr ?_ _ _
          change generateFrom (@countablePartition 𝓧 m' _ n) = generateFrom (P : Set (Set 𝓧))
          rw [hfin.coe_toFinset]

open scoped Classical in
/-- Georgii (15.7) with the explicit sums: `𝓗_m(μ | ν) = ⨆ P, ∑ A ∈ P, μ A * log (μ A / ν A)` over
finite `m`-measurable partitions `P`, with Georgii's convention that a summand with `ν A = 0 < μ A`
is `∞` (and Mathlib's finite-measure correction `ν A - μ A` in each summand). -/
theorem klDiv_trim_eq_iSup_sum (hm : m ≤ m𝓧) :
    klDiv (μ.trim hm) (ν.trim hm)
      = ⨆ (P : Finset (Set 𝓧)) (_ : (P : Set (Set 𝓧)).PairwiseDisjoint id ∧
          ⋃₀ (P : Set (Set 𝓧)) = univ ∧ ∀ A ∈ P, MeasurableSet[m] A),
          if ∀ A ∈ P, ν A = 0 → μ A = 0 then
            ∑ A ∈ P, ENNReal.ofReal (μ.real A * log (μ.real A / ν.real A) + ν.real A - μ.real A)
          else ∞ := by
  rw [klDiv_trim_eq_iSup_finset_partition hm]
  refine iSup_congr fun P ↦ iSup_congr fun hP ↦ ?_
  split_ifs with hac
  · exact klDiv_trim_generateFrom_eq_sum hP.1 hP.2.1 (fun A hA ↦ hm _ (hP.2.2 A hA)) hac
  · push Not at hac
    obtain ⟨A, hA, hνA, hμA⟩ := hac
    have hA' : MeasurableSet[generateFrom (P : Set (Set 𝓧))] A :=
      measurableSet_generateFrom (Finset.mem_coe.mpr hA)
    exact klDiv_eq_top_of_measure_eq_zero (s := A) (by rwa [trim_measurableSet_eq _ hA'])
      (by rwa [trim_measurableSet_eq _ hA'])

end FinitePartition

end InformationTheory
