import Mathlib

/-!
# Shared, Mathlib-only vocabulary for the Georgii comparator challenges

This is the *preamble* shared by the `comparator` challenge files for
Georgii, *Gibbs Measures and Phase Transitions*, 2nd ed.

**It imports `Mathlib` and nothing else**, and every notion is spelled out from first principles,
so that a skeptical reader who does not trust the `GibbsMeasure` library can check each definition
by eye against the book.

## Dictionary

| Georgii | here |
| --- | --- |
| `Ω = E^S` with the product σ-algebra `𝓕 = 𝓔^S` | `Config S E := S → E` (`MeasurableSpace.pi`) |
| `𝓣_Λ = 𝓕_{S∖Λ}`, (1.21) | `outside Λ` |
| `𝓕_Λ` | `inside Λ` |
| `𝓣 = ⋂_Λ 𝓣_Λ`, the tail σ-algebra | `tail S E` |
| proper kernel, (1.18) | `IsProper` |
| specification, (1.23) | `IsSpecification` |
| `𝓖(γ)`, the DLR equations | `IsGibbs` |
| local (`𝓛`-) convergence, (4.2) | `TendstoLocally` |

## Design notes

* `outside Λ` is defined as `⨆ i ∈ Λᶜ, comap (fun ω ↦ ω i)`, the σ-algebra generated by the
  coordinates *off* the finite volume `Λ`. `outside_eq_comap` proves that this is the same as the
  σ-algebra pulled back along the restriction map `ω ↦ ω|_{Λᶜ}`, and `mem_iff_mem_of_outside` /
  `measurable_outside_of_local` show that it is *exactly* the class of objects that do not depend
  on the coordinates inside `Λ`. So the two candidate definitions agree, and both match the
  intended meaning.
* **Local convergence** is stated directly as "`μ_i A → μ A` for every local (cylinder) event `A`"
  (`TendstoLocally`), which is *literally* Georgii's characterisation of convergence in the
  `𝓛`-topology (4.2); it works for arbitrary index filters (nets, not just sequences) and needs
  neither an enumeration of the local events nor finiteness of `E`. The metric
  `Σ 2⁻ⁿ |μ(Aₙ) − ν(Aₙ)|` of Georgii (4.3)(3) metrises this topology only when `E` is finite and
  `S` is countable, and fixing an enumeration would inject an irrelevant arbitrary choice into
  every theorem statement, so we avoid it. `localTopology` records the topology itself and
  `tendstoLocally_iff_tendsto` proves that the two formulations agree.

## Non-degeneracy

A vacuous definition would make every challenge trivially satisfiable, so the definitions are
exercised on examples:

* `isProper_dirac`, `consistent_dirac`, `dirac_isGibbs`: the family `γ_Λ ω = δ_ω` is Markov, proper
  and consistent, and *every* probability measure satisfies its DLR equations. (It is **not** a
  specification for `Λ ≠ ∅`, since `ω ↦ δ_ω(A)` is not `outside Λ`-measurable; that is exactly why
  `IsSpecification` carries the measurability field.)
* `eq_dirac_of_isSpecification`, `isGibbs_empty_volume`: in any specification the empty volume is
  forced to be `γ_∅ ω = δ_ω`, so the DLR equation for `Λ = ∅` is automatic.
* `isSpecification_indep`, `isGibbs_indep`: for a finite parameter set `S` and a probability measure
  `ν` on `E`, the independent specification `γ_Λ ω = ν^Λ ⊗ δ_{ω off Λ}` satisfies **all four**
  axioms, and the product measure `ν^S` is a Gibbs measure for it. So `IsSpecification` and
  `IsGibbs` are both non-vacuous, with a non-trivial (non-Dirac) example. (`S` is finite there only
  to keep the preamble free of infinite product measures, which current Mathlib does not provide;
  nothing else in this file assumes finiteness.)
* `not_measurableSet_outside`: `outside Λ` is a *proper* sub-σ-algebra — the event `{ω : ω 0 = 1}`
  is not measurable outside `{0}`.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
set_option warn.classDefReducibility false

open MeasureTheory Filter
open scoped ENNReal

noncomputable section

namespace GibbsChallenge

variable {S E : Type*} [MeasurableSpace E]

/-! ## The configuration space -/

/-- The configuration space `Ω = E^S` of Georgii, §1.1. It carries the product σ-algebra
`MeasurableSpace.pi`, i.e. the smallest σ-algebra making every coordinate `ω ↦ ω i` measurable. -/
abbrev Config (S E : Type*) := S → E

/-- Measurability into a product space, for an arbitrary (not necessarily canonical) σ-algebra `m`
on the source: `f` is `m`-measurable as soon as each of its coordinates is. -/
theorem measurable_pi_of {α : Type*} (m : MeasurableSpace α) {ι : Type*} {β : ι → Type*}
    [∀ i, MeasurableSpace (β i)] {f : α → ∀ i, β i}
    (hf : ∀ i, Measurable[m] fun a => f a i) : Measurable[m] f := by
  simp_rw [measurable_iff_comap_le, MeasurableSpace.pi, MeasurableSpace.comap_iSup,
    MeasurableSpace.comap_comp, Function.comp_def, iSup_le_iff] at hf ⊢
  exact hf

/-! ## Gluing two configurations along a finite volume -/

open Classical in
/-- `glue Λ σ ω` follows `σ` inside `Λ` and the boundary condition `ω` outside `Λ`. -/
def glue (Λ : Finset S) (σ ω : Config S E) : Config S E := fun i => if i ∈ Λ then σ i else ω i

omit [MeasurableSpace E] in
theorem glue_of_mem {Λ : Finset S} {i : S} (hi : i ∈ Λ) (σ ω : Config S E) :
    glue Λ σ ω i = σ i := by simp [glue, hi]

omit [MeasurableSpace E] in
theorem glue_of_notMem {Λ : Finset S} {i : S} (hi : i ∉ Λ) (σ ω : Config S E) :
    glue Λ σ ω i = ω i := by simp [glue, hi]

theorem measurable_glue_comp {α : Type*} [MeasurableSpace α] (Λ : Finset S)
    {u v : α → Config S E} (hu : Measurable u) (hv : Measurable v) :
    Measurable fun a => glue Λ (u a) (v a) := by
  refine measurable_pi_lambda _ fun i => ?_
  by_cases h : i ∈ Λ
  · simp only [glue_of_mem h]
    exact (measurable_pi_apply i).comp hu
  · simp only [glue_of_notMem h]
    exact (measurable_pi_apply i).comp hv

theorem measurable_glue (Λ : Finset S) :
    Measurable fun p : Config S E × Config S E => glue Λ p.1 p.2 :=
  measurable_glue_comp Λ measurable_fst measurable_snd

theorem measurable_glue_swap (Λ : Finset S) :
    Measurable fun p : Config S E × Config S E => glue Λ p.2 p.1 :=
  measurable_glue_comp Λ measurable_snd measurable_fst

theorem measurable_glue_left (Λ : Finset S) (ω : Config S E) :
    Measurable fun σ : Config S E => glue Λ σ ω :=
  measurable_glue_comp Λ measurable_id measurable_const

omit [MeasurableSpace E] in
/-- For `Λ ⊆ Δ`, updating inside `Λ` after updating inside `Δ` is again an update inside `Δ`. -/
theorem glue_glue {Λ Δ : Finset S} (h : Λ ⊆ Δ) (σ σ' ω : Config S E) :
    glue Λ σ (glue Δ σ' ω) = glue Δ (glue Λ σ σ') ω := by
  funext i
  by_cases hΛ : i ∈ Λ
  · rw [glue_of_mem hΛ, glue_of_mem (h hΛ), glue_of_mem hΛ]
  · rw [glue_of_notMem hΛ]
    by_cases hΔ : i ∈ Δ
    · rw [glue_of_mem hΔ, glue_of_mem hΔ, glue_of_notMem hΛ]
    · rw [glue_of_notMem hΔ, glue_of_notMem hΔ]

/-! ## The σ-algebras attached to a finite volume -/

/-- Georgii's external σ-algebra `𝓣_Λ = 𝓕_{S∖Λ}` (1.21): generated by the coordinates **off** the
finite volume `Λ`. -/
def outside (Λ : Finset S) : MeasurableSpace (Config S E) :=
  ⨆ i ∈ (Λ : Set S)ᶜ, MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance

/-- Georgii's `𝓕_Λ`: generated by the coordinates **inside** the finite volume `Λ`. -/
def inside (Λ : Finset S) : MeasurableSpace (Config S E) :=
  ⨆ i ∈ (Λ : Set S), MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance

theorem comap_le_outside {Λ : Finset S} {i : S} (hi : i ∉ Λ) :
    MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance ≤ outside Λ :=
  le_iSup₂ (f := fun i (_ : i ∈ (Λ : Set S)ᶜ) =>
    MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance) i hi

theorem comap_le_inside {Λ : Finset S} {i : S} (hi : i ∈ Λ) :
    MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance ≤ inside Λ :=
  le_iSup₂ (f := fun i (_ : i ∈ (Λ : Set S)) =>
    MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance) i hi

theorem outside_le (Λ : Finset S) :
    outside (E := E) Λ ≤ (inferInstance : MeasurableSpace (Config S E)) := by
  refine iSup₂_le fun i _ => ?_
  rintro s ⟨t, ht, rfl⟩
  exact measurable_pi_apply i ht

theorem inside_le (Λ : Finset S) :
    inside (E := E) Λ ≤ (inferInstance : MeasurableSpace (Config S E)) := by
  refine iSup₂_le fun i _ => ?_
  rintro s ⟨t, ht, rfl⟩
  exact measurable_pi_apply i ht

theorem measurableSet_of_outside {Λ : Finset S} {B : Set (Config S E)}
    (hB : MeasurableSet[outside Λ] B) : MeasurableSet B := outside_le Λ _ hB

theorem measurableSet_of_inside {Λ : Finset S} {B : Set (Config S E)}
    (hB : MeasurableSet[inside Λ] B) : MeasurableSet B := inside_le Λ _ hB

/-- The bigger the volume, the less information is left outside it. -/
theorem outside_antitone {Λ Δ : Finset S} (h : Λ ⊆ Δ) : outside (E := E) Δ ≤ outside Λ :=
  iSup₂_le fun _ hi => comap_le_outside fun hiΛ => hi (h hiΛ)

/-- The restriction of a configuration to the complement of `Λ`. -/
def restrictOutside (Λ : Finset S) (ω : Config S E) : {i : S // i ∉ Λ} → E := fun i => ω i.1

theorem measurable_restrictOutside (Λ : Finset S) :
    Measurable[outside Λ] (restrictOutside (E := E) Λ) :=
  measurable_pi_of _ fun i => Measurable.of_comap_le (comap_le_outside i.2)

/-- The two usual descriptions of `𝓣_Λ` agree: the σ-algebra generated by the coordinates off `Λ`
is the σ-algebra pulled back along the restriction map `ω ↦ ω|_{Λᶜ}`. -/
theorem outside_eq_comap (Λ : Finset S) :
    outside (E := E) Λ = MeasurableSpace.comap (restrictOutside Λ) inferInstance := by
  refine le_antisymm ?_ (measurable_restrictOutside Λ).comap_le
  refine iSup₂_le fun i hi => ?_
  have h1 : Measurable[MeasurableSpace.comap (restrictOutside (E := E) Λ) inferInstance]
      (restrictOutside Λ) := Measurable.of_comap_le le_rfl
  exact ((measurable_pi_apply (⟨i, hi⟩ : {i : S // i ∉ Λ})).comp h1).comap_le

/-- **Events measurable outside `Λ` do not depend on the coordinates inside `Λ`.** -/
theorem mem_iff_mem_of_outside {Λ : Finset S} {B : Set (Config S E)}
    (hB : MeasurableSet[outside Λ] B) {ω ω' : Config S E} (h : ∀ i ∉ Λ, ω i = ω' i) :
    ω ∈ B ↔ ω' ∈ B := by
  rw [outside_eq_comap] at hB
  obtain ⟨C, -, rfl⟩ := hB
  have hr : restrictOutside Λ ω = restrictOutside Λ ω' := funext fun i => h i.1 i.2
  simp only [Set.mem_preimage, hr]

/-- **Conversely**, a measurable function that does not depend on the coordinates inside `Λ` is
measurable with respect to `outside Λ`. -/
theorem measurable_outside_of_local [Nonempty E] {α : Type*} [MeasurableSpace α] (Λ : Finset S)
    {f : Config S E → α} (hf : Measurable f)
    (hloc : ∀ ω ω' : Config S E, (∀ i ∉ Λ, ω i = ω' i) → f ω = f ω') :
    Measurable[outside Λ] f := by
  set ζ : Config S E := fun _ => Classical.arbitrary E with hζ
  have hg : Measurable[outside Λ] fun ω : Config S E => glue Λ ζ ω := by
    refine measurable_pi_of _ fun i => ?_
    by_cases hi : i ∈ Λ
    · simp only [glue_of_mem hi]
      exact measurable_const
    · simp only [glue_of_notMem hi]
      exact Measurable.of_comap_le (comap_le_outside hi)
  have hfg : f = f ∘ fun ω : Config S E => glue Λ ζ ω :=
    funext fun ω => hloc _ _ fun i hi => (glue_of_notMem hi ζ ω).symm
  rw [hfg]
  exact hf.comp hg

/-- Nothing is measurable outside `Λ = ∅`, i.e. `𝓣_∅ = 𝓕`. -/
theorem outside_empty :
    outside (S := S) (E := E) ∅ = (inferInstance : MeasurableSpace (Config S E)) := by
  refine le_antisymm (outside_le _) ?_
  show (⨆ i, MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance) ≤ _
  exact iSup_le fun i => comap_le_outside (Finset.notMem_empty i)

/-! ## The tail σ-algebra -/

/-- Georgii's tail σ-algebra (σ-algebra at infinity) `𝓣 = ⋂_{Λ finite} 𝓣_Λ`. -/
def tail (S E : Type*) [MeasurableSpace E] : MeasurableSpace (Config S E) :=
  ⨅ Λ : Finset S, outside Λ

theorem tail_le_outside (Λ : Finset S) : tail S E ≤ outside Λ := iInf_le _ _

theorem tail_le : tail S E ≤ (inferInstance : MeasurableSpace (Config S E)) :=
  (tail_le_outside ∅).trans (outside_le _)

/-! ## Proper kernels, specifications, Gibbs measures -/

/-- **Properness**, Georgii (1.18): `γ(A ∩ B | ·) = γ(A | ·) 1_B` for every `A ∈ 𝓕` and every
`B ∈ 𝓣_Λ`. -/
def IsProper (Λ : Finset S) (γ : Config S E → Measure (Config S E)) : Prop :=
  ∀ A B : Set (Config S E), MeasurableSet A → MeasurableSet[outside Λ] B →
    ∀ ω : Config S E, γ ω (A ∩ B) = B.indicator (fun _ => γ ω A) ω

/-- **Specification**, Georgii (1.23): a family of proper probability kernels from `𝓣_Λ` to `𝓕`,
consistent in the sense `γ_Δ γ_Λ = γ_Δ` for `Λ ⊆ Δ`. -/
structure IsSpecification (γ : Finset S → Config S E → Measure (Config S E)) : Prop where
  /-- each `γ_Λ(·|ω)` is a probability measure -/
  isProbabilityMeasure : ∀ (Λ : Finset S) (ω : Config S E), IsProbabilityMeasure (γ Λ ω)
  /-- `γ_Λ` is a kernel *from `𝓣_Λ`*: `ω ↦ γ_Λ(A|ω)` is measurable outside `Λ` -/
  measurable_apply : ∀ (Λ : Finset S) (A : Set (Config S E)), MeasurableSet A →
    Measurable[outside Λ] fun ω => γ Λ ω A
  /-- each `γ_Λ` is proper -/
  proper : ∀ Λ : Finset S, IsProper Λ (γ Λ)
  /-- consistency `γ_Δ γ_Λ = γ_Δ` for `Λ ⊆ Δ` -/
  consistent : ∀ Λ Δ : Finset S, Λ ⊆ Δ → ∀ (ω : Config S E) (A : Set (Config S E)),
    MeasurableSet A → ∫⁻ ω', γ Λ ω' A ∂(γ Δ ω) = γ Δ ω A

/-- **The DLR equations**: `μ ∈ 𝓖(γ)` iff `μ` is a probability measure with `μ γ_Λ = μ` for every
finite volume `Λ` (Georgii (1.23) together with Remark (1.24)). -/
def IsGibbs (γ : Finset S → Config S E → Measure (Config S E)) (μ : Measure (Config S E)) : Prop :=
  IsProbabilityMeasure μ ∧ ∀ (Λ : Finset S) (A : Set (Config S E)), MeasurableSet A →
    μ A = ∫⁻ ω, γ Λ ω A ∂μ

/-! ## Local events and the topology of local convergence -/

/-- A *local* (cylinder) event: one depending on finitely many coordinates only. Georgii's algebra
`𝓕⁰ = ⋃_Λ 𝓕_Λ` (4.1). -/
def IsLocalEvent (A : Set (Config S E)) : Prop := ∃ Λ : Finset S, MeasurableSet[inside Λ] A

theorem IsLocalEvent.measurableSet {A : Set (Config S E)} (hA : IsLocalEvent A) :
    MeasurableSet A := by
  obtain ⟨Λ, hΛ⟩ := hA
  exact measurableSet_of_inside hΛ

theorem isLocalEvent_coord (i : S) {B : Set E} (hB : MeasurableSet B) :
    IsLocalEvent {ω : Config S E | ω i ∈ B} :=
  ⟨{i}, comap_le_inside (Finset.mem_singleton_self i) _ ⟨B, hB, rfl⟩⟩

/-- **Local convergence**, Georgii (4.2): `μ_i → ν` along the filter `L` iff `μ_i A → ν A` for
every local event `A`. -/
def TendstoLocally {ι : Type*} (μ : ι → Measure (Config S E)) (L : Filter ι)
    (ν : Measure (Config S E)) : Prop :=
  ∀ A : Set (Config S E), IsLocalEvent A → Tendsto (fun i => μ i A) L (nhds (ν A))

/-- The `𝓛`-topology of Georgii (4.2): the coarsest topology making `μ ↦ μ A` continuous for every
local event `A`. -/
def localTopology : TopologicalSpace (Measure (Config S E)) :=
  ⨅ A : {A : Set (Config S E) // IsLocalEvent A},
    TopologicalSpace.induced (fun μ : Measure (Config S E) => μ A.1) inferInstance

theorem tendstoLocally_iff_tendsto {ι : Type*} (μ : ι → Measure (Config S E)) (L : Filter ι)
    (ν : Measure (Config S E)) :
    TendstoLocally μ L ν ↔ Tendsto μ L (@nhds _ localTopology ν) := by
  rw [localTopology, nhds_iInf, tendsto_iInf]
  refine ⟨fun h A => ?_, fun h A hA => ?_⟩
  · rw [nhds_induced, tendsto_comap_iff]
    exact h A.1 A.2
  · have := h ⟨A, hA⟩
    rwa [nhds_induced, tendsto_comap_iff] at this

/-! ## Non-degeneracy: the identity family -/

section Dirac

theorem dirac_apply_eq {A : Set (Config S E)} (hA : MeasurableSet A) :
    (fun ω : Config S E => Measure.dirac ω A) = A.indicator 1 :=
  funext fun ω => Measure.dirac_apply' ω hA

/-- The family `γ_Λ ω = δ_ω` is proper. -/
theorem isProper_dirac (Λ : Finset S) : IsProper Λ (fun ω : Config S E => Measure.dirac ω) := by
  intro A B hA hB ω
  have hB' : MeasurableSet B := measurableSet_of_outside hB
  simp only [Measure.dirac_apply' _ (hA.inter hB'), Measure.dirac_apply' _ hA]
  by_cases hωA : ω ∈ A <;> by_cases hωB : ω ∈ B <;> simp [hωA, hωB]

/-- The family `γ_Λ ω = δ_ω` is consistent. -/
theorem consistent_dirac (ω : Config S E) {A : Set (Config S E)} (hA : MeasurableSet A) :
    ∫⁻ ω', (Measure.dirac ω') A ∂(Measure.dirac ω) = Measure.dirac ω A := by
  rw [dirac_apply_eq hA, lintegral_dirac' _ (measurable_one.indicator hA)]
  exact congrFun (dirac_apply_eq hA).symm ω

/-- **Every** probability measure satisfies the DLR equations of the family `γ_Λ ω = δ_ω`. -/
theorem dirac_isGibbs (μ : Measure (Config S E)) [IsProbabilityMeasure μ] :
    IsGibbs (fun (_ : Finset S) (ω : Config S E) => Measure.dirac ω) μ := by
  refine ⟨inferInstance, fun Λ A hA => ?_⟩
  rw [dirac_apply_eq hA, lintegral_indicator_one hA]

end Dirac

/-! ## Non-degeneracy: the empty volume -/

section Empty

variable {γ : Finset S → Config S E → Measure (Config S E)}

/-- In **any** specification the empty-volume kernel is forced to be the identity kernel. -/
theorem eq_dirac_of_isSpecification (hγ : IsSpecification γ) (ω : Config S E) :
    γ ∅ ω = Measure.dirac ω := by
  have := hγ.isProbabilityMeasure ∅ ω
  refine Measure.ext fun B hB => ?_
  have hB0 : MeasurableSet[outside (∅ : Finset S)] B := by rw [outside_empty]; exact hB
  have h := hγ.proper ∅ Set.univ B MeasurableSet.univ hB0 ω
  rw [Set.univ_inter, measure_univ] at h
  rw [h, Measure.dirac_apply' _ hB]
  by_cases hωB : ω ∈ B <;> simp [hωB]

/-- Consequently the DLR equation for the empty volume is automatic. -/
theorem isGibbs_empty_volume (hγ : IsSpecification γ) (μ : Measure (Config S E))
    [IsProbabilityMeasure μ] {A : Set (Config S E)} (hA : MeasurableSet A) :
    μ A = ∫⁻ ω, γ ∅ ω A ∂μ := by
  simp only [eq_dirac_of_isSpecification hγ]
  rw [dirac_apply_eq hA, lintegral_indicator_one hA]

end Empty

/-! ## Non-degeneracy: `outside Λ` is a proper sub-σ-algebra -/

theorem not_measurableSet_outside :
    ¬ MeasurableSet[outside ({0} : Finset ℕ)] {ω : Config ℕ Bool | ω 0 = true} := by
  intro h
  have h2 := mem_iff_mem_of_outside h (ω := fun _ => true)
    (ω' := fun i => if i = 0 then false else true) (fun i hi => by simp at hi; simp [hi])
  simp at h2

/-! ## Non-degeneracy: the independent specification -/

section Independent

variable [Fintype S]

theorem nonempty_of_isProbabilityMeasure (ν : Measure E) [IsProbabilityMeasure ν] : Nonempty E := by
  by_contra h
  rw [not_nonempty_iff] at h
  have h1 : (ν Set.univ) = 1 := measure_univ
  rw [Set.univ_eq_empty_iff.mpr h, measure_empty] at h1
  exact zero_ne_one h1

variable (ν : Measure E) [IsProbabilityMeasure ν]

/-- **The independent specification**: inside `Λ` the spins are resampled i.i.d. from `ν`, outside
`Λ` the boundary condition `ω` is kept. -/
def indepSpec (Λ : Finset S) (ω : Config S E) : Measure (Config S E) :=
  Measure.map (fun σ => glue Λ σ ω) (Measure.pi fun _ : S => ν)

instance instIsProbabilityMeasureIndepSpec (Λ : Finset S) (ω : Config S E) :
    IsProbabilityMeasure (indepSpec ν Λ ω) :=
  Measure.isProbabilityMeasure_map (measurable_glue_left Λ ω).aemeasurable

omit [IsProbabilityMeasure ν] in
theorem indepSpec_apply (Λ : Finset S) (ω : Config S E) {A : Set (Config S E)}
    (hA : MeasurableSet A) :
    indepSpec ν Λ ω A = ∫⁻ σ, A.indicator 1 (glue Λ σ ω) ∂(Measure.pi fun _ : S => ν) := by
  have h : (fun σ : Config S E => A.indicator (1 : Config S E → ℝ≥0∞) (glue Λ σ ω))
      = ((fun σ : Config S E => glue Λ σ ω) ⁻¹' A).indicator 1 := by
    funext σ
    by_cases h : glue Λ σ ω ∈ A <;> simp [h]
  rw [h, lintegral_indicator_one (measurable_glue_left Λ ω hA), indepSpec,
    Measure.map_apply (measurable_glue_left Λ ω) hA]

/-- **The key resampling identity**: the i.i.d. product measure `ν^S` is invariant under
independently resampling the coordinates inside a finite volume `Λ`. -/
theorem map_glue_prod (Λ : Finset S) :
    Measure.map (fun p : Config S E × Config S E => glue Λ p.2 p.1)
        ((Measure.pi fun _ : S => ν).prod (Measure.pi fun _ : S => ν))
      = Measure.pi fun _ : S => ν := by
  classical
  refine (Measure.pi_eq fun s hs => ?_).symm
  rw [Measure.map_apply (measurable_glue_swap Λ) (MeasurableSet.univ_pi hs)]
  have hpre : (fun p : Config S E × Config S E => glue Λ p.2 p.1) ⁻¹' (Set.univ.pi s)
      = (Set.univ.pi fun i => if i ∈ Λ then Set.univ else s i) ×ˢ
        (Set.univ.pi fun i => if i ∈ Λ then s i else Set.univ) := by
    ext p
    simp only [Set.mem_preimage, Set.mem_univ_pi, Set.mem_prod]
    constructor
    · refine fun h => ⟨fun i => ?_, fun i => ?_⟩
      · by_cases hi : i ∈ Λ
        · simp [hi]
        · simpa [hi, glue_of_notMem hi] using h i
      · by_cases hi : i ∈ Λ
        · simpa [hi, glue_of_mem hi] using h i
        · simp [hi]
    · rintro ⟨h1, h2⟩ i
      by_cases hi : i ∈ Λ
      · rw [glue_of_mem hi]; simpa [hi] using h2 i
      · rw [glue_of_notMem hi]; simpa [hi] using h1 i
  rw [hpre, Measure.prod_prod, Measure.pi_pi, Measure.pi_pi, ← Finset.prod_mul_distrib]
  refine Finset.prod_congr rfl fun i _ => ?_
  by_cases hi : i ∈ Λ <;> simp [hi]

/-- The integrated form of the resampling identity. -/
theorem lintegral_glue (Λ : Finset S) {F : Config S E → ℝ≥0∞} (hF : Measurable F) :
    ∫⁻ ω, (∫⁻ σ, F (glue Λ σ ω) ∂(Measure.pi fun _ : S => ν)) ∂(Measure.pi fun _ : S => ν)
      = ∫⁻ τ, F τ ∂(Measure.pi fun _ : S => ν) := by
  calc ∫⁻ ω, (∫⁻ σ, F (glue Λ σ ω) ∂(Measure.pi fun _ : S => ν)) ∂(Measure.pi fun _ : S => ν)
      = ∫⁻ p, F (glue Λ p.2 p.1)
          ∂((Measure.pi fun _ : S => ν).prod (Measure.pi fun _ : S => ν)) :=
        (lintegral_prod _ (hF.comp (measurable_glue_swap Λ)).aemeasurable).symm
    _ = ∫⁻ τ, F τ ∂(Measure.map (fun p : Config S E × Config S E => glue Λ p.2 p.1)
          ((Measure.pi fun _ : S => ν).prod (Measure.pi fun _ : S => ν))) :=
        (lintegral_map hF (measurable_glue_swap Λ)).symm
    _ = ∫⁻ τ, F τ ∂(Measure.pi fun _ : S => ν) := by rw [map_glue_prod]

theorem measurable_indepSpec_apply (Λ : Finset S) {A : Set (Config S E)} (hA : MeasurableSet A) :
    Measurable[outside Λ] fun ω => indepSpec ν Λ ω A := by
  have : Nonempty E := nonempty_of_isProbabilityMeasure ν
  have heq : (fun ω : Config S E => indepSpec ν Λ ω A)
      = fun ω => ∫⁻ σ, A.indicator 1 (glue Λ σ ω) ∂(Measure.pi fun _ : S => ν) :=
    funext fun ω => indepSpec_apply ν Λ ω hA
  refine measurable_outside_of_local Λ ?_ ?_
  · rw [heq]
    exact Measurable.lintegral_prod_right'
      (f := fun p : Config S E × Config S E => A.indicator 1 (glue Λ p.2 p.1))
      ((measurable_one.indicator hA).comp (measurable_glue_swap Λ))
  · intro ω ω' h
    rw [indepSpec_apply ν Λ ω hA, indepSpec_apply ν Λ ω' hA]
    refine lintegral_congr fun σ => ?_
    have hgg : glue Λ σ ω = glue Λ σ ω' := by
      funext i
      by_cases hi : i ∈ Λ
      · rw [glue_of_mem hi, glue_of_mem hi]
      · rw [glue_of_notMem hi, glue_of_notMem hi, h i hi]
    rw [hgg]

omit [IsProbabilityMeasure ν] in
theorem isProper_indepSpec (Λ : Finset S) : IsProper Λ (indepSpec ν Λ) := by
  intro A B hA hB ω
  have hB' : MeasurableSet B := measurableSet_of_outside hB
  have key : ∀ σ : Config S E, (glue Λ σ ω ∈ B ↔ ω ∈ B) := fun σ =>
    (mem_iff_mem_of_outside hB (fun i hi => (glue_of_notMem hi σ ω).symm)).symm
  simp only [indepSpec, Measure.map_apply (measurable_glue_left Λ ω) (hA.inter hB'),
    Measure.map_apply (measurable_glue_left Λ ω) hA]
  by_cases hωB : ω ∈ B
  · rw [Set.indicator_of_mem hωB]
    congr 1
    ext σ
    simp only [Set.mem_preimage, Set.mem_inter_iff, and_iff_left_iff_imp]
    exact fun _ => (key σ).mpr hωB
  · rw [Set.indicator_of_notMem hωB]
    have hempty : (fun σ : Config S E => glue Λ σ ω) ⁻¹' (A ∩ B) = ∅ := by
      ext σ
      simp only [Set.mem_preimage, Set.mem_inter_iff, Set.mem_empty_iff_false, iff_false, not_and]
      exact fun _ hc => hωB ((key σ).mp hc)
    rw [hempty, measure_empty]

theorem consistent_indepSpec {Λ Δ : Finset S} (hΛΔ : Λ ⊆ Δ) (ω : Config S E)
    {A : Set (Config S E)} (hA : MeasurableSet A) :
    ∫⁻ ω', indepSpec ν Λ ω' A ∂(indepSpec ν Δ ω) = indepSpec ν Δ ω A := by
  have hmeas : Measurable fun ω' : Config S E => indepSpec ν Λ ω' A :=
    (measurable_indepSpec_apply ν Λ hA).mono (outside_le Λ) le_rfl
  rw [indepSpec, lintegral_map hmeas (measurable_glue_left Δ ω)]
  simp only [indepSpec_apply ν Λ _ hA, glue_glue hΛΔ]
  rw [lintegral_glue ν Λ
      (F := fun τ : Config S E => A.indicator (1 : Config S E → ℝ≥0∞) (glue Δ τ ω))
      ((measurable_one.indicator hA).comp (measurable_glue_left Δ ω)),
    ← indepSpec_apply ν Δ ω hA, indepSpec]

/-- **The independent specification really is a specification.** -/
theorem isSpecification_indep : IsSpecification (indepSpec (S := S) ν) := by
  refine ⟨fun Λ ω => inferInstance, fun Λ A hA => measurable_indepSpec_apply ν Λ hA,
    fun Λ => isProper_indepSpec ν Λ, fun Λ Δ h ω A hA => consistent_indepSpec ν h ω hA⟩

/-- **And its set of Gibbs measures is non-empty**: the i.i.d. product measure `ν^S` is a Gibbs
measure for the independent specification. -/
theorem isGibbs_indep : IsGibbs (indepSpec (S := S) ν) (Measure.pi fun _ : S => ν) := by
  refine ⟨inferInstance, fun Λ A hA => ?_⟩
  simp only [indepSpec_apply ν Λ _ hA]
  rw [lintegral_glue ν Λ (measurable_one.indicator hA), lintegral_indicator_one hA]

end Independent

end GibbsChallenge

/-!
# Existence and compactness of Gibbs measures for absolutely summable potentials

Georgii, *Gibbs Measures and Phase Transitions*, 2nd ed., Theorem (4.22) and Theorem (4.23)(a),
(b).

Everything below is stated with the Mathlib-only vocabulary of the preamble above, extended by
first-principles definitions of

* an **absolutely summable potential** (Georgii Definition (2.2) together with (2.11)/(2.12)):
  a family `Φ : Finset S → Config S E → ℝ` such that each interaction term `Φ A` is measurable
  with respect to the coordinates inside `A`, and such that
  `‖Φ‖ᵢ = ∑_{A ∋ i} sup_ω |Φ_A(ω)| < ∞` for every site `i`;
* the **Hamiltonian** `H_Λ = ∑_{A : A ∩ Λ ≠ ∅} Φ_A` of Georgii (2.3);
* the **Gibbsian specification** `γ^Φ` generated by `Φ` and an a-priori single-spin measure `ν`,
  Georgii Definition (2.9): the finite-volume Gibbs distribution
  `γ_Λ(A | ω) = Z_Λ(ω)⁻¹ ∫ 1_A(σ) e^{-β H_Λ(σ)} λ_Λ^ω(dσ)`,
  where `λ_Λ^ω` resamples the coordinates inside `Λ` independently from `ν` and keeps the
  boundary condition `ω` outside `Λ`.

## Main statements

* `isSpecification_gibbsKernel`: **Georgii (2.9)/(2.10)**, the family `γ^Φ` really is a
  specification in the sense of the preamble (proper Markov kernels from `𝓣_Λ`, consistent).
* `exists_isGibbs_gibbsKernel`: **Georgii Theorem (4.22)**, over a standard Borel state space and
  for an absolutely summable potential, `𝓖(γ^Φ) ≠ ∅`.
* `isCompact_setOf_isGibbs_gibbsKernel`: **Georgii Theorem (4.23)(a)**, `𝓖(γ^Φ)` is compact in the
  topology of local convergence.
* `exists_isCompact_superset_iUnion_setOf_isGibbs`: **Georgii Theorem (4.23)(b)**, for a family of
  absolutely summable potentials that is bounded in the sense `sup_i ‖Φ_i‖_a < ∞` for every site
  `a`, the union `⋃_i 𝒢(Φ_i)` is relatively compact in the topology of local convergence, i.e. it
  is contained in a locally compact set.
-/

namespace GibbsChallenge

open MeasureTheory Filter
open scoped ENNReal

noncomputable section

variable {S E : Type*} [MeasurableSpace E]

/-! ## Absolutely summable potentials -/

open Classical in
/-- Extend an inner configuration `ζ : Λ → E` to a configuration on all of `S`, using the boundary
condition `ω` outside `Λ`. -/
def extend (Λ : Finset S) (ζ : Λ → E) (ω : Config S E) : Config S E :=
  fun i => if h : i ∈ Λ then ζ ⟨i, h⟩ else ω i

theorem measurable_extend (Λ : Finset S) (ω : Config S E) :
    Measurable fun ζ : Λ → E => extend Λ ζ ω := by
  refine measurable_pi_lambda _ fun i => ?_
  by_cases hi : i ∈ Λ
  · have h : (fun ζ : Λ → E => extend Λ ζ ω i) = fun ζ => ζ ⟨i, hi⟩ := by
      funext ζ; simp [extend, hi]
    rw [h]
    exact measurable_pi_apply _
  · have h : (fun ζ : Λ → E => extend Λ ζ ω i) = fun _ => ω i := by
      funext ζ; simp [extend, hi]
    rw [h]
    exact measurable_const

/-- **Georgii (2.12).** The interaction norm `‖Φ‖ᵢ = ∑_{A ∋ i} sup_ω |Φ_A(ω)|` at the site `i`,
computed in `[0, ∞]` so that no finiteness has to be assumed in order to write it down. -/
def potentialNormAt (Φ : Finset S → Config S E → ℝ) (i : S) : ℝ≥0∞ :=
  ∑' A : Finset S,
    {A : Finset S | i ∈ A}.indicator (fun A => ⨆ ω : Config S E, ENNReal.ofReal |Φ A ω|) A

/-- **An absolutely summable potential**, Georgii Definition (2.2)(i) together with (2.11):
a family `Φ` of interaction terms indexed by the finite subsets `A` of the parameter set `S`, such
that `Φ A` is measurable with respect to the coordinates *inside* `A`, and such that the
interaction norm `‖Φ‖ᵢ` is finite at every site. -/
structure IsAbsolutelySummablePotential (Φ : Finset S → Config S E → ℝ) : Prop where
  /-- Georgii (2.2)(i): `Φ_A` is `𝓕_A`-measurable. -/
  measurable_inside : ∀ A : Finset S, Measurable[inside A] (Φ A)
  /-- Georgii (2.11): `∑_{A ∋ i} sup_ω |Φ_A(ω)| < ∞` for every site `i`. -/
  normAt_ne_top : ∀ i : S, potentialNormAt Φ i ≠ ⊤

/-- **The Hamiltonian in the volume `Λ`**, Georgii (2.3): `H_Λ = ∑_{A : A ∩ Λ ≠ ∅} Φ_A`, the
(unconditionally convergent, by absolute summability) sum of all interaction terms whose support
meets `Λ`. -/
def hamiltonian (Φ : Finset S → Config S E → ℝ) (Λ : Finset S) (ω : Config S E) : ℝ :=
  ∑' A : Finset S, {A : Finset S | ∃ i ∈ A, i ∈ Λ}.indicator (fun A => Φ A ω) A

/-- **The Boltzmann factor** `e^{-β H_Λ}`, Georgii (2.4). -/
def boltzmannFactor (Φ : Finset S → Config S E → ℝ) (β : ℝ) (Λ : Finset S)
    (ω : Config S E) : ℝ≥0∞ :=
  ENNReal.ofReal (Real.exp (-β * hamiltonian Φ Λ ω))

/-! ## The Gibbsian specification of an absolutely summable potential -/

/-- **The a-priori measure `λ_Λ^ω` in the volume `Λ`** (Georgii's `λ_Λ`, (1.27)): the coordinates
inside `Λ` are resampled independently from the single-spin measure `ν`, while the boundary
condition `ω` is kept outside `Λ`. -/
def freeMeasure (ν : Measure E) (Λ : Finset S) (ω : Config S E) : Measure (Config S E) :=
  Measure.map (fun ζ : Λ → E => extend Λ ζ ω) (Measure.pi fun _ : Λ => ν)

/-- **The partition function** `Z_Λ(ω) = ∫ e^{-β H_Λ} dλ_Λ^ω`, Georgii (2.9). -/
def partitionFunction (Φ : Finset S → Config S E → ℝ) (ν : Measure E) (β : ℝ) (Λ : Finset S)
    (ω : Config S E) : ℝ≥0∞ :=
  ∫⁻ σ, boltzmannFactor Φ β Λ σ ∂(freeMeasure ν Λ ω)

/-- **The Gibbsian specification of `Φ`**, Georgii Definition (2.9):
`γ_Λ(A | ω) = Z_Λ(ω)⁻¹ ∫ 1_A(σ) e^{-β H_Λ(σ)} λ_Λ^ω(dσ)`. -/
def gibbsKernel (Φ : Finset S → Config S E → ℝ) (ν : Measure E) (β : ℝ) (Λ : Finset S)
    (ω : Config S E) : Measure (Config S E) :=
  (partitionFunction Φ ν β Λ ω)⁻¹ • (freeMeasure ν Λ ω).withDensity (boltzmannFactor Φ β Λ)

/-- The a-priori measure is a probability measure. -/
instance isProbabilityMeasure_freeMeasure (ν : Measure E) [IsProbabilityMeasure ν] (Λ : Finset S)
    (ω : Config S E) : IsProbabilityMeasure (freeMeasure ν Λ ω) := by
  rw [freeMeasure]
  exact Measure.isProbabilityMeasure_map (measurable_extend Λ ω).aemeasurable

/-! ## Non-degeneracy: the zero potential -/

/-- The zero potential is absolutely summable. -/
theorem isAbsolutelySummablePotential_zero :
    IsAbsolutelySummablePotential (fun (_ : Finset S) (_ : Config S E) => (0 : ℝ)) where
  measurable_inside _ := measurable_const
  normAt_ne_top i := by
    have h : potentialNormAt (fun (_ : Finset S) (_ : Config S E) => (0 : ℝ)) i = 0 := by
      rw [potentialNormAt]
      refine ENNReal.tsum_eq_zero.2 fun A => ?_
      by_cases hA : i ∈ A <;> simp [hA]
    simp [h]

omit [MeasurableSpace E] in
/-- Its Hamiltonian vanishes. -/
theorem hamiltonian_zero (Λ : Finset S) (ω : Config S E) :
    hamiltonian (fun (_ : Finset S) (_ : Config S E) => (0 : ℝ)) Λ ω = 0 := by
  have h : (fun A : Finset S =>
      {A : Finset S | ∃ i ∈ A, i ∈ Λ}.indicator (fun _ => (0 : ℝ)) A) = fun _ => 0 := by
    funext A
    by_cases hA : A ∈ {A : Finset S | ∃ i ∈ A, i ∈ Λ} <;> simp [hA]
  rw [hamiltonian, h, tsum_zero]

/-- **The Gibbsian specification of the zero potential is the independent one**: the a-priori
measure itself. So `gibbsKernel` is not a vacuous definition. -/
theorem gibbsKernel_zero (ν : Measure E) [IsProbabilityMeasure ν] (β : ℝ) (Λ : Finset S)
    (ω : Config S E) :
    gibbsKernel (fun (_ : Finset S) (_ : Config S E) => (0 : ℝ)) ν β Λ ω = freeMeasure ν Λ ω := by
  have hprob : IsProbabilityMeasure (freeMeasure ν Λ ω) :=
    isProbabilityMeasure_freeMeasure ν Λ ω
  have hbz : boltzmannFactor (fun (_ : Finset S) (_ : Config S E) => (0 : ℝ)) β Λ = 1 := by
    funext σ
    simp [boltzmannFactor, hamiltonian_zero]
  rw [gibbsKernel, partitionFunction, hbz]
  simp

/-! ## The theorems -/

/-- **Georgii (2.9)/(2.10).** The Gibbsian specification of an absolutely summable potential really
is a specification in the sense of the preamble: a consistent family of proper probability kernels
from the exterior σ-algebra `𝓣_Λ`. -/
theorem isSpecification_gibbsKernel [Countable S] (Φ : Finset S → Config S E → ℝ)
    (hΦ : IsAbsolutelySummablePotential Φ) (ν : Measure E) [IsProbabilityMeasure ν] (β : ℝ) :
    IsSpecification (gibbsKernel Φ ν β) :=
  sorry

/-- **Georgii, Theorem (4.22).** Over a standard Borel state space, and for an absolutely summable
potential, the set of Gibbs measures of the Gibbsian specification is non-empty. -/
theorem exists_isGibbs_gibbsKernel [Countable S] [StandardBorelSpace E]
    (Φ : Finset S → Config S E → ℝ)
    (hΦ : IsAbsolutelySummablePotential Φ) (ν : Measure E) [IsProbabilityMeasure ν] (β : ℝ) :
    ∃ μ : Measure (Config S E), IsGibbs (gibbsKernel Φ ν β) μ :=
  sorry

/-- **Georgii, Theorem (4.23)(a).** The set of Gibbs measures of an absolutely summable potential
is compact in the topology of local convergence. -/
theorem isCompact_setOf_isGibbs_gibbsKernel [Countable S] [StandardBorelSpace E]
    (Φ : Finset S → Config S E → ℝ)
    (hΦ : IsAbsolutelySummablePotential Φ) (ν : Measure E) [IsProbabilityMeasure ν] (β : ℝ) :
    @IsCompact (Measure (Config S E)) localTopology {μ | IsGibbs (gibbsKernel Φ ν β) μ} :=
  sorry

/-- **Georgii, Theorem (4.23)(b).** If a family `(Φ_i)` of absolutely summable potentials is
bounded in `ℬ`, i.e. `sup_i ‖Φ_i‖_a < ∞` for every site `a`, then the union of the corresponding
sets of Gibbs measures is relatively compact in the topology of local convergence: it is contained
in a compact set of probability measures. -/
theorem exists_isCompact_superset_iUnion_setOf_isGibbs [Countable S] [StandardBorelSpace E]
    {ι : Type*} (Φs : ι → Finset S → Config S E → ℝ)
    (hΦs : ∀ i, IsAbsolutelySummablePotential (Φs i))
    (hbdd : ∀ a : S, (⨆ i, potentialNormAt (Φs i) a) < ⊤)
    (ν : Measure E) [IsProbabilityMeasure ν] (β : ℝ) :
    ∃ K : Set (Measure (Config S E)), @IsCompact (Measure (Config S E)) localTopology K ∧
      (∀ μ ∈ K, IsProbabilityMeasure μ) ∧
      (⋃ i, {μ : Measure (Config S E) | IsGibbs (gibbsKernel (Φs i) ν β) μ}) ⊆ K :=
  sorry

end

end GibbsChallenge

end
