import Comparator.Defs
import Comparator.Defs_Ising

/-!
# Definitions: Georgii's metric (4.3)(3) and the shift-invariant Gibbs measures of the Ising model

This module extends the shared preamble `Comparator.Defs` and the two-dimensional Ising model of
`Comparator.Defs_Ising` with the notions needed for Georgii, *Gibbs Measures and Phase
Transitions*, 2nd ed., Theorem (6.9), first assertion:
`lim_{β → ∞} d(𝒢_Θ(βΦ), δ₊) = lim_{β → ∞} d(𝒢_Θ(βΦ), δ₋) = 0`,
where `d` is a metric for the topology of local convergence and `𝒢_Θ(βΦ)` is the set of
shift-invariant Gibbs measures.  It holds the definitions used by
`Comparator/Challenge_LowTemperature.lean` and `Comparator/Solution_LowTemperature.lean`.

**Its only imports are `Comparator.Defs` and `Comparator.Defs_Ising`, which import `Mathlib` and
nothing else.**  The two-dimensional Ising model (the lattice `ℤ²`, the spins, the
nearest-neighbour bonds, the Hamiltonian, the finite-volume Gibbs distribution, the DLR equation,
the lattice shifts) is spelled out from first principles in `Comparator/Defs_Ising.lean`, shared
verbatim with `Comparator/Challenge.lean`; here it is extended by Georgii's metric of Remark
(4.3)(3) for the topology of local convergence.

## Dictionary for the new notions

| Georgii | here |
| --- | --- |
| ground states `ω⁺`, `ω⁻` | `fun _ : Site ↦ true`, `fun _ : Site ↦ false` |
| `δ₊`, `δ₋` | `Measure.dirac (fun _ : Site ↦ true)`, `Measure.dirac (fun _ : Site ↦ false)` |
| `𝓛`-convergence (4.2) | `TendstoLocally` (from the preamble) |
| `d(μ, ν) = ∑_{n≥1} 2⁻ⁿ|μ(Aₙ) − ν(Aₙ)|`, Remark (4.3)(3) | `localDist` |
| `d(F, ν) = inf_{μ ∈ F} d(μ, ν)` | `localDistSet` |
| `𝒢_Θ(βΦ)`, (5.13) | `shiftInvariantGibbs` |


## Design note

Georgii writes "we let `d` denote **any** metric for the `𝓛`-topology, cf. Remark (4.3)(3)".
Remark (4.3)(3) produces such a metric from **any** enumeration `(Aₙ)` of the countable algebra
`𝓕⁰` of local events.  So instead of fixing one arbitrary enumeration — an irrelevant choice which
would weaken the statements — `localDist A` is defined for an arbitrary sequence
`A : ℕ → Set Config` and the theorems are asserted **for every** such sequence all of whose
members are local events.  This covers every enumeration of `𝓕⁰`, hence every metric supplied by
Remark (4.3)(3), and is strictly stronger than fixing one.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
set_option warn.classDefReducibility false

open MeasureTheory Filter
open scoped ENNReal
open scoped Topology

noncomputable section

namespace GibbsChallenge

/-! ## Local events depend only on the coordinates inside the volume

The preamble shows that an event measurable *outside* a finite volume `Λ` does not depend on the
coordinates inside `Λ` (`mem_iff_mem_of_outside`).  Here is the mirror statement for `inside Λ`,
which is what makes `IsLocalEvent` mean what it should: *a local event depends on finitely many
coordinates only*. -/

variable {S E : Type*} [MeasurableSpace E]

/-- The restriction of a configuration to the finite volume `Λ`. -/
def restrictInside (Λ : Finset S) (ω : Config S E) : {i : S // i ∈ Λ} → E := fun i => ω i.1

theorem measurable_restrictInside (Λ : Finset S) :
    Measurable[inside Λ] (restrictInside (E := E) Λ) :=
  measurable_pi_of _ fun i => Measurable.of_comap_le (comap_le_inside i.2)

/-- The two usual descriptions of `𝓕_Λ` agree: the σ-algebra generated by the coordinates in `Λ`
is the σ-algebra pulled back along the restriction map `ω ↦ ω|_Λ`. -/
theorem inside_eq_comap (Λ : Finset S) :
    inside (E := E) Λ = MeasurableSpace.comap (restrictInside Λ) inferInstance := by
  refine le_antisymm ?_ (measurable_restrictInside Λ).comap_le
  refine iSup₂_le fun i hi => ?_
  have h1 : Measurable[MeasurableSpace.comap (restrictInside (E := E) Λ) inferInstance]
      (restrictInside Λ) := Measurable.of_comap_le le_rfl
  exact ((measurable_pi_apply (⟨i, hi⟩ : {i : S // i ∈ Λ})).comp h1).comap_le

/-- **Events measurable inside `Λ` depend only on the coordinates inside `Λ`.** -/
theorem mem_iff_mem_of_inside {Λ : Finset S} {A : Set (Config S E)}
    (hA : MeasurableSet[inside Λ] A) {ω ω' : Config S E} (h : ∀ i ∈ Λ, ω i = ω' i) :
    ω ∈ A ↔ ω' ∈ A := by
  rw [inside_eq_comap] at hA
  obtain ⟨C, -, rfl⟩ := hA
  have hr : restrictInside Λ ω = restrictInside Λ ω' := funext fun i => h i.1 i.2
  simp only [Set.mem_preimage, hr]

end GibbsChallenge

namespace IsingChallenge

/-! ### Georgii (5.13): the shift-invariant Gibbs measures `𝒢_Θ(βΦ)` -/

/-- **Georgii (5.13)**: `𝒢_Θ(βΦ)`, the set of *shift-invariant* Gibbs measures of the
two-dimensional Ising ferromagnet at inverse temperature `β`. -/
def shiftInvariantGibbs (β : ℝ) : Set (Measure Config) :=
  {μ | IsGibbs β μ ∧ ∀ j : Site, μ.map (shift j) = μ}

/-! ### Local events and Georgii's metric (4.3)(3) for the `𝓛`-topology -/

/-- A *local* event of the Ising configuration space: an event depending on finitely many spins
only.  This is the preamble's `IsLocalEvent`, i.e. Georgii's algebra `𝓕⁰ = ⋃_Λ 𝓕_Λ` (4.1),
specialised to `S = ℤ²` and `E = {±1}`. -/
abbrev IsLocalEvent (A : Set Config) : Prop :=
  GibbsChallenge.IsLocalEvent (S := Site) (E := Bool) A

/-- Georgii's local (`𝓛`-) convergence (4.2), specialised to the Ising configuration space: this
is the preamble's `TendstoLocally`, i.e. `μ_β A → ν A` for every local event `A`. -/
abbrev TendstoLocally (μ : ℝ → Measure Config) (L : Filter ℝ) (ν : Measure Config) : Prop :=
  GibbsChallenge.TendstoLocally (S := Site) (E := Bool) μ L ν

/-- **Georgii, Remark (4.3)(3)**: the metric `d(μ, ν) = ∑_{n ≥ 1} 2⁻ⁿ |μ(Aₙ) − ν(Aₙ)|` for the
topology of local convergence, built from a sequence `A` of local events.  Taking for `A` any
enumeration of the countable algebra `𝓕⁰` of local events yields Georgii's metric; the theorems
below are stated for *every* sequence of local events, hence for every such metric. -/
def localDist (A : ℕ → Set Config) (μ ν : Measure Config) : ℝ :=
  ∑' n : ℕ, (2 : ℝ)⁻¹ ^ (n + 1) * |(μ (A n)).toReal - (ν (A n)).toReal|

/-- **Georgii's `d(F, ν)`**: the distance from a set `F` of random fields to the random field `ν`,
i.e. `inf_{μ ∈ F} d(μ, ν)`. -/
def localDistSet (A : ℕ → Set Config) (F : Set (Measure Config)) (ν : Measure Config) : ℝ :=
  sInf ((fun μ ↦ localDist A μ ν) '' F)

/-! #### `localDist` is a pseudometric, and `localDistSet` is the associated distance to a set -/

theorem abs_toReal_sub_le_one {μ ν : Measure Config} [IsProbabilityMeasure μ]
    [IsProbabilityMeasure ν] (B : Set Config) :
    |(μ B).toReal - (ν B).toReal| ≤ 1 := by
  have hμ1 : (μ B).toReal ≤ 1 := measureReal_le_one (μ := μ) (s := B)
  have hν1 : (ν B).toReal ≤ 1 := measureReal_le_one (μ := ν) (s := B)
  have hμ0 : (0 : ℝ) ≤ (μ B).toReal := ENNReal.toReal_nonneg
  have hν0 : (0 : ℝ) ≤ (ν B).toReal := ENNReal.toReal_nonneg
  rw [abs_sub_le_iff]
  constructor <;> linarith

theorem summable_geomHalf : Summable (fun n : ℕ ↦ (2 : ℝ)⁻¹ ^ (n + 1)) := by
  have h : Summable (fun n : ℕ ↦ ((2 : ℝ)⁻¹) ^ n) :=
    summable_geometric_of_lt_one (by norm_num) (by norm_num)
  simpa [pow_succ] using h.mul_right ((2 : ℝ)⁻¹)

theorem localDist_summand_nonneg (A : ℕ → Set Config) (μ ν : Measure Config) (n : ℕ) :
    0 ≤ (2 : ℝ)⁻¹ ^ (n + 1) * |(μ (A n)).toReal - (ν (A n)).toReal| := by positivity

theorem localDist_summand_le (A : ℕ → Set Config) {μ ν : Measure Config} [IsProbabilityMeasure μ]
    [IsProbabilityMeasure ν] (n : ℕ) :
    (2 : ℝ)⁻¹ ^ (n + 1) * |(μ (A n)).toReal - (ν (A n)).toReal| ≤ (2 : ℝ)⁻¹ ^ (n + 1) := by
  nth_rewrite 2 [← mul_one ((2 : ℝ)⁻¹ ^ (n + 1))]
  exact mul_le_mul_of_nonneg_left (abs_toReal_sub_le_one _) (by positivity)

theorem summable_localDist (A : ℕ → Set Config) (μ ν : Measure Config) [IsProbabilityMeasure μ]
    [IsProbabilityMeasure ν] :
    Summable (fun n : ℕ ↦ (2 : ℝ)⁻¹ ^ (n + 1) * |(μ (A n)).toReal - (ν (A n)).toReal|) :=
  Summable.of_nonneg_of_le (localDist_summand_nonneg A μ ν)
    (fun n ↦ localDist_summand_le A n) summable_geomHalf

theorem localDist_nonneg (A : ℕ → Set Config) (μ ν : Measure Config) : 0 ≤ localDist A μ ν :=
  tsum_nonneg (localDist_summand_nonneg A μ ν)

theorem localDist_self (A : ℕ → Set Config) (μ : Measure Config) : localDist A μ μ = 0 := by
  simp [localDist]

theorem localDist_comm (A : ℕ → Set Config) (μ ν : Measure Config) :
    localDist A μ ν = localDist A ν μ :=
  tsum_congr fun n ↦ by rw [abs_sub_comm]

theorem localDist_triangle (A : ℕ → Set Config) (μ ν ρ : Measure Config) [IsProbabilityMeasure μ]
    [IsProbabilityMeasure ν] [IsProbabilityMeasure ρ] :
    localDist A μ ρ ≤ localDist A μ ν + localDist A ν ρ := by
  rw [localDist, localDist, localDist,
    ← (summable_localDist A μ ν).tsum_add (summable_localDist A ν ρ)]
  refine (summable_localDist A μ ρ).tsum_le_tsum (fun n ↦ ?_)
    ((summable_localDist A μ ν).add (summable_localDist A ν ρ))
  rw [← mul_add]
  exact mul_le_mul_of_nonneg_left (abs_sub_le _ _ _) (by positivity)

theorem localDistSet_bddBelow (A : ℕ → Set Config) (F : Set (Measure Config))
    (ν : Measure Config) : BddBelow ((fun μ ↦ localDist A μ ν) '' F) := by
  refine ⟨0, ?_⟩
  rintro x ⟨μ, -, rfl⟩
  exact localDist_nonneg A μ ν

theorem localDistSet_nonneg (A : ℕ → Set Config) (F : Set (Measure Config)) (ν : Measure Config) :
    0 ≤ localDistSet A F ν := by
  rcases F.eq_empty_or_nonempty with rfl | hF
  · simp [localDistSet]
  · refine le_csInf (hF.image _) ?_
    rintro x ⟨μ, -, rfl⟩
    exact localDist_nonneg A μ ν

theorem localDistSet_le (A : ℕ → Set Config) {F : Set (Measure Config)} {μ ν : Measure Config}
    (hμ : μ ∈ F) : localDistSet A F ν ≤ localDist A μ ν :=
  csInf_le (localDistSet_bddBelow A F ν) (Set.mem_image_of_mem _ hμ)

end IsingChallenge

end
