import Comparator.Defs

/-!
# Definitions: absolutely summable potentials and their Gibbsian specifications

Georgii, *Gibbs Measures and Phase Transitions*, 2nd ed., Definitions (2.2), (2.3) and (2.9).

This module holds the definitions used by `Comparator/Challenge_Existence.lean` and
`Comparator/Solution_Existence.lean`.  **It imports `Comparator.Defs` — which imports `Mathlib`
and nothing else — and nothing further.**

Everything below is stated with the Mathlib-only vocabulary of `Comparator.Defs`, extended by
first-principles definitions of

* an **absolutely summable potential** (Georgii Definition (2.2) together with (2.11)/(2.12)):
  a family `Φ : Finset S → Config S E → ℝ` such that each interaction term `Φ A` is measurable
  with respect to the coordinates inside `A`, and such that
  `‖Φ‖ᵢ = ∑_{A ∋ i} sup_ω |Φ_A(ω)| < ∞` for every site `i`;
* the **Hamiltonian** `H_Λ = ∑_{A : A ∩ Λ ≠ ∅} Φ_A` of Georgii (2.3);
* the **Gibbsian specification** `γ^Φ` generated by `Φ` and an a-priori single-spin measure `ν`,
  Georgii Definition (2.9): the finite-volume Gibbs distribution
  `γ_Λ(A | ω) = Z_Λ(ω)⁻¹ ∫ 1_A(σ) e^{-β H_Λ(σ)} λ_Λ^ω(dσ)`,
  where `λ_Λ^ω` resamples the coordinates inside `Λ` independently from `ν` and keeps the
  boundary condition `ω` outside `Λ`.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
set_option warn.classDefReducibility false

open MeasureTheory Filter
open scoped ENNReal

noncomputable section

namespace GibbsChallenge

variable {S E : Type*} [MeasurableSpace E]

/-! ## Absolutely summable potentials -/

open Classical in
/-- Extend an inner configuration `ζ : Λ → E` to a configuration on all of `S`, using the boundary
condition `ω` outside `Λ`. -/
def extend (Λ : Finset S) (ζ : Λ → E) (ω : Config S E) : Config S E :=
  fun i => if h : i ∈ Λ then ζ ⟨i, h⟩ else ω i

theorem measurable_extend (Λ : Finset S) (ω : Config S E) :
    Measurable fun ζ : Λ → E => extend Λ ζ ω := by
  refine measurable_pi_lambda _ fun i => ?_
  by_cases hi : i ∈ Λ
  · have h : (fun ζ : Λ → E => extend Λ ζ ω i) = fun ζ => ζ ⟨i, hi⟩ := by
      funext ζ; simp [extend, hi]
    rw [h]
    exact measurable_pi_apply _
  · have h : (fun ζ : Λ → E => extend Λ ζ ω i) = fun _ => ω i := by
      funext ζ; simp [extend, hi]
    rw [h]
    exact measurable_const

/-- **Georgii (2.12).** The interaction norm `‖Φ‖ᵢ = ∑_{A ∋ i} sup_ω |Φ_A(ω)|` at the site `i`,
computed in `[0, ∞]` so that no finiteness has to be assumed in order to write it down. -/
def potentialNormAt (Φ : Finset S → Config S E → ℝ) (i : S) : ℝ≥0∞ :=
  ∑' A : Finset S,
    {A : Finset S | i ∈ A}.indicator (fun A => ⨆ ω : Config S E, ENNReal.ofReal |Φ A ω|) A

/-- **An absolutely summable potential**, Georgii Definition (2.2)(i) together with (2.11):
a family `Φ` of interaction terms indexed by the finite subsets `A` of the parameter set `S`, such
that `Φ A` is measurable with respect to the coordinates *inside* `A`, and such that the
interaction norm `‖Φ‖ᵢ` is finite at every site. -/
structure IsAbsolutelySummablePotential (Φ : Finset S → Config S E → ℝ) : Prop where
  /-- Georgii (2.2)(i): `Φ_A` is `𝓕_A`-measurable. -/
  measurable_inside : ∀ A : Finset S, Measurable[inside A] (Φ A)
  /-- Georgii (2.11): `∑_{A ∋ i} sup_ω |Φ_A(ω)| < ∞` for every site `i`. -/
  normAt_ne_top : ∀ i : S, potentialNormAt Φ i ≠ ⊤

/-- **The Hamiltonian in the volume `Λ`**, Georgii (2.3): `H_Λ = ∑_{A : A ∩ Λ ≠ ∅} Φ_A`, the
(unconditionally convergent, by absolute summability) sum of all interaction terms whose support
meets `Λ`. -/
def hamiltonian (Φ : Finset S → Config S E → ℝ) (Λ : Finset S) (ω : Config S E) : ℝ :=
  ∑' A : Finset S, {A : Finset S | ∃ i ∈ A, i ∈ Λ}.indicator (fun A => Φ A ω) A

/-- **The Boltzmann factor** `e^{-β H_Λ}`, Georgii (2.4). -/
def boltzmannFactor (Φ : Finset S → Config S E → ℝ) (β : ℝ) (Λ : Finset S)
    (ω : Config S E) : ℝ≥0∞ :=
  ENNReal.ofReal (Real.exp (-β * hamiltonian Φ Λ ω))

/-! ## The Gibbsian specification of an absolutely summable potential -/

/-- **The a-priori measure `λ_Λ^ω` in the volume `Λ`** (Georgii's `λ_Λ`, (1.27)): the coordinates
inside `Λ` are resampled independently from the single-spin measure `ν`, while the boundary
condition `ω` is kept outside `Λ`. -/
def freeMeasure (ν : Measure E) (Λ : Finset S) (ω : Config S E) : Measure (Config S E) :=
  Measure.map (fun ζ : Λ → E => extend Λ ζ ω) (Measure.pi fun _ : Λ => ν)

/-- **The partition function** `Z_Λ(ω) = ∫ e^{-β H_Λ} dλ_Λ^ω`, Georgii (2.9). -/
def partitionFunction (Φ : Finset S → Config S E → ℝ) (ν : Measure E) (β : ℝ) (Λ : Finset S)
    (ω : Config S E) : ℝ≥0∞ :=
  ∫⁻ σ, boltzmannFactor Φ β Λ σ ∂(freeMeasure ν Λ ω)

/-- **The Gibbsian specification of `Φ`**, Georgii Definition (2.9):
`γ_Λ(A | ω) = Z_Λ(ω)⁻¹ ∫ 1_A(σ) e^{-β H_Λ(σ)} λ_Λ^ω(dσ)`. -/
def gibbsKernel (Φ : Finset S → Config S E → ℝ) (ν : Measure E) (β : ℝ) (Λ : Finset S)
    (ω : Config S E) : Measure (Config S E) :=
  (partitionFunction Φ ν β Λ ω)⁻¹ • (freeMeasure ν Λ ω).withDensity (boltzmannFactor Φ β Λ)

/-- The a-priori measure is a probability measure. -/
instance isProbabilityMeasure_freeMeasure (ν : Measure E) [IsProbabilityMeasure ν] (Λ : Finset S)
    (ω : Config S E) : IsProbabilityMeasure (freeMeasure ν Λ ω) := by
  rw [freeMeasure]
  exact Measure.isProbabilityMeasure_map (measurable_extend Λ ω).aemeasurable

/-! ## Non-degeneracy: the zero potential -/

/-- The zero potential is absolutely summable. -/
theorem isAbsolutelySummablePotential_zero :
    IsAbsolutelySummablePotential (fun (_ : Finset S) (_ : Config S E) => (0 : ℝ)) where
  measurable_inside _ := measurable_const
  normAt_ne_top i := by
    have h : potentialNormAt (fun (_ : Finset S) (_ : Config S E) => (0 : ℝ)) i = 0 := by
      rw [potentialNormAt]
      refine ENNReal.tsum_eq_zero.2 fun A => ?_
      by_cases hA : i ∈ A <;> simp [hA]
    simp [h]

omit [MeasurableSpace E] in
/-- Its Hamiltonian vanishes. -/
theorem hamiltonian_zero (Λ : Finset S) (ω : Config S E) :
    hamiltonian (fun (_ : Finset S) (_ : Config S E) => (0 : ℝ)) Λ ω = 0 := by
  have h : (fun A : Finset S =>
      {A : Finset S | ∃ i ∈ A, i ∈ Λ}.indicator (fun _ => (0 : ℝ)) A) = fun _ => 0 := by
    funext A
    by_cases hA : A ∈ {A : Finset S | ∃ i ∈ A, i ∈ Λ} <;> simp [hA]
  rw [hamiltonian, h, tsum_zero]

/-- **The Gibbsian specification of the zero potential is the independent one**: the a-priori
measure itself. So `gibbsKernel` is not a vacuous definition. -/
theorem gibbsKernel_zero (ν : Measure E) [IsProbabilityMeasure ν] (β : ℝ) (Λ : Finset S)
    (ω : Config S E) :
    gibbsKernel (fun (_ : Finset S) (_ : Config S E) => (0 : ℝ)) ν β Λ ω = freeMeasure ν Λ ω := by
  have hprob : IsProbabilityMeasure (freeMeasure ν Λ ω) :=
    isProbabilityMeasure_freeMeasure ν Λ ω
  have hbz : boltzmannFactor (fun (_ : Finset S) (_ : Config S E) => (0 : ℝ)) β Λ = 1 := by
    funext σ
    simp [boltzmannFactor, hamiltonian_zero]
  rw [gibbsKernel, partitionFunction, hbz]
  simp

end GibbsChallenge

end
