import Mathlib
import GibbsMeasure

/-!
# Shared, Mathlib-only vocabulary for the Georgii comparator challenges

This is the *preamble* shared by the `comparator` challenge files for
Georgii, *Gibbs Measures and Phase Transitions*, 2nd ed.

**It imports `Mathlib` and nothing else**, and every notion is spelled out from first principles,
so that a skeptical reader who does not trust the `GibbsMeasure` library can check each definition
by eye against the book.

## Dictionary

| Georgii | here |
| --- | --- |
| `Ω = E^S` with the product σ-algebra `𝓕 = 𝓔^S` | `Config S E := S → E` (`MeasurableSpace.pi`) |
| `𝓣_Λ = 𝓕_{S∖Λ}`, (1.21) | `outside Λ` |
| `𝓕_Λ` | `inside Λ` |
| `𝓣 = ⋂_Λ 𝓣_Λ`, the tail σ-algebra | `tail S E` |
| proper kernel, (1.18) | `IsProper` |
| specification, (1.23) | `IsSpecification` |
| `𝓖(γ)`, the DLR equations | `IsGibbs` |
| local (`𝓛`-) convergence, (4.2) | `TendstoLocally` |

## Design notes

* `outside Λ` is defined as `⨆ i ∈ Λᶜ, comap (fun ω ↦ ω i)`, the σ-algebra generated by the
  coordinates *off* the finite volume `Λ`. `outside_eq_comap` proves that this is the same as the
  σ-algebra pulled back along the restriction map `ω ↦ ω|_{Λᶜ}`, and `mem_iff_mem_of_outside` /
  `measurable_outside_of_local` show that it is *exactly* the class of objects that do not depend
  on the coordinates inside `Λ`. So the two candidate definitions agree, and both match the
  intended meaning.
* **Local convergence** is stated directly as "`μ_i A → μ A` for every local (cylinder) event `A`"
  (`TendstoLocally`), which is *literally* Georgii's characterisation of convergence in the
  `𝓛`-topology (4.2); it works for arbitrary index filters (nets, not just sequences) and needs
  neither an enumeration of the local events nor finiteness of `E`. The metric
  `Σ 2⁻ⁿ |μ(Aₙ) − ν(Aₙ)|` of Georgii (4.3)(3) metrises this topology only when `E` is finite and
  `S` is countable, and fixing an enumeration would inject an irrelevant arbitrary choice into
  every theorem statement, so we avoid it. `localTopology` records the topology itself and
  `tendstoLocally_iff_tendsto` proves that the two formulations agree.

## Non-degeneracy

A vacuous definition would make every challenge trivially satisfiable, so the definitions are
exercised on examples:

* `isProper_dirac`, `consistent_dirac`, `dirac_isGibbs`: the family `γ_Λ ω = δ_ω` is Markov, proper
  and consistent, and *every* probability measure satisfies its DLR equations. (It is **not** a
  specification for `Λ ≠ ∅`, since `ω ↦ δ_ω(A)` is not `outside Λ`-measurable; that is exactly why
  `IsSpecification` carries the measurability field.)
* `eq_dirac_of_isSpecification`, `isGibbs_empty_volume`: in any specification the empty volume is
  forced to be `γ_∅ ω = δ_ω`, so the DLR equation for `Λ = ∅` is automatic.
* `isSpecification_indep`, `isGibbs_indep`: for a finite parameter set `S` and a probability measure
  `ν` on `E`, the independent specification `γ_Λ ω = ν^Λ ⊗ δ_{ω off Λ}` satisfies **all four**
  axioms, and the product measure `ν^S` is a Gibbs measure for it. So `IsSpecification` and
  `IsGibbs` are both non-vacuous, with a non-trivial (non-Dirac) example. (`S` is finite there only
  to keep the preamble free of infinite product measures, which current Mathlib does not provide;
  nothing else in this file assumes finiteness.)
* `not_measurableSet_outside`: `outside Λ` is a *proper* sub-σ-algebra — the event `{ω : ω 0 = 1}`
  is not measurable outside `{0}`.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
set_option warn.classDefReducibility false

open MeasureTheory Filter
open scoped ENNReal

noncomputable section

namespace GibbsChallenge

variable {S E : Type*} [MeasurableSpace E]

/-! ## The configuration space -/

/-- The configuration space `Ω = E^S` of Georgii, §1.1. It carries the product σ-algebra
`MeasurableSpace.pi`, i.e. the smallest σ-algebra making every coordinate `ω ↦ ω i` measurable. -/
abbrev Config (S E : Type*) := S → E

/-- Measurability into a product space, for an arbitrary (not necessarily canonical) σ-algebra `m`
on the source: `f` is `m`-measurable as soon as each of its coordinates is. -/
theorem measurable_pi_of {α : Type*} (m : MeasurableSpace α) {ι : Type*} {β : ι → Type*}
    [∀ i, MeasurableSpace (β i)] {f : α → ∀ i, β i}
    (hf : ∀ i, Measurable[m] fun a => f a i) : Measurable[m] f := by
  simp_rw [measurable_iff_comap_le, MeasurableSpace.pi, MeasurableSpace.comap_iSup,
    MeasurableSpace.comap_comp, Function.comp_def, iSup_le_iff] at hf ⊢
  exact hf

/-! ## Gluing two configurations along a finite volume -/

open Classical in
/-- `glue Λ σ ω` follows `σ` inside `Λ` and the boundary condition `ω` outside `Λ`. -/
def glue (Λ : Finset S) (σ ω : Config S E) : Config S E := fun i => if i ∈ Λ then σ i else ω i

omit [MeasurableSpace E] in
theorem glue_of_mem {Λ : Finset S} {i : S} (hi : i ∈ Λ) (σ ω : Config S E) :
    glue Λ σ ω i = σ i := by simp [glue, hi]

omit [MeasurableSpace E] in
theorem glue_of_notMem {Λ : Finset S} {i : S} (hi : i ∉ Λ) (σ ω : Config S E) :
    glue Λ σ ω i = ω i := by simp [glue, hi]

theorem measurable_glue_comp {α : Type*} [MeasurableSpace α] (Λ : Finset S)
    {u v : α → Config S E} (hu : Measurable u) (hv : Measurable v) :
    Measurable fun a => glue Λ (u a) (v a) := by
  refine measurable_pi_lambda _ fun i => ?_
  by_cases h : i ∈ Λ
  · simp only [glue_of_mem h]
    exact (measurable_pi_apply i).comp hu
  · simp only [glue_of_notMem h]
    exact (measurable_pi_apply i).comp hv

theorem measurable_glue (Λ : Finset S) :
    Measurable fun p : Config S E × Config S E => glue Λ p.1 p.2 :=
  measurable_glue_comp Λ measurable_fst measurable_snd

theorem measurable_glue_swap (Λ : Finset S) :
    Measurable fun p : Config S E × Config S E => glue Λ p.2 p.1 :=
  measurable_glue_comp Λ measurable_snd measurable_fst

theorem measurable_glue_left (Λ : Finset S) (ω : Config S E) :
    Measurable fun σ : Config S E => glue Λ σ ω :=
  measurable_glue_comp Λ measurable_id measurable_const

omit [MeasurableSpace E] in
/-- For `Λ ⊆ Δ`, updating inside `Λ` after updating inside `Δ` is again an update inside `Δ`. -/
theorem glue_glue {Λ Δ : Finset S} (h : Λ ⊆ Δ) (σ σ' ω : Config S E) :
    glue Λ σ (glue Δ σ' ω) = glue Δ (glue Λ σ σ') ω := by
  funext i
  by_cases hΛ : i ∈ Λ
  · rw [glue_of_mem hΛ, glue_of_mem (h hΛ), glue_of_mem hΛ]
  · rw [glue_of_notMem hΛ]
    by_cases hΔ : i ∈ Δ
    · rw [glue_of_mem hΔ, glue_of_mem hΔ, glue_of_notMem hΛ]
    · rw [glue_of_notMem hΔ, glue_of_notMem hΔ]

/-! ## The σ-algebras attached to a finite volume -/

/-- Georgii's external σ-algebra `𝓣_Λ = 𝓕_{S∖Λ}` (1.21): generated by the coordinates **off** the
finite volume `Λ`. -/
def outside (Λ : Finset S) : MeasurableSpace (Config S E) :=
  ⨆ i ∈ (Λ : Set S)ᶜ, MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance

/-- Georgii's `𝓕_Λ`: generated by the coordinates **inside** the finite volume `Λ`. -/
def inside (Λ : Finset S) : MeasurableSpace (Config S E) :=
  ⨆ i ∈ (Λ : Set S), MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance

theorem comap_le_outside {Λ : Finset S} {i : S} (hi : i ∉ Λ) :
    MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance ≤ outside Λ :=
  le_iSup₂ (f := fun i (_ : i ∈ (Λ : Set S)ᶜ) =>
    MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance) i hi

theorem comap_le_inside {Λ : Finset S} {i : S} (hi : i ∈ Λ) :
    MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance ≤ inside Λ :=
  le_iSup₂ (f := fun i (_ : i ∈ (Λ : Set S)) =>
    MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance) i hi

theorem outside_le (Λ : Finset S) :
    outside (E := E) Λ ≤ (inferInstance : MeasurableSpace (Config S E)) := by
  refine iSup₂_le fun i _ => ?_
  rintro s ⟨t, ht, rfl⟩
  exact measurable_pi_apply i ht

theorem inside_le (Λ : Finset S) :
    inside (E := E) Λ ≤ (inferInstance : MeasurableSpace (Config S E)) := by
  refine iSup₂_le fun i _ => ?_
  rintro s ⟨t, ht, rfl⟩
  exact measurable_pi_apply i ht

theorem measurableSet_of_outside {Λ : Finset S} {B : Set (Config S E)}
    (hB : MeasurableSet[outside Λ] B) : MeasurableSet B := outside_le Λ _ hB

theorem measurableSet_of_inside {Λ : Finset S} {B : Set (Config S E)}
    (hB : MeasurableSet[inside Λ] B) : MeasurableSet B := inside_le Λ _ hB

/-- The bigger the volume, the less information is left outside it. -/
theorem outside_antitone {Λ Δ : Finset S} (h : Λ ⊆ Δ) : outside (E := E) Δ ≤ outside Λ :=
  iSup₂_le fun _ hi => comap_le_outside fun hiΛ => hi (h hiΛ)

/-- The restriction of a configuration to the complement of `Λ`. -/
def restrictOutside (Λ : Finset S) (ω : Config S E) : {i : S // i ∉ Λ} → E := fun i => ω i.1

theorem measurable_restrictOutside (Λ : Finset S) :
    Measurable[outside Λ] (restrictOutside (E := E) Λ) :=
  measurable_pi_of _ fun i => Measurable.of_comap_le (comap_le_outside i.2)

/-- The two usual descriptions of `𝓣_Λ` agree: the σ-algebra generated by the coordinates off `Λ`
is the σ-algebra pulled back along the restriction map `ω ↦ ω|_{Λᶜ}`. -/
theorem outside_eq_comap (Λ : Finset S) :
    outside (E := E) Λ = MeasurableSpace.comap (restrictOutside Λ) inferInstance := by
  refine le_antisymm ?_ (measurable_restrictOutside Λ).comap_le
  refine iSup₂_le fun i hi => ?_
  have h1 : Measurable[MeasurableSpace.comap (restrictOutside (E := E) Λ) inferInstance]
      (restrictOutside Λ) := Measurable.of_comap_le le_rfl
  exact ((measurable_pi_apply (⟨i, hi⟩ : {i : S // i ∉ Λ})).comp h1).comap_le

/-- **Events measurable outside `Λ` do not depend on the coordinates inside `Λ`.** -/
theorem mem_iff_mem_of_outside {Λ : Finset S} {B : Set (Config S E)}
    (hB : MeasurableSet[outside Λ] B) {ω ω' : Config S E} (h : ∀ i ∉ Λ, ω i = ω' i) :
    ω ∈ B ↔ ω' ∈ B := by
  rw [outside_eq_comap] at hB
  obtain ⟨C, -, rfl⟩ := hB
  have hr : restrictOutside Λ ω = restrictOutside Λ ω' := funext fun i => h i.1 i.2
  simp only [Set.mem_preimage, hr]

/-- **Conversely**, a measurable function that does not depend on the coordinates inside `Λ` is
measurable with respect to `outside Λ`. -/
theorem measurable_outside_of_local [Nonempty E] {α : Type*} [MeasurableSpace α] (Λ : Finset S)
    {f : Config S E → α} (hf : Measurable f)
    (hloc : ∀ ω ω' : Config S E, (∀ i ∉ Λ, ω i = ω' i) → f ω = f ω') :
    Measurable[outside Λ] f := by
  set ζ : Config S E := fun _ => Classical.arbitrary E with hζ
  have hg : Measurable[outside Λ] fun ω : Config S E => glue Λ ζ ω := by
    refine measurable_pi_of _ fun i => ?_
    by_cases hi : i ∈ Λ
    · simp only [glue_of_mem hi]
      exact measurable_const
    · simp only [glue_of_notMem hi]
      exact Measurable.of_comap_le (comap_le_outside hi)
  have hfg : f = f ∘ fun ω : Config S E => glue Λ ζ ω :=
    funext fun ω => hloc _ _ fun i hi => (glue_of_notMem hi ζ ω).symm
  rw [hfg]
  exact hf.comp hg

/-- Nothing is measurable outside `Λ = ∅`, i.e. `𝓣_∅ = 𝓕`. -/
theorem outside_empty :
    outside (S := S) (E := E) ∅ = (inferInstance : MeasurableSpace (Config S E)) := by
  refine le_antisymm (outside_le _) ?_
  show (⨆ i, MeasurableSpace.comap (fun ω : Config S E => ω i) inferInstance) ≤ _
  exact iSup_le fun i => comap_le_outside (Finset.notMem_empty i)

/-! ## The tail σ-algebra -/

/-- Georgii's tail σ-algebra (σ-algebra at infinity) `𝓣 = ⋂_{Λ finite} 𝓣_Λ`. -/
def tail (S E : Type*) [MeasurableSpace E] : MeasurableSpace (Config S E) :=
  ⨅ Λ : Finset S, outside Λ

theorem tail_le_outside (Λ : Finset S) : tail S E ≤ outside Λ := iInf_le _ _

theorem tail_le : tail S E ≤ (inferInstance : MeasurableSpace (Config S E)) :=
  (tail_le_outside ∅).trans (outside_le _)

/-! ## Proper kernels, specifications, Gibbs measures -/

/-- **Properness**, Georgii (1.18): `γ(A ∩ B | ·) = γ(A | ·) 1_B` for every `A ∈ 𝓕` and every
`B ∈ 𝓣_Λ`. -/
def IsProper (Λ : Finset S) (γ : Config S E → Measure (Config S E)) : Prop :=
  ∀ A B : Set (Config S E), MeasurableSet A → MeasurableSet[outside Λ] B →
    ∀ ω : Config S E, γ ω (A ∩ B) = B.indicator (fun _ => γ ω A) ω

/-- **Specification**, Georgii (1.23): a family of proper probability kernels from `𝓣_Λ` to `𝓕`,
consistent in the sense `γ_Δ γ_Λ = γ_Δ` for `Λ ⊆ Δ`. -/
structure IsSpecification (γ : Finset S → Config S E → Measure (Config S E)) : Prop where
  /-- each `γ_Λ(·|ω)` is a probability measure -/
  isProbabilityMeasure : ∀ (Λ : Finset S) (ω : Config S E), IsProbabilityMeasure (γ Λ ω)
  /-- `γ_Λ` is a kernel *from `𝓣_Λ`*: `ω ↦ γ_Λ(A|ω)` is measurable outside `Λ` -/
  measurable_apply : ∀ (Λ : Finset S) (A : Set (Config S E)), MeasurableSet A →
    Measurable[outside Λ] fun ω => γ Λ ω A
  /-- each `γ_Λ` is proper -/
  proper : ∀ Λ : Finset S, IsProper Λ (γ Λ)
  /-- consistency `γ_Δ γ_Λ = γ_Δ` for `Λ ⊆ Δ` -/
  consistent : ∀ Λ Δ : Finset S, Λ ⊆ Δ → ∀ (ω : Config S E) (A : Set (Config S E)),
    MeasurableSet A → ∫⁻ ω', γ Λ ω' A ∂(γ Δ ω) = γ Δ ω A

/-- **The DLR equations**: `μ ∈ 𝓖(γ)` iff `μ` is a probability measure with `μ γ_Λ = μ` for every
finite volume `Λ` (Georgii (1.23) together with Remark (1.24)). -/
def IsGibbs (γ : Finset S → Config S E → Measure (Config S E)) (μ : Measure (Config S E)) : Prop :=
  IsProbabilityMeasure μ ∧ ∀ (Λ : Finset S) (A : Set (Config S E)), MeasurableSet A →
    μ A = ∫⁻ ω, γ Λ ω A ∂μ

/-! ## Local events and the topology of local convergence -/

/-- A *local* (cylinder) event: one depending on finitely many coordinates only. Georgii's algebra
`𝓕⁰ = ⋃_Λ 𝓕_Λ` (4.1). -/
def IsLocalEvent (A : Set (Config S E)) : Prop := ∃ Λ : Finset S, MeasurableSet[inside Λ] A

theorem IsLocalEvent.measurableSet {A : Set (Config S E)} (hA : IsLocalEvent A) :
    MeasurableSet A := by
  obtain ⟨Λ, hΛ⟩ := hA
  exact measurableSet_of_inside hΛ

theorem isLocalEvent_coord (i : S) {B : Set E} (hB : MeasurableSet B) :
    IsLocalEvent {ω : Config S E | ω i ∈ B} :=
  ⟨{i}, comap_le_inside (Finset.mem_singleton_self i) _ ⟨B, hB, rfl⟩⟩

/-- **Local convergence**, Georgii (4.2): `μ_i → ν` along the filter `L` iff `μ_i A → ν A` for
every local event `A`. -/
def TendstoLocally {ι : Type*} (μ : ι → Measure (Config S E)) (L : Filter ι)
    (ν : Measure (Config S E)) : Prop :=
  ∀ A : Set (Config S E), IsLocalEvent A → Tendsto (fun i => μ i A) L (nhds (ν A))

/-- The `𝓛`-topology of Georgii (4.2): the coarsest topology making `μ ↦ μ A` continuous for every
local event `A`. -/
def localTopology : TopologicalSpace (Measure (Config S E)) :=
  ⨅ A : {A : Set (Config S E) // IsLocalEvent A},
    TopologicalSpace.induced (fun μ : Measure (Config S E) => μ A.1) inferInstance

theorem tendstoLocally_iff_tendsto {ι : Type*} (μ : ι → Measure (Config S E)) (L : Filter ι)
    (ν : Measure (Config S E)) :
    TendstoLocally μ L ν ↔ Tendsto μ L (@nhds _ localTopology ν) := by
  rw [localTopology, nhds_iInf, tendsto_iInf]
  refine ⟨fun h A => ?_, fun h A hA => ?_⟩
  · rw [nhds_induced, tendsto_comap_iff]
    exact h A.1 A.2
  · have := h ⟨A, hA⟩
    rwa [nhds_induced, tendsto_comap_iff] at this

/-! ## Non-degeneracy: the identity family -/

section Dirac

theorem dirac_apply_eq {A : Set (Config S E)} (hA : MeasurableSet A) :
    (fun ω : Config S E => Measure.dirac ω A) = A.indicator 1 :=
  funext fun ω => Measure.dirac_apply' ω hA

/-- The family `γ_Λ ω = δ_ω` is proper. -/
theorem isProper_dirac (Λ : Finset S) : IsProper Λ (fun ω : Config S E => Measure.dirac ω) := by
  intro A B hA hB ω
  have hB' : MeasurableSet B := measurableSet_of_outside hB
  simp only [Measure.dirac_apply' _ (hA.inter hB'), Measure.dirac_apply' _ hA]
  by_cases hωA : ω ∈ A <;> by_cases hωB : ω ∈ B <;> simp [hωA, hωB]

/-- The family `γ_Λ ω = δ_ω` is consistent. -/
theorem consistent_dirac (ω : Config S E) {A : Set (Config S E)} (hA : MeasurableSet A) :
    ∫⁻ ω', (Measure.dirac ω') A ∂(Measure.dirac ω) = Measure.dirac ω A := by
  rw [dirac_apply_eq hA, lintegral_dirac' _ (measurable_one.indicator hA)]
  exact congrFun (dirac_apply_eq hA).symm ω

/-- **Every** probability measure satisfies the DLR equations of the family `γ_Λ ω = δ_ω`. -/
theorem dirac_isGibbs (μ : Measure (Config S E)) [IsProbabilityMeasure μ] :
    IsGibbs (fun (_ : Finset S) (ω : Config S E) => Measure.dirac ω) μ := by
  refine ⟨inferInstance, fun Λ A hA => ?_⟩
  rw [dirac_apply_eq hA, lintegral_indicator_one hA]

end Dirac

/-! ## Non-degeneracy: the empty volume -/

section Empty

variable {γ : Finset S → Config S E → Measure (Config S E)}

/-- In **any** specification the empty-volume kernel is forced to be the identity kernel. -/
theorem eq_dirac_of_isSpecification (hγ : IsSpecification γ) (ω : Config S E) :
    γ ∅ ω = Measure.dirac ω := by
  have := hγ.isProbabilityMeasure ∅ ω
  refine Measure.ext fun B hB => ?_
  have hB0 : MeasurableSet[outside (∅ : Finset S)] B := by rw [outside_empty]; exact hB
  have h := hγ.proper ∅ Set.univ B MeasurableSet.univ hB0 ω
  rw [Set.univ_inter, measure_univ] at h
  rw [h, Measure.dirac_apply' _ hB]
  by_cases hωB : ω ∈ B <;> simp [hωB]

/-- Consequently the DLR equation for the empty volume is automatic. -/
theorem isGibbs_empty_volume (hγ : IsSpecification γ) (μ : Measure (Config S E))
    [IsProbabilityMeasure μ] {A : Set (Config S E)} (hA : MeasurableSet A) :
    μ A = ∫⁻ ω, γ ∅ ω A ∂μ := by
  simp only [eq_dirac_of_isSpecification hγ]
  rw [dirac_apply_eq hA, lintegral_indicator_one hA]

end Empty

/-! ## Non-degeneracy: `outside Λ` is a proper sub-σ-algebra -/

theorem not_measurableSet_outside :
    ¬ MeasurableSet[outside ({0} : Finset ℕ)] {ω : Config ℕ Bool | ω 0 = true} := by
  intro h
  have h2 := mem_iff_mem_of_outside h (ω := fun _ => true)
    (ω' := fun i => if i = 0 then false else true) (fun i hi => by simp at hi; simp [hi])
  simp at h2

/-! ## Non-degeneracy: the independent specification -/

section Independent

variable [Fintype S]

theorem nonempty_of_isProbabilityMeasure (ν : Measure E) [IsProbabilityMeasure ν] : Nonempty E := by
  by_contra h
  rw [not_nonempty_iff] at h
  have h1 : (ν Set.univ) = 1 := measure_univ
  rw [Set.univ_eq_empty_iff.mpr h, measure_empty] at h1
  exact zero_ne_one h1

variable (ν : Measure E) [IsProbabilityMeasure ν]

/-- **The independent specification**: inside `Λ` the spins are resampled i.i.d. from `ν`, outside
`Λ` the boundary condition `ω` is kept. -/
def indepSpec (Λ : Finset S) (ω : Config S E) : Measure (Config S E) :=
  Measure.map (fun σ => glue Λ σ ω) (Measure.pi fun _ : S => ν)

instance instIsProbabilityMeasureIndepSpec (Λ : Finset S) (ω : Config S E) :
    IsProbabilityMeasure (indepSpec ν Λ ω) :=
  Measure.isProbabilityMeasure_map (measurable_glue_left Λ ω).aemeasurable

omit [IsProbabilityMeasure ν] in
theorem indepSpec_apply (Λ : Finset S) (ω : Config S E) {A : Set (Config S E)}
    (hA : MeasurableSet A) :
    indepSpec ν Λ ω A = ∫⁻ σ, A.indicator 1 (glue Λ σ ω) ∂(Measure.pi fun _ : S => ν) := by
  have h : (fun σ : Config S E => A.indicator (1 : Config S E → ℝ≥0∞) (glue Λ σ ω))
      = ((fun σ : Config S E => glue Λ σ ω) ⁻¹' A).indicator 1 := by
    funext σ
    by_cases h : glue Λ σ ω ∈ A <;> simp [h]
  rw [h, lintegral_indicator_one (measurable_glue_left Λ ω hA), indepSpec,
    Measure.map_apply (measurable_glue_left Λ ω) hA]

/-- **The key resampling identity**: the i.i.d. product measure `ν^S` is invariant under
independently resampling the coordinates inside a finite volume `Λ`. -/
theorem map_glue_prod (Λ : Finset S) :
    Measure.map (fun p : Config S E × Config S E => glue Λ p.2 p.1)
        ((Measure.pi fun _ : S => ν).prod (Measure.pi fun _ : S => ν))
      = Measure.pi fun _ : S => ν := by
  classical
  refine (Measure.pi_eq fun s hs => ?_).symm
  rw [Measure.map_apply (measurable_glue_swap Λ) (MeasurableSet.univ_pi hs)]
  have hpre : (fun p : Config S E × Config S E => glue Λ p.2 p.1) ⁻¹' (Set.univ.pi s)
      = (Set.univ.pi fun i => if i ∈ Λ then Set.univ else s i) ×ˢ
        (Set.univ.pi fun i => if i ∈ Λ then s i else Set.univ) := by
    ext p
    simp only [Set.mem_preimage, Set.mem_univ_pi, Set.mem_prod]
    constructor
    · refine fun h => ⟨fun i => ?_, fun i => ?_⟩
      · by_cases hi : i ∈ Λ
        · simp [hi]
        · simpa [hi, glue_of_notMem hi] using h i
      · by_cases hi : i ∈ Λ
        · simpa [hi, glue_of_mem hi] using h i
        · simp [hi]
    · rintro ⟨h1, h2⟩ i
      by_cases hi : i ∈ Λ
      · rw [glue_of_mem hi]; simpa [hi] using h2 i
      · rw [glue_of_notMem hi]; simpa [hi] using h1 i
  rw [hpre, Measure.prod_prod, Measure.pi_pi, Measure.pi_pi, ← Finset.prod_mul_distrib]
  refine Finset.prod_congr rfl fun i _ => ?_
  by_cases hi : i ∈ Λ <;> simp [hi]

/-- The integrated form of the resampling identity. -/
theorem lintegral_glue (Λ : Finset S) {F : Config S E → ℝ≥0∞} (hF : Measurable F) :
    ∫⁻ ω, (∫⁻ σ, F (glue Λ σ ω) ∂(Measure.pi fun _ : S => ν)) ∂(Measure.pi fun _ : S => ν)
      = ∫⁻ τ, F τ ∂(Measure.pi fun _ : S => ν) := by
  calc ∫⁻ ω, (∫⁻ σ, F (glue Λ σ ω) ∂(Measure.pi fun _ : S => ν)) ∂(Measure.pi fun _ : S => ν)
      = ∫⁻ p, F (glue Λ p.2 p.1)
          ∂((Measure.pi fun _ : S => ν).prod (Measure.pi fun _ : S => ν)) :=
        (lintegral_prod _ (hF.comp (measurable_glue_swap Λ)).aemeasurable).symm
    _ = ∫⁻ τ, F τ ∂(Measure.map (fun p : Config S E × Config S E => glue Λ p.2 p.1)
          ((Measure.pi fun _ : S => ν).prod (Measure.pi fun _ : S => ν))) :=
        (lintegral_map hF (measurable_glue_swap Λ)).symm
    _ = ∫⁻ τ, F τ ∂(Measure.pi fun _ : S => ν) := by rw [map_glue_prod]

theorem measurable_indepSpec_apply (Λ : Finset S) {A : Set (Config S E)} (hA : MeasurableSet A) :
    Measurable[outside Λ] fun ω => indepSpec ν Λ ω A := by
  have : Nonempty E := nonempty_of_isProbabilityMeasure ν
  have heq : (fun ω : Config S E => indepSpec ν Λ ω A)
      = fun ω => ∫⁻ σ, A.indicator 1 (glue Λ σ ω) ∂(Measure.pi fun _ : S => ν) :=
    funext fun ω => indepSpec_apply ν Λ ω hA
  refine measurable_outside_of_local Λ ?_ ?_
  · rw [heq]
    exact Measurable.lintegral_prod_right'
      (f := fun p : Config S E × Config S E => A.indicator 1 (glue Λ p.2 p.1))
      ((measurable_one.indicator hA).comp (measurable_glue_swap Λ))
  · intro ω ω' h
    rw [indepSpec_apply ν Λ ω hA, indepSpec_apply ν Λ ω' hA]
    refine lintegral_congr fun σ => ?_
    have hgg : glue Λ σ ω = glue Λ σ ω' := by
      funext i
      by_cases hi : i ∈ Λ
      · rw [glue_of_mem hi, glue_of_mem hi]
      · rw [glue_of_notMem hi, glue_of_notMem hi, h i hi]
    rw [hgg]

omit [IsProbabilityMeasure ν] in
theorem isProper_indepSpec (Λ : Finset S) : IsProper Λ (indepSpec ν Λ) := by
  intro A B hA hB ω
  have hB' : MeasurableSet B := measurableSet_of_outside hB
  have key : ∀ σ : Config S E, (glue Λ σ ω ∈ B ↔ ω ∈ B) := fun σ =>
    (mem_iff_mem_of_outside hB (fun i hi => (glue_of_notMem hi σ ω).symm)).symm
  simp only [indepSpec, Measure.map_apply (measurable_glue_left Λ ω) (hA.inter hB'),
    Measure.map_apply (measurable_glue_left Λ ω) hA]
  by_cases hωB : ω ∈ B
  · rw [Set.indicator_of_mem hωB]
    congr 1
    ext σ
    simp only [Set.mem_preimage, Set.mem_inter_iff, and_iff_left_iff_imp]
    exact fun _ => (key σ).mpr hωB
  · rw [Set.indicator_of_notMem hωB]
    have hempty : (fun σ : Config S E => glue Λ σ ω) ⁻¹' (A ∩ B) = ∅ := by
      ext σ
      simp only [Set.mem_preimage, Set.mem_inter_iff, Set.mem_empty_iff_false, iff_false, not_and]
      exact fun _ hc => hωB ((key σ).mp hc)
    rw [hempty, measure_empty]

theorem consistent_indepSpec {Λ Δ : Finset S} (hΛΔ : Λ ⊆ Δ) (ω : Config S E)
    {A : Set (Config S E)} (hA : MeasurableSet A) :
    ∫⁻ ω', indepSpec ν Λ ω' A ∂(indepSpec ν Δ ω) = indepSpec ν Δ ω A := by
  have hmeas : Measurable fun ω' : Config S E => indepSpec ν Λ ω' A :=
    (measurable_indepSpec_apply ν Λ hA).mono (outside_le Λ) le_rfl
  rw [indepSpec, lintegral_map hmeas (measurable_glue_left Δ ω)]
  simp only [indepSpec_apply ν Λ _ hA, glue_glue hΛΔ]
  rw [lintegral_glue ν Λ
      (F := fun τ : Config S E => A.indicator (1 : Config S E → ℝ≥0∞) (glue Δ τ ω))
      ((measurable_one.indicator hA).comp (measurable_glue_left Δ ω)),
    ← indepSpec_apply ν Δ ω hA, indepSpec]

/-- **The independent specification really is a specification.** -/
theorem isSpecification_indep : IsSpecification (indepSpec (S := S) ν) := by
  refine ⟨fun Λ ω => inferInstance, fun Λ A hA => measurable_indepSpec_apply ν Λ hA,
    fun Λ => isProper_indepSpec ν Λ, fun Λ Δ h ω A hA => consistent_indepSpec ν h ω hA⟩

/-- **And its set of Gibbs measures is non-empty**: the i.i.d. product measure `ν^S` is a Gibbs
measure for the independent specification. -/
theorem isGibbs_indep : IsGibbs (indepSpec (S := S) ν) (Measure.pi fun _ : S => ν) := by
  refine ⟨inferInstance, fun Λ A hA => ?_⟩
  simp only [indepSpec_apply ν Λ _ hA]
  rw [lintegral_glue ν Λ (measurable_one.indicator hA), lintegral_indicator_one hA]

end Independent

end GibbsChallenge

/-!
# Comparator challenge: Georgii Theorem (6.9), first assertion — the low-temperature limit

This is the *challenge* file for the **first** assertion of Georgii, *Gibbs Measures and Phase
Transitions*, 2nd ed., Theorem (6.9):
`lim_{β → ∞} d(𝒢_Θ(βΦ), δ₊) = lim_{β → ∞} d(𝒢_Θ(βΦ), δ₋) = 0`
for the two-dimensional Ising ferromagnet, where `d` is a metric for the topology of local
convergence and `𝒢_Θ(βΦ)` is the set of shift-invariant Gibbs measures.  (`Comparator/Challenge.lean`
of this repository states only the *second* assertion, the "in particular" half.)

**The file imports `Mathlib` and nothing else.**  Everything above this docstring is the shared
preamble; everything below spells out, from first principles, the two-dimensional Ising model (the
lattice `ℤ²`, the spins, the nearest-neighbour bonds, the Hamiltonian, the finite-volume Gibbs
distribution, the DLR equation, the lattice shifts — all copied verbatim from
`Comparator/Challenge.lean`) together with Georgii's metric of Remark (4.3)(3) for the topology of
local convergence.

## Dictionary for the new notions

| Georgii | here |
| --- | --- |
| ground states `ω⁺`, `ω⁻` | `fun _ : Site ↦ true`, `fun _ : Site ↦ false` |
| `δ₊`, `δ₋` | `Measure.dirac (fun _ : Site ↦ true)`, `Measure.dirac (fun _ : Site ↦ false)` |
| `𝓛`-convergence (4.2) | `TendstoLocally` (from the preamble) |
| `d(μ, ν) = ∑_{n≥1} 2⁻ⁿ|μ(Aₙ) − ν(Aₙ)|`, Remark (4.3)(3) | `localDist` |
| `d(F, ν) = inf_{μ ∈ F} d(μ, ν)` | `localDistSet` |
| `𝒢_Θ(βΦ)`, (5.13) | `shiftInvariantGibbs` |

## Design notes

* Georgii writes "we let `d` denote **any** metric for the `𝓛`-topology, cf. Remark (4.3)(3)".
  Remark (4.3)(3) produces such a metric from **any** enumeration `(Aₙ)` of the countable algebra
  `𝓕⁰` of local events.  So instead of fixing one arbitrary enumeration — an irrelevant choice which
  would weaken the statement — `localDist A` is defined for an arbitrary sequence `A : ℕ → Set Config`
  and the theorem below is asserted **for every** such sequence all of whose members are local
  events.  This covers every enumeration of `𝓕⁰`, hence every metric supplied by Remark (4.3)(3),
  and is strictly stronger than fixing one.
* Because `sInf ∅ = 0` by convention in `ℝ`, a statement about `d(F, ν)` alone could conceivably be
  satisfied vacuously.  `ising_low_temperature_limit` therefore asserts the content of Georgii's
  proof directly: it *exhibits* shift-invariant Gibbs measures `μ₊^β, μ₋^β ∈ 𝒢_Θ(βΦ)` converging
  locally (in the sense of the preamble's `TendstoLocally`, which is Georgii's (4.2) verbatim, and
  in the sense of `localDist`) to `δ₊` and `δ₋`.  The displayed form
  `lim_β d(𝒢_Θ(βΦ), δ_±) = 0` is then `ising_low_temperature_localDistSet`.

## Main statements

* `ising_low_temperature_limit`: **Georgii, Theorem (6.9), first assertion**, in the form
  established by Georgii's proof.
* `ising_low_temperature_localDistSet`: the same, in the displayed form
  `lim_{β → ∞} d(𝒢_Θ(βΦ), δ₊) = lim_{β → ∞} d(𝒢_Θ(βΦ), δ₋) = 0`.
-/

open scoped Topology

namespace GibbsChallenge

/-! ## Local events depend only on the coordinates inside the volume

The preamble shows that an event measurable *outside* a finite volume `Λ` does not depend on the
coordinates inside `Λ` (`mem_iff_mem_of_outside`).  Here is the mirror statement for `inside Λ`,
which is what makes `IsLocalEvent` mean what it should: *a local event depends on finitely many
coordinates only*. -/

variable {S E : Type*} [MeasurableSpace E]

/-- The restriction of a configuration to the finite volume `Λ`. -/
def restrictInside (Λ : Finset S) (ω : Config S E) : {i : S // i ∈ Λ} → E := fun i => ω i.1

theorem measurable_restrictInside (Λ : Finset S) :
    Measurable[inside Λ] (restrictInside (E := E) Λ) :=
  measurable_pi_of _ fun i => Measurable.of_comap_le (comap_le_inside i.2)

/-- The two usual descriptions of `𝓕_Λ` agree: the σ-algebra generated by the coordinates in `Λ`
is the σ-algebra pulled back along the restriction map `ω ↦ ω|_Λ`. -/
theorem inside_eq_comap (Λ : Finset S) :
    inside (E := E) Λ = MeasurableSpace.comap (restrictInside Λ) inferInstance := by
  refine le_antisymm ?_ (measurable_restrictInside Λ).comap_le
  refine iSup₂_le fun i hi => ?_
  have h1 : Measurable[MeasurableSpace.comap (restrictInside (E := E) Λ) inferInstance]
      (restrictInside Λ) := Measurable.of_comap_le le_rfl
  exact ((measurable_pi_apply (⟨i, hi⟩ : {i : S // i ∈ Λ})).comp h1).comap_le

/-- **Events measurable inside `Λ` depend only on the coordinates inside `Λ`.** -/
theorem mem_iff_mem_of_inside {Λ : Finset S} {A : Set (Config S E)}
    (hA : MeasurableSet[inside Λ] A) {ω ω' : Config S E} (h : ∀ i ∈ Λ, ω i = ω' i) :
    ω ∈ A ↔ ω' ∈ A := by
  rw [inside_eq_comap] at hA
  obtain ⟨C, -, rfl⟩ := hA
  have hr : restrictInside Λ ω = restrictInside Λ ω' := funext fun i => h i.1 i.2
  simp only [Set.mem_preimage, hr]

end GibbsChallenge

namespace IsingChallenge

/-! ### The lattice and the configuration space -/

/-- The sites of the two-dimensional lattice `ℤ²`. -/
abbrev Site : Type := Fin 2 → ℤ

/-- A spin configuration: a `Bool`, i.e. a sign, attached to every site of `ℤ²`. Being a product
of copies of the discrete space `Bool`, this carries the product σ-algebra. -/
abbrev Config : Type := Site → Bool

/-- The `±1`-valued spin attached to a `Bool`: `true ↦ +1`, `false ↦ -1`. -/
def spin (b : Bool) : ℝ := if b then 1 else -1

/-- The `k`-th unit vector of the lattice `ℤ²`. -/
def e (k : Fin 2) : Site := fun l ↦ if l = k then 1 else 0

/-! ### The nearest-neighbour bonds meeting a finite volume

A nearest-neighbour bond of `ℤ²` is an unordered pair `{i, i + e k}` with `k : Fin 2`; we encode
it by the ordered pair `(i, k)`, so that each bond has exactly one encoding. -/

/-- An auxiliary finite set of sites containing every left endpoint of a bond meeting `Λ`: the
volume `Λ` itself together with all of its translates by `-e k`. -/
def bondBase (Λ : Finset Site) : Finset Site :=
  Λ ∪ (Finset.univ : Finset (Fin 2)).biUnion fun k ↦ Λ.image fun i ↦ i - e k

/-- The set of nearest-neighbour bonds `{i, i + e k}` of `ℤ²` that *meet* the finite volume `Λ`,
encoded as ordered pairs `(i, k)`. It is finite because the left endpoint `i` of such a bond lies
either in `Λ` or in one of the two translates `Λ - e k`. -/
def bonds (Λ : Finset Site) : Finset (Site × Fin 2) :=
  (bondBase Λ ×ˢ (Finset.univ : Finset (Fin 2))).filter fun p ↦ p.1 ∈ Λ ∨ p.1 + e p.2 ∈ Λ

/-- The promised characterisation: `(i, k)` belongs to `bonds Λ` exactly when the nearest-neighbour
bond `{i, i + e k}` meets `Λ`. -/
theorem mem_bonds (Λ : Finset Site) (i : Site) (k : Fin 2) :
    (i, k) ∈ bonds Λ ↔ (i ∈ Λ ∨ i + e k ∈ Λ) := by
  refine ⟨fun h ↦ (Finset.mem_filter.mp h).2, fun h ↦ Finset.mem_filter.mpr ⟨?_, h⟩⟩
  refine Finset.mem_product.mpr ⟨?_, Finset.mem_univ _⟩
  rcases h with h | h
  · exact Finset.mem_union_left _ h
  · refine Finset.mem_union_right _ (Finset.mem_biUnion.mpr ⟨k, Finset.mem_univ _, ?_⟩)
    exact Finset.mem_image.mpr ⟨i + e k, h, by simp⟩

/-! ### The Ising Hamiltonian -/

/-- The energy of the configuration `σ` in the finite volume `Λ`: minus the sum of the products of
neighbouring spins, over all nearest-neighbour bonds meeting `Λ`. This is the ferromagnetic Ising
Hamiltonian with coupling constant `1` and zero external field. -/
def hamiltonian (Λ : Finset Site) (σ : Config) : ℝ :=
  -∑ p ∈ bonds Λ, spin (σ p.1) * spin (σ (p.1 + e p.2))

/-! ### The finite-volume Gibbs distribution -/

/-- `glue Λ ζ ω` follows `ζ` inside `Λ` and the boundary condition `ω` outside `Λ`. -/
def glue (Λ : Finset Site) (ζ ω : Config) : Config := fun i ↦ if i ∈ Λ then ζ i else ω i

/-- Extend an inner configuration `ζ : Λ → Bool` to all of `ℤ²`, using `ω` outside `Λ`. -/
def extend (Λ : Finset Site) (ζ : Λ → Bool) (ω : Config) : Config :=
  fun i ↦ if h : i ∈ Λ then ζ ⟨i, h⟩ else ω i

/-- The unnormalised Boltzmann weight `exp (-β * H)` of the inner configuration `ζ` in the volume
`Λ` with boundary condition `ω`. -/
def weight (β : ℝ) (Λ : Finset Site) (ω : Config) (ζ : Λ → Bool) : ℝ :=
  Real.exp (-β * hamiltonian Λ (glue Λ (extend Λ ζ ω) ω))

/-- The partition function in the volume `Λ` with boundary condition `ω`: the sum of the Boltzmann
weights over the `2 ^ #Λ` inner configurations. -/
def partitionFunction (β : ℝ) (Λ : Finset Site) (ω : Config) : ℝ :=
  ∑ ζ : Λ → Bool, weight β Λ ω ζ

/-- The finite-volume Gibbs distribution in `Λ` at inverse temperature `β` with boundary condition
`ω`, written out explicitly as a normalised finite sum of Dirac measures: the configuration that
agrees with `ζ` on `Λ` and with `ω` off `Λ` gets probability `exp (-β * H) / Z`. -/
def gibbsMeasure (β : ℝ) (Λ : Finset Site) (ω : Config) : Measure Config :=
  (ENNReal.ofReal (partitionFunction β Λ ω))⁻¹ •
    ∑ ζ : Λ → Bool,
      ENNReal.ofReal (weight β Λ ω ζ) • Measure.dirac (glue Λ (extend Λ ζ ω) ω)

/-! ### Gibbs measures (the DLR equation) -/

/-- `μ` is a Gibbs measure for the two-dimensional Ising model at inverse temperature `β`: it is a
probability measure on `Config` whose conditional distribution in every finite volume `Λ`, given
the configuration outside `Λ`, is the finite-volume Gibbs distribution. This is the
Dobrushin–Lanford–Ruelle equation, written in the elementary integrated form
`μ A = ∫⁻ ω, gibbsMeasure β Λ ω A ∂μ` for measurable `A`. -/
def IsGibbs (β : ℝ) (μ : Measure Config) : Prop :=
  IsProbabilityMeasure μ ∧
    ∀ Λ : Finset Site, ∀ A : Set Config, MeasurableSet A →
      μ A = ∫⁻ ω, gibbsMeasure β Λ ω A ∂μ

/-- Translation of a configuration by the lattice vector `j`. -/
def shift (j : Site) (σ : Config) : Config := fun i ↦ σ (i - j)

/-! ### Georgii (5.13): the shift-invariant Gibbs measures `𝒢_Θ(βΦ)` -/

/-- **Georgii (5.13)**: `𝒢_Θ(βΦ)`, the set of *shift-invariant* Gibbs measures of the
two-dimensional Ising ferromagnet at inverse temperature `β`. -/
def shiftInvariantGibbs (β : ℝ) : Set (Measure Config) :=
  {μ | IsGibbs β μ ∧ ∀ j : Site, μ.map (shift j) = μ}

/-! ### Local events and Georgii's metric (4.3)(3) for the `𝓛`-topology -/

/-- A *local* event of the Ising configuration space: an event depending on finitely many spins
only.  This is the preamble's `IsLocalEvent`, i.e. Georgii's algebra `𝓕⁰ = ⋃_Λ 𝓕_Λ` (4.1),
specialised to `S = ℤ²` and `E = {±1}`. -/
abbrev IsLocalEvent (A : Set Config) : Prop :=
  GibbsChallenge.IsLocalEvent (S := Site) (E := Bool) A

/-- Georgii's local (`𝓛`-) convergence (4.2), specialised to the Ising configuration space: this
is the preamble's `TendstoLocally`, i.e. `μ_β A → ν A` for every local event `A`. -/
abbrev TendstoLocally (μ : ℝ → Measure Config) (L : Filter ℝ) (ν : Measure Config) : Prop :=
  GibbsChallenge.TendstoLocally (S := Site) (E := Bool) μ L ν

/-- **Georgii, Remark (4.3)(3)**: the metric `d(μ, ν) = ∑_{n ≥ 1} 2⁻ⁿ |μ(Aₙ) − ν(Aₙ)|` for the
topology of local convergence, built from a sequence `A` of local events.  Taking for `A` any
enumeration of the countable algebra `𝓕⁰` of local events yields Georgii's metric; the theorems
below are stated for *every* sequence of local events, hence for every such metric. -/
def localDist (A : ℕ → Set Config) (μ ν : Measure Config) : ℝ :=
  ∑' n : ℕ, (2 : ℝ)⁻¹ ^ (n + 1) * |(μ (A n)).toReal - (ν (A n)).toReal|

/-- **Georgii's `d(F, ν)`**: the distance from a set `F` of random fields to the random field `ν`,
i.e. `inf_{μ ∈ F} d(μ, ν)`. -/
def localDistSet (A : ℕ → Set Config) (F : Set (Measure Config)) (ν : Measure Config) : ℝ :=
  sInf ((fun μ ↦ localDist A μ ν) '' F)

/-! #### `localDist` is a pseudometric, and `localDistSet` is the associated distance to a set -/

theorem abs_toReal_sub_le_one {μ ν : Measure Config} [IsProbabilityMeasure μ]
    [IsProbabilityMeasure ν] (B : Set Config) :
    |(μ B).toReal - (ν B).toReal| ≤ 1 := by
  have hμ1 : (μ B).toReal ≤ 1 := measureReal_le_one (μ := μ) (s := B)
  have hν1 : (ν B).toReal ≤ 1 := measureReal_le_one (μ := ν) (s := B)
  have hμ0 : (0 : ℝ) ≤ (μ B).toReal := ENNReal.toReal_nonneg
  have hν0 : (0 : ℝ) ≤ (ν B).toReal := ENNReal.toReal_nonneg
  rw [abs_sub_le_iff]
  constructor <;> linarith

theorem summable_geomHalf : Summable (fun n : ℕ ↦ (2 : ℝ)⁻¹ ^ (n + 1)) := by
  have h : Summable (fun n : ℕ ↦ ((2 : ℝ)⁻¹) ^ n) :=
    summable_geometric_of_lt_one (by norm_num) (by norm_num)
  simpa [pow_succ] using h.mul_right ((2 : ℝ)⁻¹)

theorem localDist_summand_nonneg (A : ℕ → Set Config) (μ ν : Measure Config) (n : ℕ) :
    0 ≤ (2 : ℝ)⁻¹ ^ (n + 1) * |(μ (A n)).toReal - (ν (A n)).toReal| := by positivity

theorem localDist_summand_le (A : ℕ → Set Config) {μ ν : Measure Config} [IsProbabilityMeasure μ]
    [IsProbabilityMeasure ν] (n : ℕ) :
    (2 : ℝ)⁻¹ ^ (n + 1) * |(μ (A n)).toReal - (ν (A n)).toReal| ≤ (2 : ℝ)⁻¹ ^ (n + 1) := by
  nth_rewrite 2 [← mul_one ((2 : ℝ)⁻¹ ^ (n + 1))]
  exact mul_le_mul_of_nonneg_left (abs_toReal_sub_le_one _) (by positivity)

theorem summable_localDist (A : ℕ → Set Config) (μ ν : Measure Config) [IsProbabilityMeasure μ]
    [IsProbabilityMeasure ν] :
    Summable (fun n : ℕ ↦ (2 : ℝ)⁻¹ ^ (n + 1) * |(μ (A n)).toReal - (ν (A n)).toReal|) :=
  Summable.of_nonneg_of_le (localDist_summand_nonneg A μ ν)
    (fun n ↦ localDist_summand_le A n) summable_geomHalf

theorem localDist_nonneg (A : ℕ → Set Config) (μ ν : Measure Config) : 0 ≤ localDist A μ ν :=
  tsum_nonneg (localDist_summand_nonneg A μ ν)

theorem localDist_self (A : ℕ → Set Config) (μ : Measure Config) : localDist A μ μ = 0 := by
  simp [localDist]

theorem localDist_comm (A : ℕ → Set Config) (μ ν : Measure Config) :
    localDist A μ ν = localDist A ν μ :=
  tsum_congr fun n ↦ by rw [abs_sub_comm]

theorem localDist_triangle (A : ℕ → Set Config) (μ ν ρ : Measure Config) [IsProbabilityMeasure μ]
    [IsProbabilityMeasure ν] [IsProbabilityMeasure ρ] :
    localDist A μ ρ ≤ localDist A μ ν + localDist A ν ρ := by
  rw [localDist, localDist, localDist,
    ← (summable_localDist A μ ν).tsum_add (summable_localDist A ν ρ)]
  refine (summable_localDist A μ ρ).tsum_le_tsum (fun n ↦ ?_)
    ((summable_localDist A μ ν).add (summable_localDist A ν ρ))
  rw [← mul_add]
  exact mul_le_mul_of_nonneg_left (abs_sub_le _ _ _) (by positivity)

theorem localDistSet_bddBelow (A : ℕ → Set Config) (F : Set (Measure Config))
    (ν : Measure Config) : BddBelow ((fun μ ↦ localDist A μ ν) '' F) := by
  refine ⟨0, ?_⟩
  rintro x ⟨μ, -, rfl⟩
  exact localDist_nonneg A μ ν

theorem localDistSet_nonneg (A : ℕ → Set Config) (F : Set (Measure Config)) (ν : Measure Config) :
    0 ≤ localDistSet A F ν := by
  rcases F.eq_empty_or_nonempty with rfl | hF
  · simp [localDistSet]
  · refine le_csInf (hF.image _) ?_
    rintro x ⟨μ, -, rfl⟩
    exact localDist_nonneg A μ ν

theorem localDistSet_le (A : ℕ → Set Config) {F : Set (Measure Config)} {μ ν : Measure Config}
    (hμ : μ ∈ F) : localDistSet A F ν ≤ localDist A μ ν :=
  csInf_le (localDistSet_bddBelow A F ν) (Set.mem_image_of_mem _ hμ)

/-! ### The bridge to the `GibbsMeasure` library

Everything in this namespace is auxiliary: it identifies the definitions above with those of the
`GibbsMeasure` library.  None of the statements of the challenge is touched. -/

namespace Bridge

open scoped ENNReal
open MeasureTheory.GibbsMeasure (isingPotential latticeGraph isingSpecification
  uniformSpinMeasure GP)

/-- The library's Ising potential on `ℤ²` with coupling `1` and no external field. -/
abbrev P : Potential Site Bool := isingPotential (latticeGraph 2) 1 0

lemma P_eq : P = Potential.nearestNeighbourPair (latticeGraph 2) 1 0
    MeasureTheory.GibbsMeasure.spin := rfl

lemma spin_eq : spin = MeasureTheory.GibbsMeasure.spin := rfl

/-! #### Unit vectors and nearest-neighbour bonds -/

lemma e_self (k : Fin 2) : e k k = 1 := by simp [e]

lemma e_of_ne {k l : Fin 2} (h : l ≠ k) : e k l = 0 := by simp [e, h]

lemma add_e_ne_self (i : Site) (k : Fin 2) : i + e k ≠ i := by
  intro h
  have h1 := congrFun h k
  rw [Pi.add_apply, e_self] at h1
  omega

lemma e_inj {k m : Fin 2} (h : e k = e m) : k = m := by
  by_contra hkm
  have h1 := congrFun h k
  rw [e_self, e_of_ne hkm] at h1
  exact one_ne_zero h1

lemma adj_add_e (i : Site) (k : Fin 2) : (latticeGraph 2).Adj i (i + e k) := by
  show ∑ l, (i l - (i + e k) l).natAbs = 1
  rw [Finset.sum_eq_single k]
  · have h1 : i k - (i + e k) k = -1 := by rw [Pi.add_apply, e_self]; ring
    rw [h1]
    rfl
  · intro l _ hl
    have h1 : i l - (i + e k) l = 0 := by rw [Pi.add_apply, e_of_ne hl]; ring
    rw [h1]
    rfl
  · intro h
    exact absurd (Finset.mem_univ k) h

lemma adj_decomp {i j : Site} (h : (latticeGraph 2).Adj i j) :
    ∃ k : Fin 2, j = i + e k ∨ i = j + e k := by
  classical
  have h1 : ∑ l, (i l - j l).natAbs = 1 := h
  obtain ⟨k, -, hk⟩ := Finset.exists_ne_zero_of_sum_ne_zero
    (by rw [h1]; exact one_ne_zero)
  have hk1 : (i k - j k).natAbs = 1 := by
    have hle : (i k - j k).natAbs ≤ 1 := by
      rw [← h1]
      exact Finset.single_le_sum (f := fun l ↦ (i l - j l).natAbs)
        (fun l _ ↦ Nat.zero_le _) (Finset.mem_univ k)
    omega
  have herase : ∑ l ∈ Finset.univ.erase k, (i l - j l).natAbs = 0 := by
    have hadd := Finset.add_sum_erase Finset.univ (fun l ↦ (i l - j l).natAbs) (Finset.mem_univ k)
    omega
  have hrest : ∀ l, l ≠ k → j l = i l := by
    intro l hl
    have hle : (i l - j l).natAbs ≤ ∑ m ∈ Finset.univ.erase k, (i m - j m).natAbs :=
      Finset.single_le_sum (f := fun m ↦ (i m - j m).natAbs) (fun m _ ↦ Nat.zero_le _)
        (Finset.mem_erase.2 ⟨hl, Finset.mem_univ l⟩)
    omega
  refine ⟨k, ?_⟩
  rcases (by omega : j k = i k + 1 ∨ i k = j k + 1) with hjk | hjk
  · refine Or.inl (funext fun l ↦ ?_)
    by_cases hl : l = k
    · subst hl
      rw [Pi.add_apply, e_self, hjk]
    · rw [Pi.add_apply, e_of_ne hl, add_zero, hrest l hl]
  · refine Or.inr (funext fun l ↦ ?_)
    by_cases hl : l = k
    · subst hl
      rw [Pi.add_apply, e_self, hjk]
    · rw [Pi.add_apply, e_of_ne hl, add_zero, (hrest l hl).symm]

lemma pair_eq_pair {a b : Site} {k m : Fin 2}
    (h : ({a, a + e k} : Finset Site) = {b, b + e m}) : a = b ∧ k = m := by
  have ha : a ∈ ({b, b + e m} : Finset Site) := by
    rw [← h]; exact Finset.mem_insert_self _ _
  have hak : a + e k ∈ ({b, b + e m} : Finset Site) := by
    rw [← h]; exact Finset.mem_insert_of_mem (Finset.mem_singleton_self _)
  rcases Finset.mem_insert.1 ha with rfl | ha'
  · rcases Finset.mem_insert.1 hak with h1 | h1
    · exact absurd h1 (add_e_ne_self a k)
    · rw [Finset.mem_singleton] at h1
      exact ⟨rfl, e_inj (add_left_cancel h1)⟩
  · rw [Finset.mem_singleton] at ha'
    rcases Finset.mem_insert.1 hak with h1 | h1
    · exfalso
      have hz : e m + e k = 0 := by
        have h2 : b + (e m + e k) = b + 0 := by
          rw [← add_assoc, ← ha', h1, add_zero]
        exact add_left_cancel h2
      have h3 := congrFun hz k
      rw [Pi.add_apply, Pi.zero_apply, e_self] at h3
      rcases eq_or_ne k m with rfl | hkm
      · rw [e_self] at h3; omega
      · rw [e_of_ne hkm] at h3; omega
    · rw [Finset.mem_singleton] at h1
      exact absurd (h1.trans ha'.symm) (add_e_ne_self a k)

/-! #### The Hamiltonian -/

lemma P_pair (a : Site) (k : Fin 2) (σ : Config) :
    P {a, a + e k} σ = -(spin (σ a) * spin (σ (a + e k))) := by
  have hne : a ≠ a + e k := (add_e_ne_self a k).symm
  have hcard : ({a, a + e k} : Finset Site).card = 2 := Finset.card_pair hne
  have hadj : ∃ x ∈ ({a, a + e k} : Finset Site), ∃ y ∈ ({a, a + e k} : Finset Site),
      (latticeGraph 2).Adj x y :=
    ⟨a, Finset.mem_insert_self _ _, a + e k,
      Finset.mem_insert_of_mem (Finset.mem_singleton_self _), adj_add_e a k⟩
  rw [P_eq, Potential.nearestNeighbourPair_apply_pair ⟨hcard, hadj⟩, Finset.prod_pair hne,
    ← spin_eq]
  ring

lemma exists_pair_of_P_ne_zero {Δ : Finset Site} (h : P Δ ≠ 0) :
    ∃ (a : Site) (k : Fin 2), Δ = {a, a + e k} := by
  classical
  by_cases h1 : Δ.card = 1
  · exact absurd (funext fun η ↦ by
      rw [P_eq, Potential.nearestNeighbourPair_apply_card_one h1]
      simp) h
  by_cases h2 : Δ.card = 2 ∧ ∃ x ∈ Δ, ∃ y ∈ Δ, (latticeGraph 2).Adj x y
  · obtain ⟨hcard, x, hx, y, hy, hxy⟩ := h2
    have hne : x ≠ y := (latticeGraph 2).ne_of_adj hxy
    have hsub : ({x, y} : Finset Site) ⊆ Δ := by
      intro z hz
      rcases Finset.mem_insert.1 hz with rfl | hz
      · exact hx
      · rw [Finset.mem_singleton] at hz; exact hz ▸ hy
    have hΔ : Δ = {x, y} :=
      (Finset.eq_of_subset_of_card_le hsub
        (le_of_eq (by rw [hcard, Finset.card_pair hne]))).symm
    obtain ⟨k, hk | hk⟩ := adj_decomp hxy
    · exact ⟨x, k, by rw [hΔ, hk]⟩
    · exact ⟨y, k, by rw [hΔ, hk, Finset.pair_comm]⟩
  · exact absurd (funext fun η ↦ Potential.nearestNeighbourPair_apply_eq_zero (G := latticeGraph 2)
      (J := 1) (h := 0) (σ := MeasureTheory.GibbsMeasure.spin) h1 h2 η) h

lemma hamiltonian_P_eq (Λ : Finset Site) (σ : Config) :
    P.hamiltonian Λ σ = hamiltonian Λ σ := by
  classical
  have hmem : ∀ Δ ∈ (bonds Λ).image (fun p : Site × Fin 2 ↦ ({p.1, p.1 + e p.2} : Finset Site)),
      ((Δ : Set Site) ∩ (Λ : Set Site)).Nonempty := by
    intro Δ hΔ
    obtain ⟨p, hp, rfl⟩ := Finset.mem_image.1 hΔ
    rcases (mem_bonds Λ p.1 p.2).1 hp with hp' | hp'
    · exact ⟨p.1, by simp, by simpa using hp'⟩
    · exact ⟨p.1 + e p.2, by simp, by simpa using hp'⟩
  have hsub : Potential.interactingSupport (Φ := P) Λ ⊆
      (bonds Λ).image (fun p : Site × Fin 2 ↦ ({p.1, p.1 + e p.2} : Finset Site)) := by
    intro Δ hΔ
    obtain ⟨hne, hΦ⟩ := Potential.mem_interactingSupport.1 hΔ
    obtain ⟨a, k, rfl⟩ := exists_pair_of_P_ne_zero hΦ
    refine Finset.mem_image.2 ⟨(a, k), ?_, rfl⟩
    rw [mem_bonds]
    obtain ⟨x, hxΔ, hxΛ⟩ := hne
    have hxΔ' : x = a ∨ x = a + e k := by
      simpa using hxΔ
    rcases hxΔ' with rfl | rfl
    · exact Or.inl (by simpa using hxΛ)
    · exact Or.inr (by simpa using hxΛ)
  have hzero : ∀ Δ ∈ (bonds Λ).image (fun p : Site × Fin 2 ↦ ({p.1, p.1 + e p.2} : Finset Site)),
      Δ ∉ Potential.interactingSupport (Φ := P) Λ → P Δ σ = 0 := by
    intro Δ hΔ hΔ'
    have := Potential.mem_interactingSupport (Φ := P) (Λ := Λ) (Δ := Δ)
    have hPz : P Δ = 0 := by
      by_contra hc
      exact hΔ' (this.2 ⟨hmem Δ hΔ, hc⟩)
    exact congrFun hPz σ
  have hinj : ∀ p ∈ bonds Λ, ∀ q ∈ bonds Λ,
      ({p.1, p.1 + e p.2} : Finset Site) = {q.1, q.1 + e q.2} → p = q := by
    intro p _ q _ hpq
    obtain ⟨h1, h2⟩ := pair_eq_pair hpq
    exact Prod.ext h1 h2
  rw [Potential.hamiltonian_eq_interactingHamiltonian, Potential.interactingHamiltonian,
    Finset.sum_subset hsub hzero, Finset.sum_image hinj, hamiltonian,
    ← Finset.sum_neg_distrib]
  exact Finset.sum_congr rfl fun p _ ↦ P_pair p.1 p.2 σ

/-! #### The independent specification over the uniform spin measure -/

lemma glue_extend (Λ : Finset Site) (ζ : Λ → Bool) (ω : Config) :
    glue Λ (extend Λ ζ ω) ω = extend Λ ζ ω := by
  funext i
  by_cases h : i ∈ Λ <;> simp [glue, extend, h]

lemma juxt_eq_extend (Λ : Finset Site) (ω : Config) (ζ : Λ → Bool) :
    juxt (Λ : Set Site) ω ζ = extend Λ ζ ω := by
  funext i
  by_cases h : i ∈ Λ <;> simp [juxt, extend, h]

lemma uniformSpinMeasure_singleton (c : Bool) : uniformSpinMeasure {c} = 2⁻¹ := by
  show ((2 : ℝ≥0∞)⁻¹ • Measure.count) {c} = 2⁻¹
  rw [Measure.smul_apply, Measure.count_singleton, smul_eq_mul, mul_one]

lemma pi_uniform_singleton (Λ : Finset Site) (ζ : Λ → Bool) :
    (Measure.pi fun _ : Λ ↦ uniformSpinMeasure) {ζ} = (2 ^ Λ.card : ℝ≥0∞)⁻¹ := by
  rw [← Set.univ_pi_singleton ζ, Measure.pi_pi]
  simp only [uniformSpinMeasure_singleton, Finset.prod_const, Finset.card_univ, Fintype.card_coe]
  rw [← ENNReal.inv_pow]

lemma isssd_eq (Λ : Finset Site) (ω : Config) :
    Specification.isssd (S := Site) (E := Bool) uniformSpinMeasure Λ ω
      = Measure.map (juxt (Λ : Set Site) ω) (Measure.pi fun _ : Λ ↦ uniformSpinMeasure) := rfl

lemma lintegral_isssd (Λ : Finset Site) (ω : Config) {f : Config → ℝ≥0∞} (hf : Measurable f) :
    ∫⁻ y, f y ∂(Specification.isssd (S := Site) (E := Bool) uniformSpinMeasure Λ ω)
      = (2 ^ Λ.card : ℝ≥0∞)⁻¹ * ∑ ζ : Λ → Bool, f (extend Λ ζ ω) := by
  rw [isssd_eq, lintegral_map hf Measurable.juxt, lintegral_fintype, Finset.mul_sum]
  refine Finset.sum_congr rfl fun ζ _ ↦ ?_
  rw [pi_uniform_singleton, juxt_eq_extend, mul_comm]

/-! #### Identification of the finite-volume kernels -/

lemma inv_mul_cancel_aux {c s x : ℝ≥0∞} (hc0 : c ≠ 0) (hct : c ≠ ⊤) :
    (c * s)⁻¹ * (c * x) = s⁻¹ * x := by
  rw [ENNReal.mul_inv (Or.inl hc0) (Or.inl hct), mul_comm c⁻¹ s⁻¹, mul_assoc,
    ← mul_assoc c⁻¹ c x, ENNReal.inv_mul_cancel hc0 hct, one_mul]

lemma boltzmann_extend (β : ℝ) (Λ : Finset Site) (ω : Config) (ζ : Λ → Bool) :
    P.boltzmannFactor β Λ (extend Λ ζ ω) = ENNReal.ofReal (weight β Λ ω ζ) := by
  rw [Potential.boltzmannFactor, hamiltonian_P_eq, weight, glue_extend]

lemma gibbsMeasure_apply (β : ℝ) (Λ : Finset Site) (ω : Config) {A : Set Config}
    (hA : MeasurableSet A) :
    gibbsMeasure β Λ ω A
      = (∑ ζ : Λ → Bool, ENNReal.ofReal (weight β Λ ω ζ))⁻¹ *
        ∑ ζ : Λ → Bool,
          A.indicator (fun _ ↦ ENNReal.ofReal (weight β Λ ω ζ)) (extend Λ ζ ω) := by
  rw [gibbsMeasure, Measure.smul_apply, smul_eq_mul, Measure.finsetSum_apply, partitionFunction,
    ENNReal.ofReal_sum_of_nonneg (s := Finset.univ)
      (f := fun ζ : Λ → Bool ↦ weight β Λ ω ζ) (fun ζ _ ↦ (Real.exp_pos _).le)]
  refine congrArg _ (Finset.sum_congr rfl fun ζ _ ↦ ?_)
  rw [Measure.smul_apply, smul_eq_mul, Measure.dirac_apply' _ hA, glue_extend]
  by_cases hx : extend Λ ζ ω ∈ A
  · rw [Set.indicator_of_mem hx, Set.indicator_of_mem hx, Pi.one_apply, mul_one]
  · rw [Set.indicator_of_notMem hx, Set.indicator_of_notMem hx, mul_zero]

lemma spec_apply (β : ℝ) (Λ : Finset Site) (ω : Config) {A : Set Config} (hA : MeasurableSet A) :
    isingSpecification (latticeGraph 2) 1 0 β Λ ω A = gibbsMeasure β Λ ω A := by
  classical
  have hc0 : (2 ^ Λ.card : ℝ≥0∞)⁻¹ ≠ 0 := by simp
  have hct : (2 ^ Λ.card : ℝ≥0∞)⁻¹ ≠ ⊤ := by simp
  have hZ : Specification.premodifierZ (S := Site) (E := Bool) uniformSpinMeasure
      (P.boltzmannFactor β) Λ ω
      = (2 ^ Λ.card : ℝ≥0∞)⁻¹ * ∑ ζ : Λ → Bool, ENNReal.ofReal (weight β Λ ω ζ) := by
    rw [Specification.premodifierZ,
      lintegral_isssd Λ ω (Potential.measurable_boltzmannFactor (Φ := P) β Λ)]
    exact congrArg _ (Finset.sum_congr rfl fun ζ _ ↦ boltzmann_extend β Λ ω ζ)
  have hnum : ∫⁻ y in A, P.boltzmannFactor β Λ y
        ∂(Specification.isssd (S := Site) (E := Bool) uniformSpinMeasure Λ ω)
      = (2 ^ Λ.card : ℝ≥0∞)⁻¹ *
        ∑ ζ : Λ → Bool,
          A.indicator (fun _ ↦ ENNReal.ofReal (weight β Λ ω ζ)) (extend Λ ζ ω) := by
    rw [← lintegral_indicator hA,
      lintegral_isssd Λ ω
        ((Potential.measurable_boltzmannFactor (Φ := P) β Λ).indicator hA)]
    refine congrArg _ (Finset.sum_congr rfl fun ζ _ ↦ ?_)
    by_cases hx : extend Λ ζ ω ∈ A
    · rw [Set.indicator_of_mem hx, Set.indicator_of_mem hx]
      exact boltzmann_extend β Λ ω ζ
    · rw [Set.indicator_of_notMem hx, Set.indicator_of_notMem hx]
  rw [isingSpecification, Potential.gibbsSpecificationOfAbsolutelySummable,
    Specification.modification_apply,
    Specification.withDensity_premodifierNorm_apply uniformSpinMeasure
      (Potential.isPremodifier_boltzmannFactor (Φ := P) β) hA ω,
    hZ, hnum, gibbsMeasure_apply β Λ ω hA]
  exact inv_mul_cancel_aux hc0 hct

lemma spec_eq (β : ℝ) (Λ : Finset Site) (ω : Config) :
    isingSpecification (latticeGraph 2) 1 0 β Λ ω = gibbsMeasure β Λ ω :=
  Measure.ext fun _ hA ↦ spec_apply β Λ ω hA

/-! #### The DLR equation -/

lemma dlr_iff (β : ℝ) (μ : Measure Config) [IsProbabilityMeasure μ] :
    (∀ Λ : Finset Site, ∀ A : Set Config, MeasurableSet A →
        μ A = ∫⁻ ω, gibbsMeasure β Λ ω A ∂μ)
      ↔ Specification.IsGibbsMeasure (isingSpecification (latticeGraph 2) 1 0 β) μ := by
  rw [Specification.isGibbsMeasure_iff_forall_bind_eq_of_prob]
  constructor
  · intro h Λ
    refine Measure.ext fun A hA ↦ ?_
    rw [Measure.bind_apply hA
      (((isingSpecification (latticeGraph 2) 1 0 β Λ).measurable.mono
        cylinderEvents_le_pi le_rfl).aemeasurable)]
    calc ∫⁻ a, (isingSpecification (latticeGraph 2) 1 0 β Λ a) A ∂μ
        = ∫⁻ a, gibbsMeasure β Λ a A ∂μ := lintegral_congr fun a ↦ spec_apply β Λ a hA
      _ = μ A := (h Λ A hA).symm
  · intro h Λ A hA
    have h1 : μ.bind (isingSpecification (latticeGraph 2) 1 0 β Λ) A = μ A := by rw [h Λ]
    rw [Measure.bind_apply hA
      (((isingSpecification (latticeGraph 2) 1 0 β Λ).measurable.mono
        cylinderEvents_le_pi le_rfl).aemeasurable)] at h1
    calc μ A = ∫⁻ a, (isingSpecification (latticeGraph 2) 1 0 β Λ a) A ∂μ := h1.symm
      _ = ∫⁻ ω, gibbsMeasure β Λ ω A ∂μ := lintegral_congr fun a ↦ spec_apply β Λ a hA

lemma isGibbs_of_mem_GP (β : ℝ) (m : ProbabilityMeasure Config)
    (hm : m ∈ GP (S := Site) (E := Bool) (isingSpecification (latticeGraph 2) 1 0 β)) :
    IsGibbs β (m : Measure Config) :=
  ⟨inferInstance, (dlr_iff β (m : Measure Config)).2 hm⟩

lemma mem_GP_of_isGibbs (β : ℝ) (μ : Measure Config) (h : IsGibbs β μ) :
    (⟨μ, h.1⟩ : ProbabilityMeasure Config) ∈
      GP (S := Site) (E := Bool) (isingSpecification (latticeGraph 2) 1 0 β) := by
  have := h.1
  exact (dlr_iff β μ).1 h.2

/-! #### The lattice shifts and the spin flip -/

lemma shift_eq (j : Site) : (MeasureTheory.GibbsMeasure.shift Bool j).toFun = shift j :=
  funext fun ω ↦ funext fun i ↦ MeasureTheory.GibbsMeasure.shift_toFun_apply j ω i

lemma spinFlip_eq :
    MeasureTheory.GibbsMeasure.Peierls.spinFlip.toFun = fun (σ : Config) (i : Site) ↦ !σ i := rfl

end Bridge


/-! ### The bridge for the low-temperature limit

This namespace identifies Georgii's phases `μ_+^β`, `μ_-^β` with the library's `Peierls.plusPhase`
and `Peierls.minusPhase`, and transports the library's Peierls estimate
`μ_±^β(σ_a ≠ ω_a^±) ≤ r(β) → 0` to the challenge's from-scratch notions of local event, local
convergence and Georgii metric. -/

namespace LowTempBridge

open scoped ENNReal
open MeasureTheory.GibbsMeasure.Peierls (plusPhase minusPhase r
  plusPhase_mem_GP plusPhase_measurePreserving_shift plusPhase_real_ne_le
  minusPhase_mem_GP minusPhase_measurePreserving_shift minusPhase_real_ne_le
  tendsto_toReal_r_atTop)

/-- Georgii's plus phase `μ_+^β`, as a plain measure on the challenge's configuration space. -/
def muP (b : ℝ) : Measure Config := ((plusPhase b : ProbabilityMeasure Config) : Measure Config)

/-- Georgii's minus phase `μ_-^β = τ(μ_+^β)`, as a plain measure. -/
def muM (b : ℝ) : Measure Config := ((minusPhase b : ProbabilityMeasure Config) : Measure Config)

instance instIsProbabilityMeasureMuP (b : ℝ) : IsProbabilityMeasure (muP b) := (plusPhase b).2

instance instIsProbabilityMeasureMuM (b : ℝ) : IsProbabilityMeasure (muM b) := (minusPhase b).2

lemma muP_mem (b : ℝ) : muP b ∈ shiftInvariantGibbs b := by
  refine ⟨Bridge.isGibbs_of_mem_GP b (plusPhase b) (plusPhase_mem_GP b), fun j ↦ ?_⟩
  show Measure.map (shift j) (muP b) = muP b
  rw [← Bridge.shift_eq j]
  exact (plusPhase_measurePreserving_shift b j).map_eq

lemma muM_mem (b : ℝ) : muM b ∈ shiftInvariantGibbs b := by
  refine ⟨Bridge.isGibbs_of_mem_GP b (minusPhase b) (minusPhase_mem_GP b), fun j ↦ ?_⟩
  show Measure.map (shift j) (muM b) = muM b
  rw [← Bridge.shift_eq j]
  exact (minusPhase_measurePreserving_shift b j).map_eq

/-- Georgii's estimate `|μ_+^β(A) − δ_+(A)| ≤ |Λ| r(β)` for a local event `A`, together with
`r(β) → 0`, gives real-valued convergence `μ_+^β(A) → δ_+(A)`. -/
lemma tendsto_toReal_muP {A : Set Config} (hA : IsLocalEvent A) :
    Tendsto (fun b : ℝ ↦ (muP b A).toReal) atTop
      (𝓝 (((Measure.dirac fun _ : Site ↦ true) : Measure Config) A).toReal) := by
  obtain ⟨Λ, hΛ⟩ := hA
  have hAm : MeasurableSet A := GibbsChallenge.measurableSet_of_inside hΛ
  have hdep : ∀ ζ ζ' : Config, (∀ a ∈ Λ, ζ a = ζ' a) → (ζ ∈ A ↔ ζ' ∈ A) :=
    fun _ _ h ↦ GibbsChallenge.mem_iff_mem_of_inside hΛ h
  rw [tendsto_iff_dist_tendsto_zero]
  simp only [Real.dist_eq]
  refine squeeze_zero' (g := fun b : ℝ ↦ (Λ.card : ℝ) * (r b).toReal)
    (Eventually.of_forall fun _ ↦ abs_nonneg _) ?_ ?_
  · filter_upwards [eventually_ge_atTop (8 * Real.log 2)] with b hb
    exact abs_measureReal_sub_dirac_le (μ := muP b) (ω := fun _ : Site ↦ true)
      (c := (r b).toReal) (Λ := Λ) hAm hdep fun a _ ↦ plusPhase_real_ne_le hb a
  · simpa using tendsto_toReal_r_atTop.const_mul (Λ.card : ℝ)

/-- The same for the minus phase. -/
lemma tendsto_toReal_muM {A : Set Config} (hA : IsLocalEvent A) :
    Tendsto (fun b : ℝ ↦ (muM b A).toReal) atTop
      (𝓝 (((Measure.dirac fun _ : Site ↦ false) : Measure Config) A).toReal) := by
  obtain ⟨Λ, hΛ⟩ := hA
  have hAm : MeasurableSet A := GibbsChallenge.measurableSet_of_inside hΛ
  have hdep : ∀ ζ ζ' : Config, (∀ a ∈ Λ, ζ a = ζ' a) → (ζ ∈ A ↔ ζ' ∈ A) :=
    fun _ _ h ↦ GibbsChallenge.mem_iff_mem_of_inside hΛ h
  rw [tendsto_iff_dist_tendsto_zero]
  simp only [Real.dist_eq]
  refine squeeze_zero' (g := fun b : ℝ ↦ (Λ.card : ℝ) * (r b).toReal)
    (Eventually.of_forall fun _ ↦ abs_nonneg _) ?_ ?_
  · filter_upwards [eventually_ge_atTop (8 * Real.log 2)] with b hb
    exact abs_measureReal_sub_dirac_le (μ := muM b) (ω := fun _ : Site ↦ false)
      (c := (r b).toReal) (Λ := Λ) hAm hdep fun a _ ↦ minusPhase_real_ne_le hb a
  · simpa using tendsto_toReal_r_atTop.const_mul (Λ.card : ℝ)

/-- `μ_+^β → δ_+` locally, in the `ℝ≥0∞`-valued form of the preamble's `TendstoLocally`. -/
lemma tendsto_muP_apply {A : Set Config} (hA : IsLocalEvent A) :
    Tendsto (fun b : ℝ ↦ muP b A) atTop
      (𝓝 (((Measure.dirac fun _ : Site ↦ true) : Measure Config) A)) := by
  have h := tendsto_toReal_muP hA
  have hfun : (fun b : ℝ ↦ muP b A) = fun b : ℝ ↦ ENNReal.ofReal ((muP b A).toReal) := by
    funext b
    rw [ENNReal.ofReal_toReal (measure_ne_top (muP b) A)]
  rw [hfun, ← ENNReal.ofReal_toReal
    (measure_ne_top ((Measure.dirac fun _ : Site ↦ true) : Measure Config) A)]
  exact ENNReal.tendsto_ofReal h

/-- `μ_-^β → δ_-` locally. -/
lemma tendsto_muM_apply {A : Set Config} (hA : IsLocalEvent A) :
    Tendsto (fun b : ℝ ↦ muM b A) atTop
      (𝓝 (((Measure.dirac fun _ : Site ↦ false) : Measure Config) A)) := by
  have h := tendsto_toReal_muM hA
  have hfun : (fun b : ℝ ↦ muM b A) = fun b : ℝ ↦ ENNReal.ofReal ((muM b A).toReal) := by
    funext b
    rw [ENNReal.ofReal_toReal (measure_ne_top (muM b) A)]
  rw [hfun, ← ENNReal.ofReal_toReal
    (measure_ne_top ((Measure.dirac fun _ : Site ↦ false) : Measure Config) A)]
  exact ENNReal.tendsto_ofReal h

/-- Local convergence upgrades to convergence in Georgii's metric `d` of Remark (4.3)(3), by
dominated convergence for the series `∑ 2⁻ⁿ |·|`. -/
lemma tendsto_localDist_muP (A : ℕ → Set Config) (hA : ∀ n : ℕ, IsLocalEvent (A n)) :
    Tendsto (fun b : ℝ ↦ localDist A (muP b) (Measure.dirac fun _ : Site ↦ true))
      atTop (𝓝 0) := by
  have hterm : ∀ n : ℕ, Tendsto (fun b : ℝ ↦ (2 : ℝ)⁻¹ ^ (n + 1) *
      |(muP b (A n)).toReal -
        (((Measure.dirac fun _ : Site ↦ true) : Measure Config) (A n)).toReal|)
      atTop (𝓝 0) := by
    intro n
    have h2 : Tendsto (fun b : ℝ ↦ |(muP b (A n)).toReal -
        (((Measure.dirac fun _ : Site ↦ true) : Measure Config) (A n)).toReal|)
        atTop (𝓝 0) := by
      simpa only [Real.dist_eq] using tendsto_iff_dist_tendsto_zero.1 (tendsto_toReal_muP (hA n))
    simpa using h2.const_mul ((2 : ℝ)⁻¹ ^ (n + 1))
  have hbd : ∀ᶠ b : ℝ in atTop, ∀ n : ℕ, ‖(2 : ℝ)⁻¹ ^ (n + 1) *
      |(muP b (A n)).toReal -
        (((Measure.dirac fun _ : Site ↦ true) : Measure Config) (A n)).toReal|‖
      ≤ (2 : ℝ)⁻¹ ^ (n + 1) := by
    refine Eventually.of_forall fun b n ↦ ?_
    rw [Real.norm_eq_abs, abs_of_nonneg (localDist_summand_nonneg A (muP b) _ n)]
    exact localDist_summand_le (μ := muP b) (ν := (Measure.dirac fun _ : Site ↦ true)) A n
  simpa [localDist] using tendsto_tsum_of_dominated_convergence summable_geomHalf hterm hbd

/-- The same for the minus phase. -/
lemma tendsto_localDist_muM (A : ℕ → Set Config) (hA : ∀ n : ℕ, IsLocalEvent (A n)) :
    Tendsto (fun b : ℝ ↦ localDist A (muM b) (Measure.dirac fun _ : Site ↦ false))
      atTop (𝓝 0) := by
  have hterm : ∀ n : ℕ, Tendsto (fun b : ℝ ↦ (2 : ℝ)⁻¹ ^ (n + 1) *
      |(muM b (A n)).toReal -
        (((Measure.dirac fun _ : Site ↦ false) : Measure Config) (A n)).toReal|)
      atTop (𝓝 0) := by
    intro n
    have h2 : Tendsto (fun b : ℝ ↦ |(muM b (A n)).toReal -
        (((Measure.dirac fun _ : Site ↦ false) : Measure Config) (A n)).toReal|)
        atTop (𝓝 0) := by
      simpa only [Real.dist_eq] using tendsto_iff_dist_tendsto_zero.1 (tendsto_toReal_muM (hA n))
    simpa using h2.const_mul ((2 : ℝ)⁻¹ ^ (n + 1))
  have hbd : ∀ᶠ b : ℝ in atTop, ∀ n : ℕ, ‖(2 : ℝ)⁻¹ ^ (n + 1) *
      |(muM b (A n)).toReal -
        (((Measure.dirac fun _ : Site ↦ false) : Measure Config) (A n)).toReal|‖
      ≤ (2 : ℝ)⁻¹ ^ (n + 1) := by
    refine Eventually.of_forall fun b n ↦ ?_
    rw [Real.norm_eq_abs, abs_of_nonneg (localDist_summand_nonneg A (muM b) _ n)]
    exact localDist_summand_le (μ := muM b) (ν := (Measure.dirac fun _ : Site ↦ false)) A n
  simpa [localDist] using tendsto_tsum_of_dominated_convergence summable_geomHalf hterm hbd

end LowTempBridge

/-! ### The theorems -/

/-- **Georgii, Theorem (6.9), first assertion**, in the form produced by Georgii's proof: at low
temperature the shift-invariant Gibbs measures of the two-dimensional Ising ferromagnet are
attracted by the two ground states.

Explicitly, there are families `β ↦ μ₊^β` and `β ↦ μ₋^β` of *shift-invariant Gibbs measures* for
the two-dimensional Ising ferromagnet at inverse temperature `β` such that, as `β → ∞`,
`μ₊^β → δ₊` and `μ₋^β → δ₋` in the topology of local convergence (Georgii (4.2)), equivalently
`d(μ₊^β, δ₊) → 0` and `d(μ₋^β, δ₋) → 0` for Georgii's metric `d` of Remark (4.3)(3) — here for
*every* metric obtained from a sequence of local events, in particular for every enumeration of
the algebra `𝓕⁰`. -/
theorem ising_low_temperature_limit :
    ∃ μp μm : ℝ → Measure Config,
      (∀ β : ℝ, μp β ∈ shiftInvariantGibbs β) ∧
      (∀ β : ℝ, μm β ∈ shiftInvariantGibbs β) ∧
      TendstoLocally μp atTop (Measure.dirac fun _ : Site ↦ true) ∧
      TendstoLocally μm atTop (Measure.dirac fun _ : Site ↦ false) ∧
      (∀ A : ℕ → Set Config, (∀ n : ℕ, IsLocalEvent (A n)) →
        Tendsto (fun β : ℝ ↦ localDist A (μp β) (Measure.dirac fun _ : Site ↦ true))
            atTop (𝓝 0) ∧
          Tendsto (fun β : ℝ ↦ localDist A (μm β) (Measure.dirac fun _ : Site ↦ false))
            atTop (𝓝 0)) := by
  refine ⟨LowTempBridge.muP, LowTempBridge.muM, LowTempBridge.muP_mem, LowTempBridge.muM_mem,
    fun _ hA ↦ LowTempBridge.tendsto_muP_apply hA,
    fun _ hA ↦ LowTempBridge.tendsto_muM_apply hA,
    fun A hA ↦ ⟨LowTempBridge.tendsto_localDist_muP A hA,
      LowTempBridge.tendsto_localDist_muM A hA⟩⟩

/-- **Georgii, Theorem (6.9), first assertion**, in the displayed form
`lim_{β → ∞} d(𝒢_Θ(βΦ), δ₊) = lim_{β → ∞} d(𝒢_Θ(βΦ), δ₋) = 0`,
where `d` is Georgii's metric of Remark (4.3)(3) for the topology of local convergence — built
here from an arbitrary sequence `A` of local events, so that the statement covers every such
metric — and `𝒢_Θ(βΦ)` is the set of shift-invariant Gibbs measures of the two-dimensional Ising
ferromagnet at inverse temperature `β`. -/
theorem ising_low_temperature_localDistSet (A : ℕ → Set Config)
    (hA : ∀ n : ℕ, IsLocalEvent (A n)) :
    Tendsto (fun β : ℝ ↦ localDistSet A (shiftInvariantGibbs β)
        (Measure.dirac fun _ : Site ↦ true)) atTop (𝓝 0) ∧
      Tendsto (fun β : ℝ ↦ localDistSet A (shiftInvariantGibbs β)
        (Measure.dirac fun _ : Site ↦ false)) atTop (𝓝 0) := by
  obtain ⟨μp, μm, hp, hm, -, -, hd⟩ := ising_low_temperature_limit
  obtain ⟨hdp, hdm⟩ := hd A hA
  exact ⟨squeeze_zero (fun _ ↦ localDistSet_nonneg A _ _) (fun b ↦ localDistSet_le A (hp b)) hdp,
    squeeze_zero (fun _ ↦ localDistSet_nonneg A _ _) (fun b ↦ localDistSet_le A (hm b)) hdm⟩

end IsingChallenge

end
