/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/
module

public import GibbsMeasure.Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
public import Mathlib.MeasureTheory.Integral.Lebesgue.Countable
public import Mathlib.Probability.ConditionalProbability

/-!
# Conditional expectation given a countable-valued random variable

If `Y : Ω → β` takes values in a countable measurable space with measurable singletons, the
σ-algebra `MeasurableSpace.comap Y` it generates is *atomic*: its atoms are the fibres
`Y ⁻¹' {b}`. Conditioning on it is therefore elementary — no Radon–Nikodym theorem is involved —
and the conditional expectation of an indicator is the elementary conditional probability:

`μ[1_A | σ(Y)](ω) = μ(A ∩ {Y = Y ω}) / μ({Y = Y ω})`.

The convention `0 / 0 = 0` of `ℝ≥0∞` takes care of the null fibres, which form a `μ`-null set
anyway.

## Main declarations

* `MeasureTheory.toReal_measure_inter_fibre_div_ae_eq_condExp_indicator`: the displayed identity.
* `MeasureTheory.condExp_indicator_comap_ae_eq_toReal_cond`: the same statement written with
  `ProbabilityTheory.cond`, `μ[1_A | σ(Y)](ω) = μ[A | {Y = Y ω}]`.
-/

@[expose] public section

open Set
open scoped ENNReal

namespace MeasureTheory

variable {Ω β : Type*} [MeasurableSpace Ω] [MeasurableSpace β] [Countable β]
  [MeasurableSingletonClass β] {μ : Measure Ω} [IsFiniteMeasure μ] {Y : Ω → β}

/-- **Conditioning on a countable-valued random variable.** The conditional expectation of the
indicator of a measurable set `A` given the σ-algebra generated by a measurable `Y : Ω → β` with
`β` countable is the elementary conditional probability of `A` given the fibre of `Y` through the
sample point.

The proof only uses that every `σ(Y)`-measurable set is a countable disjoint union of fibres
`Y ⁻¹' {b}`, on each of which both sides integrate to `μ (A ∩ Y ⁻¹' {b})`. -/
theorem toReal_measure_inter_fibre_div_ae_eq_condExp_indicator (hY : Measurable Y) {A : Set Ω}
    (hA : MeasurableSet A) :
    (fun ω ↦ (μ (A ∩ Y ⁻¹' {Y ω}) / μ (Y ⁻¹' {Y ω})).toReal)
      =ᵐ[μ] μ[A.indicator (1 : Ω → ℝ) | MeasurableSpace.comap Y inferInstance] := by
  classical
  set h : β → ℝ≥0∞ := fun b ↦ μ (A ∩ Y ⁻¹' {b}) / μ (Y ⁻¹' {b}) with hh_def
  have hm : MeasurableSpace.comap Y (inferInstance : MeasurableSpace β)
      ≤ (inferInstance : MeasurableSpace Ω) := measurable_iff_comap_le.1 hY
  have hYm : Measurable[MeasurableSpace.comap Y inferInstance] Y :=
    measurable_iff_comap_le.2 le_rfl
  have hgm : Measurable[MeasurableSpace.comap Y inferInstance] fun ω ↦ h (Y ω) :=
    (measurable_of_countable h).comp hYm
  have hfibre : ∀ b : β, MeasurableSet (Y ⁻¹' {b}) := fun b ↦ hY (measurableSet_singleton b)
  -- The elementary conditional probability is bounded by `1`.
  have hle1 : ∀ b : β, h b ≤ 1 := fun b ↦
    ENNReal.div_le_of_le_mul (by rw [one_mul]; exact measure_mono inter_subset_right)
  refine toReal_ae_eq_indicator_condExp_of_forall_setLIntegral_eq hm hA
    hgm.aestronglyMeasurable (fun t ht _ ↦ ?_) (fun t ht _ ↦ ?_)
  · refine ne_top_of_le_ne_top (measure_ne_top μ t) ?_
    calc ∫⁻ a in t, h (Y a) ∂μ ≤ ∫⁻ _ in t, 1 ∂μ := lintegral_mono fun a ↦ hle1 (Y a)
      _ = μ t := by simp
  -- Every `σ(Y)`-measurable set is a preimage; both sides sum the fibre masses over it.
  · obtain ⟨B, hB, rfl⟩ := ht
    have key : ∀ b : β, B.indicator h b * μ (Y ⁻¹' {b})
        = B.indicator (1 : β → ℝ≥0∞) b * μ (Y ⁻¹' {b} ∩ A) := by
      intro b
      by_cases hbB : b ∈ B
      · rw [indicator_of_mem hbB, indicator_of_mem hbB, Pi.one_apply, one_mul, hh_def,
          ENNReal.div_mul_cancel'
            (fun h0 ↦ measure_mono_null inter_subset_right h0)
            (fun htop ↦ absurd htop (measure_ne_top μ _)), inter_comm]
      · rw [indicator_of_notMem hbB, indicator_of_notMem hbB, zero_mul, zero_mul]
    calc ∫⁻ a in Y ⁻¹' B, h (Y a) ∂μ
        = ∫⁻ a, (B.indicator h) (Y a) ∂μ := by
          rw [← lintegral_indicator (hY hB)]
          exact lintegral_congr fun a ↦
            (Set.indicator_comp_right Y (s := B) (g := h) (x := a)).symm
      _ = ∫⁻ b, B.indicator h b ∂(μ.map Y) :=
          (lintegral_map (measurable_of_countable _) hY).symm
      _ = ∑' b, B.indicator h b * μ (Y ⁻¹' {b}) := by
          rw [lintegral_countable']
          exact tsum_congr fun b ↦ by rw [Measure.map_apply hY (measurableSet_singleton b)]
      _ = ∑' b, B.indicator (1 : β → ℝ≥0∞) b * ((μ.restrict A).map Y) {b} := by
          refine tsum_congr fun b ↦ (key b).trans ?_
          rw [Measure.map_apply hY (measurableSet_singleton b),
            Measure.restrict_apply (hfibre b)]
      _ = ∫⁻ b, B.indicator (1 : β → ℝ≥0∞) b ∂((μ.restrict A).map Y) :=
          (lintegral_countable' _).symm
      _ = ((μ.restrict A).map Y) B := lintegral_indicator_one hB
      _ = μ (A ∩ Y ⁻¹' B) := by
          rw [Measure.map_apply hY hB, Measure.restrict_apply (hY hB), inter_comm]

/-- **Conditioning on a countable-valued random variable**, in the language of
`ProbabilityTheory.cond`: `μ[1_A | σ(Y)](ω) = μ[A | Y = Y ω]`. -/
theorem condExp_indicator_comap_ae_eq_toReal_cond (hY : Measurable Y) {A : Set Ω}
    (hA : MeasurableSet A) :
    μ[A.indicator (1 : Ω → ℝ) | MeasurableSpace.comap Y inferInstance]
      =ᵐ[μ] fun ω ↦ (ProbabilityTheory.cond μ (Y ⁻¹' {Y ω}) A).toReal := by
  refine (toReal_measure_inter_fibre_div_ae_eq_condExp_indicator hY hA).symm.trans
    (Filter.Eventually.of_forall fun ω ↦ ?_)
  change (μ (A ∩ Y ⁻¹' {Y ω}) / μ (Y ⁻¹' {Y ω})).toReal
    = (ProbabilityTheory.cond μ (Y ⁻¹' {Y ω}) A).toReal
  rw [ProbabilityTheory.cond_apply' hA, ENNReal.div_eq_inv_mul, inter_comm]

end MeasureTheory

end
