/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/
module

public import Mathlib.Algebra.Group.Action.Pointwise.Finset
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import Mathlib.MeasureTheory.Group.FoelnerFilter
public import Mathlib.MeasureTheory.Measure.Count

/-!
# Følner sequences for abelian groups

Mathlib defines `IsAddFoelner G μ l F` for an additive group acting on a measure space, but
provides no group for which a Følner net exists. This file supplies the basic source of
examples: **every abelian group is amenable**, in the combinatorial form that for every finite
set `s` of group elements and every `ε > 0` there is a non-empty finite `F` with
`|(g + F) ∆ F| ≤ ε |F|` for all `g ∈ s`; for a countable abelian group this assembles into a
Følner *sequence*.

## Main definitions

* `Finset.transDist F x = |(x + F) ∆ F|`, the number of points of `F` displaced by translating
  by `x`, symmetrised. It is subadditive, symmetric and vanishes at `0`, so it behaves like the
  distance from `x` to the stabiliser of `F`.
* `Finset.cosetSlices a M X = ⋃_{k < M} (k • a + X k)`, the finite set obtained by placing `X k`
  in the `k`-th coset of a subgroup along `a`. This is the inductive step of the construction.

## Main results

* `AddCommGroup.exists_finset_transDist_le`: the ε-form of the Følner property, for an arbitrary
  abelian group and an arbitrary finite set of directions.
* `AddCommGroup.exists_foelner_seq`: a Følner sequence for a countable abelian group.
* `AddCommGroup.exists_isAddFoelner_count`: the same statement in Mathlib's `IsAddFoelner` form,
  for the translation action of `G` on itself with the counting measure.
* `AddCommGroup.exists_invariant_finitelyAdditive`: consequently a countable abelian group carries
  a translation-invariant finitely additive probability measure.
* `isFoelner_count_iff` / `isAddFoelner_count_iff`: for a net of finite sets in any group,
  Mathlib's `IsFoelner` with the counting measure is the elementary condition
  `|(g • F i) ∆ F i| / |F i| → 0` plus eventual non-emptiness.
* `countable_of_tendsto_card_smul_symmDiff_div_card`: a group with a Følner net of non-empty finite
  sets along a countably generated filter (e.g. a Følner sequence) is countable.

The construction is the classical one: enumerate the group, and grow a box one generator at a
time. Adding a generator `a` to a set `F` contained in the subgroup `H` generated by the previous
ones replaces `F` by `⋃_{k < M} (k • a + F)`, where `M` is the order of `a` in `G ⧸ H` if that is
finite and is chosen large otherwise. The slices lie in distinct cosets, so cardinalities add;
this preserves the ratios already achieved and makes the new one small.
-/

@[expose] public section

open Filter Finset MeasureTheory Set
open scoped ENNReal Pointwise symmDiff Topology

namespace Finset
variable {G : Type*} [AddCommGroup G] [DecidableEq G]

/-! ### The translation displacement `|(x + F) ∆ F|` -/

/-- The number of points of `F` displaced by translation by `x`, symmetrised:
`|(x + F) ∆ F|`. Følner's condition asks it to be small compared to `|F|`. -/
def transDist (F : Finset G) (x : G) : ℕ := ((x +ᵥ F) ∆ F).card

lemma transDist_def (F : Finset G) (x : G) : F.transDist x = ((x +ᵥ F) ∆ F).card := rfl

@[simp] lemma transDist_zero (F : Finset G) : F.transDist 0 = 0 := by
  simp [transDist]

lemma transDist_le_two_mul_card (F : Finset G) (x : G) : F.transDist x ≤ 2 * F.card := by
  refine (card_le_card (symmDiff_subset_union ..)).trans ?_
  refine (card_union_le _ _).trans ?_
  simp [card_vadd_finset, two_mul]

lemma transDist_add_le (F : Finset G) (x y : G) :
    F.transDist (x + y) ≤ F.transDist x + F.transDist y := by
  have hsub : ((x + y) +ᵥ F) ∆ F ⊆ (((x + y) +ᵥ F) ∆ (x +ᵥ F)) ∪ ((x +ᵥ F) ∆ F) :=
    symmDiff_triangle _ _ _
  have hxy : ((x + y) +ᵥ F) ∆ (x +ᵥ F) = x +ᵥ ((y +ᵥ F) ∆ F) := by
    rw [vadd_finset_symmDiff, ← add_vadd]
  calc F.transDist (x + y) ≤ ((((x + y) +ᵥ F) ∆ (x +ᵥ F)) ∪ ((x +ᵥ F) ∆ F)).card :=
        card_le_card hsub
    _ ≤ (((x + y) +ᵥ F) ∆ (x +ᵥ F)).card + ((x +ᵥ F) ∆ F).card := card_union_le _ _
    _ = F.transDist y + F.transDist x := by rw [hxy, card_vadd_finset]; rfl
    _ = F.transDist x + F.transDist y := Nat.add_comm _ _

@[simp] lemma transDist_neg (F : Finset G) (x : G) : F.transDist (-x) = F.transDist x := by
  have h : ((-x) +ᵥ F) ∆ F = (-x) +ᵥ (F ∆ (x +ᵥ F)) := by
    rw [vadd_finset_symmDiff, ← add_vadd]
    simp
  rw [transDist, h, card_vadd_finset, symmDiff_comm]
  rfl

lemma transDist_nsmul_le (F : Finset G) (n : ℕ) (x : G) :
    F.transDist (n • x) ≤ n * F.transDist x := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [succ_nsmul, Nat.succ_mul]
    exact (F.transDist_add_le _ _).trans (Nat.add_le_add_right ih _)

lemma transDist_zsmul_le (F : Finset G) (n : ℤ) (x : G) :
    F.transDist (n • x) ≤ n.natAbs * F.transDist x := by
  obtain ⟨m, rfl | rfl⟩ := n.eq_nat_or_neg
  · rw [natCast_zsmul]
    simpa using F.transDist_nsmul_le m x
  · rw [neg_zsmul, natCast_zsmul, transDist_neg]
    simpa using F.transDist_nsmul_le m x

lemma transDist_sum_le (F : Finset G) {ι : Type*} (s : Finset ι) (g : ι → G) :
    F.transDist (∑ i ∈ s, g i) ≤ ∑ i ∈ s, F.transDist (g i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert a s ha ih =>
    rw [Finset.sum_insert ha, Finset.sum_insert ha]
    exact (F.transDist_add_le _ _).trans (Nat.add_le_add_left ih _)

/-! ### Slices along the cosets of a subgroup -/

/-- `⋃_{k < M} (k • a + X k)`: the finite sets `X k` placed in the successive cosets `k • a + H`
of a subgroup `H` along an element `a`. -/
def cosetSlices (a : G) (M : ℕ) (X : ℕ → Finset G) : Finset G :=
  (Finset.range M).biUnion fun k ↦ (k • a) +ᵥ X k

lemma mem_vadd_finset_iff_sub_mem {F : Finset G} {c y : G} : y ∈ c +ᵥ F ↔ y - c ∈ F := by
  simp only [mem_vadd_finset, vadd_eq_add]
  exact ⟨by rintro ⟨z, hz, rfl⟩; simpa using hz, fun h ↦ ⟨y - c, h, by abel⟩⟩

lemma mem_cosetSlices {a : G} {M : ℕ} {X : ℕ → Finset G} {y : G} :
    y ∈ cosetSlices a M X ↔ ∃ k < M, y - k • a ∈ X k := by
  simp [cosetSlices, mem_vadd_finset_iff_sub_mem]

variable {H : AddSubgroup G} {a : G} {M : ℕ} {X Y : ℕ → Finset G}

omit [DecidableEq G] in
/-- If no `j • a` with `0 < j < M` lies in `H`, the slices of `cosetSlices a M X` lie in pairwise
distinct cosets of `H`, so the index of a point is determined. -/
lemma cosetSlices_index_unique (hM : ∀ j, 0 < j → j < M → j • a ∉ H)
    (hX : ∀ k, ↑(X k) ⊆ (H : Set G)) (hY : ∀ k, ↑(Y k) ⊆ (H : Set G)) {y : G} {k k' : ℕ}
    (hk : k < M) (hk' : k' < M) (h : y - k • a ∈ X k) (h' : y - k' • a ∈ Y k') : k = k' := by
  have key : ∀ p q : ℕ, p < q → q < M → y - p • a ∈ H → y - q • a ∈ H → False := by
    intro p q hpq hq hp' hq'
    have hsub : (q - p) • a ∈ H := by
      have : (q - p) • a = (y - p • a) - (y - q • a) := by
        have hqp : (q - p) • a + p • a = q • a := by
          rw [← add_nsmul, Nat.sub_add_cancel hpq.le]
        have : (q - p) • a = q • a - p • a := by
          rw [← hqp]; abel
        rw [this]; abel
      rw [this]
      exact AddSubgroup.sub_mem _ hp' hq'
    exact hM _ (by omega) (by omega) hsub
  have hxH : y - k • a ∈ H := hX k h
  have hyH : y - k' • a ∈ H := hY k' h'
  rcases lt_trichotomy k k' with hlt | heq | hgt
  · exact absurd (key k k' hlt hk' hxH hyH) (by simp)
  · exact heq
  · exact absurd (key k' k hgt hk hyH hxH) (by simp)

lemma card_cosetSlices (hM : ∀ j, 0 < j → j < M → j • a ∉ H)
    (hX : ∀ k, ↑(X k) ⊆ (H : Set G)) :
    (cosetSlices a M X).card = ∑ k ∈ Finset.range M, (X k).card := by
  rw [cosetSlices, Finset.card_biUnion]
  · exact Finset.sum_congr rfl fun k _ ↦ card_vadd_finset _ _
  · intro k hk k' hk' hne
    simp only [Function.onFun]
    rw [Finset.disjoint_left]
    intro y hy hy'
    rw [mem_vadd_finset_iff_sub_mem] at hy hy'
    exact hne (cosetSlices_index_unique hM hX hX (Finset.mem_range.1 hk) (Finset.mem_range.1 hk')
      hy hy')

lemma cosetSlices_symmDiff (hM : ∀ j, 0 < j → j < M → j • a ∉ H)
    (hX : ∀ k, ↑(X k) ⊆ (H : Set G)) (hY : ∀ k, ↑(Y k) ⊆ (H : Set G)) :
    (cosetSlices a M X) ∆ (cosetSlices a M Y) = cosetSlices a M fun k ↦ X k ∆ Y k := by
  ext y
  simp only [Finset.mem_symmDiff, mem_cosetSlices]
  constructor
  · rintro (⟨⟨k, hk, hkx⟩, hny⟩ | ⟨⟨k, hk, hky⟩, hnx⟩)
    · exact ⟨k, hk, Or.inl ⟨hkx, fun hc ↦ hny ⟨k, hk, hc⟩⟩⟩
    · exact ⟨k, hk, Or.inr ⟨hky, fun hc ↦ hnx ⟨k, hk, hc⟩⟩⟩
  · rintro ⟨k, hk, (⟨hkx, hky⟩ | ⟨hky, hkx⟩)⟩
    · refine Or.inl ⟨⟨k, hk, hkx⟩, ?_⟩
      rintro ⟨k', hk', hk'y⟩
      exact hky (cosetSlices_index_unique hM hX hY hk hk' hkx hk'y ▸ hk'y)
    · refine Or.inr ⟨⟨k, hk, hky⟩, ?_⟩
      rintro ⟨k', hk', hk'x⟩
      exact hkx (cosetSlices_index_unique hM hY hX hk hk' hky hk'x ▸ hk'x)

lemma vadd_cosetSlices (h : G) (a : G) (M : ℕ) (X : ℕ → Finset G) :
    h +ᵥ cosetSlices a M X = cosetSlices a M fun k ↦ h +ᵥ X k := by
  ext y
  simp only [mem_vadd_finset_iff_sub_mem, mem_cosetSlices]
  exact exists_congr fun k ↦ and_congr_right fun _ ↦ by rw [sub_right_comm]

/-- Translating by `a` cycles the slices: the top slice `M • a + X (M - 1)` lands back in the
subgroup, as slice `0`. -/
lemma vadd_self_cosetSlices (hM0 : 0 < M) (h0 : Y 0 = (M • a) +ᵥ X (M - 1))
    (hk : ∀ k, 0 < k → k < M → Y k = X (k - 1)) :
    a +ᵥ cosetSlices a M X = cosetSlices a M Y := by
  ext y
  simp only [mem_vadd_finset_iff_sub_mem, mem_cosetSlices]
  constructor
  · rintro ⟨j, hj, hmem⟩
    have hy : y - (j + 1) • a ∈ X j := by
      have he : y - (j + 1) • a = y - a - j • a := by rw [succ_nsmul]; abel
      rw [he]; exact hmem
    rcases Nat.lt_or_ge (j + 1) M with hj' | hj'
    · refine ⟨j + 1, hj', ?_⟩
      rw [hk _ (Nat.succ_pos j) hj', show j.succ - 1 = j from rfl]
      exact hy
    · have hjM : j + 1 = M := by omega
      refine ⟨0, hM0, ?_⟩
      rw [h0, mem_vadd_finset_iff_sub_mem, show M - 1 = j by omega, ← hjM]
      have he : y - (0 : ℕ) • a - (j + 1) • a = y - (j + 1) • a := by simp
      rw [he]
      exact hy
  · rintro ⟨k, hk', hmem⟩
    rcases Nat.eq_zero_or_pos k with rfl | hk0
    · rw [h0, mem_vadd_finset_iff_sub_mem] at hmem
      refine ⟨M - 1, by omega, ?_⟩
      have he : y - a - (M - 1) • a = y - (0 : ℕ) • a - M • a := by
        have : (M - 1) • a + a = M • a := by rw [← succ_nsmul]; congr 1; omega
        rw [← this]; simp; abel
      rw [he]
      exact hmem
    · rw [hk _ hk0 hk'] at hmem
      refine ⟨k - 1, by omega, ?_⟩
      have he : y - a - (k - 1) • a = y - k • a := by
        have : (k - 1) • a + a = k • a := by rw [← succ_nsmul]; congr 1; omega
        rw [← this]; abel
      rw [he]
      exact hmem

lemma cosetSlices_succ (hY : ∀ k, k < M → Y k = X k) (hYM : Y M = ∅) :
    cosetSlices a M X = cosetSlices a (M + 1) Y := by
  ext y
  simp only [mem_cosetSlices]
  constructor
  · rintro ⟨k, hk, hmem⟩
    exact ⟨k, by omega, by rw [hY k hk]; exact hmem⟩
  · rintro ⟨k, hk, hmem⟩
    rcases Nat.lt_or_ge k M with hkM | hkM
    · exact ⟨k, hkM, by rw [hY k hkM] at hmem; exact hmem⟩
    · rw [show k = M by omega, hYM] at hmem
      exact absurd hmem (Finset.notMem_empty _)

lemma vadd_self_cosetSlices_succ (hY0 : Y 0 = ∅)
    (hYk : ∀ k, 0 < k → k < M + 1 → Y k = X (k - 1)) :
    a +ᵥ cosetSlices a M X = cosetSlices a (M + 1) Y := by
  ext y
  simp only [mem_vadd_finset_iff_sub_mem, mem_cosetSlices]
  constructor
  · rintro ⟨j, hj, hmem⟩
    refine ⟨j + 1, by omega, ?_⟩
    rw [hYk _ (Nat.succ_pos j) (by omega), show j.succ - 1 = j from rfl]
    have he : y - (j + 1) • a = y - a - j • a := by rw [succ_nsmul]; abel
    rw [he]
    exact hmem
  · rintro ⟨k, hk, hmem⟩
    rcases Nat.eq_zero_or_pos k with rfl | hk0
    · rw [hY0] at hmem
      exact absurd hmem (Finset.notMem_empty _)
    · rw [hYk _ hk0 hk] at hmem
      refine ⟨k - 1, by omega, ?_⟩
      have he : y - a - (k - 1) • a = y - k • a := by
        have : (k - 1) • a + a = k • a := by rw [← succ_nsmul]; congr 1; omega
        rw [← this]; abel
      rw [he]
      exact hmem

/-! ### Growing a Følner set by one generator -/

lemma coe_vadd_finset_subset {F : Finset G} (hFH : ↑F ⊆ (H : Set G)) {c : G} (hc : c ∈ H) :
    ↑(c +ᵥ F) ⊆ (H : Set G) := by
  intro y hy
  rw [Finset.mem_coe, mem_vadd_finset_iff_sub_mem] at hy
  simpa using AddSubgroup.add_mem _ hc (hFH hy)

lemma card_cosetSlices_const {F : Finset G} (hM : ∀ j, 0 < j → j < M → j • a ∉ H)
    (hFH : ↑F ⊆ (H : Set G)) : (cosetSlices a M fun _ ↦ F).card = M * F.card := by
  rw [card_cosetSlices hM fun _ ↦ hFH, Finset.sum_const, Finset.card_range, smul_eq_mul]

lemma transDist_cosetSlices_const {F : Finset G} (hM : ∀ j, 0 < j → j < M → j • a ∉ H)
    (hFH : ↑F ⊆ (H : Set G)) {h : G} (hh : h ∈ H) :
    (cosetSlices a M fun _ ↦ F).transDist h = M * F.transDist h := by
  have hHF : ↑(h +ᵥ F) ⊆ (H : Set G) := coe_vadd_finset_subset hFH hh
  have hsymm : ∀ k : ℕ, ↑((h +ᵥ F) ∆ F) ⊆ (H : Set G) := fun _ ↦ by
    refine (Finset.coe_subset.2 (symmDiff_subset_union ..)).trans ?_
    rw [Finset.coe_union]
    exact Set.union_subset hHF hFH
  rw [transDist, vadd_cosetSlices, cosetSlices_symmDiff hM (fun _ ↦ hHF) (fun _ ↦ hFH),
    card_cosetSlices hM hsymm, Finset.sum_const, Finset.card_range, smul_eq_mul]
  rfl

lemma transDist_self_cosetSlices_const_of_mem {F : Finset G} (hM0 : 0 < M)
    (hM : ∀ j, 0 < j → j < M → j • a ∉ H) (hFH : ↑F ⊆ (H : Set G)) (hMa : M • a ∈ H) :
    (cosetSlices a M fun _ ↦ F).transDist a = F.transDist (M • a) := by
  classical
  set Y : ℕ → Finset G := fun k ↦ if k = 0 then (M • a) +ᵥ F else F with hYdef
  have hYH : ∀ k, ↑(Y k) ⊆ (H : Set G) := by
    intro k
    by_cases hk : k = 0
    · simpa [hYdef, hk] using coe_vadd_finset_subset hFH hMa
    · simpa [hYdef, hk] using hFH
  have hsymm : ∀ k, ↑(Y k ∆ F) ⊆ (H : Set G) := fun k ↦ by
    refine (Finset.coe_subset.2 (symmDiff_subset_union ..)).trans ?_
    rw [Finset.coe_union]
    exact Set.union_subset (hYH k) hFH
  have hvadd : a +ᵥ cosetSlices a M (fun _ ↦ F) = cosetSlices a M Y :=
    vadd_self_cosetSlices hM0 (by simp [hYdef]) fun k hk0 _ ↦ by simp [hYdef, hk0.ne']
  rw [transDist, hvadd, cosetSlices_symmDiff hM hYH (fun _ ↦ hFH), card_cosetSlices hM hsymm,
    Finset.sum_eq_single_of_mem 0 (Finset.mem_range.2 hM0) (fun k _ hk ↦ by simp [hYdef, hk])]
  simp [hYdef, transDist]

lemma transDist_self_cosetSlices_const_of_notMem {F : Finset G} (hM0 : 0 < M)
    (hFH : ↑F ⊆ (H : Set G)) (hna : ∀ j, 0 < j → j • a ∉ H) :
    (cosetSlices a M fun _ ↦ F).transDist a = 2 * F.card := by
  classical
  have hM' : ∀ j, 0 < j → j < M + 1 → j • a ∉ H := fun j hj _ ↦ hna j hj
  set Y : ℕ → Finset G := fun k ↦ if k = 0 then (∅ : Finset G) else F with hYdef
  set Z : ℕ → Finset G := fun k ↦ if k = M then (∅ : Finset G) else F with hZdef
  have hYH : ∀ k, ↑(Y k) ⊆ (H : Set G) := by
    intro k
    by_cases hk : k = 0
    · simp [hYdef, hk]
    · simpa [hYdef, hk] using hFH
  have hZH : ∀ k, ↑(Z k) ⊆ (H : Set G) := by
    intro k
    by_cases hk : k = M
    · simp [hZdef, hk]
    · simpa [hZdef, hk] using hFH
  have hsymm : ∀ k, ↑(Y k ∆ Z k) ⊆ (H : Set G) := fun k ↦ by
    refine (Finset.coe_subset.2 (symmDiff_subset_union ..)).trans ?_
    rw [Finset.coe_union]
    exact Set.union_subset (hYH k) (hZH k)
  have hvadd : a +ᵥ cosetSlices a M (fun _ ↦ F) = cosetSlices a (M + 1) Y :=
    vadd_self_cosetSlices_succ (by simp [hYdef]) fun k hk0 _ ↦ by simp [hYdef, hk0.ne']
  have hbase : cosetSlices a M (fun _ ↦ F) = cosetSlices a (M + 1) Z :=
    cosetSlices_succ (fun k hk ↦ by simp [hZdef, hk.ne]) (by simp [hZdef])
  rw [transDist, hvadd, hbase, cosetSlices_symmDiff hM' hYH hZH, card_cosetSlices hM' hsymm,
    Finset.sum_range_succ,
    Finset.sum_eq_single_of_mem 0 (Finset.mem_range.2 hM0) (fun k hk hk0 ↦ by
      simp [hYdef, hZdef, hk0, (Finset.mem_range.1 hk).ne])]
  have he1 : (∅ : Finset G) ∆ F = F := by rw [Finset.symmDiff_def]; simp
  have he2 : F ∆ (∅ : Finset G) = F := by rw [Finset.symmDiff_def]; simp
  simp [hYdef, hZdef, hM0.ne, hM0.ne', two_mul, he1, he2]

end Finset

namespace AddCommGroup

open Finset

variable {G : Type*} [AddCommGroup G] [DecidableEq G]

/-- **Every abelian group is amenable**, in the Følner form: given finitely many directions `s`
and `ε > 0` there is a non-empty finite set `F`, contained in the subgroup generated by `s`,
with `|(g + F) ∆ F| ≤ ε |F|` for every `g ∈ s`. -/
theorem exists_finset_transDist_le (s : Finset G) :
    ∀ ε : ℝ, 0 < ε → ∃ F : Finset G, F.Nonempty ∧
      ↑F ⊆ (AddSubgroup.closure (s : Set G) : Set G) ∧
      ∀ g ∈ s, (F.transDist g : ℝ) ≤ ε * F.card := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    intro ε hε
    exact ⟨{0}, ⟨0, Finset.mem_singleton_self 0⟩, by simp, by simp⟩
  | insert a s ha ih =>
    intro ε hε
    set H := AddSubgroup.closure (s : Set G) with hH
    have hmono : (H : Set G) ⊆
        (AddSubgroup.closure ((insert a s : Finset G) : Set G) : Set G) := by
      refine AddSubgroup.closure_mono ?_
      simp only [Finset.coe_insert]
      exact Set.subset_insert _ _
    have hacl : a ∈ AddSubgroup.closure ((insert a s : Finset G) : Set G) :=
      AddSubgroup.subset_closure (by simp)
    have hclosure : ∀ (M : ℕ) (F : Finset G), ↑F ⊆ (H : Set G) →
        ↑(cosetSlices a M fun _ ↦ F) ⊆
          (AddSubgroup.closure ((insert a s : Finset G) : Set G) : Set G) := by
      intro M F hFH y hy
      rw [Finset.mem_coe, mem_cosetSlices] at hy
      obtain ⟨k, -, hmem⟩ := hy
      have := AddSubgroup.add_mem _ (hmono (hFH hmem)) (AddSubgroup.nsmul_mem _ hacl k)
      simpa using this
    by_cases hex : ∃ d : ℕ, 0 < d ∧ d • a ∈ H
    · -- `a` has finite order `d` modulo `H`
      set d := Nat.find hex with hd
      have hd0 : 0 < d := (Nat.find_spec hex).1
      have hdH : d • a ∈ H := (Nat.find_spec hex).2
      have hdmin : ∀ j, 0 < j → j < d → j • a ∉ H := fun j hj hjd hjH ↦
        Nat.find_min hex hjd ⟨hj, hjH⟩
      have hspan : d • a ∈ Submodule.span ℤ (s : Set G) := by
        rw [← AddSubgroup.toIntSubmodule_closure]
        exact hdH
      obtain ⟨c, -, hc⟩ := Submodule.mem_span_finset.1 hspan
      set C : ℝ := 1 + ∑ i ∈ s, ((c i).natAbs : ℝ) with hCdef
      have hCsum : (0 : ℝ) ≤ ∑ i ∈ s, ((c i).natAbs : ℝ) :=
        Finset.sum_nonneg fun _ _ ↦ Nat.cast_nonneg _
      have hC1 : (1 : ℝ) ≤ C := by rw [hCdef]; linarith
      have hC0 : (0 : ℝ) < C := lt_of_lt_of_le one_pos hC1
      obtain ⟨F, hFne, hFH, hFbd⟩ := ih (ε / C) (div_pos hε hC0)
      have hεle : ε / C ≤ ε := by
        rw [div_le_iff₀ hC0]
        nlinarith
      refine ⟨cosetSlices a d fun _ ↦ F, ?_, hclosure d F hFH, ?_⟩
      · rw [← Finset.card_pos, card_cosetSlices_const hdmin hFH]
        exact Nat.mul_pos hd0 (Finset.card_pos.2 hFne)
      · have hcard : (cosetSlices a d fun _ ↦ F).card = d * F.card :=
          card_cosetSlices_const hdmin hFH
        have hcardR : ((cosetSlices a d fun _ ↦ F).card : ℝ) = d * F.card := by
          rw [hcard]; push_cast; ring
        have hd1 : (1 : ℝ) ≤ (d : ℝ) := by exact_mod_cast hd0
        have hFc : (0 : ℝ) ≤ (F.card : ℝ) := Nat.cast_nonneg _
        have hFcard : (F.card : ℝ) ≤ (cosetSlices a d fun _ ↦ F).card := by
          rw [hcardR]; nlinarith
        intro g hg
        rcases Finset.mem_insert.1 hg with heq | hgs
        · rw [heq, transDist_self_cosetSlices_const_of_mem hd0 hdmin hFH hdH, ← hc]
          have h1 : (F.transDist (∑ i ∈ s, c i • i) : ℝ) ≤
              ∑ i ∈ s, (F.transDist (c i • i) : ℝ) := by
            exact_mod_cast Nat.cast_le.2 (F.transDist_sum_le s fun i ↦ c i • i)
          have h2 : ∀ i ∈ s, (F.transDist (c i • i) : ℝ) ≤
              ((c i).natAbs : ℝ) * (ε / C * F.card) := by
            intro i hi
            refine le_trans ?_ (mul_le_mul_of_nonneg_left (hFbd i hi) (Nat.cast_nonneg _))
            exact_mod_cast Nat.cast_le.2 (F.transDist_zsmul_le (c i) i)
          calc (F.transDist (∑ i ∈ s, c i • i) : ℝ)
              ≤ ∑ i ∈ s, (F.transDist (c i • i) : ℝ) := h1
            _ ≤ ∑ i ∈ s, ((c i).natAbs : ℝ) * (ε / C * F.card) := Finset.sum_le_sum h2
            _ = (∑ i ∈ s, ((c i).natAbs : ℝ)) * (ε / C * F.card) := by rw [Finset.sum_mul]
            _ ≤ C * (ε / C * F.card) := by
                refine mul_le_mul_of_nonneg_right (by rw [hCdef]; linarith) ?_
                positivity
            _ = ε * F.card := by field_simp
            _ ≤ ε * (cosetSlices a d fun _ ↦ F).card := by
                exact mul_le_mul_of_nonneg_left hFcard hε.le
        · rw [transDist_cosetSlices_const hdmin hFH (AddSubgroup.subset_closure hgs), hcardR]
          have hdn : (0 : ℝ) ≤ (d : ℝ) := Nat.cast_nonneg _
          have h3 : (F.transDist g : ℝ) ≤ ε * F.card :=
            (hFbd g hgs).trans (mul_le_mul_of_nonneg_right hεle hFc)
          push_cast
          nlinarith
    · -- `a` has infinite order modulo `H`
      push Not at hex
      have hna : ∀ j, 0 < j → j • a ∉ H := fun j hj ↦ hex j hj
      set M := ⌈(2 : ℝ) / ε⌉₊ + 1 with hMdef
      have hM0 : 0 < M := Nat.succ_pos _
      have hM : ∀ j, 0 < j → j < M → j • a ∉ H := fun j hj _ ↦ hna j hj
      have hεM : (2 : ℝ) ≤ ε * M := by
        have h1 : (2 : ℝ) / ε ≤ (⌈(2 : ℝ) / ε⌉₊ : ℝ) := Nat.le_ceil _
        have h2 : ((⌈(2 : ℝ) / ε⌉₊ : ℕ) : ℝ) ≤ (M : ℝ) := by
          rw [hMdef]; push_cast; linarith
        rw [← div_le_iff₀' hε]
        linarith
      obtain ⟨F, hFne, hFH, hFbd⟩ := ih ε hε
      refine ⟨cosetSlices a M fun _ ↦ F, ?_, hclosure M F hFH, ?_⟩
      · rw [← Finset.card_pos, card_cosetSlices_const hM hFH]
        exact Nat.mul_pos hM0 (Finset.card_pos.2 hFne)
      · have hcardR : ((cosetSlices a M fun _ ↦ F).card : ℝ) = M * F.card := by
          rw [card_cosetSlices_const hM hFH]; push_cast; ring
        have hFc : (0 : ℝ) ≤ (F.card : ℝ) := Nat.cast_nonneg _
        have hMn : (0 : ℝ) ≤ (M : ℝ) := Nat.cast_nonneg _
        intro g hg
        rcases Finset.mem_insert.1 hg with heq | hgs
        · rw [heq, transDist_self_cosetSlices_const_of_notMem hM0 hFH hna, hcardR]
          push_cast
          nlinarith
        · rw [transDist_cosetSlices_const hM hFH (AddSubgroup.subset_closure hgs), hcardR]
          have h3 := hFbd g hgs
          push_cast
          nlinarith

/-! ### Følner sequences for countable abelian groups -/

/-- **Every countable abelian group admits a Følner sequence**: non-empty finite sets `F n` with
`|(g + F n) ∆ F n| / |F n| → 0` for every `g`. -/
theorem exists_foelner_seq [Countable G] :
    ∃ F : ℕ → Finset G, (∀ n, (F n).Nonempty) ∧
      ∀ g : G, Tendsto (fun n ↦ ((F n).transDist g : ℝ) / (F n).card) atTop (𝓝 0) := by
  classical
  obtain ⟨e, he⟩ := exists_surjective_nat G
  choose F hFne _ hFbd using fun n : ℕ ↦
    exists_finset_transDist_le ((Finset.range n).image e) (1 / ((n : ℝ) + 1)) (by positivity)
  refine ⟨F, hFne, fun g ↦ ?_⟩
  obtain ⟨m, rfl⟩ := he g
  refine squeeze_zero' (Eventually.of_forall fun n ↦ by positivity) ?_
    tendsto_one_div_add_atTop_nhds_zero_nat
  filter_upwards [eventually_ge_atTop (m + 1)] with n hn
  have hmem : e m ∈ (Finset.range n).image e :=
    Finset.mem_image.2 ⟨m, Finset.mem_range.2 (by omega), rfl⟩
  have hc : (0 : ℝ) < (F n).card := by exact_mod_cast Finset.card_pos.2 (hFne n)
  rw [div_le_iff₀ hc]
  exact hFbd n (e m) hmem

/-- The counting measure is invariant under the translation action of an additive group on
itself. -/
theorem vaddInvariantMeasure_count {G : Type*} [AddGroup G] [MeasurableSpace G]
    [MeasurableSingletonClass G] : VAddInvariantMeasure G G (Measure.count : Measure G) where
  measure_preimage_vadd c s _ := by
    have himg : (fun x ↦ c +ᵥ x) ⁻¹' s = (fun x ↦ -c + x) '' s := by
      ext x
      simp only [Set.mem_preimage, Set.mem_image, vadd_eq_add]
      exact ⟨fun h ↦ ⟨c + x, h, by simp⟩, by rintro ⟨y, hy, rfl⟩; simpa using hy⟩
    rw [himg]
    exact Measure.count_injective_image (add_right_injective (-c)) s

omit [DecidableEq G] in
/-- **Every countable abelian group admits a Følner sequence**, in Mathlib's `IsAddFoelner` form
for the translation action of `G` on itself with the counting measure. -/
theorem exists_isAddFoelner_count [Countable G] [MeasurableSpace G]
    [MeasurableSingletonClass G] :
    ∃ F : ℕ → Finset G, (∀ n, (F n).Nonempty) ∧
      IsAddFoelner G (Measure.count : Measure G) atTop fun n ↦ ((F n : Finset G) : Set G) := by
  classical
  obtain ⟨F, hFne, hF⟩ := exists_foelner_seq (G := G)
  have hcount : ∀ n, (Measure.count : Measure G) (F n : Set G) = (F n).card :=
    fun n ↦ Measure.count_apply_finset _
  refine ⟨F, hFne, ?_, ?_, ?_, fun g ↦ ?_⟩
  · exact Eventually.of_forall fun n ↦ (F n).measurableSet
  · exact Eventually.of_forall fun n ↦ by
      rw [hcount]
      exact_mod_cast (Finset.card_pos.2 (hFne n)).ne'
  · exact Eventually.of_forall fun n ↦ by rw [hcount]; exact ENNReal.natCast_ne_top _
  · have hset : ∀ n, (g +ᵥ ((F n : Finset G) : Set G)) ∆ ((F n : Finset G) : Set G) =
        (((g +ᵥ F n) ∆ F n : Finset G) : Set G) := by
      intro n
      rw [Finset.coe_symmDiff, Finset.coe_vadd_finset]
    have hfun : ∀ n, (Measure.count : Measure G)
          ((g +ᵥ ((F n : Finset G) : Set G)) ∆ ((F n : Finset G) : Set G)) /
            (Measure.count : Measure G) ((F n : Finset G) : Set G) =
        ENNReal.ofReal (((F n).transDist g : ℝ) / (F n).card) := by
      intro n
      have hc : (0 : ℝ) < (F n).card := by exact_mod_cast Finset.card_pos.2 (hFne n)
      rw [hset n, Measure.count_apply_finset, hcount n, ENNReal.ofReal_div_of_pos hc]
      simp [Finset.transDist]
    simp only [hfun]
    simpa using ENNReal.tendsto_ofReal (hF g)

omit [DecidableEq G] in
/-- **A countable abelian group is amenable**: it carries a translation-invariant finitely
additive probability measure. -/
theorem exists_invariant_finitelyAdditive [Countable G] [MeasurableSpace G]
    [MeasurableSingletonClass G] :
    ∃ m : Set G → ℝ≥0∞, m Set.univ = 1 ∧
      (∀ s t, MeasurableSet t → Disjoint s t → m (s ∪ t) = m s + m t) ∧
        ∀ (g : G) (s : Set G), m (g +ᵥ s) = m s := by
  classical
  have := vaddInvariantMeasure_count (G := G)
  obtain ⟨F, -, hF⟩ := exists_isAddFoelner_count (G := G)
  exact hF.amenable

end AddCommGroup

/-! ### Følner sequences of finite sets in an arbitrary group -/

section FinsetFoelner

variable {G ι : Type*} [Group G] [DecidableEq G] {l : Filter ι} {F : ι → Finset G}

/-- A group admitting a Følner net of non-empty finite sets, indexed by a countably generated
filter, is countable: every `g` lies in `F i * (F i)⁻¹` for all large `i`, and countably many
`i` suffice. In particular a Følner *sequence* of finite sets forces countability. -/
@[to_additive countable_of_tendsto_card_vadd_symmDiff_div_card /-- An additive group admitting a
Følner net of non-empty finite sets, indexed by a countably generated filter, is countable: every
`g` lies in `F i + -F i` for all large `i`, and countably many `i` suffice. In particular a Følner
*sequence* of finite sets forces countability. -/]
theorem countable_of_tendsto_card_smul_symmDiff_div_card [l.IsCountablyGenerated] [l.NeBot]
    (hne : ∀ᶠ i in l, (F i).Nonempty)
    (hF : ∀ g : G, Tendsto (fun i ↦ (((g • F i) ∆ F i).card : ℝ) / (F i).card) l (𝓝 0)) :
    Countable G := by
  obtain ⟨s, hs⟩ := l.exists_antitone_basis
  choose k hk using fun n ↦ Filter.nonempty_of_mem (hs.mem n)
  have hcov : ∀ g : G, ∃ n, g ∈ F (k n) * (F (k n))⁻¹ := by
    intro g
    have h1 : ∀ᶠ i in l, (((g • F i) ∆ F i).card : ℝ) / (F i).card < 2 :=
      (hF g).eventually (gt_mem_nhds (by norm_num))
    obtain ⟨n, hn⟩ := hs.mem_iff.1 (h1.and hne)
    obtain ⟨hlt, hFne⟩ := hn (hk n)
    refine ⟨n, ?_⟩
    by_contra hg
    have hdisj : Disjoint (g • F (k n)) (F (k n)) := by
      rw [Finset.disjoint_left]
      intro x hx hx'
      obtain ⟨a, ha, rfl⟩ := Finset.mem_smul_finset.1 hx
      refine hg ?_
      have : g = (g • a) * a⁻¹ := by simp
      rw [this]
      exact Finset.mul_mem_mul hx' (Finset.inv_mem_inv ha)
    have hcard : (((g • F (k n)) ∆ F (k n)).card : ℝ) = 2 * (F (k n)).card := by
      rw [Finset.symmDiff_eq_union hdisj, Finset.card_union_eq_card_add_card.2 hdisj,
        Finset.card_smul_finset]
      push_cast
      ring
    have hpos : (0 : ℝ) < (F (k n)).card := by exact_mod_cast hFne.card_pos
    rw [hcard, mul_div_assoc, div_self hpos.ne', mul_one] at hlt
    exact lt_irrefl _ hlt
  refine Set.countable_univ_iff.1 ((Set.countable_iUnion fun n ↦
    (F (k n) * (F (k n))⁻¹).countable_toSet).mono fun g _ ↦ ?_)
  obtain ⟨n, hn⟩ := hcov g
  exact Set.mem_iUnion.2 ⟨n, hn⟩

/-- Mathlib's `IsFoelner` for the translation action of `G` on itself with the counting measure,
along a net of finite sets, is the elementary condition
`|(g • F i) ∆ F i| / |F i| → 0` together with eventual non-emptiness. -/
@[to_additive isAddFoelner_count_iff /-- Mathlib's `IsAddFoelner` for the translation action of
`G` on itself with the counting measure, along a net of finite sets, is the elementary condition
`|(g +ᵥ F i) ∆ F i| / |F i| → 0` together with eventual non-emptiness. -/]
theorem isFoelner_count_iff [MeasurableSpace G] [MeasurableSingletonClass G] :
    IsFoelner G (Measure.count : Measure G) l (fun i ↦ ((F i : Finset G) : Set G)) ↔
      (∀ᶠ i in l, (F i).Nonempty) ∧
        ∀ g : G, Tendsto (fun i ↦ (((g • F i) ∆ F i).card : ℝ) / (F i).card) l (𝓝 0) := by
  have hcount : ∀ i, (Measure.count : Measure G) (F i : Set G) = (F i).card :=
    fun i ↦ Measure.count_apply_finset _
  have hset : ∀ (g : G) i, (g • ((F i : Finset G) : Set G)) ∆ ((F i : Finset G) : Set G) =
      (((g • F i) ∆ F i : Finset G) : Set G) := fun g i ↦ by
    rw [Finset.coe_symmDiff, Finset.coe_smul_finset]
  have hratio : ∀ (g : G) i, (F i).Nonempty →
      (Measure.count : Measure G) ((g • ((F i : Finset G) : Set G)) ∆ ((F i : Finset G) : Set G)) /
        (Measure.count : Measure G) ((F i : Finset G) : Set G) =
      ENNReal.ofReal ((((g • F i) ∆ F i).card : ℝ) / (F i).card) := fun g i hi ↦ by
    have hc : (0 : ℝ) < (F i).card := by exact_mod_cast hi.card_pos
    rw [hset, Measure.count_apply_finset, hcount, ENNReal.ofReal_div_of_pos hc]
    simp
  have hne_iff : (∀ᶠ i in l, (Measure.count : Measure G) (F i : Set G) ≠ 0) ↔
      ∀ᶠ i in l, (F i).Nonempty := by
    refine eventually_congr (Eventually.of_forall fun i ↦ ?_)
    rw [hcount, ← Finset.card_pos, pos_iff_ne_zero]
    exact_mod_cast Iff.rfl
  constructor
  · intro h
    have hne := hne_iff.1 h.eventually_meas_ne_zero
    refine ⟨hne, fun g ↦ ?_⟩
    have := (ENNReal.tendsto_toReal ENNReal.zero_ne_top).comp (h.tendsto_meas_smul_symmDiff g)
    rw [ENNReal.toReal_zero] at this
    refine this.congr' (hne.mono fun i hi ↦ ?_)
    rw [Function.comp_apply, hratio g i hi, ENNReal.toReal_ofReal (by positivity)]
  · rintro ⟨hne, hF⟩
    refine ⟨Eventually.of_forall fun i ↦ (F i).measurableSet, hne_iff.2 hne,
      Eventually.of_forall fun i ↦ by rw [hcount]; exact ENNReal.natCast_ne_top _, fun g ↦ ?_⟩
    have := (ENNReal.tendsto_ofReal (hF g)).congr' (hne.mono fun i hi ↦ (hratio g i hi).symm)
    simpa using this

end FinsetFoelner

end
